### ISSUE TITLE
请问下Button里写Link或者Link里写Button，字体上有下划线的问题是否已处理？

### ISSUE THREAD

**Issue by sujingclg** [DouyinFE/semi-design#100]
如题
谢谢

**Comment by JokerQyou** [comment]
他指的恰好是「链接按钮」的反面：将链接作为按钮，也就是实际是一个链接，但是其样式与按钮保持一致。

**Comment by sujingclg** [comment]
> 他指的恰好是「链接按钮」的反面：将链接作为按钮，也就是实际是一个链接，但是其样式与按钮保持一致。

bingo!

**Comment by JokerQyou** [comment]
我提出了 #487 ，希望可以支持这种用法。
