### ISSUE TITLE
[Select] 希望新增平铺模式

### ISSUE THREAD

**Issue by moonsky-all** [DouyinFE/semi-design#1002]
### Which Component Need Enhancement 期望新增功能的组件
- Select

### Feature Description 功能描述
Select 的下拉框是列表形式展示，但是每个选项通常只有 5 个字以内的内容，这样很容易造成选项右侧大量空间浪费，平铺模式就是将选项以行内元素（inline 或 inline-block）形式展示，充分利用下拉框空间展示更多选项信息，这尤其对 ToB 项目很有用。如图，
![image](https://user-images.githubusercontent.com/82572484/181871259-2c52e646-aa52-4c53-b02d-5016cfd7b81c.png)

![image](https://user-images.githubusercontent.com/82572484/181872073-e7d6c417-4b12-4e03-ba24-92daa1dc97e5.png)

### Additional information 补充说明
平铺模式希望也支持分组、自定义样式、自定义渲染等

**Comment by pointhalo** [comment]
暂时没有这方面的计划。这个交互更像是 tabs的交互，看起来跟select的关系不大。并且与Select现有的结构交互完全不是一码事了。从API设计的角度上讲，也会造成很多不兼容的问题。
建议自己封装组件实现。

**Comment by moonsky-all** [comment]
Done
