### ISSUE TITLE
[BUG] Input 密码模式，自带眼睛icon和 windows edge 的眼睛图标重复

### ISSUE THREAD

**Issue by endlesstravel** [DouyinFE/semi-design#1004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Input

### Semi Version

2.16.0

### Current Behavior

输入文字后，仅 windows edge 会出现，重复的密码
![image](https://user-images.githubusercontent.com/10757838/181888294-a5144ce9-45dc-4b6c-a382-66cecfee6baf.png)

### Expected Behavior

 windows edge 不会出现自带的眼睛图标。
目前解决方案，使用 css 去掉他们
全局消除：
```css
 input::-ms-reveal,  input::-ms-clear {
        display: none;
 }
```

答案链接：
https://stackoverflow.com/questions/61449079/how-to-hide-the-eye-from-a-password-input-in-ms-edge-and-ie

### ReproducibleCode

```markdown
import React from 'react';
import { Input } from '@douyinfe/semi-ui';

() => (
    <Input mode="password" ></Input>
);
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by linjunc** [comment]
I'll fix it tonight

**Comment by pointhalo** [comment]
![image](https://user-images.githubusercontent.com/88709023/183062271-87d73657-aab3-415a-bd1b-8935a1e8512b.png)

**Comment by mu-mu-zi** [comment]
我想替换掉这个小眼睛的svg需要怎么做

**Comment by pointhalo** [comment]
> 我想替换掉这个小眼睛的svg需要怎么做

暂不支持。如果确实需要可以提个 PR。
改这里 https://github.com/DouyinFE/semi-design/blob/f29429fcc83ee16ddefe9e5fbe10e8554c001e2f/packages/semi-ui/input/index.tsx#L334
