### ISSUE TITLE
[Table] 期望可以设置粘性头部和滚动条

### ISSUE THREAD

**Issue by afc164** [DouyinFE/semi-design#1005]
### Which Component Need Enhancement 期望新增功能的组件
- Table

### What does the proposed API look like 期望支持的API
sticky

### Feature Description 功能描述
粘性头部和滚动条

**Comment by pointhalo** [comment]
1、table header sticky能从字面意思理解。

2、滚动条是什么意思，没get到，可以举个例子吗

**Comment by afc164** [comment]
粘性滚动条，就是当滚动条超出视口后可以吸底，形同antd design 4.6.0版本新增的sticky属性实现的功能

**Comment by shijiatongxue** [comment]
sticky 表头 2.21.0 已支持

**Comment by shijiatongxue** [comment]
粘性滚动条可以单独开 issue，暂时没有收到更多关于粘性滚动条的支持诉求
