### ISSUE TITLE
table 树形表格 开启bordered 边框错乱

### ISSUE THREAD

**Issue by zh1011** [DouyinFE/semi-design#101]
### Which Component 出现bug的组件
  - Table 

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 

### Actual result 实际的结果是什么
  - 

### Steps to reproduce 复现步骤
最右边开启fixed
![image](https://user-images.githubusercontent.com/41102878/139170401-ea9c9069-cb05-45cf-9cc8-49f4ec6884bb.png)

### Reproducible code 复现代码
```
<Table bordered expandAllRows
      scroll={{ y: 300 }}
      columns={tableColumns}
      rowKey="id" size="small"
      loading={state.tableLoading}
      dataSource={state.tableData}
      pagination={false}
  />  

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by shijiatongxue** [comment]
v2.0.7 fixed
