### ISSUE TITLE
[Upload] <allowlist里有jpg没有jpeg的时候 选择文件例jpeg不会置灰 但是选了之后又传不上来 还是被过滤了>

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#1016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Upload

### Semi Version

latest

### Current Behavior

allowlist里有jpg没有jpeg的时候 选择文件例jpeg不会置灰    但是选了之后又传不上来 还是被过滤了
```
import React from 'react';
import { Upload, Button } from '@douyinfe/semi-ui';
import { IconUpload } from '@douyinfe/semi-icons';

() => {
    let action = 'https://run.mocky.io/v3/d6ac5c9e-4d39-4309-a747-7ed3b5694859';
    let imageOnly = 'image/*';
    let videoOnly = 'video/*';
    let fileLimit = '.jpg,.png';
    return (
        <>
            <Upload action={action} accept={fileLimit}>
                <Button icon={<IconUpload />} theme="light">
                    上传
                </Button>
            </Upload>
        </>
    );
};
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
这个应该是无法规避的
- 文件选择弹窗里哪些置灰是浏览器的行为。如果要严格允许的话，应该 jpg和jpeg都写上最好。
- 选择了文件后，会根据file对象返回的 mimetype （如果accepti有mime写法时）或者 filename （如果accept里有文件后缀名写法时）与 accept进行对比，这里因为 file的后缀名与 accept不符，所以就认为是不符合的了。
