### ISSUE TITLE
[BUG] Empty组件在2.16.1版本image，darkModeImage都设置的情景下浅色模式使用darkModeImage

### ISSUE THREAD

**Issue by lixiaoming-bit** [DouyinFE/semi-design#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Empty

### Semi Version

2.16.1

### Current Behavior

![image](https://user-images.githubusercontent.com/42863578/183615901-cf346834-e148-4d7a-a3ce-f295981bdb2e.png)

### Expected Behavior

https://semi.design/zh-CN/show/empty

### Steps To Reproduce

    "@douyinfe/semi-icons": "^2.16.1",
    "@douyinfe/semi-illustrations": "^2.16.1",
    "@douyinfe/semi-next": "^2.16.1",
    "@douyinfe/semi-ui": "^2.16.1",

### ReproducibleCode

```markdown
<Empty
  image={<IllustrationNoAccess style={{ width: 250, height: 250 }} />}
  darkModeImage={<IllustrationNoAccessDark style={{ width: 250, height: 250 }} />}
/>
```

### Environment

```markdown
- OS:mac 12.5 monstry
- browser:chrome最新
```

### Anything else?

是在next中使用的组件，同时引入两种状态时，仅显示暗黑模式的图片

**Comment by pointhalo** [comment]
不好意思，没看明白，我确认一下，
是指在亮色模式下，Empty显示了暗色模式下的样式？

**Comment by lixiaoming-bit** [comment]
> 不好意思，没看明白，我确认一下， 是指在亮色模式下，Empty显示了暗色模式下的样式？

亮色模式下 图片是暗色模式的样式

**Comment by lixiaoming-bit** [comment]
> 我这里有个简单的demo，https://codesandbox.io/s/zen-hooks-s23o9x?file=/src/App.jsx 但不是next项目。 或许我们可以就这个demo展开讨论（如果是仅在next项目中才出现的问题，那单独说）

[https://codesandbox.io/s/kind-hodgkin-u5wzv4?file=/src/App.jsx](url)
这个确实存在问题，我根据你的示例改了一下 问题就出现了 应该是获取这个主题的属性值 没有判断准确

**Comment by lixiaoming-bit** [comment]
> 我这里有个简单的demo，https://codesandbox.io/s/zen-hooks-s23o9x?file=/src/App.jsx 但不是next项目。 或许我们可以就这个demo展开讨论（如果是仅在next项目中才出现的问题，那单独说）

不好意思 是我这边的问题，我以为你们浅色主题 theme-mode 也存在值 但事实上你们只有在深色模式下theme-mode="dark"，浅色时会移除属性。但是这样判断也不太好，这样就只能去切换两种主题，

**Comment by pointhalo** [comment]
我好像get到了。**这个应该是个bug**。我们的预期插画只有两种状态。官网 Empty文档页的表现是符合预期的。但是在codesandbox里实际行为不太一样。

- ✅  theme-mode未声明时  或者 theme-mode=light时，预期样式
<img width="633" alt="image" src="https://user-images.githubusercontent.com/88709023/183640172-4771bf3f-8358-4a01-9b86-db9413cc9b60.png">
- ✅ theme-mode=dark，预期样式
<img width="591" alt="image" src="https://user-images.githubusercontent.com/88709023/183640349-89831b53-7d7f-4cd3-88ec-241f769815fb.png">

- ❌ 现在声明 theme-mode=light时，有部分节点的背景色不太对
<img width="577" alt="image" src="https://user-images.githubusercontent.com/88709023/183640690-b2f16534-a9e5-4ddb-9a60-eb935ca9a4f7.png">

**Comment by pointhalo** [comment]
我想我get到你意思了。这里应该是个bug。插画应该只有两种样式。我们修一下

**Comment by pointhalo** [comment]
我们在 body下挂了一套色盘，在 body[theme-mode='dark'] 的时候也挂了一套色盘

不过这里的问题其实是Empty里的判断有点不够严谨，如果theme-mode设了其他字符串时，也认为是dark了，所以会应用上dark的 svg

**Comment by DaiQiangReal** [comment]
Fixed.  https://github.com/DouyinFE/semi-design/pull/1027

**Comment by lixiaoming-bit** [comment]
3q
