### ISSUE TITLE
[Tree] 虚拟滚动下，增加滚动到指定 key 条目的方法

### ISSUE THREAD

**Issue by YyumeiZhang** [DouyinFE/semi-design#1024]
### Which Component Need Enhancement 期望新增功能的组件
- Tree

### What does the proposed API look like 期望支持的API
scrollTo({  key: string })

### Feature Description 功能描述

在设置虚拟滚动条件下，增加滚动到指定增加滚动到指定 key 条目的方法

**Comment by pointhalo** [comment]
v2.18.0-beta.0
