### ISSUE TITLE
rating 组件 item 子组件多次重复点击不会 re-render

### ISSUE THREAD

**Issue by EchoZhaoH** [DouyinFE/semi-design#103]
### Which Component 出现bug的组件
 Rating

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 在切换评分时，star 应该切换, 原因是 hoverValue 没有更新

### Actual result 实际的结果是什么
  - 在同一个 star 多次重复点击，不会触发 item 组件 re-render

### Steps to reproduce 复现步骤
  - 1

### Additional information 补充说明
这是使用 Rating 组件遇到的

https://user-images.githubusercontent.com/23427655/139179181-a11b0087-3b59-4394-b700-7fbc0a9736fd.mov

**Comment by tank0317** [comment]
@EchoZhaoH 问题已收到。我们会尽快解决。

使用 hoverValue 是为了在鼠标 hover 过程中展示预期的数据变化，这一点没有问题。
现在的问题是，需要在点击时，使用点击的数据展示 star
