### ISSUE TITLE
[Toast] Add update content based on id

### ISSUE THREAD

**Issue by gwsbhqt** [DouyinFE/semi-design#1035]
Just like antd, the content of tosta can be updated according to the id, which can achieve some useful effects.

[update_message](https://ant.design/components/message-cn/#components-message-demo-update)

Like this.

https://user-images.githubusercontent.com/16471930/184106218-0226315a-e418-4ed4-8023-f762e99de863.mp4

https://user-images.githubusercontent.com/16471930/184106231-3437c6f4-ff6a-444e-be44-26708ee2ad64.mp4

In the case of poor network.

https://user-images.githubusercontent.com/16471930/184107313-6c9fb4b5-cd32-4994-9365-ef0e51d671c2.mp4

**Comment by gwsbhqt** [comment]
Is this repository welcome to push request? I think I can give it a try. @pointhalo

**Comment by pointhalo** [comment]
Of course, this is an open source project, and we welcome anyone to participate. Welcome PR🧙🏻‍♂️

btw, let me explain why this issue has not been dealt with

For the past three years, Semi has maintained a release cadence of a minor version every two weeks, that is, a month contains two versions. We arrange the work plan on a monthly basis, and the features to be provided for each version will be determined at the beginning of the month.

The requirement for intermediate insertion will be discussed in the next cycle on how and when to process it, so this feature has not been processed yet, only the relevant label is marked.

**Comment by pointhalo** [comment]
If you have time and are willing to directly submit PR to modify the code to implement related functions, you can checkout the latest code from the main branch.

About how to run this project, you can refer to https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md

Then modify the relevant implementation, and after the self-test passes, add relevant unit test cases or e2e use cases. Submit PR to release branch, we will review ASAP.

**Comment by DaiQiangReal** [comment]
> @pointhalo I've tried to fix this, but don't know if it's correct, this is my first time committing, please point out if there are any mistakes. Thanks!

Your PR have merged into branch feat-1035 , and the branch will be merged into release branch while publishing semi version 2.20.0-beta.0. https://github.com/DouyinFE/semi-design/pull/1106

**Comment by pointhalo** [comment]
support v2.20.0-beta.0
