### ISSUE TITLE
[BUG] (Slider) Weird behavior with some "step" values

### ISSUE THREAD

**Issue by Saul-BT** [DouyinFE/semi-design#1043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Slider

### Semi Version

2.17.0

### Current Behavior

The slider values are wrong, it seems like there is a buggy round up behind or something when using certain `step` values.

These are the props that trigger the weird behavior:

```
min: 0
max: 1
step: 0.125
```

Demo:

https://user-images.githubusercontent.com/25767185/185071406-e90d06a2-bcac-40fa-8b65-e69da95b3a1d.mp4

### Expected Behavior

The slider values are right and the tooltip displays the whole current value, as it works with the following props:

```
min: 0
max: 1
step: 0.005
```

Demo:

https://user-images.githubusercontent.com/25767185/185071989-3171ec08-fad1-4693-a3de-67a973a1ba45.mp4

### Steps To Reproduce

1. With these info:

```
Next.js: 12.2.5
Semi-ui: 2.17.0
Semi-next: 2.17.0
```

2. Import and use the component `Slider` with the following props:

```
min: 0
max: 1
step: 0.125
```

3. See the weird behavior when using the slider.

### ReproducibleCode

```markdown
import type { NextPage } from "next";
import { Form } from "@douyinfe/semi-ui";

const SliderIssue: NextPage = () => {
  return (
    <Form
      initValues={{ sliderCtrl: 0.125 }}
      render={({ formState }) => (
        <>
          <Form.Slider
            label="Slider (min=0 max=1 step=0.125)"
            field="sliderCtrl"
            min={0}
            max={1}
            step={0.125}
          />
          <pre>{JSON.stringify(formState, null, 2)}</pre>
        </>
      )}
    />
  );
};

export default SliderIssue;
```

### Environment

```markdown
- OS: Windows
- browser: Chrome
```

**Comment by DaiQiangReal** [comment]
fix on #1093
