### ISSUE TITLE
[BUG] <DSM 发布主题 500 error & figma plugin runtime abort>

### ISSUE THREAD

**Issue by CrazyChildren** [DouyinFE/semi-design#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

DSM 

### Semi Version

latest 2.17.1

### Current Behavior

Error: validate npm package name failed. Detail: Error: Request failed with status code 500

### Expected Behavior

publish theme successfully

### Steps To Reproduce

1. 创建一个DSM主题，只修改圆角至8
2. 发布主题，name: xxxtest, npm version 1.0.x, semi version 2.17.1
3. publish

### Environment

```markdown
- OS: Windows 11 
- browser: Edge 104.0.1293.54 no proxy
- DSM: https://semi.design/dsm/web_console/manual?dsmID=3847
```

**Comment by pointhalo** [comment]
500 目前是由于我们server跟 npm.org 之间的网络链路间接性不通，这个还在追查原因。

**Comment by DaiQiangReal** [comment]
现在应该好了 @CrazyChildren

**Comment by pointhalo** [comment]
可以再试试，DSM publish应该好了。这个issue我们先关掉了哈，如果还有同样问题可以再reopen

**Comment by DaiQiangReal** [comment]
@anc95  在左侧预览页面能正常预览吗？

**Comment by DaiQiangReal** [comment]
> @DaiQiangReal 可以正常预览 <img alt="image" width="1472" src="https://user-images.githubusercontent.com/13167934/191449777-e60abe51-c00f-412f-aea7-c8962142645b.png">

发包的时候 兼容的 semi 版本 先选择 2.19.0。 不要选新的 beta。这个我们一会修复。

**Comment by DaiQiangReal** [comment]
> 可以了 👍

刚刚修复了 现在选任何版本应该都可以成功发包了
