### ISSUE TITLE
[BUG] Dropdown组件内部使用Space不会触发Dropdown的展开行为

### ISSUE THREAD

**Issue by lixiaoming-bit** [DouyinFE/semi-design#1048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Dropdown

### Semi Version

2.17.1

### Current Behavior

```jsx
<Dropdown
  trigger="hover"
  showTick
  render={
    <Dropdown.Menu>
      <Dropdown.Item active>所有</Dropdown.Item>
      <Dropdown.Item>我的</Dropdown.Item>
    </Dropdown.Menu>
  }
>
  <Space>
    <Typography.Text type="secondary">创建者</Typography.Text>
    <IconChevronDown />
  </Space>
</Dropdown>
```
鼠标移入上去不起作用！

### Expected Behavior

正常展开

### ReproducibleCode

```markdown
https://codesandbox.io/s/snowy-grass-md64no?file=/src/App.js:214-604
```

### Environment

```markdown
- OS: mac monstery m1
- browser: chrome latest
```

**Comment by pointhalo** [comment]
Space 本身不提供 onMouseEnter、onMouseLeave、onClick等事件。**而Dropdown、Tooltip、Popover等这类浮层组件，都是需要劫持 children的事件来做 trigger 判断的**。所以这样用确实不行。
可以加一个span或者 inline 的div包裹作为 第一层children

**Comment by lixiaoming-bit** [comment]
> Space 本身不提供 onMouseEnter、onMouseLeave、onClick等事件。**而Dropdown、Tooltip、Popover等这类浮层组件，都是需要劫持 children的事件来做 trigger 判断的**。所以这样用确实不行。 可以加一个span或者 inline 的div包裹作为 第一层children

好叭，只能加一层么，或者自己写一个flex 居中

**Comment by pointhalo** [comment]
是的。浮层类组件的children 必须支持并接收 onMouseLeave、Enter事件才可以，不然事件没法穿透。
