### ISSUE TITLE
[BUG] input component focus, when switch to another application(eg: the notepad, copy text) and then return back, the input lost the focus state

### ISSUE THREAD

**Issue by NsGFr** [DouyinFE/semi-design#1062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Input

### Semi Version

2.17.1

### Current Behavior

input component focus, when switch to another application(eg: the notepad, copy text) and then return back, the input lost the focus state

### Expected Behavior

keep the input component focus as before.

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
This should be a bug, not what we expected. 
We didn't explicitly control this behavior, maybe some properties of our application were accidentally affecting it.
We need time to figure out why

**Comment by YyumeiZhang** [comment]
v2.38.0无法复现该问题，先 close 掉了
