### ISSUE TITLE
[BUG] 新版本 (2.18.0) 引入自定义主题的情况下编译报错

### ISSUE THREAD

**Issue by nekocode** [DouyinFE/semi-design#1072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Semi Version

2.18.0

### Current Behavior

![image](https://user-images.githubusercontent.com/4783781/187022916-368ec1ef-4c42-4b85-8c99-5ddada3c8ff5.png)

我尝试在 DSM 系统上重新发布主题，但是新的 npm 包里依旧没有 animation.scss 文件👇

![image](https://user-images.githubusercontent.com/4783781/187023015-c07a75ec-005e-45d2-af41-53d1ca7bd20b.png)

### Environment

```markdown
- OS: macOS
```

**Comment by DaiQiangReal** [comment]
修复中，稍等

**Comment by DaiQiangReal** [comment]
npm i @douyinfe/semi-webpack-plugin@2.18.1 @nekocode   使用这个版本

**Comment by DaiQiangReal** [comment]
已发新版修复
