### ISSUE TITLE
[BUG] 使用pnpm，在vite中使用自定义主题，会出现编译错误

### ISSUE THREAD

**Issue by zk8080** [DouyinFE/semi-design#1076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Semi Version

2.18.2

### Current Behavior

<img width="903" alt="image" src="https://user-images.githubusercontent.com/24732774/187230616-82c5ab99-914d-45e0-8cc9-52c9aa84ee4e.png">

### Expected Behavior

 在pnpm中能够正常使用自定义主题

### Steps To Reproduce

使用pnpm初始化一个vite的react-ts项目，使用自定义主题即可复现

### Environment

```markdown
- OS: macos
- browser:chorome
```

### Anything else?

调试了一下vite-plugin-semi-theme的源码，发现是没有兼容pnpm下依赖的路径问题，导致引入的自定义主题下的scss文件指向了.pnpm中的目录，而不是直接指向node_modules中的自定义主题包

**Comment by DaiQiangReal** [comment]
vite 的插件是社区维护的，可以给他们提 Issue，目前可以先临时使用 主题包内部的全量 semi.css 来绕过。

**Comment by pointhalo** [comment]
理论上pnpm下这个是软链，路径做额外处理感觉不是很合理。看起来是dart-sass不识别软链

**Comment by ianho7** [comment]
同样遇到这个问题。

**Comment by pointhalo** [comment]
这个暂时没有解决方案，需要先换 yarn或者npm绕过

**Comment by Kelier** [comment]
same ，绕不过去啊，直接Import也不生效

**Comment by popdo** [comment]
> 这个暂时没有解决方案，需要先换 yarn或者npm绕过

semi官方是否会计划开发vite插件。现在vite已经非常成熟了，无论预览还是打包效率比webpage高了不知道多少倍。= 两年快过去了，依然不支持vite。

**Comment by pointhalo** [comment]
> > 这个暂时没有解决方案，需要先换 yarn或者npm绕过
> 
> semi官方是否会计划开发vite插件。现在vite已经非常成熟了，无论预览还是打包效率比webpage高了不知道多少倍。= 两年快过去了，依然不支持vite。

1. 不是不支持vite，是 pnpm 下它的特殊目录结构会导致结合使用时有一些问题，vite + npm/yarn 是没问题的
2. vite plugin 有社区版本，pnpm你可以试下 https://github.com/Codpoe/vite-plugin-semi-theming ，非pnpm可以用 https://github.com/boenfu/vite-plugin-semi-theme
3. 我们自身人力有限，没有那么多人力去cover所有的工程化方案（这里的人力消耗会包括：初始版本以及跟进后续所有的使用问题），我们公司内部高强度使用的是 webpack 和 rspack，仅对这两者的构建方案提供官方支持。

**Comment by popdo** [comment]
> > > 这个暂时没有解决方案，需要先换 yarn或者npm绕过
> > 
> > 
> > semi官方是否会计划开发vite插件。现在vite已经非常成熟了，无论预览还是打包效率比webpage高了不知道多少倍。= 两年快过去了，依然不支持vite。
> 
> 1. 不是不支持vite，是 pnpm 下它的特殊目录结构会导致结合使用时有一些问题，vite + npm/yarn 是没问题的
> 2. vite plugin 有社区版本，pnpm你可以试下 https://github.com/Codpoe/vite-plugin-semi-theming ，非pnpm可以用 https://github.com/boenfu/vite-plugin-semi-theme
> 3. 我们自身人力有限，没有那么多人力去cover所有的工程化方案（这里的人力消耗会包括：初始版本以及跟进后续所有的使用问题），我们公司内部高强度使用的是 webpack 和 rspack，仅对这两者的构建方案提供官方支持。

这个支持pnpm，亲测可用。非常感谢！主题好棒！

```md
https://github.com/Codpoe/vite-plugin-semi-theming
```

**Comment by sydboys** [comment]
@kousum/vite-plugin-semi-theme vite8 react 19 这个很不错。

**Comment by sydboys** [comment]
> vite 的插件是社区维护的，可以给他们提 Issue，目前可以先临时使用 主题包内部的全量 semi.css 来绕过。

为何我全量覆盖不起作用呢
