### ISSUE TITLE
官网无法注册， 后端跨域了 ，cors [BUG] <title>

### ISSUE THREAD

**Issue by icetech233** [DouyinFE/semi-design#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
试了一下没有复现。
1. 检查下是否有浏览器插件干预了请求头？
2. 如果问题依然存在，麻烦给下操作路径，错误截图

**Comment by DaiQiangReal** [comment]
@icetech233

**Comment by icetech233** [comment]
> 试了一下没有复现。
> 
> 1. 检查下是否有浏览器插件干预了请求头？
> 2. 如果问题依然存在，麻烦给下操作路径，错误截图

arco 登录没有问题啊

**Comment by icetech233** [comment]
> 试了一下没有复现。
> 
> 1. 检查下是否有浏览器插件干预了请求头？
> 2. 如果问题依然存在，麻烦给下操作路径，错误截图



浏览器 截图


https://i.postimg.cc/FzVzxy2P/DFN-7-H-9-M-4-GE-IBEBLONG3.png

**Comment by icetech233** [comment]
> 试了一下没有复现。
> 
> 1. 检查下是否有浏览器插件干预了请求头？
> 2. 如果问题依然存在，麻烦给下操作路径，错误截图

跨域要是有问题，所有浏览器都有问题了   帮忙自测一下

**Comment by DaiQiangReal** [comment]
> > 试了一下没有复现。
> > 
> > 1. 检查下是否有浏览器插件干预了请求头？
> > 2. 如果问题依然存在，麻烦给下操作路径，错误截图
> 
> 跨域要是有问题，所有浏览器都有问题了 帮忙自测一下

因为你访问的是 HTTP，不是HTTPs

**Comment by pointhalo** [comment]
麻烦使用 https://semi.design 吧。这里我们后续也会加个http -> https的重定向。
