### ISSUE TITLE
[Progress] Auto-fill gradient colours & custom colours according to progress

### ISSUE THREAD

**Issue by uiuing** [DouyinFE/semi-design#1092]
### Which Component Need Enhancement 期望新增功能的组件
- Progress

### What does the proposed API look like 期望支持的API
Modify API:
 - `stroke`  : type[string] -> type[string | Array<{percent:number, color:string}>]
Add API:
- `strokeGradient`  : type[boolean]

#### Modify `stroke` API
`stroke` can be set to an array:
```typescript
[
 {'percent':1,'color':'#fff'},
]
```
This means that when the api `percent` is one percent, the colour of all percentages including and after is `#fff`.

Or this:
```typescript
[
 {'percent':1, 'color':'#fff'},
 {'percent':80, 'color':'#000'},
]
```
This means that when the api  `percent`  is between 1% and 79%, the colour is `#fff`  and when it is 80% and above, the colour is  `#000` .

#### Add `strokeGradient` API
This is an interesting feature, when it is set to `true` and there is an interval between the colours set by `stroke`, it will automatically create a gradient between the two colours to achieve a transitional effect.

It's like this:
```typescript
const stroke = [
 {'percent':0, 'color':'#000000'},
 {'percent':3, 'color':'#ffffff'},
]
const strokeGradient = true
```
An array of gradient colours will be generated automatically:
```typescript
const gradient = [
 {'percent':0, 'color':'#000000'},
 {'percent':1, 'color':'#555555'},
 {'percent':2, 'color':'#aaaaaa'},
 {'percent':3, 'color':'#ffffff'},
]
```

### Additional information 补充说明
This is a requirement I found in an actual scenario, But I'm not sure everyone needs it, so please consider it.  If this is the right request, I will submit Pr so as not to put anyone off. Thank.

**Comment by DaiQiangReal** [comment]
欢迎👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻

**Comment by DaiQiangReal** [comment]
@uiuing  ❤️

**Comment by pointhalo** [comment]
Looks like a very useful api，PR Welcome

About how to run this project, you can refer to https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md

You may need to modifying these code
```
pacakges/semi-ui/progress
pacakges/semi-foundation/progress
```

**Comment by uiuing** [comment]
thx @DaiQiangReal  @pointhalo , I'll do it immediately 🤪

**Comment by pointhalo** [comment]
Release v2.20.0-beta.0
