### ISSUE TITLE
[BUG] <title>TagGroup多个组件公用一份tagList的时候，tagList会被修改引起bug

### ISSUE THREAD

**Issue by 17839359913** [DouyinFE/semi-design#1107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

TagGroup

### Semi Version

2.19.0-beta.0

### Current Behavior

TagGroup多个组件公用一份tagList的时候，tagList会被修改引起bug

### Expected Behavior

不应该互相影响

### Steps To Reproduce

TagGroup多个组件公用一份tagList的时候，tagList会被修改引起bug

### ReproducibleCode

```markdown
import React from 'react';
import { TagGroup } from '@douyinfe/semi-ui';

() => {
    const tagList = [
        { color: 'white', children:'抖音' },
        { color: 'white', children:'火山' },
        { color: 'white', children:'剪映' },
        { color: 'white', children:'醒图' },
    ];
    const src = 'https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/root-web-sites/dy.png';
    const tagList2 = [
        { color: 'white', children:'Douyin', avatarSrc:src },
        { color: 'white', children:'Hotsoon', avatarSrc:src },
        { color: 'white', children:'Capcut', avatarSrc:src },
        { color: 'white', children:'Xingtu', avatarSrc:src },
    ];
    const divStyle = {
        backgroundColor: 'var(--semi-color-fill-0)',
        height: 35,
        width: 300,
        display: 'flex',
        alignItems: 'center',
        padding: '0 10px',
        marginBottom: 30,
    };
    const tagGroupStyle = {
        display: 'flex',
        alignItems: 'center',
        width: 350,
    };
    return (
        <>
            <div style={divStyle}>
                <TagGroup maxTagCount={3} style={tagGroupStyle} tagList={tagList} size="large" />
            </div>
            <div style={divStyle}>
                <TagGroup
                    maxTagCount={2}
                    style={tagGroupStyle}
                    tagList={tagList2}
                    size="large"
                    avatarShape="circle"
                    showPopover
                />
            </div>
        </>
    );
};
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by YannLynn** [comment]
能多给一些信息吗？从你的例子没有发现多个组件公用一份tagList并产生bug的情况

**Comment by 17839359913** [comment]
> 能多给一些信息吗？从你的例子没有发现多个组件公用一份tagList并产生bug的情况
第一个TagGroup会把tagList污染了，第二个渲染时用的是已经被污染的数据，看下面截图
<div style={divStyle}>
                <TagGroup maxTagCount={3} style={tagGroupStyle} tagList={tagList} size="large" />
            </div>
            <div style={divStyle}>
                <TagGroup maxTagCount={3} style={tagGroupStyle} tagList={tagList} size="small" />
            </div>

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/22956606/188624062-3caea2cb-9598-4d19-944c-3d9120022cc2.png">

**Comment by 17839359913** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/22956606/188624841-7d446d0b-ce76-4df9-95c5-2cb3545e86c0.png">
这一段源码的问题

**Comment by 17839359913** [comment]
二次开发的话，新增组件有可用的命令吗？

**Comment by YyumeiZhang** [comment]
@17839359913 没有get到你的意思，再详细点？

**Comment by 17839359913** [comment]
> @17839359913 没有get到你的意思，再详细点？

我们现在是在semi的基础上进行二次开发，就是如何快速的新增一个新的组件？

**Comment by YyumeiZhang** [comment]
> > @17839359913 没有get到你的意思，再详细点？
> 
> 我们现在是在semi的基础上进行二次开发，就是如何快速的新增一个新的组件？

听起来是在组件基础上做包装自己的业务组件，如果是这样的话我理解没有什么命令。是在什么使用情况下，有觉得需要命令呢？现在的方式有哪些你觉得可以加快的方式呢？

**Comment by pointhalo** [comment]
> 二次开发的话，新增组件有可用的命令吗？

没有。新增组件是相对低频的操作，所以并没有封装cli之类的工具。如果是想对齐 Semi 原有组件的规范，可以基于现有组件 copy paste & edit。
