### ISSUE TITLE
[BUG] Select `onBlur` 失效

### ISSUE THREAD

**Issue by zwlafk** [DouyinFE/semi-design#1110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select

### Semi Version

latest

### Current Behavior

失去焦点未触发`onBlur`
![20220907184533](https://user-images.githubusercontent.com/24400915/188859830-ff96ae99-7898-4fa8-92dc-12bc86c1a42d.gif)

### Steps To Reproduce

可在官网复现
```
import React from 'react';
import { Select } from '@douyinfe/semi-ui';

() => (
    <>
        <Select onBlur={() => console.log('blur!')} defaultValue='abc' style={{ width: 120 }}>
            <Select.Option value='abc'>抖音</Select.Option>
            <Select.Option value='ulikecam'>轻颜相机</Select.Option>
            <Select.Option value='jianying' disabled>剪映</Select.Option>
            <Select.Option value='xigua'>西瓜视频</Select.Option>
        </Select>
    </>
);
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
v2.17 对 Select 的 A11y 做了键盘和焦点支持改造。

有蓝色border的情况下，代表此时select还是聚焦的。只点击 option的情况下，焦点还是在trigger上的，可以通过键盘再进行打开。点击了外部的时候才是真正失焦，此时会触发 onblur。

![image](https://user-images.githubusercontent.com/88709023/188861618-d131fb33-cad1-4daa-8ad6-b07f329e0b62.png)

**Comment by zwlafk** [comment]
> v2.17 对 Select 的 A11y 做了键盘和焦点支持改造。
> 
> 有蓝色border的情况下，代表此时select还是聚焦的。只点击 option的情况下，焦点还是在trigger上的，可以通过键盘再进行打开。点击了外部的时候才是真正失焦，此时会触发 onblur。
> 
> ![image](https://user-images.githubusercontent.com/88709023/188861618-d131fb33-cad1-4daa-8ad6-b07f329e0b62.png)

现在点外部是不触发失焦的，我看已经有修复的PR了～
