### ISSUE TITLE
[BUG]在 Electron 中使用nav组件 显示不正常

### ISSUE THREAD

**Issue by VirtualHotBar** [DouyinFE/semi-design#1115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

nav

### Semi Version

2.18.2

### Current Behavior

![L~YKQ2D`L`QL7565)%DZ`)2](https://user-images.githubusercontent.com/96966978/189121249-be6b590d-f1d6-41d4-8248-9807d7f10c47.png)
点击时会有一个橙色的边框，焦点消失时变为正常

### Expected Behavior

![IE8($N8{1 BSSTA@K~TFW@9](https://user-images.githubusercontent.com/96966978/189121556-d90bbd16-76ab-4c27-b1d1-5365bc7ea249.png)
焦点消失时变为正常

### Environment

```markdown
- OS:win11 
- browser:electron 8.5.5
```

**Comment by DaiQiangReal** [comment]
可以先给个 outline:none 临时解决下问题。 我们目前没有在 electron 上复现。理论上 electron 的行为和 chromium 应该是一致的。我们还在排查，在 safari 上是已知问题。 @VirtualHotBar
