### ISSUE TITLE
[BUG]  Skeleton Use with Avatar,  exist ts type error

### ISSUE THREAD

**Issue by xiaoping027** [DouyinFE/semi-design#1117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Skeleton.Avatar

### Semi Version

2.15.1

### Current Behavior

![image](https://user-images.githubusercontent.com/17611082/189326677-6f21ca33-8451-46cf-8199-ad2bf0589838.png)

### Expected Behavior

TS right

### Steps To Reproduce

import  Skeleton

Skeleton.Avatar

set Skeleton.Avatar

### ReproducibleCode

```markdown
<Skeleton placeholder={<Skeleton.Avatar className={className} shape={shape} style={style} />} loading={loading}>
      <Avatar
        src={loadedSrc}
        alt=""
        className={className}
        shape={shape}
        style={style}
      />
    </Skeleton>
```

### Environment

```markdown
semi:2。15.1
```

### Anything else?

no

**Comment by MuxinFeng** [comment]
这个需要加个配置，然后根据这个配置写点样式，难度不大，但这个配置是否有必要呢？加载期间，`avatar`是正方形还是圆形有那么大必要吗，大佬你觉得？要是必要的话，我提个PR @pointhalo

**Comment by MuxinFeng** [comment]
嗯，有道理，我的解决方案有点局限于眼前的问题了。您的思路可能是将 avatar 原生 api 都能传给它，这样也能适配更多问题。

**Comment by MuxinFeng** [comment]
但如果就在骨架屏这个场景，我认为 avatar 就是一个用来占位的 div ，目前源码里也是这么实现的，比如它实现圆角也是通过 css 而非自己的 api 实现的
![Uploading image.png…]()

**Comment by pointhalo** [comment]
> 嗯，有道理，我的解决方案有点局限于眼前的问题了。您的思路可能是将 avatar 原生 api 都能传给它，这样也能适配更多场景。

抱歉，重新看了下代码。你的理解是对的，我原先的理解是错的。我刚开始以为 Skeleton import 了 avatar组件，然后中间的类型传导除了问题。但实际上，这里确实是如你所说，是通过css直接模拟样式实现的。然后只支持了size属性，没有支持其他。

![image](https://user-images.githubusercontent.com/88709023/189889887-98d3a1ba-2f89-4911-96c1-16d5ced60c02.png)

**Comment by pointhalo** [comment]
> 这个需要加个配置，然后根据这个配置写点样式，难度不大，但这个配置是否有必要呢？加载期间，`avatar`是正方形还是圆形有那么大影响吗，大佬你觉得呢？要是必要的话，我提个PR @pointhalo

可以做下增强，加下对应样式。欢迎 PR~

**Comment by MuxinFeng** [comment]
好的，我提一个

**Comment by MuxinFeng** [comment]
麻烦大佬cc，相关文档也补充好了 https://github.com/DouyinFE/semi-design/pull/1119

**Comment by pointhalo** [comment]
support v2.20.0-beta.0
