### ISSUE TITLE
[BUG] Tree 组件搜索字段全部删除后，filterTreeNode未触发

### ISSUE THREAD

**Issue by GoldSubmarine** [DouyinFE/semi-design#1125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Tree

### Semi Version

latest

### Current Behavior

我使用Tree组件的高级自定义功能，想在搜索时，实现匹配label文字高亮的功能（就像semi自己实现的一样），所以使用 filterTreeNode 去获取到用户输入的值，但是我发现当全部删除过滤字段时，也就是input的值为undifined的时候，filterTreeNode不会被触发

### Expected Behavior

期望搜索框最后一个字符被删除时，也触发filterTreeNode事件

### ReproducibleCode

```markdown
`filterTreeNode={i=> console.log(i)}`

输入几个字符，然后依次删除他们，注意删除最后一个字符时，上述函数不会执行
```

### Environment

```markdown
- OS: 
- browser:
```

**Comment by YyumeiZhang** [comment]
filterTreeNode 在搜索框最后一个字符被删除时没有触发是符合预期的，当input的最后一个字符被删除时候，认为是没有筛选，所以不进行任何筛选行为。

**Comment by YyumeiZhang** [comment]
对于用户而言，的确没有办法感知到搜索框的最后一个字符被删除（input从有值到空的这个动作）

**Comment by YyumeiZhang** [comment]
@GoldSubmarine 如果想要感知到搜索框的最后一个字符被删除，获取可以考虑设置 searchRender 自定义搜索框， 扩展下onChange
![image](https://user-images.githubusercontent.com/101110131/190944337-b62361cb-7cd3-46dc-9be5-e562e230acfe.png)

**Comment by GoldSubmarine** [comment]
> filterTreeNode 在搜索框最后一个字符被删除时没有触发是符合预期的，当input的最后一个字符被删除时候，认为是没有筛选，所以不进行任何筛选行为。

交给 filterTreeNode 由这个函数决定不进行任何筛选，这样处理也没有问题吧，。

既然开启了这个函数，自然期望掌控所有的过滤行为(包括undifined)，感觉可以让它的功能边界更大一点

**Comment by YyumeiZhang** [comment]
@GoldSubmarine v2.43.0在 renderFullLabel 中透传了 searchWord，应该能够更满足自定义渲染项的功能
![image](https://github.com/DouyinFE/semi-design/assets/101110131/955640ae-6958-40b7-884f-4737f8cd6526)
