### ISSUE TITLE
[Table] 表格组件是否有总结栏的支持

### ISSUE THREAD

**Issue by cnTrent** [DouyinFE/semi-design#1127]
### Which Component Need Enhancement 期望新增功能的组件
- Table

### What does the proposed API look like 期望支持的API
表格组件是否有支持总结栏summary

### Feature Description 功能描述
例如这种
![image](https://user-images.githubusercontent.com/35205692/190944786-ac702169-ce03-4dd6-a969-d548109fe6fd.png)

**Comment by pointhalo** [comment]
可以通过自己控制column render来实现。判断当前处于最后一行时，自己控制内容就好。

**Comment by xmsz** [comment]
希望组件能默认支持 自己操控有点麻烦

**Comment by pointhalo** [comment]
PR welcome～

> 希望组件能默认支持 自己操控有点麻烦
