### ISSUE TITLE
Notification 组件样式问题

### ISSUE THREAD

**Issue by TaroXin** [DouyinFE/semi-design#113]
### Which Component 出现bug的组件
  - Notification

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 黑色主题下正常显示

### Actual result 实际的结果是什么
  - 黑色主题下背景色是透明的

### Steps to reproduce 复现步骤
  - 1
![image](https://user-images.githubusercontent.com/19855713/139202896-7175901a-9143-43cf-93b0-bf27d4c2382a.png)

不知道是不是因为我自己的问题

**Comment by pointhalo** [comment]
@Carlosfengv 确认下，暗色模式下，这个透明度是否符合预期？

**Comment by YannLynn** [comment]
v2.2.0-beta.1 fixed
