### ISSUE TITLE
[Image] Image以及ImagePreview在哪个版本释出？

### ISSUE THREAD

**Issue by NorColumba** [DouyinFE/semi-design#1131]
你好，我在官网上看到Image，ImagePreview 组件 ，并未找到版本对比。
@douyinfe/semi-ui里面也没有引出，请问是还未释出吗？

**Comment by NorColumba** [comment]
![image](https://user-images.githubusercontent.com/57288432/191066384-da60b972-42ae-43d9-ba80-b1c7107e7e04.png)

**Comment by pointhalo** [comment]
应当是跟随昨天的 2.20.0-beta.0。看了一下，一个依赖包（@douyinfe/semi-foundation）的产物有问题，导致引入会报错。
![image](https://user-images.githubusercontent.com/88709023/191166166-40bf6d46-5c83-435a-9b92-7062684e438e.png)

我重新发布了一次，现在你使用 @douyinfe/semi-ui@2.20.0-beta.1 应该是ok的了
