### ISSUE TITLE
[Typography] Add `<Numeral />` component for number formatting

### ISSUE THREAD

**Issue by uiuing** [DouyinFE/semi-design#1136]
### Which Component Need Enhancement 期望新增功能的组件
- Typography

### What does the proposed API look like 期望支持的API
Typography.Numeral

### Feature Description 功能描述
Custom number formats can control the display of numbers, dates, times, fractions, percentages, and other numeric values. 

It might look like this when used:
``` javascript
import React from 'react';
import { Typography } from '@douyinfe/semi-ui';

function Demo() {
    const { Numeral } = Typography;
    return (
        <div>  
            <Numeral rule='currency'  precision={2}>
                   1000.2 ¥
            </Numeral>
            <br />
            <Numeral rule='bytes-binary'>
                   1024
            </Numeral>
            <br />
            <Numeral rule='exponential'>
                   1123456789
            </Numeral>
        </div>
    );
}
```

``` text
1,000.20 ¥

1KiB

1e+9
```

It also inherits the attribute of <Text />.
In addition it is possible to customise the formatting rules method:
``` javascript
<Numeral 
    type='warning' 
    copyable={true} 
    parser={(oldValue:string):string => { ...; return newValue }}
>
      1+1
</Numeral>
```

### Additional information 补充说明
I applied semi to the backend system and found it unfortunate that `<InputNumber />` was supported but not the formatted presentation of number.

However, I'm not sure if my judgement is accurate or not, so I'll need to trouble you to judge and if appropriate I'll still try to add this content for reference.

**Comment by pointhalo** [comment]
Discuss with our designer. The scenario you mentioned is very useful. We think this is a reasonable need.

**Comment by YyumeiZhang** [comment]
v2.22.0-beta.0已发版
