### ISSUE TITLE
[BUG] Next.js Input React Hydration Error and  useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by 0x30** [DouyinFE/semi-design#1140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Input

### Semi Version

2.19.0

### Current Behavior

```
Warning: Prop `style` did not match. Server: "null" Client: "padding-left:"
```

### Steps To Reproduce

1. pnpm create vite -> choose next,js
2. setp semi ui
3. use <Input>

### ReproducibleCode

```markdown
import { Input } from '@douyinfe/semi-ui'

function MyApp({ Component, pageProps }: AppProps) {
  return <Input></Input>
}
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by 0x30** [comment]
Is it normal to use 'suppressHydrationWarning' to solve the problem?

**Comment by 0x30** [comment]
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at SemiField (webpack-internal:///./node_modules/.pnpm/registry.npmmirror.com+@douyinfe+semi-ui@2.19.0_biqbaboplfbrettd7655fr4n2y/node_modules/@douyinfe/semi-ui/lib/cjs/form/hoc/withField.js:87:33)
```

**Comment by zieen** [comment]
Same Issue while using Select from Form

**Comment by pointhalo** [comment]
I feel that you have two different questions?
1. In the given demo code, there is an input component, this component does not involve Semi Field, it's not relative with useLayoutEffect
2. Only Form related components are related to useLayoutEffect

**Comment by pointhalo** [comment]
If there is a warning when using the Form component, I can reproduce this problem locally.

**Comment by 0x30** [comment]
非常感谢回复

https://github.com/0x30/my-next-semi-app 这个项目

可以重现 `Warning: Prop `style` did not match. Server: "null" Client: "padding-left:"` 的问题。  

![image](https://user-images.githubusercontent.com/6121524/192280276-e820f35e-8711-4204-8232-d35cdcf27219.png)


是的，确实是两个问题的。当时第一个问题 发现 `suppressHydrationWarning `可以解决之后，我不确定这是不是大家都知道的常规操作，所以关闭了，当然再次遇到  useLayoutEffect  的问题时候，觉得他们都是 ssr 的问题，所以就放到一起了

**Comment by pointhalo** [comment]
> https://github.com/0x30/my-next-semi-app 这个项目
> 
> 可以重现 `Warning: Prop `style` did not match. Server: "null" Client: "padding-left:"` 的问题。
> 
> ![image](https://user-images.githubusercontent.com/6121524/192280276-e820f35e-8711-4204-8232-d35cdcf27219.png)
> 
> 是的，确实是两个问题的。当时第一个问题 发现 `suppressHydrationWarning `可以解决之后，我不确定这是不是大家都知道的常规操作，所以关闭了，当然再次遇到 useLayoutEffect 的问题时候，觉得他们都是 ssr 的问题，所以就放到一起了

试了下你提供的项目。这个仅在 React 18时会有这个warning。 16/17都不会有这个问题（也是为什么我一开始没复现的原因）。具体原因我们后续再看一下。

**Comment by pointhalo** [comment]
已明确具体问题如下： 

A. NextJs + React 18 下，使用 Input 会有关于 props.style 的warning ，react 17不会


B. NextJs 下 使用withField 或 基于 withField封装的组件，例如 Form.Input、Form.Select、Form.xx 等会有warning

**Comment by pointhalo** [comment]
问题B已经修复。 v2.20.3

**Comment by pointhalo** [comment]
问题A 我单独再开个 Issue吧，这个先关掉。因为与 Issue Title 相关联的其实是问题B。
