### ISSUE TITLE
[BUG] <title>InputNumber 设置innerButtons={true}后bug

### ISSUE THREAD

**Issue by 17839359913** [DouyinFE/semi-design#1144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

InputNumber

### Semi Version

2.19.0-beta.0

### Current Behavior

1.点击聚焦
2.点击步进器按钮
3.点击其它地方
问题：foucs样式依然存在

### Expected Behavior

foucs样式消失

### Steps To Reproduce

1.点击聚焦
2.点击步进器按钮
3.点击其它地方
问题：foucs样式依然存在

### ReproducibleCode

```markdown
<InputNumber innerButtons={true} suffix={'小时'} defaultValue={1} style={{ width: 190 }} />
```

**Comment by Dawnwangzi** [comment]
+1 我也遇到了

**Comment by Junaid300** [comment]
Is someone working on this bug? I am interested to work on it.
So expected behavior should be:
when click up/down button focus should disappear. right ? I will take a deep look to this bug.

**Comment by YyumeiZhang** [comment]
> Is someone working on this bug? I am interested to work on it. So expected behavior should be: when click up/down button focus should disappear. right ? I will take a deep look to this bug.

Welcome PR！

**Comment by Junaid300** [comment]
The thing i figure out is  by default  innerButtons is true and `<InputNumber/>` it works totally fine. If we pass `<InputNumber innerButtons={true} />` Focus cause issue.

**Comment by Junaid300** [comment]
@YyumeiZhang 
I have forked the project and when I run `git clone <path>`.  It start cloning but after cloning, it compresses the project, and then through this error
 
```
remote: Enumerating objects: 22927, done.
remote: Counting objects: 100% (2308/2308), done.
remote: Compressing objects: 100% (1092/1092), done.
remote: Total 22927 (delta 1333), reused 2084 (delta 1188), pack-reused 20619
Receiving objects: 100% (22927/22927), 18.81 MiB | 58.00 KiB/s, done.
Resolving deltas: 100% (14559/14559), done.
error: invalid path '.github/workflows/test:coverage.yml'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by YyumeiZhang** [comment]
> 

Have you encountered similar problems when cloning other projects? I didn't have a similar problem on Mac OS, maybe you can try the workaround here https://stackoverflow.com/questions/39542177/warning-clone-succeeded-but-checkout-failed

**Comment by Junaid300** [comment]
@YyumeiZhang  thank you for sharing helpful like. For some reason i am able to solve this error but now i am getting a new error. I don't know is it right place to ask.
I have did 
```
git clone <path/>
npm install --global lerna yarn
npm run bootstrap
```
everything worked fine  but i when i run `npm start` 
i get this error.

![image](https://user-images.githubusercontent.com/66414908/200761294-fb12755f-eb47-403a-ad35-25a89083e703.png)

**Comment by YyumeiZhang** [comment]
> @YyumeiZhang thank you for sharing helpful resource. For some reason I am able to solve this error but now I am getting a new error. I don't know is it right place to ask. I have did
> 
> ```
> git clone <path/>
> npm install --global lerna yarn
> npm run bootstrap
> ```
> 
> everything worked fine but i when i run `npm start` i get this error.
> 
> ![image](https://user-images.githubusercontent.com/66414908/200761294-fb12755f-eb47-403a-ad35-25a89083e703.png)

en,  If you are on windows,the rm command is not available under this system, git bash may run such commands.

**Comment by Junaid300** [comment]
Is it targeting Mac and Linux OS for contributors? I will try it on Linux . But there should be support for window too. Just a suggestion.

**Comment by Junaid300** [comment]
@YyumeiZhang , i am wandering how can i open components in my browser instead of storybook? For example i want to access this route: `en-US/start/getting-started` on my local-machine ? Can i do so?

**Comment by YyumeiZhang** [comment]
> @YyumeiZhang , i am wandering how can i open components in my browser instead of storybook? For example i want to access this route: `en-US/start/getting-started` on my local-machine ? Can i do so?

try 
![image](https://user-images.githubusercontent.com/101110131/202948611-01908962-51be-4333-8dc1-667660eb83c7.png)
