### ISSUE TITLE
Switch组件不可用且未选中状态下hover背景色问题

### ISSUE THREAD

**Issue by ivan0525** [DouyinFE/semi-design#115]
### Which Component 出现bug的组件
  - Switch

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - Switch组件不可用且未选中状态下hover背景色不变

### Actual result 实际的结果是什么
  - Switch组件不可用且未选中状态下hover背景色会改变
 
![2021-10-28 16-05-28 2021-10-28 16_08_01](https://user-images.githubusercontent.com/42532333/139216272-54f4c3ab-627b-4479-9502-2cb39ebe0f46.gif)

### Steps to reproduce 复现步骤
  - 1 鼠标移入到不可用且未选中状态下Switch组件

### Additional information 补充说明
- [官网](https://semi.design/zh-CN/input/switch#%E4%B8%8D%E5%8F%AF%E7%94%A8)

**Comment by pointhalo** [comment]
@Dachang disabled态的hover color是保持不变还是需要有变化，我感觉现在有active态以及hover态应该是符合预期的？

**Comment by Dachang** [comment]
disabled态的hover color应保持不变

**Comment by pointhalo** [comment]
Related styles have been modified and will be released with the next patch version. (v2.0.2)
