### ISSUE TITLE
[DOC] 官方文档中引用 semi-webpack-plugin 的姿势不对

### ISSUE THREAD

**Issue by lavyun** [DouyinFE/semi-design#1158]
![image](https://user-images.githubusercontent.com/22797898/192700105-1af3c14e-19f0-4b10-b306-58a2202e4410.png)

源码中的 SemiWebpackPlugin  并不是 module.exports 默认导出的
![image](https://user-images.githubusercontent.com/22797898/192700196-e5d4a4d4-9d55-40f7-a1dd-07173d48d4f8.png)

真正使用的时候其实后面需要加上 default
```js
const SemiWebpackPlugin = require('@douyinfe/semi-webpack-plugin').default;
```

**Comment by pointhalo** [comment]
get。这里改漏了。我们更正一下
