### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by NicholasJupiter** [DouyinFE/semi-design#1167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

ButtonGroup

### Semi Version

^2.19.0

### Current Behavior

![image](https://user-images.githubusercontent.com/34204576/193414876-63a3e5e4-ff67-4b67-b2bd-ac4a33478816.png)
![image](https://user-images.githubusercontent.com/34204576/193414952-3facb4c4-ef43-4869-9f37-6d9eb0fe8004.png)

### ReproducibleCode

```markdown
<ButtonGroup>
              <Button
                type={accountConfig[account]?.open ? 'primary' : 'danger'}
                icon={accountConfig[account]?.open ? <IconPause /> : <IconPlay />}
                onClick={
                  () => setAccountConfig((config) => {
                    config[account].open = !config[account].open;
                    return { ...config };
                  })
                }
                key="play"
              >
                {accountConfig[account]?.open ? '开始中' : '已暂停'}
              </Button>
              <Button icon={<IconRefresh />} />
              <Button icon={<IconMore />} />
            </ButtonGroup>
```

### Environment

```markdown
- OS:
- browser:
- node: 16.14.2
- npm: 8.19.2
- react: 18.2
```

**Comment by NicholasJupiter** [comment]
const renderCol = () => accounts.map((account) => (
    <Col lg={12} span={24} key={account}>
      <Card>
        <div className="flex items-center py-2">
          <div className="account-name">
            <Typography.Text
              link={{
                href: `https://wax.bloks.io/account/${account}`,
                target: '_blank',
              }}
              copyable
            >
              {account}
            </Typography.Text>
          </div>
          <div className="ml-auto">
            <ButtonGroup>
              <Button
                type={accountConfig[account]?.open ? 'primary' : 'danger'}
                icon={accountConfig[account]?.open ? <IconPause /> : <IconPlay />}
                onClick={
                  () => setAccountConfig((config) => {
                    config[account].open = !config[account].open;
                    return { ...config };
                  })
                }
                key="play"
              >
                {accountConfig[account]?.open ? '开始中' : '已暂停'}
              </Button>
              <Button icon={<IconRefresh />} />
              <Button icon={<IconMore />} />
            </ButtonGroup>
          </div>
        </div>
        <TableBalance fetchBalances={fetchBalances} account={account} />
        <Tools account={account} />
      </Card>
    </Col>
  ));

**Comment by NicholasJupiter** [comment]
```javascript
const renderCol = () => accounts.map((account) => (
    <Col lg={12} span={24} key={account}>
      <Card>
        <div className="flex items-center py-2">
          <div className="account-name">
            <Typography.Text
              link={{
                href: `https://wax.bloks.io/account/${account}`,
                target: '_blank',
              }}
              copyable
            >
              {account}
            </Typography.Text>
          </div>
          <div className="ml-auto">
            <ButtonGroup>
              <Button
                type={accountConfig[account]?.open ? 'primary' : 'danger'}
                icon={accountConfig[account]?.open ? <IconPause /> : <IconPlay />}
                onClick={
                  () => setAccountConfig((config) => {
                    config[account].open = !config[account].open;
                    return { ...config };
                  })
                }
                key="play"
              >
                {accountConfig[account]?.open ? '开始中' : '已暂停'}
              </Button>
              <Button icon={<IconRefresh />} />
              <Button icon={<IconMore />} />
            </ButtonGroup>
          </div>
        </div>
        <TableBalance fetchBalances={fetchBalances} account={account} />
        <Tools account={account} />
      </Card>
    </Col>
  ));
```

**Comment by pointhalo** [comment]
![image](https://user-images.githubusercontent.com/88709023/194685460-2bb98e89-9d6a-4c9a-a11f-1dd47c9491ab.png)

please update version of semi-ui
