### ISSUE TITLE
[BUG] AutoComplete onSelect 拿到的参数类型与实际的 ts 提示不一致

### ISSUE THREAD

**Issue by yuanzhixiang** [DouyinFE/semi-design#1180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

AutoComplete

### Semi Version

2.20.4

### Current Behavior

AutoComplete 这个组件的泛型参数不对，按照 ts 的提示，data 的类型和 onSelect 的类型一致，但实际上获取到的是 T 中的 value
<img width="597" alt="image" src="https://user-images.githubusercontent.com/25138766/195024243-fd944c09-c106-430f-98c2-696706542620.png">

### Expected Behavior

期望和 ts 提示的表现一致

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
onSelect 的入参类型受另外的开关影响，可能存在两种形式。如果 onSelectWithObject 为true的情况下，会是object类型。
![image](https://user-images.githubusercontent.com/88709023/195327000-d97164de-c51f-4272-a6f0-4ef8be6253e2.png)

其次 props.data 既允许字符串数组，也允许对象数组。所以这里用的泛型做类型定义。
它的类型其实是跟运行时传入的参数相关的。
