### ISSUE TITLE
[BUG] foundation 中使用了可能只有react专有的属性`e.nativeEvent`,`e.persist`, `**ref.current`。还有  image 和rating 含有React Type

### ISSUE THREAD

**Issue by rashagu** [DouyinFE/semi-design#1189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

foundation: inputNumber, autoComplete, image ,checkbox, table, slider, textarea

### Semi Version

2.21.1

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
Thanks for your feedback🤝, I will release a patch version to fix it next week

**Comment by pointhalo** [comment]
@shijiatongxue eslint-plugin-semi-design再里加一个对 foundation 中 interface 的类型检测？现在code review容易因为代码太多漏掉。

**Comment by shijiatongxue** [comment]
好的，还有这种使用方式

<img width="612" alt="image" src="https://user-images.githubusercontent.com/26477537/195825778-903512d7-2d4b-4162-acb9-5e24c9e48c81.png">

**Comment by pointhalo** [comment]
v 2.22.0-beta.0 fix
