### ISSUE TITLE
期望文档内容与超链接导航栏不重合

### ISSUE THREAD

**Issue by 1771346368** [DouyinFE/semi-design#12]
### 文档内容与超链接导航栏重合

或许可以控制文档内容宽度🤔

![image](https://user-images.githubusercontent.com/35482197/138804167-f5fdf805-2d58-4451-8c25-67d98c1d5bbb.png)

**Comment by DaiQiangReal** [comment]
Fixed. https://github.com/DouyinFE/semi-design/commit/fd3a46d33bb0c7a7831eed36d765c0d9421f2cc4
