### ISSUE TITLE
[BUG] DatePicker UI shifting after range start is selected  on right panel

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

DatePicker

### Semi Version

lastest

### Current Behavior

![bug-datePicker-ui-shifting](https://user-images.githubusercontent.com/26477537/198499976-a67d98f5-1655-47c2-915f-40c6c5fb594e.gif)

### Steps To Reproduce

1. open date range picker
2. select a data on right panel
3. the selected date jump to left panel

### ReproducibleCode

```markdown
import React from 'react';
import { DatePicker } from '@douyinfe/semi-ui';

() => <DatePicker type="dateRange" style={{ width: 260 }} onChange={console.log} />;
```

**Comment by edc-hui** [comment]
这个应该不是bug吧，那么无论是左panel选中的日期还是右panel选中的日期，只要聚焦在哪个框，那么选中的日期就会填充到对应聚焦的框里。看了很多组件库的DatePicker ，都是这么交互的。

**Comment by pointhalo** [comment]
> 这个应该不是bug吧，那么无论是左panel选中的日期还是右panel选中的日期，只要聚焦在哪个框，那么选中的日期就会填充到对应聚焦的框里。看了很多组件库的DatePicker ，都是这么交互的。

【聚焦在哪个框，那么选中的日期就会填充到对应聚焦的框里】这个是没错的，也是符合预期的。

这个issue 截屏示意里不符合预期的点，主要是，当进行选择 start操作时，如果点击的是右侧panel，自动将右侧panel切换到了左侧panel（即任何情况下都认为start panel在左边），导致了必须再次移动鼠标，才能继续做选择操作。
打断操作导致不够友好。

**Comment by pointhalo** [comment]
fix 2.28.1
