### ISSUE TITLE
[BUG] Select、Popover、Tooltip 等关闭是会闪烁

### ISSUE THREAD

**Issue by moonsky-all** [DouyinFE/semi-design#1225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select、Popover、Popconfirm 等组件

### Semi Version

2.22.0

### Current Behavior

Select、Popover、Tooltip 等气泡型组件在关闭时会闪烁

### Expected Behavior

不希望闪烁

### ReproducibleCode

```markdown
<Tooltip content="Tips">
  <Button icon={(<IconFilter/>)} children={‘Save’}/>
</Tooltip>
```

### Environment

```markdown
- OS: Win10
- browser: Chrome 106
- pnpm: 7.1
- vite
- react: 18
```

**Comment by shijiatongxue** [comment]
可复现的 codesandbox：https://codesandbox.io/s/react18-semi2-22-7yui5y

录屏效果出不来，直接看 codesandbox 吧。

![tooltip-bug-react18](https://user-images.githubusercontent.com/26477537/198923036-60a0039f-b410-414d-af67-856d4fae9919.gif)

**Comment by shijiatongxue** [comment]
v2.22.2 fixed
