### ISSUE TITLE
[BUG] Popover 中的 Transfer 无法拖拽排序

### ISSUE THREAD

**Issue by moonsky-all** [DouyinFE/semi-design#1226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Popover, Transfer 

### Semi Version

2.22.0

### Current Behavior

1. 将穿梭框（Transfer）嵌入到气泡卡片（Popover）content 中；
2. 任意选择几个选项；
3. 在选中栏拖拽排序，此时 Popover 会关闭；
4. 且 Popover 关闭时会闪烁；

### Expected Behavior

Transfer 能在 Popover 中拖拽排序，且拖拽排序是Popover不会关闭

### Environment

```markdown
- OS: Win10
- browser: Chrome 106
- pnpm: 7.1
- vite
- react: 18.0.0
```

**Comment by pointhalo** [comment]
fix v.2.23.1

**Comment by moonsky-all** [comment]
Nice
