### ISSUE TITLE
[BUG] NavItem中的li元素面积比它包裹的a元素的大, 导致触发了onSelect但是没有触发a元素的跳转

### ISSUE THREAD

**Issue by Almagestum469** [DouyinFE/semi-design#1234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Nav

### Semi Version

2.22.2

### Current Behavior

<img width="223" alt="image" src="https://user-images.githubusercontent.com/14080372/199420955-df5bcc7b-be41-4dcb-a743-bc1fba98fe9f.png">
点击浅绿色的地方会触发onSelect, 使item被选中, 但是没有跳转, 产生让人疑惑的结果

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
并非是点击一定就会跳转。点击跟跳转是两个正交的行为。并不强关联。

是否跳转取决于你有没有配置 link（当配置link时，Item会被 a 标签包裹）。

如果说你在 text传入了 reactNode，它本身的热区就是蓝色部分，那点击绿色区域自然不属于它的响应范围。

**Comment by pointhalo** [comment]
更正一下，我上面的说法有误。
我猜你现在应该就是已经配置了 link，然后发现 a 标签的控制范围只有蓝色部分。所以点击绿色区域不会触发跳转，对吧？

问题 get，这个场景我们处理一下。

**Comment by Almagestum469** [comment]
> 更正一下，我上面的说法有误。 我猜你现在应该就是已经配置了 link，然后发现 a 标签的控制范围只有蓝色部分。所以点击绿色区域不会触发跳转，对吧？
> 
> 问题 get，这个场景我们处理一下。

是的
