### ISSUE TITLE
[BUG] Input 派生的其他 Input 类组件点击前/后缀 不会正常focus

### ISSUE THREAD

**Issue by wiseqingyang** [DouyinFE/semi-design#1237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

InputNumber TimePicker 等

### Semi Version

2.22.0

### Current Behavior

点击 `<InputNumber />` 的前缀或后缀后，输入框会高亮，但是 `<input />` 元素并未自动 `focus`，点击其他区域后，高亮不消失

### Expected Behavior

- 点击前后缀正常 focus 
- 点击其他区域取消高亮

### ReproducibleCode

```markdown
<InputNumber prefix="年龄" />
```

### Environment

```markdown
- OS: macOS Monterey
- browser: Edge 107
```

### Anything else?

经过查看源码，发现当 `Input` 组件被传入 `forwardRef ` 属性时，不会保留 `<input />` 元素的 `ref`
https://github.com/DouyinFE/semi-design/blob/48f6ee8bfcac609d5fc890058be31b647072bf73/packages/semi-ui/input/index.tsx#L435
https://github.com/DouyinFE/semi-design/blob/48f6ee8bfcac609d5fc890058be31b647072bf73/packages/semi-ui/input/index.tsx#L501
在 `prefix/suffix` 的点击事件中无法触发元素的 `focus` 事件

**Comment by edc-hui** [comment]
该bug和 #1144 bug产生的原因一样，都是input组件中ref拿不到input 的DOM导致的。PR合并之后会顺带着解决#1144的问题

**Comment by YyumeiZhang** [comment]
问题已于版本2.24.0修复
