### ISSUE TITLE
[Docsite] 分裂按钮 demo 存在错误

### ISSUE THREAD

**Issue by lorcannn** [DouyinFE/semi-design#1254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

组件文档中分裂按钮组合的 demo 点击该按钮后交互异常
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/56643497/200989434-5b562939-0fbc-4fde-808a-05a14f014c1c.png">

### Expected Behavior

期待点击 DropDwon 按钮后展示菜单

### Environment

```markdown
- OS: macOS 12.6
- browser: Chrome 106.0.5249.91（正式版本） (arm64)
```

### Anything else?

初步定位为 demo 中的示例代码存在语法错误（newBtnVisible 变量未声明）所导致。我可以尝试提个 PR。
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/56643497/200990167-36b56def-da23-4c97-9b6b-c7e7f8d81e2c.png">

**Comment by pointhalo** [comment]
welcome pr ~

**Comment by lorcannn** [comment]
> 

我尝试 fork 代码并在本地跑起来，发现相同环境在本地未复现官方文档的问题。
我执行了如下操作：
1. `yarn docsite` 未在本地复现问题
2. 
```
yarn build:gatsbydoc
serve build
```
未在本地复现问题
@pointhalo 看来这个问题不是我初步定位的原因（demo 中的示例代码存在语法错误）所引发的。

**Comment by pointhalo** [comment]
重新看了下，这个应该是 Dropdown A11y 关联（展现后对元素进行聚焦）的问题，文档中的未声明variable不是主要问题。我们来跟进吧。

**Comment by YannLynn** [comment]
fixed in V2.23.1
