### ISSUE TITLE
Table组件，rowSelection添加受控的selectedRowKeys，第二页选择后，页码以及数据会回到第一页

### ISSUE THREAD

**Issue by LouXuehui** [DouyinFE/semi-design#1256]
这个是bug还是需要什么操作，示例里也是有这个问题的
![c75fd742-39df-4cb2-9f8a-8241219baf00](https://user-images.githubusercontent.com/34302000/201044487-4bc46d81-d695-4c2c-b21c-ff8b71bdd09f.jpeg)

**Comment by shijiatongxue** [comment]
Table 的 dataSource 更新时，会回到首页。可以把 dataSource useMemo 一下或者存在 state 里。
