### ISSUE TITLE
[BUG] 关闭SideSheet会闪烁

### ISSUE THREAD

**Issue by csshidi** [DouyinFE/semi-design#1257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

SideSheet

### Semi Version

2.22.

### Current Behavior

关闭SideSheet侧边栏会闪烁

### Expected Behavior

正常关闭，不闪烁

### Steps To Reproduce

1. 使用Vite创建React项目，pnpm安装@douyinfe/semi-ui
2. App引入SideSheet组件
3. 测试打开关闭SideSheet

### ReproducibleCode

```markdown
import { useState } from 'react'
import { SideSheet, Button } from '@douyinfe/semi-ui'

function App() {
  const [visible, setVisible] = useState(false)

  return (
    <div className="App">
      <Button onClick={() => setVisible(true)}>打开侧边栏</Button>
      <SideSheet placement="left" visible={visible} onCancel={() => setVisible(false)}>
        <h1>侧边栏</h1>
      </SideSheet>
    </div>
  )
}

export default App
```

### Environment

```markdown
- OS: Win10
- browser: Chrome
```

### Anything else?

![动画](https://user-images.githubusercontent.com/17515153/201247961-f77aecb3-9da3-4be7-9cb2-6f1b7d56bb13.gif)

**Comment by pointhalo** [comment]
react 18 ?

**Comment by csshidi** [comment]
> react 18 ?

是的，与这个有关吗

**Comment by pointhalo** [comment]
@DaiQiangReal 确认下是否也是需要加 animation-fill-mode 配置

**Comment by pointhalo** [comment]
> > react 18 ?
> 
> 是的，与这个有关吗

有关系。你换到17 以下应该是没问题的。

18下的这个问题我们也会fix。

**Comment by csshidi** [comment]
> > > react 18 ?
> > 
> > 
> > 是的，与这个有关吗
> 
> 有关系。你换到17 以下应该是没问题的。
> 
> 18下的这个问题我们也会fix。

确实如此，换到17.0.2就正常了

**Comment by pointhalo** [comment]
v2.25.0 fix
