### ISSUE TITLE
[Global] 提供解决与其他库（例如 tailwindcss）的潜在样式冲突的办法

### ISSUE THREAD

**Issue by ylc395** [DouyinFE/semi-design#1261]
与 tailwindcss 共用时，它的 preflight 样式的 <style> 标签总是出现在最后，覆盖了 semi-design 的一些样式：

<img width="434" alt="image" src="https://user-images.githubusercontent.com/12264626/201483539-8ab04980-c187-4b80-9d44-c78255ba0765.png">

可以参考这个组件库的做法：https://www.naiveui.com/zh-CN/os-theme/docs/style-conflict

**Comment by pointhalo** [comment]
目前我们仅发现 Button 会有这样的问题。还有其他组件吗？
如果只是极少部分组件，我们比较倾向于直接加大semi侧的权重来解决问题。

**Comment by yybawang** [comment]
不用引入 tailwindcss 的 base 部分，scss参考示例
```
@import "reset-css";    // 配合 semi 使用，因为 tw 的默认样式有冲突
//@import "tailwindcss/base.css";
@import "tailwindcss/components.css";
@import "tailwindcss/utilities.css";
```

**Comment by xmsz-stu** [comment]
现在会遇到tailwindcss无法覆盖semi的情况 好蛋疼

**Comment by linpan** [comment]
> 目前我们仅发现 Button 会有这样的问题。还有其他组件吗？ 如果只是极少部分组件，我们比较倾向于直接加大semi侧的权重来解决问题。

more components, not only button

**Comment by pointhalo** [comment]
v2.59.0 后提供了 css layer 能力，可更细粒度控制样式优先级问题。详见 https://semi.design/zh-CN/start/tailwind

**Comment by viocha** [comment]
> v2.59.0 后提供了 css layer 能力，可更细粒度控制样式优先级问题。详见 https://semi.design/zh-CN/start/tailwind

tailwind V4会支持吗
