### ISSUE TITLE
[BUG]  Input框引入报错server:null, Client:"padding-left"

### ISSUE THREAD

**Issue by Circkoooooo** [DouyinFE/semi-design#1262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Input

### Semi Version

2.23.1

### Current Behavior

在nextjs框架中使用Input框，没有给它添加任何的props，报错
![图片](https://user-images.githubusercontent.com/75945382/201514148-396c4091-26cb-4ca5-a8e0-984a420a7f43.png)

### Expected Behavior

不报错

### Steps To Reproduce

1. 配置nextjs的semi
2. 引入Input
```import { Input} from '@douyinfe/semi-ui';```
4. 
```
<SemiInput	
	className={search_input}
	placeholder={'输入文字'}
	prefix={<IconSearch />}
></SemiInput>
```

### ReproducibleCode

```markdown
<SemiInput	
	className={search_input}
	placeholder={'输入文字'}
	prefix={<IconSearch />}
></SemiInput>
```

### Environment

```markdown
- OS:win11
- browser:firefox
```

### Anything else?

none

**Comment by pointhalo** [comment]
#1181 如果对react 版本没有硬性要求，可以先换到17
这个问题仅在 react 18下出现

具体原因之前还没有时间跟进。我们再看一下。

如果有时间也欢迎PR~

**Comment by pointhalo** [comment]
试一下 v2.23.2

**Comment by Circkoooooo** [comment]
> 试一下 v2.23.2

好的 谢谢

**Comment by Circkoooooo** [comment]
> 试一下 v2.23.2

v2.23.2 解决了，没有报错了
