### ISSUE TITLE
[Style] TagInput、TimePicker in  InputGroup ，style is incorrect

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#1268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

InputGroup、TagInput、TimePicker

### Semi Version

2.23

### Current Behavior

- Timepicker
  - style：left border-radius is incorrect
![image](https://user-images.githubusercontent.com/88709023/201657917-bfd44620-36f0-432f-af2f-853a13051bef.png)
```
      <InputGroup>
            <Input placeholder="Name" style={{ width: 100 }} />
            <TimePicker placeholder="Score" style={{ width: 140 }} />
        </InputGroup>
```

- TagInput（Not supported now）
  - style：height、border-radius is incorrect
![image](https://user-images.githubusercontent.com/88709023/201657994-c1fccbc4-a92e-4aca-8642-5f266b957ccc.png)

```
      <InputGroup>
            <Input placeholder="Name" style={{ width: 100 }} />
            <TagInput placeholder="Score" style={{ width: 140 }} />
        </InputGroup>
```

### Expected Behavior

same as datepicker/cascader / select ...

### Environment

```markdown
- OS:
- browser:
```

**Comment by andrewkykoo** [comment]
Hi @pointhalo, I would like to work on this issue! Thanks.

**Comment by pointhalo** [comment]
> Hi @pointhalo, I would like to work on this issue! Thanks.

Glad to hear that you are interested in participating in this project.  Welcome PR. 
About how to run this project, you can refer to [contribution](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING.md)

**Comment by pointhalo** [comment]
v2.25.0 fix
