### ISSUE TITLE
Nextjs13最新版支持吗？因为nextjs13改动较大

### ISSUE THREAD

**Issue by Alvazz** [DouyinFE/semi-design#1269]
请问Nextjs13最新版支持吗？因为nextjs13改动较大

**Comment by pointhalo** [comment]
1. 抱歉，我们还没有详细了解 next 13 具体做了哪些方面的变更。所以也没有进行过相关的测试。
2. Semi 作为 UI表现层的库，理论上不会有太多影响。可以试用，如果遇到问题，issue进行对应的反馈即可。相关问题我们会及时跟进处理。

**Comment by Alvazz** [comment]
感谢。
