### ISSUE TITLE
Tab 控件功能咨询

### ISSUE THREAD

**Issue by Alvazz** [DouyinFE/semi-design#1271]
请教一下作者，Semi里的 Tabs控件，可以像下面这张图片一样的效果吗？

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/50744096/201741193-5e4b61c0-8f23-4a29-8a33-8ee532ea3327.png">

如果可以的话，那么我想用 Tabs 控件来做主导航，是否可行？

**Comment by pointhalo** [comment]
tabs本身就提供了标签式的交互
![image](https://user-images.githubusercontent.com/88709023/201876390-41206d03-ab7d-4644-839d-72e6516efb8e.png)

颜色之类的样式你可以自己调（通过css覆盖的方式），或者通过在semi dsm中以 design token的方式调。

至于是否用作主导航，我理解这个取决于你们实际需求，我不清楚你的预期是什么，按照实际功能评估就好。
UI组件本身不做什么用途的限制。
