### ISSUE TITLE
[Image] 点击图片放大后，应该阻止用户滑动页面。

### ISSUE THREAD

**Issue by VanHoth** [DouyinFE/semi-design#1273]
### Which Component Need Enhancement 期望新增功能的组件
- Image

### Feature Description 功能描述
点击图片放大后，阻止用户滑动页面。

**Comment by edc-hui** [comment]
我来修复此问题

**Comment by VanHoth** [comment]
你好，我是小范，你的邮件我已经收到了

**Comment by YyumeiZhang** [comment]
V2.24.0-beta.0已发版
![image](https://user-images.githubusercontent.com/101110131/203245444-60287151-2971-479d-a825-b3f66994c110.png)
