### ISSUE TITLE
[Tree] 自定义 TreeNode 的 field

### ISSUE THREAD

**Issue by ylc395** [DouyinFE/semi-design#1274]
当前 Tree 组件接受的`treeData`，数据的 shape 必须满足 `TreeNode`。因此如果源数据不满足这个 shape，还得写个 transform 函数，每次re-render，还需要重新 transform。建议增加相关的 props，让 Tree 组件正确地使用源数据的相关 field。

类似 naive-ui 的以下 props：

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/12264626/202122880-dbbfb31a-eca3-461b-a52f-b5de2705af50.png">

或是 antd 的以下 prop：

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/12264626/202123053-9fe7db19-b9cb-4584-b99b-2e045d6c9abc.png">

**Comment by 1031531798** [comment]
同感 增加了不必要的数据处理开销

**Comment by YyumeiZhang** [comment]
功能已跟版本 v2.47.0-beta.0
