### ISSUE TITLE
[Navigation] 导航组件缺少getPopupContainer，处理不了局部亮暗模式

### ISSUE THREAD

**Issue by moondymo** [DouyinFE/semi-design#1277]
### Which Component Need Enhancement 期望新增功能的组件
- Navigation

### Feature Description 功能描述

导航组件缺少getPopupContainer，处理不了局部亮暗模式

**Comment by pointhalo** [comment]
下周  v2.24 提供

**Comment by YyumeiZhang** [comment]
v2.24.0-beta.0已发版
