### ISSUE TITLE
[Select] 提供 open API 供用户自行控制的选项面板开关

### ISSUE THREAD

**Issue by YyumeiZhang** [DouyinFE/semi-design#1280]
### Which Component Need Enhancement 期望新增功能的组件
- Select

### What does the proposed API look like 期望支持的API
open

### Feature Description 功能描述
目前 Select 中是单选场景下，选项面板选择即关闭；多选场景下，点击非面板和 trigger 的位置关闭，希望提供 open 参数，能够配合onVisibleChange选项，供用户自己自行控制的开关

需求场景： 单选场景下，在选项面板的 top or bottom slot 中有对选项排序的按钮，因此希望能够不单选时候不选择即关闭

**Comment by pointhalo** [comment]
ref method可做到类似交互，暂不提供受控 open形式。不倾向于由用户控制展开态。
