### ISSUE TITLE
[Image] 点击预览的 img 缺少crossOrigin的配置 

### ISSUE THREAD

**Issue by leenin** [DouyinFE/semi-design#1284]
### Which Component Need Enhancement 期望新增功能的组件
- Image

### Feature Description 功能描述
Preview内部的img希望能跟随Image配置的crossOrigin

**Comment by YyumeiZhang** [comment]
V2.24.0-beta.0已发版
![image](https://user-images.githubusercontent.com/101110131/203245143-8514ec98-5844-44e0-88ea-85d70db6fb20.png)
