### ISSUE TITLE
[BUG] <Select 设置getPopupContainer后样式错误>

### ISSUE THREAD

**Issue by 2513483494** [DouyinFE/semi-design#1288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select

### Semi Version

2.20.4

### Current Behavior

Select 设置getPopupContainer后样式错误
下拉框位置偏移了很多
<img width="416" alt="截屏2022-11-20 15 22 56" src="https://user-images.githubusercontent.com/48058550/202890722-a26ffd20-8659-47d8-b50b-b04cb9293492.png">

### Expected Behavior

下拉框不偏移

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
![image](https://user-images.githubusercontent.com/88709023/202951126-d5c71d4d-b01e-4bb0-94d4-492e12760d4b.png)
这个设置了吗？

**Comment by 2513483494** [comment]
> ![image](https://user-images.githubusercontent.com/88709023/202951126-d5c71d4d-b01e-4bb0-94d4-492e12760d4b.png) 这个设置了吗？

设置了，最后是绑定在距离select最近的父节点就正常了，不知道为啥。

**Comment by pointhalo** [comment]
> > ![image](https://user-images.githubusercontent.com/88709023/202951126-d5c71d4d-b01e-4bb0-94d4-492e12760d4b.png) 这个设置了吗？
> 
> 设置了，最后是绑定在距离select最近的父节点就正常了，不知道为啥。

如果你的 container本身有偏移（例如父级有一些位置属性设置），那可能位置依然不正确噢。
