### ISSUE TITLE
[DatePicker] 日期时间选择面板能不能剥离出来单独使用

### ISSUE THREAD

**Issue by moonsky-all** [DouyinFE/semi-design#1299]
### Which Component Need Enhancement 期望新增功能的组件
- DatePicker
- TimePicker

### Feature Description 功能描述

日期/时间选择面板能不能单独拿出来使用：
1.  有时候希望将日期选择面板静态放入到页面中更直观；
2. 有时候希望在选择面板之外有更多的行为，目前只能通过 topSlot 和 bottomSlot 来做，但是这样还是比较局限；

### Additional information 补充说明
1. 单独提取出来后可以释放 presets、topSlot、bottomSlot 的空间，有更强大的自定义能力；
2. 内部原本用在 Popover 的属性，可由户自己使用；

**Comment by shijiatongxue** [comment]
你好，这是一个很好的功能。比较遗憾，DatePicker 设计时面板和输入框耦合比较大，把面板拆出来比较复杂。短时间内可能无法支持。欢迎你为此功能提交 PR。

**Comment by xmsz-stu** [comment]
+1 要是datePicker和timePicker能剥离用就好了 因为有些页面直接展示日历和时间，用户选择更方便，现在还得点开。其次如果想在移动端实现自定义弹窗也不行
