### ISSUE TITLE
[Form Field]  希望表单控件设置showClear 时，能支持设置 clearIcon

### ISSUE THREAD

**Issue by moonsky-all** [DouyinFE/semi-design#1309]
### Which Component Need Enhancement 期望新增功能的组件
-  表单 输入控件，如 Input, Select 等

### What does the proposed API look like 期望支持的API
- clearIcon 用于设置 clear 图标

### Feature Description 功能描述
目前 DatePicker、Select 等表单输入控件设置 showClear 后，当有值时鼠标 hover 上去会显示清除图标，目前像 Select 可以设置 arrowIcon，希望清除图标也能像这样设置 clearIcon

**Comment by pointhalo** [comment]
👌，后续可以支持。

**Comment by pointhalo** [comment]
需要新增props支持的组件包括

- Input
- Select
- Cascader
- TagInput
- TimePicker
- DatePicker
- TreeSelect
- InputNumber

**Comment by pointhalo** [comment]
v2.25.0-beta.0 已提供。 
eg: 
```
<Input clearIcon={<IconSemiLogo />} />
```
