### ISSUE TITLE
[DatePicker] 日期选择器多选样式不统一

### ISSUE THREAD

**Issue by moonsky-all** [DouyinFE/semi-design#1310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

DatePicker

### Semi Version

2.23.0

### Current Behavior

![image](https://user-images.githubusercontent.com/82572484/204119602-f1e1e14e-6693-4a0a-97c3-d4df27fb3401.png)
![image](https://user-images.githubusercontent.com/82572484/204119610-299c6db1-f9e0-41da-8e78-d9964dfb4f09.png)

### Environment

```markdown
- OS:
- browser:
```

**Comment by shijiatongxue** [comment]
你好，这个确实是个交互不一致的地方。内部在 0.x 时也有注意到这个问题。当时是因为没有 TagInput 组件，因此没有做这个功能，现在 [TagInput](https://semi.design/zh-CN/input/taginput) 支持了，我们评估一下哈。

**Comment by moonsky-all** [comment]
感谢支持

**Comment by shijiatongxue** [comment]
暂无这样的设计，先关掉了
