### ISSUE TITLE
[BUG] input's prop extraText doesn't work in InputGroup

### ISSUE THREAD

**Issue by Benno-Wu** [DouyinFE/semi-design#1313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

input, textarea

### Semi Version

2.24.1

### Current Behavior

extraText does not render

### Expected Behavior

input's prop extraText works fine when input is children of inputGroup

### Steps To Reproduce

paste code into the live-demo
https://semi.design/zh-CN/input/form#%E4%BD%BF%E7%94%A8%20InputGroup%20%E7%BB%84%E5%90%88%E5%A4%9A%E4%B8%AA%20Field

### ReproducibleCode

```js
import React from 'react';
import { Form, Button } from '@douyinfe/semi-ui';

() => (
    <Form onSubmit={(values) => console.log(values)} labelPosition='top' style={{ width: 400 }}>
        <Form.InputGroup label={{ text: (<span>手机号码</span>), required: true }} labelPosition='top'>
            <Form.Input initValue='18912345678' style={{ width: 250 }} extraText='test' field='phoneNumber' rules={[{ required: true }]} showClear />
        </Form.InputGroup>
        <Form.Input field='姓名' trigger='blur' initValue='Semi' extraText='test'></Form.Input>
        <Button htmlType='submit'>提交</Button>
    </Form>
);

**Comment by pointhalo** [comment]
v 2.29.0-beta.0 已支持
