### ISSUE TITLE
[BUG] dark mode对部分组件内的样式不生效

### ISSUE THREAD

**Issue by xwzy** [DouyinFE/semi-design#1319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

dark mode

### Semi Version

2.24.2

### Current Behavior

div, h1 等标签的color没有变化

<img width="895" alt="image" src="https://user-images.githubusercontent.com/13077117/205478034-ff09d3f8-3654-4484-98db-d092dc5cacd8.png">

### Expected Behavior

浅色模式没有问题

<img width="897" alt="image" src="https://user-images.githubusercontent.com/13077117/205478044-0ec29c92-6bd6-471f-aed1-1bc90574c606.png">

### Steps To Reproduce

use dark mode

### ReproducibleCode

```markdown
function Demo() {
    const switchMode = () => {
        const body = document.body;
        if (body.hasAttribute('theme-mode')) {
            body.removeAttribute('theme-mode');
        } else {
            body.setAttribute('theme-mode', 'dark');
            window.setMode('dark');
        }
    };

    return (
        <Button
            onClick={switchMode}
        >
            Switch Mode
        </Button>
    );
}
```

### Environment

```markdown
- OS: macos
- browser: chrome 107.0.5304.121
```

### Anything else?

请问我是否遗漏了什么配置，十分感谢

**Comment by pointhalo** [comment]
给个codesandbox url？

你可以检查一下
![image](https://user-images.githubusercontent.com/88709023/205533871-0ebb5ef8-516d-4084-9a63-b522f1966804.png)
这部分区域具体现在生效的 backbackgroundColor、color 是什么值

正常情况下你在body上设过，子元素如果没有单独覆盖 color、backgroundColor属性，应该是 inherit继承自body。如果你们单独设了但是又没有使用 semi token作为值，而是用的绝对色值例如hex色值，那就没法自适应。

**Comment by pointhalo** [comment]
![image](https://user-images.githubusercontent.com/88709023/205543330-4abf90ff-20ad-483c-b2b6-d4194618095d.png)

css variable的语法不对。不需要引号。去掉就行。

**Comment by pointhalo** [comment]
这里的语法我们文档上也有误。我更正一下。
