### ISSUE TITLE
[BUG] Select使用optionList，label值相同时存在bug

### ISSUE THREAD

**Issue by ZhiguangXiong** [DouyinFE/semi-design#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select

### Semi Version

2.42.2

### Current Behavior

<img width="1327" alt="截屏2022-12-05 15 38 13" src="https://user-images.githubusercontent.com/25341976/205580735-18fe75d3-a5af-484a-b516-1cface7a8d11.png">

当label相同但value不同时，会同时选中多个label相同的选项（如图，两个“今日头条”的选项均被选中）

预期效果：仅选中value匹配的单个选项

### Expected Behavior

预期效果：仅选中value匹配的单个选项

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
可以看下一下 Select 的 FAQ
