### ISSUE TITLE
[DatePicker] 允许控制内嵌输入框的属性

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#1343]
### Which Component Need Enhancement 期望新增功能的组件
- DatePicker

### What does the proposed API look like 期望支持的API

- showClear
- placeholder：控制内嵌输入框的默认提示文本

**Comment by pointhalo** [comment]
内嵌输入框是否还有其他属性可能需要透传，直接暴露一个  insetInputProps ？

**Comment by shijiatongxue** [comment]
> 内嵌输入框是否还有其他属性可能需要透传，直接暴露一个 insetInputProps ？

可能有，可以暴露一个通用的，但因为有多个内嵌的输入框，一些属性 placeholder 这里还不太好控制。

**Comment by pointhalo** [comment]
> > 内嵌输入框是否还有其他属性可能需要透传，直接暴露一个 insetInputProps ？
> 
> 可能有，可以暴露一个通用的，但因为有多个内嵌的输入框，一些属性 placeholder 这里还不太好控制。

inputProps: {
 placeholder: ['left', 'right'] 
}

特殊的props搞成数组形式？

**Comment by shijiatongxue** [comment]
> > > 内嵌输入框是否还有其他属性可能需要透传，直接暴露一个 insetInputProps ？
> > 
> > 
> > 可能有，可以暴露一个通用的，但因为有多个内嵌的输入框，一些属性 placeholder 这里还不太好控制。
> 
> inputProps: { placeholder: ['left', 'right'] }
> 
> 特殊的props搞成数组形式？

数组是一个思路。现在 DatePicker 有一个数组类型的 placeholder 了。内嵌的不太好用这个，因为里面可能有四个内嵌的输入框，数组写四个我觉得很容易弄不清楚哪个是哪个。

这样可能好点。

```ts
interface InsetInputPlaceholder {
    dateStart: sting;
    dateEnd: string;
    timeStart: string;
    timeEnd: string;
}
```

**Comment by pointhalo** [comment]
v 2.29.0-beta.0
