### ISSUE TITLE
[Button] feature description for this component

### ISSUE THREAD

**Issue by Jiajun-Huang** [DouyinFE/semi-design#1354]
### Which Component Need Enhancement 期望新增功能的组件
- Upload, Form.Upload

### What does the proposed API look like 期望支持的API
特定事件发生时上传文件，或者不上传文件
### Feature Description 功能描述
有时候我只想使用 Upload 组件获取文件的reference，或者在表单的上传按钮按下之后上传文件， 并不想直接上传文件。
需要一个方法给Upload 传文件之后不直接开启上传。

**Comment by pointhalo** [comment]
https://semi.design/zh-CN/input/upload#%E6%89%8B%E5%8A%A8%E8%A7%A6%E5%8F%91%E4%B8%8A%E4%BC%A0
