### ISSUE TITLE
[Modal] Modal 去除标题,布局错乱

### ISSUE THREAD

**Issue by ZH-TX** [DouyinFE/semi-design#1359]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Which Component

Modal 模态对话框

### Semi Version

2.26.0

### 去除标题后, 布局错乱, 如图
1. 去除标题后, content 内容, 与头部的close按钮布局相互影响

![image](https://user-images.githubusercontent.com/48384297/210321037-79aa3831-63fb-44b0-ac31-b1af66e6305f.png)
![image](https://user-images.githubusercontent.com/48384297/210321229-a773f2d2-96be-44a6-9372-874f26aad145.png)

### 期望: 与未填写标题时样式保持一致
![image](https://user-images.githubusercontent.com/48384297/210321229-a773f2d2-96be-44a6-9372-874f26aad145.png)

### Steps To Reproduce

去除标题后, 
content 内容与 close 按钮flex 布局相互存在影响

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
这是符合预期的行为。x需要始终与内容保持平行。 header存在与否会影响 x close icon的位置结构。

**Comment by ZH-TX** [comment]
> 这是符合预期的行为。x需要始终与内容保持平行。 header存在与否会影响 x close icon的位置结构。

我的理解, 去除title与否, 组件的布局样式不应该改变吧,  去除标题后, x与content 左右布局, 这是组件特色呢?,

**Comment by pointhalo** [comment]
【x需要始终与首行文本保持平行】这是设计的初衷。留出一个空白的title区域与x平行不是我们想要的设计结果

**Comment by pointhalo** [comment]
可以理解为这是一个基于设计需求而特意这么做的布局。

**Comment by ZH-TX** [comment]
> 可以理解为这是一个基于设计需求而特意这么做的布局。

我觉得antd这部分就做的比较好, 兼容了两者行为, x单独绝对定位

**Comment by pointhalo** [comment]
1. 不同设计系统有不同的设计考量取舍。只能说这个不是semi 想要的设计样式，所以不会这么做。

2. btw，在semi的v0.x版本我们也是将 x 作为绝对定位去放置的，但内部实践下来对于我们的用户而言，并非是一个合适的设计。x绝对定位的坏处在于，对于超出不换行的 title而言，容易存在遮盖的现象。

![image](https://user-images.githubusercontent.com/88709023/210503204-4dda854f-b4b8-42b2-89f5-07d4114f9cdc.png)

![image](https://user-images.githubusercontent.com/88709023/210503252-a3f2e5dc-6318-4f1a-8355-d8b01891877d.png)
