### ISSUE TITLE
[BUG] 打开/关闭modal引发布局抖动

### ISSUE THREAD

**Issue by ForgQi** [DouyinFE/semi-design#1361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

layout 和 modal

### Semi Version

2.26.0

### Current Behavior

当前layout组件的className是稍后添加的`semi-layout semi-layout-has-sider`会引发布局较大变化出现滚动条，而当此时modal也在屏幕内时，modal会在此时计算滚动条宽度，导致随后打开、关闭模态框引发横向布局变化`width: calc(100% - xxpx);`

### Expected Behavior

不出现横向的伸缩

### ReproducibleCode
这里是一个可以复现的例子
```markdown
https://codesandbox.io/s/fragrant-night-s09u74?file=/index.js
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
v2.28.0-beta.0 fix
