### ISSUE TITLE
[Modal] onOk 、onCancel return值为 promise时，应该自动控制 button 的loading状态，对齐 popconfirm

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#1369]
### Which Component Need Enhancement 期望新增功能的组件
- Modal

### What does the proposed API look like 期望支持的API
- 如题

**Comment by pointhalo** [comment]
命令式调用有。声明式调用没有。应该对齐。

**Comment by YyumeiZhang** [comment]
v2.28.0-beta.0 已发版
