### ISSUE TITLE
[BUG] <title> Form.RadioGroup 组件 限定boolean值的问题

### ISSUE THREAD

**Issue by CharlieYu99** [DouyinFE/semi-design#1377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Form.RadioGroup

### Semi Version

2.26

### Current Behavior

用Form.RadioGroup实现二选一,限定style为boolean的情况下,Radio组件value只能为string/number (官方文档如此),但官方文档内有如下示例:代码无法复现.
![image](https://user-images.githubusercontent.com/34127055/211700515-93666582-b664-4ccb-a3d6-8a4d11997eec.png)
代码无法复现.
通过{/* @ts-ignore */} 忽略检验可以实现预期效果.

### Expected Behavior

用Form.RadioGroup实现限定数据类型为boolean的二选一

### ReproducibleCode

```markdown
文档内示例代码如下, 此代码无法正常运行
<RadioGroup field="isMonopolize" label='是否独占资源（Radio）' rules={[
    { type: 'boolean' },
    { required: true, message: '必须选择是否独占 ' }
]}>
    <Radio value={true}>是</Radio>
    <Radio value={false}>否</Radio>
</RadioGroup>
```

### Environment

```markdown
- OS:Win11
- browser:Chrome
```

### Anything else?

希望官方加入radio组件value属性boolean数据类型的支持

**Comment by pointhalo** [comment]
是指这样写会有 ts 类型报错吗？还是说 rules没有如期执行展示 error？@CharlieYu99

**Comment by CharlieYu99** [comment]
> 是指这样写会有 ts 类型报错吗？还是说 rules没有如期执行展示 error？@CharlieYu99

会显示错误:
Type 'false' is not assignable to type 'string | number | undefined'.ts(2322)

但我又试了一下似乎是不影响运行的,

**Comment by pointhalo** [comment]
radio本身对于 value的类型定义只写了 number、string，没包括 boolean。但由于这里value的对应用的是 ===，所以其实 boolean也ok。我们改一下这个 interface吧。

**Comment by CharlieYu99** [comment]
感谢

**Comment by CharlieYu99** [comment]
感谢
