### ISSUE TITLE
umd加载的正确方法是什么？

### ISSUE THREAD

**Issue by naohwen** [DouyinFE/semi-design#138]
### Which Component 出现bug的组件
  - 官方文档中 https://semi.design/zh-CN/start/getting-started#3%E3%80%81UMD%20%E6%96%B9%E5%BC%8F%E4%BD%BF%E7%94%A8%E7%BB%84%E4%BB%B6

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 希望能一次跑成功

### Actual result 实际的结果是什么
  - 报错了babel.min.js:27 Uncaught SyntaxError: Inline Babel script: Unexpected token (2:13)
  1 | 
> 2 |       const {(Input, Button, Toast, Icon, Form)} = SemiUI; 
    |              ^
![屏幕截图 2021-10-30 233514](https://user-images.githubusercontent.com/82444429/139539685-125a3138-3b5e-4726-97be-68fd2f2242ad.png)

### Steps to reproduce 复现步骤
  - 复制文档中的代码不能正常运行

### Reproducible code 复现代码
```
<!DOCTYPE html>
    <html lang="zh-cn">
    <head>
        <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
+       <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
+       <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>

+       <script src="https://unpkg.com/@douyinfe/semi-ui@2.0.0/dist/umd/semi-ui.min.js"></script>
+       <link rel="stylesheet" href="https://unpkg.com/@douyinfe/semi-ui@2.0.0/dist/css/semi.css">

    </head>
    <body>
        <div id="root">1</div>
    </body>

    <script type="text/babel">
      const {(Input, Button, Toast, Icon, Form)} = SemiUI; 
      ReactDOM.render(
    <div>
        <Button onClick={() => Toast.warning({ duration: 0, content: 'Semi Design' })}>test</Button>
        <Input defaultValue="semi" onChange={value => Toast.info('hello semi')}></Input>
    </div>, document.getElementById("root") );
  </script>

</html>

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景
- 看官方文档的时候，想用umd加载试一下，发现并不能正常用

**Comment by wuhw** [comment]
文档有误
将`const {(Input, Button, Toast, Icon, Form)} = SemiUI; ` 
调整成
`const { Input, Button, Toast, Icon, Form } = SemiUI; `

**Comment by pointhalo** [comment]
文档已更新。

> 文档有误 将`const {(Input, Button, Toast, Icon, Form)} = SemiUI; ` 调整成 `const { Input, Button, Toast, Icon, Form } = SemiUI; `
