### ISSUE TITLE
[DOC] Modal 的 keepDOM 属性描述有问题

### ISSUE THREAD

**Issue by lavyun** [DouyinFE/semi-design#1389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Modal

### Semi Version

latest

### Current Behavior

![image](https://user-images.githubusercontent.com/22797898/212643895-79707f7c-62e7-437d-995c-6abd95f390fc.png)
看描述默认是不销毁，但实际是销毁的

### Expected Behavior

![image](https://user-images.githubusercontent.com/22797898/212643984-fdb20c0a-4cce-4b92-96da-49edd3c3258a.png)
类似SideSheet的描述，默认是销毁的表现

### Environment

```markdown
- OS:
- browser:
```

**Comment by YyumeiZhang** [comment]
已修改，感谢反馈～
