### ISSUE TITLE
[BUG] OverflowList's wrap element is always 'visibility: hidden'

### ISSUE THREAD

**Issue by chantzekin** [DouyinFE/semi-design#1393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

OverflowList

### Semi Version

2.25.1-2.28.0

### Current Behavior

OverflowList's state: overflowStatus is always 'calculating'

### Expected Behavior

Visibility would be visible after correct calcation. 

### v2.28.0
https://codesandbox.io/s/winter-cookies-xvrd7i

### v2.25.0
https://codesandbox.io/s/goofy-moon-imn9nx

### ReproducibleCode

```markdown
Copy from [doc](https://semi.design/zh-CN/show/overflowlist#%E6%8A%98%E5%8F%A0%E6%A8%A1%E5%BC%8F%20-%20%E9%BB%98%E8%AE%A4)
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
fix 2.28.1
