### ISSUE TITLE
[BUG] InputGroup style in doc site is broken

### ISSUE THREAD

**Issue by rabbitism** [DouyinFE/semi-design#1395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Input

### Semi Version

2.28

### Current Behavior

Input Group demo is broken

![image](https://user-images.githubusercontent.com/14807942/215429144-27c3d4ae-60f7-4b27-b615-9f2ebd688389.png)

### Environment

```markdown
- OS: Windows
- browser: Edge and Chrome
```

**Comment by pointhalo** [comment]
fix 2.28.1
