### ISSUE TITLE
[BUG] <Slider 组件 修改使用 setState 无法更新 max 值>

### ISSUE THREAD

**Issue by DevilC0822** [DouyinFE/semi-design#1397]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which Component

Slider

### Semi Version

latest version

### Current Behavior

官网 Slider 组件示例

使用 setState 更新 Slider 组件的 max 值出现无法拖动到新设置的值且鼠标与滑块脱离的情况

### Expected Behavior

能够使用 setState 正常更新 Slider 组件的 max 值

### Steps To Reproduce

1. 进入 [semi 官网](https://semi.design/zh-CN/input/slider)
2. 将如下代码粘入可实时编辑的代码块内
```javascript
import React, {useState} from 'react';
import { Slider } from '@douyinfe/semi-ui';

() => {
    const [count, setCount] = useState(50)
    useEffect(() => {
        setCount(10000)
    }, [])
    return (
    <div>
        <div>Default</div>
        <Slider max={count} showBoundary={true}></Slider>
    </div>
)
};
```
3. 拖动滑块

### ReproducibleCode

```markdown
import React, {useState} from 'react';
import { Slider } from '@douyinfe/semi-ui';

() => {
    const [count, setCount] = useState(50)
    useEffect(() => {
        setCount(10000)
    }, [])
    return (
    <div>
        <div>Default</div>
        <Slider max={count} showBoundary={true}></Slider>
    </div>
)
};
```

### Environment

```markdown
OS: Window 11 
Node: 16.15.0
npm: 8.5.5
```

**Comment by pointhalo** [comment]
slider目前没有考虑到 max、min props动态更新的情况，只在  mount 时消费了 max、min，所以会有问题。
我们后续会修复这个问题。

如果这个问题阻塞了你的使用，临时规避手段可以是在更新 max 的同时更新 组件的key，强制它重新挂载一下，使得max被重新消费。
```
<Slider max={max} key={max} />
```

**Comment by pointhalo** [comment]
重新考虑了一下这个case。
max 如果支持动态变更，有一些逻辑是比较业务向的，不好做取舍。

eg：如果当前已经选择了value 100，然后max 动态变更为 10。组件是否跟随变更，加上假如用户又配置了disabled时，那这个值到底是冻结还是跟随 max 变更，这个都是不好直接从组件上敲定的，不同业务场景下会有不同的行为需求

所以还是不考虑对动态变更 max、min的使用做支持了。
