### ISSUE TITLE
[Slider] Slider onAfterChange 

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#1404]
### Which Component Need Enhancement 期望新增功能的组件
- Slider

### What does the proposed API look like 期望支持的API
新增 onMouseUp

### Feature Description 功能描述
新增 onMouseUp，在用户鼠标松开的时候触发，并在后续大版本逐渐弱化 onAfterChange

详情见 oncall id 722/4377770/

**Comment by pointhalo** [comment]
v 2.41.1 提供 onMouseUp
