### ISSUE TITLE
[BUG] <Slider 组件 滑动问题>

### ISSUE THREAD

**Issue by JackyLuo666** [DouyinFE/semi-design#1412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Slider

### Semi Version

2.25.0

### Current Behavior

滑动条距离窗口边缘较近，然后进行滑动的时候鼠标不小心滑动到窗口外之后，鼠标会一直聚集在滑动条上，无需点击也能进行滑动

### Expected Behavior

鼠标移出窗口取消聚集滑动条

### Steps To Reproduce

1.按住滑动条不松手
2.滑动鼠标超出窗口
3.鼠标回到窗口内即可复现

### Environment

```markdown
- OS:
- browser:
```

**Comment by YyumeiZhang** [comment]
这个行为是符合预期的，当滑动鼠标超出窗口，如果鼠标一直处于按下状态，没有松开，则聚焦在slider上是合理的。鼠标松开后，将不再聚焦滑块，失去对滑块的控制。

**Comment by JackyLuo666** [comment]
我没表达清楚，在窗口外松手再移动回窗口，此时鼠标没有处于按下状态也会聚焦滑块

**Comment by YyumeiZhang** [comment]
我这边没有复现出同样的问题，录个屏看看？

**Comment by JackyLuo666** [comment]
![20230207111926_rec_](https://user-images.githubusercontent.com/93375339/217139935-c17bdec0-a702-429c-a836-9b53c3a313f3.gif)

**Comment by YyumeiZhang** [comment]
https://github.com/DouyinFE/semi-design/blob/main/packages/semi-ui/slider/index.tsx#L192 mouseup的事件是绑定在document.body上的，鼠标按下状态在移出浏览器边界后松开无法触发mouseup，如果换成绑定在document上，同样状态可以触发， @DaiQiangReal

**Comment by pointhalo** [comment]
fix 2.41.1
