### ISSUE TITLE
[BUG] Modal 命令式调用 ，调用生成的节点无法销毁

### ISSUE THREAD

**Issue by YyumeiZhang** [DouyinFE/semi-design#1415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Modal

### Semi Version

2.28.0

### Current Behavior

Modal 命令式调用多少次将创建多少个相应的节点，无法销毁
![image](https://user-images.githubusercontent.com/101110131/217188988-3875a266-d76f-43ab-96fd-3b32010ce11a.png)

### Expected Behavior

能够有相关的API或者方法支持销毁每次调用创建出来的DOM节点

### Steps To Reproduce

https://semi.bytedance.net/zh-CN/show/modal#%E5%91%BD%E4%BB%A4%E5%BC%8F%E8%B0%83%E7%94%A8 使用官网该例子，多次点击按钮，控制台查看调用创建的dom节点未被消除，当前也没有提供方法消除。

### Environment

```markdown
- OS:
- browser:
```

### Anything else?

命令式调用中的modal内部有destory函数，但是给出去的destroy实际上是内部的close函数，内部来销毁创建的div的destroy没有给出去https://github.com/DouyinFE/semi-design/blob/main/packages/semi-ui/modal/confirm.tsx#L60

**Comment by YyumeiZhang** [comment]
关联issue， https://github.com/DouyinFE/semi-design/issues/762，可同时关闭

**Comment by pointhalo** [comment]
v2.30 fix
