### ISSUE TITLE
[BUG] search box generated outside the parent div when using virtualize

### ISSUE THREAD

**Issue by arthur-FD** [DouyinFE/semi-design#1419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

TreeSelect

### Semi Version

2.28.1

### Current Behavior

When using the component inside a bootstrap modal, the search box does not behave as expected.

* On "trigger" mode, you would need to click twice on the search box to select an option
* On "dropdown" mode, the input box will immediately lose focus when you start typing (using the searchAutoFocus property)

I believe it is because the search box popup is generated outside the modal.

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/75984752/217771644-cd2ce323-a9d0-4e95-be9f-c8c1182fd9be.png">

"Dropdown" mode current behaviour
![dropdown](https://user-images.githubusercontent.com/75984752/217773032-b86f6f8c-ebfb-45f2-956c-9de904a248fb.gif)

### Expected Behavior

You would expect the same behaviour when you use the search box outside any modal

### Environment

```markdown
- OS: W11
- browser: chromium (latest)
```

**Comment by pointhalo** [comment]
Can you give a codesandbox link to reproduce this problem ?

**Comment by arthur-FD** [comment]
Hi
I will try to do it this weekend.
