### ISSUE TITLE
[BUG] DatePicker 多选点击第二页回到第一页

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#1422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

DatePicker

### Semi Version

latest

### Current Behavior

![datePicker-1422](https://user-images.githubusercontent.com/26477537/218063393-a4771da3-443e-40fe-8170-65c701da33fe.gif)

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
v2.30
