### ISSUE TITLE
[D2C] feature/bug description

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#1427]
If you have any questions about [Semi D2C](https://semi.design/code/en-US/), feel free to comment below.

**Comment by zhu-mingye** [comment]
社区可否提供个脚手架

**Comment by shijiatongxue** [comment]
> 社区可否提供个脚手架

不好意思，没看明白这个与d2c的关系。这个issue是与d2c相关的哦。

**Comment by zengguirong** [comment]
能开源C2D和D2C工具的代码吗？或者分享一下实现的思路

**Comment by shijiatongxue** [comment]
> 能开源C2D和D2C工具的代码吗？或者分享一下实现的思路

暂时还没有开源计划哈，相关实现思路有计划做一些文章分享的。

**Comment by shijiatongxue** [comment]
> > 能开源C2D和D2C工具的代码吗？或者分享一下实现的思路
> 
> 暂时还没有开源计划哈，相关实现思路有计划做一些文章分享的。

我们最近在微信上分享了我们的实现，介绍了我们是如何做的以及与其他方案的差异。

阅读原文👉🏻  https://mp.weixin.qq.com/s/AvqMqjQbP_whT5NBttFIGA

<img width="544" alt="image" src="https://github.com/DouyinFE/semi-design/assets/26477537/0b282a88-b338-40f5-95e0-d46284a0e846">



We recently shared our implementation on WeChat. The English version will be published when the translation is complete. ❤️
