### ISSUE TITLE
 [Icon] 如何动态导入Icon组件

### ISSUE THREAD

**Issue by HaceraI** [DouyinFE/semi-design#1432]
如果Icon是从API动态获取的，那么想要按需引入的话应该如何做？
下面已知(找到)的方案：
1、 `import * as Icons from 'icons' ` 全量导入做匹配;    缺点：(会导入不必要的Icon组件，增大包体积)

是否有根据 icon-name 获取指定 icon的方式？

**Comment by pointhalo** [comment]
icon本质上就是 react component，跟你动态import其他组件没有任何本质区别。

**Comment by pointhalo** [comment]
你如果要做到全映射，bundle size肯定都是一样的，都得 build in，只是说你可以借助像  react-lazyload、react-loadable等库，进行按需require，构建时分成不同的 chunk，然后真正用到再加载。
