### ISSUE TITLE
[BUG] <filter in table have only one result>

### ISSUE THREAD

**Issue by aga1515498255** [DouyinFE/semi-design#1438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

table

### Semi Version

2.28.1

### Current Behavior

![图片](https://user-images.githubusercontent.com/51292749/220039624-337f1d22-9f6a-43b8-af6d-69729070f7ba.png)
after clicked filter：
![图片](https://user-images.githubusercontent.com/51292749/220039777-5129bb69-72de-440a-81dd-1f6df3a761ba.png)

### ReproducibleCode

```markdown
import React from "react";
import { Table } from "@douyinfe/semi-ui";

function App() {
  const data = [
    { name: "1", level: 1 },
    { name: "2", level: 1 },
    { name: "3", level: 2 },
    { name: "4", level: 2 },
  ];

  return (
    <div className="App">
      <Table dataSource={data}>
        <Table.Column dataIndex="name" title="姓名"></Table.Column>
        <Table.Column
          dataIndex="level"
          title="等级"
          filters={[
            { text: "1", value: 1 },
            { text: "2", value: 2 },
          ]}
          onFilter={(value, record) => record.level === value}
        ></Table.Column>
      </Table>
    </div>
  );
}
```

### Environment

```markdown
- OS:windows 10
- browser:Edge
```

### Anything else?

不知道是不是我的问题。

**Comment by pointhalo** [comment]
![image](https://user-images.githubusercontent.com/88709023/220043661-6810e2df-013d-4b3a-afc9-8732098a545c.png)
你的例子，没有配 key 或 通过 rowKey指定筛选所用字段。

**Comment by aga1515498255** [comment]
好的，谢谢
