### ISSUE TITLE
Table ColumnRender 类型问题

### ISSUE THREAD

**Issue by boenfu** [DouyinFE/semi-design#144]
这个 text 实际上应该可以是任何类型吧，类型自动推断比较麻烦，直接换成 any 会不会也比 string 好，用着有点难受。

`export declare type ColumnRender<RecordType> = (text: string, record: RecordType, index: number, options?: RenderOptions) => ColumnRenderReturnType;`

还是说这有其他考虑？如果没空我可以提 pr 么 ~ ❤

**Comment by wuhw** [comment]
@shijiatongxue 看下

**Comment by shijiatongxue** [comment]
> 这个 text 实际上应该可以是任何类型吧，类型自动推断比较麻烦，直接换成 any 会不会也比 string 好，用着有点难受。
> 
> `export declare type ColumnRender<RecordType> = (text: string, record: RecordType, index: number, options?: RenderOptions) => ColumnRenderReturnType;`
> 
> 还是说这有其他考虑？如果没空我可以提 pr 么 ~ ❤

这里有点问题，今天修复。
