### ISSUE TITLE
[DatePicker] Support needConfirm option for dateRange type

### ISSUE THREAD

**Issue by R-D-D-D** [DouyinFE/semi-design#1445]
### Which Component Need Enhancement 期望新增功能的组件
- DatePicker

### What does the proposed API look like 期望支持的API
needConfirm

### Feature Description 功能描述
目前needConfirm选项只支持dateTime和dateTimeRange，希望可以支持dateRange

**Comment by shijiatongxue** [comment]
时间选择器加上了 needConfirm 是为了避免滑动时间导致频繁触发回调问题。

非 time 场景支持 needConfirm 的原因是什么，可以具体说下吗？

**Comment by R-D-D-D** [comment]
@shijiatongxue 我的场景是需要用户来选择一段60天以内的时间范围，如果他选择的日期范围超过60天了，我们就不能让他选，但是当一个Datepicker已经有数据的时候，这个时候他再选择我就不能判断他是只改了一个日期还是两个都改完了因为`rangeStart` `rangeEnd`都是有数据的。然后我就不知道什么时候触发我的检查逻辑了，所以有一个confirm能让我知道用户两个日期都选完了比较好

**Comment by shijiatongxue** [comment]
> @shijiatongxue 我的场景是需要用户来选择一段60天以内的时间范围，如果他选择的日期范围超过60天了，我们就不能让他选，但是当一个Datepicker已经有数据的时候，这个时候他再选择我就不能判断他是只改了一个日期还是两个都改完了因为`rangeStart` `rangeEnd`都是有数据的。然后我就不知道什么时候触发我的检查逻辑了，所以有一个confirm能让我知道用户两个日期都选完了比较好

2.22 版本支持了 rangeInputFocus 参数，可以根据输入框的聚焦状态判断用户的选择吗。或者将选择完的日期保存在 state 里，这样就知道改了哪个日期了。

**Comment by shijiatongxue** [comment]
暂无这样的设计
