### ISSUE TITLE
[TreeSelect] 通过 Ref 调用 open/close 方法打开/关闭面板

### ISSUE THREAD

**Issue by YyumeiZhang** [DouyinFE/semi-design#1452]
### Which Component Need Enhancement 期望新增功能的组件
- TreeSelect

### What does the proposed API look like 期望支持的API
 open，close 方法

### Additional information 补充说明
TreeSelect 中 registerClickOutsideHandler 和面板点击，focus 逻辑相关联， TreeSelect组件操作过程中，可能关闭，打开面板，https://github.com/DouyinFE/semi-design/pull/1444/files 将面板打开和关闭过程和ClickOutside相关操作解绑。因此手动调用open方法，和 close 方法时候注意事件的注册和取消

**Comment by pointhalo** [comment]
通过 #566 统一追踪，这个issue先关掉了。
