### ISSUE TITLE
[BUG] Tabs 可滚动时(collapsible="true")，点击激活一个 TabPane后，左侧箭头不可点击

### ISSUE THREAD

**Issue by moonsky-all** [DouyinFE/semi-design#1456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Tabs

### Semi Version

2.29.0

### Current Behavior

![image](https://user-images.githubusercontent.com/82572484/221365234-833f172f-8bc2-421d-acc2-746c7522c8ba.png)

点击后，左侧箭头不可点击
![image](https://user-images.githubusercontent.com/82572484/221365270-211e8d59-6f28-45f4-9b4a-cd53ff626952.png)

右侧箭头能选择全部选项
![image](https://user-images.githubusercontent.com/82572484/221365303-cd7ea237-dc25-4056-95ce-f068ddbe4a6e.png)

### ReproducibleCode

```markdown
function EntryWorkbench() {
  const panes = useMemo(() => {
    return Array(99).fill(0).map((m, i: number) => `00${m + i}`.slice(-2)).map(v => `主要对象${v}`);
  }, []);

  return (
    <Tabs
      type="card"
      collapsible={true}
      defaultActiveKey="1"
      // className="focus-tabs-workbench"
    >
      <TabPane tab="首页" itemKey="1"/>
      <TabPane tab="主要对象" itemKey="2" closable={true}/>
      {
        panes.map(pane => (<TabPane tab={pane} itemKey={pane} key={pane} closable={true}/>))
      }
    </Tabs>
  );
}
```

### Environment

```markdown
- OS: Mac
- browser: Chrome
```

**Comment by YannLynn** [comment]
官网 demo 即可复现问题。

![20230509194257_rec_](https://github.com/DouyinFE/semi-design/assets/101160769/dab9f3da-c568-452f-8920-1503c2e6b1ef)
