### ISSUE TITLE
[FlexibleColumnLayout] 希望新增一个FlexibleColumnLayout组件

### ISSUE THREAD

**Issue by iamcyw** [DouyinFE/semi-design#1460]
### Which Component Need Enhancement 期望新增功能的组件
- FlexibleColumnLayout

### Feature Description 功能描述
[spa ui5 FlexibleColumnLayout](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-flexiblecolumnlayout--default-story)
通过在单独的列中显示最多三个页面来实现列表-详细信息-详细信息范例

### Additional information 补充说明

大多数admin系统里面一个crud对象管理功能就是查看一个列表，然后对单项操作表单，可不可以做一个类似ui5这种交互的组件

**Comment by pointhalo** [comment]
- 在我们自身的使用里，这种类型的交互基本没有。所以这块不计划投人力去做
- 如果有强需求，欢迎提交 PR 共建
