### ISSUE TITLE
[BUG] Disable with Multiple selection remove the close button on render item

### ISSUE THREAD

**Issue by arthur-FD** [DouyinFE/semi-design#1462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

TreeSelect

### Semi Version

2.30.1

### Current Behavior

When you disable the parent node but not the leaf for selection with multiple selection activated, it will not render the selected items correctly.
Indeed, the leaves selected will not have the cross to unselect them from the selection box, as you can see on the screenshot bellow

Also, I tried to force the behaviour by adding the following function but it did not overwrite the rendered item:
        **renderSelectedItem={(item, { index, onClose }) => ({ content: item.label, isRenderInTag: true })}**

Also, in the documentation, the parameter used to disable one item is  "disable", however this parameter has no effect. I believe it should be "disable**d**"

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/75984752/221945554-375797ea-d352-4556-a48b-bf3065bcc031.png">

Best
Arthur

### Expected Behavior

You would like to have this cross enabled  for all the item that you can select

### ReproducibleCode

```markdown
import React from 'react';
import { TreeSelect } from '@douyinfe/semi-ui';

() => {
    const treeData = [
        {
            label: 'Asia',
            value: 'Asia',
            key: '0',
            children: [
                {
                    label: 'China',
                    value: 'China',
                    key: '0-0',
                    disabled: true,
                    children: [
                        {
                            label: 'Beijing',
                            value: 'Beijing',
                            key: '0-0-0',
                            disabled: false,

                        },
                        {
                            label: 'Shanghai',
                            value: 'Shanghai',
                            key: '0-0-1',
                            disabled: false,

                        },
                    ],
                },
                {
                    label: 'Japan',
                    value: 'Japan',
                    key: '0-1',
                },
            ],
        },
        {
            label: 'North America',
            value: 'North America',
            key: '1',
        }
    ];
    return ( 
        <div>
            <TreeSelect
                style={{ width: 300 }}
                dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
                treeData={treeData}
                disableStrictly
                // renderSelectedItem={(item, { index, onClose }) => ({ content: item.label, isRenderInTag: true })}
                multiple
                defaultValue={['Shanghai']}
            />
        </div>
    );
};
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by YyumeiZhang** [comment]
Sorry for the late reply.  

 In the demo you gave, when the parent node is set to disabled as true, the child node’s disabled is set to false. This setting is currently not supported.  

Because for the current TreeSelect, if disabledStrictly is set, when the parent node sets disabled to true, the child node will also be treated as disabled to true. If disabled of all child nodes is set to true, disabled of the parent node will also be treated as true.

**Comment by YyumeiZhang** [comment]
@arthur-FD Maybe the following example meets your usage needs?
```
import React from 'react';
import { TreeSelect } from '@douyinfe/semi-ui';
() => {
    const treeData = [
        {
            label: '亚洲',
            value: 'Asia',
            key: '0',
            children: [
                {
                    label: '中国',
                    value: 'China',
                    disabled: true,
                    key: '0-0',
                    children: [
                        {
                            label: '北京',
                            value: 'Beijing',
                            key: '0-0-0',
                        },
                        {
                            label: '上海',
                            value: 'Shanghai',
                            key: '0-0-1',
                        },
                    ],
                },
            ],
        },
        {
            label: '北美洲',
            value: 'North America',
            key: '1',
        }
    ];
    return (
        <TreeSelect
            multiple
            defaultValue='Asia'
            checkRelation='unRelated'
            style={{ width: 300 }}
            dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
            treeData={treeData}
        />
    );
};
```
If it does not meet your usage requirements, please explain the existing problems in detail, and we will continue to follow up

**Comment by arthur-FD** [comment]
Thank you @YyumeiZhang  It works perfectly.

Apologies for the late reply
