### ISSUE TITLE
[Table] feature 希望可以支持服务端渲染

### ISSUE THREAD

**Issue by geekerio** [DouyinFE/semi-design#1466]
### Which Component Need Enhancement 期望新增功能的组件
- Table

### Feature Description 功能描述
nextjs ssr table返回没有数据 希望可以实现服务器渲染

### Additional information 补充说明
这个对非管理类型后台来说 seo有点重要

**Comment by shijiatongxue** [comment]
确实有这个问题，如果有兴趣欢迎提交 PR。
