### ISSUE TITLE
window.parent被污染

### ISSUE THREAD

**Issue by xiaoxin123222** [DouyinFE/semi-design#1469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Semi Version

^2.29.0

### Current Behavior

Corrupted the window instance, window.parent
Not an instance, but a function

### Expected Behavior

window.parent is the parent window

### Steps To Reproduce

<img width="816" alt="image" src="https://user-images.githubusercontent.com/52811332/223145013-ebed7e46-4345-4e5f-984b-daecb91abfb0.png">

### ReproducibleCode

```markdown
window.parent
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by xiaoxin123222** [comment]
应该是toast组件

**Comment by pointhalo** [comment]
给个复现的 codesandbox吧
