### ISSUE TITLE
[BUG] Failed to Clone Repo on Windows Caused by Illegal Character in Filename

### ISSUE THREAD

**Issue by YuanSa** [DouyinFE/semi-design#1476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When execute `git clone https://github.com/DouyinFE/semi-design.git` on Windows, an error will be thrown and the clone failed:

```text
PS C:\Users\YuanSa\Documents> git clone https://github.com/DouyinFE/semi-design.git
Cloning into 'semi-design'...
remote: Enumerating objects: 32126, done.
remote: Counting objects: 100% (1080/1080), done.
remote: Compressing objects: 100% (660/660), done.
remote: Total 32126 (delta 512), reused 918 (delta 415), pack-reused 31046
remote: Enumerating objects: 27155, done.
remote: Counting objects: 100% (865/865), done.
remote: Compressing objects: 100% (571/571), done.
remote: Total 27155 (delta 379), reused 737 (delta 290), pack-reused 26290
Receiving objects: 100% (27155/27155), 20.95 MiB | 1.33 MiB/s, done.
Resolving deltas: 100% (18089/18089), done.
error: invalid path '.github/workflows/test:coverage.yml'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Seems like its caused by an illegal file name: `.github/workflows/test:coverage.yml` - the character `:` is illegal in a file's path on Windows OS.

I finally downloaded the ZIP and skipped the buggy file during unzipping to bypass this.

### Environment

```markdown
- OS: Windows (PowerShell)
```

### Anything else?

Curious: why `:` will be used in filename?

**Comment by pointhalo** [comment]
Initially, it should be aligned with the script command of package.json, where : is used, so the same is used directly here.
Compatibility under Windows is not considered

**Comment by shijiatongxue** [comment]
fixed now
