### ISSUE TITLE
[Table] rowSelection.hidden = false，resizable=true 时值隐藏了checkbox，而 resizable=false时隐藏了整个列

### ISSUE THREAD

**Issue by moonsky-all** [DouyinFE/semi-design#1493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Table

### Semi Version

2.29.0

### Current Behavior

当设置 rowSelection.hidden = false 隐藏预设多选列时
若 resizable=true, 此时只隐藏了复选框；
而当 resizable=false 时，隐藏了复选框及其所在列。

resizable=true 只隐藏复选框的行为不太符合认知，这样的情况下应该始终隐藏复选框及其所在列

### Expected Behavior

resizable=true 只隐藏复选框的行为不太符合认知，这样的情况下应该始终隐藏复选框及其所在列

### Environment

```markdown
- OS:
- browser:
```

**Comment by moonsky-all** [comment]
https://semi.design/zh-CN/show/table#%E5%AE%8C%E5%85%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B8%B2%E6%9F%93

官网的这个例子能在线复现

**Comment by shijiatongxue** [comment]
> 感觉你的意思是 rowSelection.hidden = true 时，resizable 会影响最左侧 checkbox 列的隐藏？

看起来是 hidden false 时，resizable 切换 true/false 会影响展示。这个是个 bug，我们排查下。

**Comment by shijiatongxue** [comment]
与 https://github.com/DouyinFE/semi-design/issues/2036 相关。hidden 时不应该展示选择列。
