### ISSUE TITLE
[BUG] <OverflowList> 特殊操作后，边界判定错误

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#1502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

OverflowList

### Current Behavior

经过操作后，边界判定错误，左侧箭头无法点击。

### Expected Behavior

可以点击

### Steps To Reproduce

[录屏 2023年03月20日 17时44分26秒.webm](https://user-images.githubusercontent.com/29626873/226303215-0d548990-bd08-4cbd-938b-8e4b758ce408.webm)

### Environment

```markdown
- OS:
- browser:
```

**Comment by YannLynn** [comment]
This issue describes the same issue as  #1456

**Comment by YannLynn** [comment]
fixed in 2.35.0
