### ISSUE TITLE
[Input] useState with input value not work

### ISSUE THREAD

**Issue by TangMonk** [DouyinFE/semi-design#1515]
For example:

create a name state:

```
const [name, setName] = useState("david");
```

and there is a Input component:

```
<Input prefix="name" value={name}></Input>
```

When the user type words in the input component, there is nothing happening.

**Comment by shijiatongxue** [comment]
Hello there.

It seems like not a bug. If you give input a value prop, it will trigger React [controlled mode.](https://legacy.reactjs.org/docs/forms.html#controlled-components)

```
import React from 'react';

() => {
    const [value, setValue] = useState('test');

    return (
        <input value={value} onChange={(e => setValue(e.target.value))}></input>
    );
};
```

If you want to use controlled mode with Semi Input, write code like this.

```
import React from 'react';
import { Input } from '@douyinfe/semi-ui';

() => {
    const [value, setValue] = useState('test');

    return (
        <Input value={value} onChange={(v => setValue(v))}></Input>
    );
};
```

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/26477537/227928435-fed50cd9-451e-4880-aaac-7dfc9de61822.png">


Lean more about [React controlled mode](https://legacy.reactjs.org/docs/forms.html#controlled-components).
