### ISSUE TITLE
[Table] 动态设置groupBy为null或者undifined时，能够从分组表格动态切换至普通表格

### ISSUE THREAD

**Issue by yupaits** [DouyinFE/semi-design#1527]
### Which Component Need Enhancement 期望新增功能的组件
- Table

### What does the proposed API look like 期望支持的API
- groupBy

### Feature Description 功能描述

By setting the value of 'groupBy' to null or undefined, it is not possible to switch from a grouped table to a normal table.
当前通过动态设置groupBy，可以从普通表格切换至分组表格，但无法从分组表格切换至普通表格状态。
希望支持动态设置groupBy属性为null或者undifined时，能够从分组表格动态切换至普通表格的特性。

**Comment by shijiatongxue** [comment]
你好，Table 没有动态响应 groupBy 的计划。groupBy 的消费与数据变化绑定，所以你可以让 dataSource 的引用发生变化以实现此效果。

也可以考虑给 Table 绑定一个新的 key 强制刷新以实现此效果。
