### ISSUE TITLE
[BUG] OverflowList props items count more than 50，component occurred error

### ISSUE THREAD

**Issue by xiaoping027** [DouyinFE/semi-design#1528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

OverflowList

### Semi Version

2.23.1

### Current Behavior

![image](https://user-images.githubusercontent.com/17611082/229015298-7a2bceef-0c78-4162-80cd-3272a869fa1e.png)

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
![image](https://user-images.githubusercontent.com/88709023/229015856-fdee7203-89dc-4a2d-8165-fd80ae6929b5.png)

update to latest version
