### ISSUE TITLE
Compatibility issue with Nextjs

### ISSUE THREAD

**Issue by Yosuamuliawan19** [DouyinFE/semi-design#153]
### Which Component 出现bug的组件
  - All

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - Compatible usage of the library with Nextjs

### Actual result 实际的结果是什么
  ```
error - ./node_modules/@douyinfe/semi-foundation/lib/es/_portal/portal.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@douyinfe/semi-ui/lib/es/_portal/index.js
```

This issue is caused by 'nextjs' restriction on global imports, rendering this library and nextjs incompatible. In light of nextjs popularity and user base, I think we should support usage of semi-design with nextjs. What do you think ?

On the other hand, ant-design doesn't encounter this issue

### Steps to reproduce 复现步骤
  - Iniitalize new project using next-js
  - install semi-design, and use any component within it

### Additional information 补充说明

Discussion of the following problem in Nextjs repository
https://github.com/vercel/next.js/issues/19936

Temporary disable of global CSS imports in nextjs isn't possible now, and is being actively discussed in the following RFC
https://github.com/vercel/next.js/discussions/27953

**Comment by wuhw** [comment]
We will deal in this week

**Comment by Yosuamuliawan19** [comment]
@wuhw is there an ongoing PR / issue to track on this ? I'm asking for tracking purposes

**Comment by wuhw** [comment]
Not yet.You can track this issue.When I finish the PR, I will associate this issue as soon as possible

**Comment by Yosuamuliawan19** [comment]
thanks, can't wait for the update 👍

**Comment by Foundj** [comment]
> 暂时还没有，可以跟踪这个issue，等我PR完成后，会第一时间关联这个issue

大概多久可以PR完成？

**Comment by wuhw** [comment]
已经开发了，正在测试阶段，本周应该能提交PR

**Comment by Saul-BT** [comment]
Hi, I have the same error and I don't know how to solve it ( [unclear documentation](https://semi.design/en-US/start/getting-started#4%E3%80%81Use%20in%20Next.js) ).

I followed all the steps, but the problem persists 😭 .

**Details:**
* Node: 16.13.2
* npm: 8.1.2
* yarn: 1.22.17
* Next.js: 12.0.8
* semi-ui: latest

**Error:**
```
error - ./node_modules/@douyinfe/semi-foundation/lib/es/_portal/portal.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@douyinfe/semi-ui/lib/es/_portal/index.js
```

**Comment by pointhalo** [comment]
> Hi, I have the same error and I don't know how to solve it ( [unclear documentation](https://semi.design/en-US/start/getting-started#4%E3%80%81Use%20in%20Next.js) ).
> 
> I followed all the steps, but the problem persists 😭 .
> 
> **Details:**
> 
> * Node: 16.13.2
> * npm: 8.1.2
> * yarn: 1.22.17
> * Next.js: 12.0.8
> * semi-ui: latest
> 
> **Error:**
> 
> ```
> error - ./node_modules/@douyinfe/semi-foundation/lib/es/_portal/portal.css
> Global CSS cannot be imported from within node_modules.
> Read more: https://nextjs.org/docs/messages/css-npm
> Location: node_modules/@douyinfe/semi-ui/lib/es/_portal/index.js
> ```

Have you try require and apply `@douyinfe/semi-next` in your `next.config.js`?  
Cause next.js not allow import css from node_modules, so we need to use plugin to process.
If you still have problem, you can send your `next.config.js` configuration to have a look

**Comment by Saul-BT** [comment]
> Have you try require and apply `@douyinfe/semi-next` in your `next.config.js`? Cause next.js not allow import css from node_modules, so we need to use plugin to process. If you still have problem, you can send your `next.config.js` configuration to have a look

I've missed the `semi` function in the code below 😓: 

```
const nextConfig = semi({
  // ...
})
```

Sorry for the inconvenience.

Thanks 😃
