### ISSUE TITLE
[AutoComplete] 使用方向键切换选项后，希望自动滚动

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#1530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

autoComplete

### Current Behavior

https://user-images.githubusercontent.com/29626873/229041085-1c803b75-7d64-48fc-85d8-7df20937c6d8.mp4

### Expected Behavior

高亮正常

### ReproducibleCode

```markdown
import React from 'react';
import { AutoComplete } from '@douyinfe/semi-ui';
import { IconSearch } from '@douyinfe/semi-icons';

class ObjectDemo extends React.Component {
    constructor() {
        super();
        this.state = {
            list: [
                { value: 'abc', label: 'douyin', email: '1@gmail.com', type: 2 },
                { value: 'hotsoon', label: 'huoshan', email: '2@gmail.com', type: 3 },
                { value: 'pipixia', label: 'pip', email: '3@gmail.com' },
                 { value: 'pipixia', label: 'pip', email: '3@gmail.com' },
                  { value: 'pipixia', label: 'pip', email: '3@gmail.com' },
                   { value: 'pipixia', label: 'pip', email: '3@gmail.com' },
                    { value: 'pipixia', label: 'pip', email: '3@gmail.com' },
                     { value: 'pipixia', label: 'pip', email: '3@gmail.com' },
                      { value: 'pipixia', label: 'pip', email: '3@gmail.com' },
                       { value: 'pipixia', label: 'pip', email: '3@gmail.com' },
            ],
            loading: false,
        };
        this.onSearch = this.onSearch.bind(this);
        this.handleSelect = this.handleSelect.bind(this);
        this.renderItem = this.renderItem.bind(this);
        this.renderSelectedItem = this.renderSelectedItem.bind(this);
        this.search = debounce(this.search.bind(this), 200);
    }

    onSearch(inputValue) {
        this.setState({ loading: true });
        this.search(inputValue);
    }

    search(inputValue) {
        let { list } = this.state;
        const newList = list.map(item => {
            let num = Math.random()
                .toString()
                .slice(2, 5);
            let option = inputValue + '-' + num;
            return { ...item, label: '名称:' + option, value: option };
        });
        this.setState({ list: newList, loading: false });
    }

    handleSelect(value) {
        console.log(value);
    }

    renderItem(item) {
        return (
            <div>
                <div>{item.label}</div>
                <div>email: {item.email}</div>
                <div style={{ color: 'pink' }}>value: {item.value}</div>
            </div>
        );
    }

    renderSelectedItem(item) {
        // 注意：与Select不同，此处只能返回String类型的值，不能返回ReactNode
        return item.value;
    }

    render() {
        const { loading } = this.state;
        return (
            <div>
                <AutoComplete
                    data={this.state.list}
                    style={{ width: 250 }}
                    prefix={<IconSearch />}
                    onSearch={this.onSearch}
                    loading={loading}
                    onChangeWithObject
                    renderItem={this.renderItem}
                    renderSelectedItem={this.renderSelectedItem}
                    onSelect={this.handleSelect}
                    maxHeight='400px'
                ></AutoComplete>
            </div>
        );
    }
}
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by shijiatongxue** [comment]
没看明白问题是啥，具体是哪里故障了。

**Comment by congziqi77** [comment]
> 没看明白问题是啥，具体是哪里故障了。

下拉框数据过多时候,使用键盘向下选择到隐藏数据，下拉框不会变化

**Comment by YyumeiZhang** [comment]
类似的issue
#607 #169 
以上 issue 是有关 select 的修改， Select 当前存在的问题是从最后一个切换到第一个会无法将聚焦移动到第一个选项，预计和选择器有关，修改本issue时候同步修改下这个问题

**Comment by pointhalo** [comment]
- @YyumeiZhang 这个case我在解决 select问题的时候顺带看了一下，在 https://github.com/DouyinFE/semi-design/pull/2501 这个PR提交了，后续可以 review一下。

- 上述提到的【 Select 当前存在的问题是从最后一个切换到第一个会无法将聚焦移动到第一个选项】是因为select内部维护 focusIndex是从0开始的，而 nth-child是从1开始编号的，所以有时候会对不上，找不到对应的DOM滚不动（已经在https://github.com/DouyinFE/semi-design/pull/2498 修复过）

**Comment by YyumeiZhang** [comment]
@pointhalo 对于 Select 问题的修复，还有以下的问题
![image](https://github.com/user-attachments/assets/9054bd6e-63f7-487a-ab88-a0bd7488efb5)
由于 autoComplete 中未提供 slot，因此无同样情况

**Comment by pointhalo** [comment]
> @pointhalo 对于 Select 问题的修复，还有以下的问题 ![image](https://private-user-images.githubusercontent.com/101110131/369301343-9054bd6e-63f7-487a-ab88-a0bd7488efb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTY1NDMsIm5iZiI6MTcyNjgxNjI0MywicGF0aCI6Ii8xMDExMTAxMzEvMzY5MzAxMzQzLTkwNTRiZDZlLTYzZjctNDg3YS1hYjg4LWEwYmQ3NDg4ZWZiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNzEwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWJkN2YzZjdlMTgxMzAwZjY1MmVlNDlmN2I4MGFhMGZlNDdmZDVkZDgyNTQ3OTVhOTkyYzI0NGMzNWQyMTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9NZVKCZcgHmVqXywoMwm55CDtAnPH9w9-WYMtIsOiDA) 由于 autoComplete 中未提供 slot，因此无同样情况

新问题？后续单独处理吧。
