### ISSUE TITLE
[BUG] <Typography> 组件在设置 disabled 之后依旧可以响应点击事件

### ISSUE THREAD

**Issue by jacob-lcs** [DouyinFE/semi-design#1531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Typography

### Semi Version

Latest

### Current Behavior

组件在设置 disabled 之后依旧可以响应点击事件

### Expected Behavior

disabled 之后不响应点击事件

### Steps To Reproduce

直接运行代码点击 disabled 的 text 即可复现

### ReproducibleCode

```markdown
import React from 'react';
import { Typography } from '@douyinfe/semi-ui';

function Demo() {
    const { Text } = Typography;
    return (
        <div>
            <Text link disabled onClick={() => alert(1)}>链接文本</Text>
        </div>
    );
}
```

### Environment

```markdown
- OS: N/A
- browser: N/A
```

**Comment by YyumeiZhang** [comment]
@jacob-lcs Typography 系列的组件支持 onClick，但是并没有将 disabled 和 onClick 进行关联。 
这里 disabled API的作用体现在样式，和点击功能没有关系。
如果用户有相关的逻辑，建议在对应回调的处理函数中做定制化处理。

**Comment by jacob-lcs** [comment]
这跟认知不太一样吧...disabled 在其他组件都是禁用点击 + 样式，为什么在这里就只有样式了呢

**Comment by YyumeiZhang** [comment]
> 这跟认知不太一样吧...disabled 在其他组件都是禁用点击 + 样式，为什么在这里就只有样式了呢

Typography 作为一个展示类的组件，因此 disabled 的定位是样式
这里的“其他组件”，我理解应该是输入类型的组件，比如 Button，Input等，disabled的定位是是样式，以及点击相关（会处理和点击回调相关的内容）

从功能性上来讲，对于 Typography  而言，点击会产生效果的是设置了 link API 相关的使用，对于 disabled 的处理是 https://github.com/DouyinFE/semi-design/blob/main/packages/semi-ui/typography/base.tsx#L74。即如果disabled，设置link只会有相关的样式，而不会具备链接的效果。所以我们仍然不关心 onClick 相关回调是否需要受到 disabled 限制问题。

**Comment by coding-ax** [comment]
可否通过 props 支持一下呢 我们目前只能全局定义 .semi-typography.semi-typography-disabled{
    pointer-events: none;
}
