### ISSUE TITLE
[Descriptions] 描述列表能否支持横向布局

### ISSUE THREAD

**Issue by HaceraI** [DouyinFE/semi-design#1534]
### Which Component Need Enhancement 期望新增功能的组件
- Descriptions

### Feature Description 功能描述
我看官网文档目前的描述列表是纵向的，能否支持像这样的描述布局呢？
![image](https://user-images.githubusercontent.com/48341368/229674914-683e7f9e-726c-465d-a91a-e719773535f9.png)

### Additional information 补充说明
官网上有个地方貌似有这样的布局，是未开放吗？
![image](https://user-images.githubusercontent.com/48341368/229675095-be6d7f4c-d6bb-479e-ab67-59af270d98ce.png)

**Comment by coding-ax** [comment]
> ### Which Component Need Enhancement 期望新增功能的组件
> * Descriptions
> 
> ### Feature Description 功能描述
> 我看官网文档目前的描述列表是纵向的，能否支持像这样的描述布局呢？ ![image](https://user-images.githubusercontent.com/48341368/229674914-683e7f9e-726c-465d-a91a-e719773535f9.png)
> 
> ### Additional information 补充说明
> 官网上有个地方貌似有这样的布局，是未开放吗？ ![image](https://user-images.githubusercontent.com/48341368/229675095-be6d7f4c-d6bb-479e-ab67-59af270d98ce.png)

![image](https://github.com/DouyinFE/semi-design/assets/53092569/31f571b7-9841-48fc-a048-30a9997481d6)
好奇地去看了一下，是用两个 description 叠放在一起做的，哈哈哈😁

**Comment by xmsz-stu** [comment]
+1 
现在优点简陋 需要自己大量的写css实现
