### ISSUE TITLE
[Table] resizable table demo bug

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#154]
### Which Component 出现bug的组件
  - Table

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - resizable Table demo has bug

**Comment by 497983606** [comment]
Nice!  But why the issues #78 has closed? if bug not  of SEMI, please describe how this problem occurred, thanks

**Comment by shijiatongxue** [comment]
> Nice! But why the issues #78 has closed? if bug not of SEMI, please describe how this problem occurred, thanks

Issue #78 includes some components bug which has been fixed. So we open a new issue only contain Table bug.(It may be clearer that an issue contains an issue)

This issue #154 marked as bug label which means we confirm it is a bug. It can be reproduced when run gatsby docsite. We found that in storybook it is fine. We are still investigating why this problem occurs in gatsby demo. Thanks!

**Comment by shijiatongxue** [comment]
v2.0.4 fixed

**Comment by 497983606** [comment]
Thanks !! so~~I'm kodev(taiwutech.com) author. Want change the UI lib to SEMI, In particular, the table component of SEMI, but now this component has some  bug, want you to fix it, thank you

![image](https://user-images.githubusercontent.com/13822946/140841695-034e19d6-c042-4dd3-b4f2-cd04a3481c51.png)

laset column dont resize and border abnormal

**Comment by shijiatongxue** [comment]
> Thanks !! so~~I'm kodev(taiwutech.com) author. Want change the UI lib to SEMI, In particular, the table component of SEMI, but now this component has some bug, want you to fix it, thank you
> 
> ![image](https://user-images.githubusercontent.com/13822946/140841695-034e19d6-c042-4dd3-b4f2-cd04a3481c51.png)
> 
> laset column dont resize and border abnormal

Hi kodev, thank you for choosing Semi Design for your UI lib. I am sorry for this bug that we know. It will be fixed after pull https://github.com/DouyinFE/semi-design/pull/164 is merged.  For now you can give a column without width that will bypass this bug :)

**Comment by 497983606** [comment]
ok, I will to try this hack, thank u, thank Semi

**Comment by shijiatongxue** [comment]
v2.0.7 fixed

**Comment by 497983606** [comment]
![image](https://user-images.githubusercontent.com/13822946/143394835-9bee5d4f-a0df-48e3-a70d-771702df6e1f.png)
1. penultimate column cant resize
2. if last column resized, please see image

**Comment by shijiame** [comment]
> 

Can you provide us with the reproduced code and environment?

**Comment by shijiatongxue** [comment]
> ![image](https://user-images.githubusercontent.com/13822946/143394835-9bee5d4f-a0df-48e3-a70d-771702df6e1f.png)
> 
> 1. penultimate column cant resize
> 2. if last column resized, please see image

Can you provide me with the reproduced code and environment? Thanks! ❤

**Comment by 497983606** [comment]
in your docsite

**Comment by shijiatongxue** [comment]
> in your docsite

https://codesandbox.io/s/semi-table-resizable-lhq5x?file=/src/App.js 

Can't reproduce this problem in Mac and Chrome.

**Comment by shijiatongxue** [comment]
> > in your docsite
> 
> https://codesandbox.io/s/semi-table-resizable-lhq5x?file=/src/App.js
> 
> Can't reproduce this problem in Mac and Chrome.

Windows 10 

- Chrome 95
- Firefox 93 

also can't repreduce

**Comment by 497983606** [comment]
![image](https://user-images.githubusercontent.com/13822946/143512449-22457b7d-7c12-4c98-a244-ce2916e2e232.png)
https://codesandbox.io/embed/semi-table-resizable-forked-hjvu7?fontsize=14&hidenavigation=1&theme=dark

**Comment by 497983606** [comment]
this is a usercase defect when table has inner scroll,need listen x-scroll exist and move to change table header hidden-scroll position

**Comment by shijiatongxue** [comment]
> this is a usercase defect when table has inner scroll,need listen x-scroll exist and move to change table header hidden-scroll position

It is not recommended to use the fixed column and resizable at the same time. The fixed column needs to specify scroll.x, which stipulates that the table has a width range, and the resizable column will expand the column width, which may cause the table to be misaligned.
