### ISSUE TITLE
[BUG] Select - Dynamic Modification Options not updating

### ISSUE THREAD

**Issue by Rigel772** [DouyinFE/semi-design#1543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select

### Semi Version

latest

### Current Behavior

Cannot get options for second select, please see the Stackblitz code.

### Expected Behavior

Expect options for second select updated on first select change.

### ReproducibleCode

```markdown
https://stackblitz.com/edit/vitejs-vite-1a6yk5?file=src%2FApp.jsx
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
When allowcreate is true, opitonList is completely controlled by the local state and no longer responds to external changes.
![image](https://user-images.githubusercontent.com/88709023/230552504-7a7f40f1-9886-4875-a6e0-f5a1882480f2.png)

**Comment by Rigel772** [comment]
@pointhalo  That information should be provided in "Create entries" section not FAQ, IMO..
So what is the recommended way of updating options with allowCreate="true"?

**Comment by pointhalo** [comment]
i will add some notes to the usage example and api description of allowCreate.

Let me explain why this design is here. In the case of allowCreate, select needs to maintain a state.optionList internally to save new creation items, which may be different from props.optionList itself.
And if it responds to the change of props.optionList again, it violates the setting of a single data source. And whether old data and new data are replaced or merged is unpredictable, and different scenarios have completely different requirements.

**Comment by pointhalo** [comment]
If you want to update optionList and support creation, you can directly use slot-related props, and place input through reactNode to interact.

Either you directly force Select to remount when updating optionList. For example to a different key. But the items you have created through allowCreate must be saved by themselves and appended to the new optionLIst.
