### ISSUE TITLE
[BUG] SideSheet 可操作外部区域选项无法正常工作

### ISSUE THREAD

**Issue by tuyutian** [DouyinFE/semi-design#1548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

SideSheet

### Semi Version

2.32.1

### Current Behavior

![image](https://user-images.githubusercontent.com/28928344/231047809-8e9bc6a1-8355-4a8f-a15b-c08f424e5948.png)
![image](https://user-images.githubusercontent.com/28928344/231047983-66150bbf-f9f8-46cb-a318-fba14af75ebd.png)
虽然配置项中设置mask 为false，但是遮罩层样式还是100%

### Expected Behavior

之前是没有问题的，但更新版本后出现了这个问题

### Steps To Reproduce

 https://semi.design/zh-CN/show/sidesheet
你们官网显示也有这个问题

### Environment

```markdown
- node: 16.15
- browser: google 版本 112.0.5615.49（正式版本）
```

**Comment by pointhalo** [comment]
@DaiQiangReal PR https://github.com/DouyinFE/semi-design/pull/1497  的副作用？这个行为应该不符合预期。

**Comment by pointhalo** [comment]
v2.32.2 fix
