### ISSUE TITLE
[Steps] <Semi的Steps组件在onChange为空时item不应该有hover状态，会让用户以为是可点击的，实际上并没有处理点击事件>

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#1554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Steps

### Current Behavior

Semi的Steps组件在onChange为空时item不应该有hover状态，会让用户以为是可点击的，实际上并没有处理点击事件

![img_v2_d55c7479-3708-408a-a4de-3828b6f6ddcg](https://user-images.githubusercontent.com/29626873/232664617-2cb65818-fc88-460e-84e3-24283a4ee4f0.jpg)

antd的步骤条就很好地处理了这个问题，可以参考下：https://ant.design/components/steps-cn
![img_v2_d379077f-f526-4eed-b1fb-c65580d7e40g](https://user-images.githubusercontent.com/29626873/232664659-6033be2d-9077-4bec-937c-66a71db7f1b8.jpg)

oncall 4530119

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
v2.34 beta fix

**Comment by byxiaozhi** [comment]
这个问题目前看来还未完全解决。
1. 默认步骤条（旧版）在没有 onChange 事件时，虽然没有按钮的hover样式，但是仍然有按钮的active样式。
2. 默认步骤条（旧版）在有 onChange 事件时，按钮光标并没有变为手型。
3. 简单步骤条（新版）在没有 onChange 事件时，光标仍旧是手型。
