### ISSUE TITLE
DatePicker的 vertical align导致某些情况下 对不齐

### ISSUE THREAD

**Issue by iktsuarpok-luo** [DouyinFE/semi-design#1561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

DatePicker

### Semi Version

2

### Current Behavior

semi2 DatePick新增了vertical-align: top; 属性，导致在外层有更高高度且设置    align-items: center;的情况下，semi1可以保证居中对齐，但semi2 datepick靠上

### ReproducibleCode

```markdown
<div style={{lineHeight: "42px";alignItems: "center"}}>
    <Select/>
    <DatePicker/>
    <Select/>
</div>
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
@shijiatongxue 看下这个问题，vertical-align:是必须的吗？

**Comment by shijiatongxue** [comment]
这个代码好像无法复现这个问题？

**Comment by shijiatongxue** [comment]
> 这个代码好像无法复现这个问题？

semi 1

![image](https://user-images.githubusercontent.com/26477537/233053790-6cc2ac5e-0cfc-48de-bbe7-b8ce6e134763.png)

semi2

<img width="2060" alt="image" src="https://user-images.githubusercontent.com/26477537/233053898-89908284-5cec-41b8-9340-27772f5c3a81.png">

**Comment by pointhalo** [comment]
补充一下复现 Demo. 在 父级 display flex 且 aligenItems center时的展示会受影响

```
import React from 'react';
import { DatePicker, Select } from '@douyinfe/semi-ui';
() => {
    return (
        <div style={{lineHeight: "42px", aligenItems: "center", display: "flex"}}>
            <div><Select/></div>
            <div><DatePicker type="dateRange"/></div>
            <div><Select/></div>
        </div>
    )
}
```

**Comment by shijiatongxue** [comment]
2.36.0-beta.0 fixed
