### ISSUE TITLE
[Typography] ellipsis  can't work expected when using in  TabPane props.tab

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#1577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Typography

### Semi Version

all - 2.34.0-beta.0

### Current Behavior

Same Code render different

https://codesandbox.io/s/modern-bird-2fzb05?file=/src/App.js

![image](https://user-images.githubusercontent.com/88709023/234291450-0ed272fd-405a-4eb4-9a06-319a2d24bd10.png)

### ReproducibleCode

```markdown
import "./styles.css";
import { useState } from "react";
import { Space, Typography, Modal, Button, Tabs } from "@douyinfe/semi-ui";

const Text = Typography.Text;
const TabPane = Tabs.TabPane;

const EllipsisDemo = (
  <Typography.Text
    copyable
    style={{ width: 20 }}
    ellipsis={{
      showTooltip: {
        opts: {
          content: "123421412412421412412312321312312214",
          style: {
            wordBreak: "break-all"
          }
        }
      }
    }}
  >
    124饿24饿242112 4e21421412412412421421
  </Typography.Text>
);

export default function App() {
  return (
    <>
      <div>
        <Tabs type="line" motion={false}>
          <TabPane
            tab={
              EllipsisDemo
            }
            itemKey="1"
          ></TabPane>
        </Tabs>
        {EllipsisDemo}
      </div>
    </>
  );
}

```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
1. if remove  `display: flex`，ellipsis will be fine
2. if remove `copyable`， also fine

**Comment by YyumeiZhang** [comment]
![image](https://user-images.githubusercontent.com/101110131/234513559-098f2a0b-edbe-4731-a218-acc0a12a2d9b.png)
因为有 复制 icon，所以采用的是 js 截断
Tabs 中设置了 white-space 为 no-wrap，所以导致影子容器中的内容无法换行，判断是否超出的计算 inRange 依据是高度是否超出，所以认为没有超出，不需要截断。

[white-space](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) 设置对换行和空白符号有影响，因此不能在影子容器中固定设置

为兼容此情况，对于 no-wrap，需要通过宽度进行判断，fixed 定位的影子容器对内表现是block效果，则maxWidth 为通过 getComputeStyle计算所得高度。
