### ISSUE TITLE
官网报错

### ISSUE THREAD

**Issue by 3438722695** [DouyinFE/semi-design#158]
## https://semi.design/zh-CN/basic/grid 报错，无法打开

**报错信息：**
```
Uncaught ReferenceError: globalThis is not defined
    at Function.value (Modal.tsx:199)
    at n.value (Modal.tsx:238)
    at lo (react-dom.production.min.js:212)
    at pu (react-dom.production.min.js:255)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ql (react-dom.production.min.js:122)
    at du (react-dom.production.min.js:248)
    at Zo (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
```

**浏览器信息：**
```
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3870.400 QQBrowser/10.8.4405.400
```

**Comment by boomboomchen** [comment]
这个问题应该是浏览器版本过低导致的，目前 semi 支持的浏览器版本可见 [README](https://github.com/DouyinFE/semi-design/blob/main/README.md)

**Comment by leenin** [comment]
504啦

**Comment by 3438722695** [comment]
> 这个问题应该是浏览器版本过低导致的，目前 semi 支持的浏览器版本可见 [README](https://github.com/DouyinFE/semi-design/blob/main/README.md#-platform-support)

确实是浏览器版本低导致，希望后期能扩大兼容行列吧，我的浏览器应该要比常规用户的版本高一些，如果我的无法支持的话，很多用户会没有办法使用

**Comment by pointhalo** [comment]
globalThis是自chrome 71支持的特性。https://caniuse.com/?search=globalThis，这个case我们可以加一个try catch，但是整体来说Semi对于一些较旧版本浏览器的兼容，目前不在我们的roadmap中。
另外补充一下，Semi的主题方案使用 css variables 技术，这个特性是69添加的，一些特殊浏览器，例如QQ浏览器最新只到70，意味着大部分非最新版QQ浏览器用户都是没办法正常使用网站的。且css variables 特性无法被完美 polyfill。如果确实需要支持低版本浏览器的话，需要准备业务降级方案。

整体兼容性的支持基线会基于css variable的最低支持版本。

**Comment by pointhalo** [comment]
@DaiQiangReal Modal这里调用GlobalThis获取scrollWidth之前，还是先判断一下吧，兼容一下，不要直接去call

**Comment by pointhalo** [comment]
已对globalThis做兜底兼容处理
