### ISSUE TITLE
ImagePreview nextjs  2.34.1  IntersectionObserver is not defined

### ISSUE THREAD

**Issue by wanglihuaya** [DouyinFE/semi-design#1595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

ImagePreview

### Semi Version

2.34.1

### Current Behavior

2.34.1, nextjs, build, error, IntersectionObserver is not defined

2.32.2 is ok

### Expected Behavior

build success

### Steps To Reproduce

1. nextjs
2. yarn build

### ReproducibleCode

```markdown
2.34.1
```

### Environment

```markdown
- OS: MacOS
- browser: Chrome
```

**Comment by YyumeiZhang** [comment]
2.34.1 版本中关于 Image 组件的修改中将 intersectionObserver 的调用放在了 construct 中，导致在 ssr 服务端渲染时候，会出现找不到 interSectionObserver 的情况，我们近期修改下

**Comment by wanglihuaya** [comment]
> 2.34.1 版本中关于 Image 组件的修改中将 intersectionObserver 的调用放在了 construct 中，导致在 ssr 服务端渲染时候，会出现找不到 interSectionObserver 的情况，我们近期修改下

ok

**Comment by pointhalo** [comment]
fix v2.36.0
