### ISSUE TITLE
[Nav] footer add onClick callback

### ISSUE THREAD

**Issue by Axbros** [DouyinFE/semi-design#1605]
### Which Component Need Enhancement 期望新增功能的组件
- Nav.Footer

### What does the proposed API look like 
希望能给Nav.Footer增加一个onClick事件，由于我的侧边栏不仅有Nav.Item，还会有一些自定义的元素，在收缩侧边栏之后，会导致我侧边栏自定义的元素样式紊乱，所以建议增加一个onClick事件，通过他来控制自定义元素的显示或者隐藏

**Comment by pointhalo** [comment]
v 2.36-beta.0 support
