### ISSUE TITLE
[BUG] <Input 与 TextArea 的 autoFocus Props 拼写写法不同> 

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#1608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Input

### Semi Version

latest

### Current Behavior

想要 自动聚焦 

Input 在且仅在传入 autofocus 生效 `<Input autofocus></Input>`

而

TextArea 在且仅在传入 autoFocus 生效` <TextArea autoFocus></TextArea>`

两个组件 API 拼写不同

### Expected Behavior

两个组件 API 拼写相同

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
原生 html input的 API 是 autofocus（小写）：https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus

但如果直接写 autofocus ，react 会抛出 warning

![image](https://github.com/DouyinFE/semi-design/assets/88709023/c5ab2d54-2402-4b83-88ef-b2a719d5beee)

这里理想情况应该是 文档以及 interface上以 autoFocus为准，但对 autofocus同样兜底，将其转成大写后再传入最终的dom，避免抛出 warning。

**Comment by pointhalo** [comment]
fix 2.41.1

**Comment by pointhalo** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/88709023/70bba493-18be-4c97-876c-9fbaafa02539)
![image](https://github.com/DouyinFE/semi-design/assets/88709023/45a438af-8249-40eb-ad28-9fbce3715047)


使用 AutoComplete 时会有 warning，这里需要再处理一下。 @DaiQiangReal 
triggerRender传出的key保持不变，防止 breaking change。当非triggerRender模式时，传入 Input的应该为 autoFocus

**Comment by popdo** [comment]
> ![image](https://private-user-images.githubusercontent.com/88709023/261913916-70bba493-18be-4c97-876c-9fbaafa02539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NzQzODQsIm5iZiI6MTcwOTU3NDA4NCwicGF0aCI6Ii84ODcwOTAyMy8yNjE5MTM5MTYtNzBiYmE0OTMtMThiZS00Yzk3LTg3NmMtOWZiYWFmYTAyNTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE3NDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNjFiMTcwN2ZiYzQyMzRiMGY2NDNhYzJjNzFkNzczZjZmOWIwOGVhZjhmNjI5MzhjMWExNWU1ZDhjZmUwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3R5V28K-bDnj-InhQlleMTkrXxq_NbvjOL2UT8a2G1E) ![image](https://private-user-images.githubusercontent.com/88709023/261913985-45a438af-8249-40eb-ad28-9fbce3715047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NzQzODQsIm5iZiI6MTcwOTU3NDA4NCwicGF0aCI6Ii84ODcwOTAyMy8yNjE5MTM5ODUtNDVhNDM4YWYtODI0OS00MGViLWFkMjgtOWZiY2UzNzE1MDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE3NDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNjEwNGRiMWJhNTNmZWFiYTdhNTRiZjM1NDgzNzE3MGI4ZGI3MjAxYzIyY2EyNzU1NmRlODY4YTJjODJiMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7bF7wKNsJ_U8PAL4HHuwJkjqe57FEqjJDjFjpGAWFS8)
> 
> 使用 AutoComplete 时会有 warning，这里需要再处理一下。 @DaiQiangReal triggerRender传出的key保持不变，防止 breaking change。当非triggerRender模式时，传入 Input的应该为 autoFocus

This issue has not been addressed yet，v2.53
