### ISSUE TITLE
https://semi.design/  挂了

### ISSUE THREAD

**Issue by zhaopengme** [DouyinFE/semi-design#161]
https://semi.design/ 挂了,竟然几个小时,没人处理

**Comment by terry-fei** [comment]
504 +1

**Comment by xiaozi** [comment]
504 +1

**Comment by shijiatongxue** [comment]
由于网络基础服务出现问题，导致了一系列服务不可用，目前网络服务应该都已经恢复了。给大家带来不便非常抱歉。

![image](https://user-images.githubusercontent.com/26477537/139790038-0d79e3d5-fbc8-44b4-8053-009f40776b46.png)

有需要可以加下用户群哈，有问题我们会及时在群里同步 ❤

![image](https://user-images.githubusercontent.com/26477537/139789821-2ff4f0ad-8ea8-4b57-8c4a-155332538266.png)

**Comment by shijiatongxue** [comment]
受底层机房网络故障影响，导致站点服务不可用，相关团队一直在跟进处理。但确实处理时长有待改进，我们后续会增加容灾方案的建设。
