### ISSUE TITLE
[Upload] 通过Ctrl+c/v等操作，从剪切板获取图片或者文件并上传的能力

### ISSUE THREAD

**Issue by yangliu97** [DouyinFE/semi-design#1612]
### Which Component Need Enhancement 期望新增功能的组件
- Upload

### Feature Description 功能描述
增加配置项，支持通过Ctrl+c/v等操作，从剪切板获取图片或者文件并上传的能力

### Additional information 补充说明
用户在聊天框或者其他网页复制图片，切换回拥有Upload的页面，通过Ctrl+v或自动读取剪切板的操作，可以直接将复制的内容上传。

**Comment by pointhalo** [comment]
v2.43.0-beta.0.  `addOnPasting`
