### ISSUE TITLE
跪求出一套vue版的 全套组件

### ISSUE THREAD

**Issue by lovesL** [DouyinFE/semi-design#1635]
### Which Component Need Enhancement 期望新增功能的组件
- Button

**Comment by pointhalo** [comment]
duplicate https://github.com/DouyinFE/semi-design/issues/311
详细原因在上述issue里已有过解释。

我们团队本身是 React 的重度用户，自身的业务诉求上对其他框架依赖并不强。如果我们自己都没法在业务里用，其实是没法去保障建设质量以及保证持久维护的。
所以没有这类计划，不会做相应推进。
