### ISSUE TITLE
[BUG] Dropdown的child太长时，弹出动画有些别扭

### ISSUE THREAD

**Issue by l0g1n** [DouyinFE/semi-design#1637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Dropdown

### Semi Version

2.36.0

### Current Behavior

```
      <Card style={{ marginBottom: 12 }}>
        <Dropdown
          trigger={'focus'}
          position={'bottomLeft'}
          render={
            <Dropdown.Menu tabIndex={-1}>
              <Dropdown.Item>Menu Item 1</Dropdown.Item>
              <Dropdown.Item>Menu Item 2</Dropdown.Item>
              <Dropdown.Item>Menu Item 3</Dropdown.Item>
            </Dropdown.Menu>
          }
        >
          <div style={{
            border: '1px solid var(--semi-color-border)',
            borderRadius: 4,
            height: 36,
            width: 1600
          }}>
            Please use Tab to focus this div
          </div>
        </Dropdown>
      </Card>
```
当内部的触发器宽度太大时，Dropdown弹出时，position设置为bottomLeft和bottomRight，会出现漂移的感觉，如何进行修改。而position设置为bottom时，不会出现。

https://github.com/DouyinFE/semi-design/assets/7485747/162df3a0-ce6a-44da-9f9b-dba8d26353ec

### Environment

```markdown
- OS: MacOS 13.4
- browser: Chrome 113
```

**Comment by YyumeiZhang** [comment]
我理解和弹出层的位置计算逻辑有关系，因为width设置的太长，超出屏幕宽度，导致弹出层的位置进行了多次计算（刚开始依据 bottomLeft ，结果发现位置超出屏幕，所以重新计算），所以有漂移的视觉效果。如果怎么长的触发器一定要保留的话，或者长的内容外部再包一层看看

**Comment by l0g1n** [comment]
感谢回复，设置宽度为1600，并未超出屏幕宽度，将宽度改为600后，依然会飘逸。只是设置大一些，效果更明显。

**Comment by l0g1n** [comment]
增加transformFromCenter={false}后，效果好了
