### ISSUE TITLE
轮播图可以加一个上下的，就是可以滚动上下轮播哪种

### ISSUE THREAD

**Issue by 43374166** [DouyinFE/semi-design#1642]
### Which Component Need Enhancement 期望新增功能的组件
- 轮播图（Carousel）

### Feature Description 功能描述
- 希望出一个上下滚动的哪种，类似米哈游官网的哪种轮播图

**Comment by pointhalo** [comment]
- 使用场景偏少，暂时不考虑推进
- 如果确实是强需求，欢迎提PR
