### ISSUE TITLE
[Table] 希望可以把筛选下拉框加一个滚动条

### ISSUE THREAD

**Issue by BZC1364976259** [DouyinFE/semi-design#1647]
### Which Component Need Enhancement 期望新增功能的组件
- Table

### Feature Description 功能描述
希望把默认开启的筛选加上一个滚动条，数据量大的话显得十分不美观

### Additional information 补充说明
无

**Comment by BZC1364976259** [comment]
滚动条

**Comment by pointhalo** [comment]
是指这个区域吗?
![image](https://github.com/DouyinFE/semi-design/assets/88709023/2656b973-35a2-4623-8c53-69622ea6d03f)

**Comment by BZC1364976259** [comment]
@pointhalo 是的

**Comment by BZC1364976259** [comment]
> 是指这个区域吗？ ![图像](https://user-images.githubusercontent.com/88709023/244289285-2656b973-35a2-4623-8c53-69622ea6d03f.png)

是的，我再回复您一下，因为我不到上面的你能不能看到....第一次提issue

**Comment by BZC1364976259** [comment]
> 好的。我们加一下最大高度限制，超出后滚动。@shijiatongxue

好的，谢谢您
