### ISSUE TITLE
[BUG] ImagePreview好像没法传递className

### ISSUE THREAD

**Issue by xmsz** [DouyinFE/semi-design#1657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

ImagePreview

### Semi Version

new

### Current Behavior

```
<ImagePreview className="a"/>
```
- 没有效果
- 我看源码好像也没有把className追加上
- style倒是有生效

### Environment

```markdown
- OS:
- browser:
```

**Comment by YyumeiZhang** [comment]
确实代码里面只将 style 传入了，没有把 className 传入，是个 bug，修复跟版本v2.38.0-beta.0，预计2023.06.19
