### ISSUE TITLE
Toast 无类型提示

### ISSUE THREAD

**Issue by boenfu** [DouyinFE/semi-design#166]
### Which Component 出现bug的组件
  - Toast

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  -  有类型提示

### Actual result 实际的结果是什么
  -  无类型提示

### Reproducible code 复现代码
```
import { Toast } from '@douyinfe/semi-ui'; // Toast is any type
```

### Additional information 补充说明
- 应该是 `packages/semi-ui/toast/index.tsx:34` line 的 any

**Comment by wanghan-js** [comment]
附议！
真的很喜欢 semi 的设计感，但是一个常用组件 Toast 居然类型标记为 any，真的太减分啦。
希望尽快修复！

![image](https://user-images.githubusercontent.com/29141768/139818062-4c7b8a87-fc55-42c7-a566-9b0b943b11c4.png)
