### ISSUE TITLE
[BUG] <autoComplete> 长按候选项 下拉框消失且没有选中，短按 有时 onSelect 未触发

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#1665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

autoComplete

### Current Behavior

长按候选项，下拉框收起 且未选中

### Expected Behavior

长按候选项，无反应

### Environment

```markdown
- OS:
- browser:
```

**Comment by wpnl** [comment]
这个有预计修复时间吗
