### ISSUE TITLE
[BUG] Select多选有filter的情况下，换行之后最后一行的间距与其他不一致

### ISSUE THREAD

**Issue by fwxhn** [DouyinFE/semi-design#1667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select

### Current Behavior

![image](https://github.com/DouyinFE/semi-design/assets/33595711/66c0494b-ca31-48b1-bec2-e56ab4b3b0ae)

### Expected Behavior

间距保持一致

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
麻烦使用的版本号给一下？我在官网latest上没有复现你的问题。

![image](https://github.com/DouyinFE/semi-design/assets/88709023/cca73d9c-c113-4030-8001-9de37dc12b7e)

**Comment by fwxhn** [comment]
多选有filter的情况，没有filter是正常的

**Comment by pointhalo** [comment]
get，filter=true下能复现。这个应该是 filter带的input line-height造成了影响，我们后续统一一下

**Comment by pointhalo** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/88709023/cd4ee9c4-f642-48a7-aef0-69f92c93dbf1)
fix v2.56.0-beta.0
