### ISSUE TITLE
[Notification] 是否可以新增参数 id，实现和 toast 一样的更新功能

### ISSUE THREAD

**Issue by moonsky-all** [DouyinFE/semi-design#1677]
### Which Component Need Enhancement 期望新增功能的组件
- Notification

### What does the proposed API look like 期望支持的API

Notification 新增参数 id，实现和 Toast 一样的更新功能

### Feature Description 功能描述

为什么要用 Notification 而不直接用 Toast：

Notification 相比 Toast 能提示更多内容，位置比较靠边，对页面主要内容的阅读和编辑影响比较小，业务中部分信息还有交互不能简单的直接关闭；

但是：
1.  Notification 每次提示都是单独弹出，所以在偶尔错误信息多的时候占用的地方也很大，所以期望某些业务上能归类的信息始终**更新**到同一个通知里；
2. Notification 多的时候不能上下滚动，更早弹出的通知可能就看不见了（这个项目中自己在 semi-notification-list 添加最大高度 100vh 和 overflow: auto，但还是希望 semi 能原生支持下）

**Comment by pointhalo** [comment]
👌，后续版本加上 @DaiQiangReal

**Comment by moonsky-all** [comment]
请问什么时候能发版这个功能呢

**Comment by pointhalo** [comment]
目前没有进入开发，具体得看 @DaiQiangReal 什么时候有空搞

**Comment by pointhalo** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/88709023/6cf6bdf1-21eb-4029-8f09-452dc5187db6)


23.10月发布的 2.45.0-beta.0 及以上版本已支持。
