### ISSUE TITLE
[RadioGroup] 表单校验有问题

### ISSUE THREAD

**Issue by moonsky-all** [DouyinFE/semi-design#1687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

RadioGroup

### Semi Version

2.36.0

### Current Behavior

![image](https://github.com/DouyinFE/semi-design/assets/82572484/4cdd0141-25db-4557-a467-f4f7263b18d1)

表单校验有问题，而且提示问题尾部出现莫名的英文

### Expected Behavior

1. 这里应该是能校验通过的；
2. 错误提示语尾部不应出现莫名的英文

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
给一下复现代码~

**Comment by moonsky-all** [comment]
我的操作步骤是调用 formApi.setValues 后直接提交，没有任何编辑动作

**Comment by pointhalo** [comment]
具体Render代码怎么写的呢？光上面这些信息我都不知道校验规则配了什么

**Comment by moonsky-all** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/82572484/2df816d6-8085-4902-8091-266bba21f852)

**Comment by moonsky-all** [comment]
校验规则是： [ { required: true, message: '"类型"是必填项' } ]

**Comment by pointhalo** [comment]
你给的信息量还是不足，options具体写的什么，radio的value给的type是什么，我从上面的信息看不出来。这些都可能是影响因子。
这类问题下次可以直接给一个能运行的，最小复现demo的 codesandbox。
没有更多上下文的前提下，我没法给你建议以及排查问题。
------

1. 我本地测试过 radio的type，无论是 number、boolean还是string，都不会出现 追加的 ’type fail‘
2. 即使是 RadioGroup的校验不通过，message也应该是你设置的  “类型"是必填项”，而不会是你图示的 “不能为空”。这个更像是你其他 field 未通过校验的 errormessage，跟RadioGroup无关，建议你再检查下其他代码。

**Comment by pointhalo** [comment]
你可以用 React DevTool 直接 Inspect一下 Form的内部状态。看一下这个 “不能为空，typefail” 具体是哪个key 的 errormessage（我从上面的信息，怎么看都不像是 RadioGroup的）

![image](https://github.com/DouyinFE/semi-design/assets/88709023/b5cc1ebf-9c1c-49ae-a0bb-a04fc72bfa45)
