### ISSUE TITLE
[Drawer] Display overlay area at any side of the screen

### ISSUE THREAD

**Issue by usman-faisal** [DouyinFE/semi-design#1692]
### Feature Description 功能描述
Drawer like GitHub's side panel.

**Comment by pointhalo** [comment]
Recommend to use the sidesheet component.

https://semi.design/en-US/show/sidesheet

![image](https://github.com/DouyinFE/semi-design/assets/88709023/e13dfbde-c1e9-4e67-977d-522e576a9dd3)
