### ISSUE TITLE
[Tree] 部分场景下，不停闪烁

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#1696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

tree

### Semi Version

latest

### Current Behavior

部分场景下，不停闪烁

### Expected Behavior

https://codesandbox.io/s/nifty-dream-qg53cn

https://github.com/DouyinFE/semi-design/assets/29626873/f516bae7-6378-4353-844c-685988075ca1

相关:
同样表现，但原因可能不同的另一个issue
https://github.com/bvaughn/react-window/issues/681

### Environment

```markdown
- OS:
- browser:
```

**Comment by YyumeiZhang** [comment]
react-window 中对于tree中treeNode元素的位置定位采用绝对定位
![image](https://github.com/DouyinFE/semi-design/assets/101110131/f7542ed9-4a34-4b5c-a5a2-be0b2397b067)
用户提供的例子中，virtualize 相关的 style 没有传入treeNode对应的层级上。
修改后的用例，https://codesandbox.io/s/nifty-dream-qg53cn?file=/src/App.js。
