### ISSUE TITLE
Add a search feature to your document

### ISSUE THREAD

**Issue by shabbyaaa** [DouyinFE/semi-design#17]
### Which Component Need Enhancement 期望新增功能的组件
- document
### Feature Description 功能描述
Add search 
### Additional information 补充说明
When you want to quickly find a component, you want a search feature
![image](https://user-images.githubusercontent.com/48679300/138805905-5affe5f0-b73d-404c-ac95-ba5d1bd02b86.png)

**Comment by DaiQiangReal** [comment]
WIP

**Comment by pointhalo** [comment]
Originally planned to access algolia, but the free version has a limit on the frequency of calls, which cannot better meet the pv of this site.
We are now based on our own internal search service, so the delivery is much later than originally planned.
We made an update last Friday and it's available now. Support Chinese and English search and recent browsing, search history
