### ISSUE TITLE
[BUG] <Nav> 组件在Nextjs 框架下编译报错

### ISSUE THREAD

**Issue by Tom-debug110** [DouyinFE/semi-design#1702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Nav

### Semi Version

最新版

### Current Behavior

使用 npx create-next-app 创建模版项目，无论哪种类型的工程，ts，还是js，都会编译错误。 
<img width="1000" alt="image" src="https://github.com/DouyinFE/semi-design/assets/70630606/634ecb60-7307-4d17-a84a-ec2c5420b933">

### Expected Behavior

可以正常结合导航创建

### ReproducibleCode

```markdown
function Navigation() {
    return (
        <Nav
            renderWrapper={({itemElement, isSubNav, isInSubNav, props}) => {
                const routerMap = {
                    Home: "/",
                    About: "/about",
                    Dashboard: "/dashboard",
                    "Nothing Here": "/nothing-here"
                };
                return (
                    <Link
                        style={{textDecoration: "none"}}
                        to={routerMap[props.itemKey]}
                    >
                        {itemElement}
                    </Link>
                );
            }}
            items={[
                {itemKey: "Home", text: "Home"},
                {itemKey: "About", text: "About"},
                {
                    text: "Sub",
                    itemKey: "Sub",
                    items: ["Dashboard", "Nothing Here"]
                }
            ]}
        ></Nav>
    )
}

export default function Home() {
    return (
        <Navigation/>
    )
}
```

### Environment

```markdown
- OS: MacOS 13.4
- browser: Edge 114.0.1823.79 (正式版本) (x86_64)
```

### Anything else?

前端刚刚入手，还请大佬见谅

**Comment by Tom-debug110** [comment]
基础 react 工程没有问题呢

**Comment by pointhalo** [comment]
SSR Node环境中没有docuemnt，window这类浏览器宿主的变量，所以如果这么用肯定是会报错的。这个是通识部分的概念了，所以一般不会不会特意再做文档说明

> 找到问题啦，因为 `<APP>` 组件没有被 `<BrowerRouter>` 包裹，但是又出现了一个新的问题，对于新人好像不太好解决 https://stackoverflow.com/questions/60629258/next-js-document-is-not-defined

**Comment by pointhalo** [comment]
1. 你的第一个图，报错是因为首先你用的 next 版本应该较低。Next有很多自己的特殊限制（例如对css import的限制）。推荐可以先看下 semi 的 getting start
![image](https://github.com/DouyinFE/semi-design/assets/88709023/4b5962f1-81ec-4547-b9cd-561d94a4f12b)

2. 上述代码应该是不包含 document 的使用的，我不知道你的第二个报错从哪里来。
4. Next是一个基于 react 进行了很多封装的开发框架，是有一定的上手门槛的，并且目前新版本的一些设定也比较激进，例如默认就是react server component。如果你对  react 尚不是很熟悉，我建议先通读完 React 的文档再入手 Next。
5. 涉及构建类的问题，可以基于 stackblitz.com 创建复现demo。不然信息量不够，我们没法排查
