### ISSUE TITLE
[TagInput] 可以增加滚动吗？

### ISSUE THREAD

**Issue by Jarvie789** [DouyinFE/semi-design#1708]
### Which Component Need Enhancement 期望新增功能的组件
- TagInput 超出高度可以滚动吗？

**Comment by pointhalo** [comment]
可以直接用css 选择器 semi-tagInput-wrapper，对DOM 直接按需追加 overflow scroll和你想配置的 height属性。

**Comment by Jarvie789** [comment]
> 可以直接用css 选择器 semi-tagInput-wrapper，对DOM 直接按需追加 overflow scroll和你想配置的 height属性。

好，感谢老哥，一开始我是这样做的，但感觉和Textarea有出入。目前已经换用List控件了 👍
