### ISSUE TITLE
InputNumber 超出最大数值 显示为科学记数法了 

### ISSUE THREAD

**Issue by shxinlei** [DouyinFE/semi-design#171]
### Which Component 出现bug的组件
  - InputNumber

### semi-ui version
  - latest
    2.0.0
### Expected result 期望的结果是什么
  - 
InputNumber 超出最大JS 数值超过16位后正常显示 并且值能够正常拿取
### Actual result 实际的结果是什么
  - 
超出最大数值后显示为科学计算法 值无法使用
### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```
<InputNumber defaultValue={12323453423453423423423} onChange={(value: number) => {console.log(value)}}/>

```

**Comment by shijiatongxue** [comment]
InputNumber 支持的最大安全数字为 JavaScript 支持的 Number.MAX_SAFE_INTERGER（暂不支持 bigInt）。如果有大数需求，建议使用 Input 组件。:heart:
