### ISSUE TITLE
[Button] Image希望可以传入背景颜色

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1719]
### Which Component Need Enhancement 期望新增功能的组件
- Image

### What does the proposed API look like 期望支持的API
bgColor="#fff"
skeletonClass="bg-white"

### Feature Description 功能描述

- 现在的Image有默认的背景颜色，为灰色。
- 我们想要默认是白色
- 希望可增加属性支持

### Additional information 补充说明

还有这个圆角没对齐，skeleton是写死的4px，但外面一层则是变量控制的默认3px
<img width="493" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/284b3d04-6f26-412d-8f48-87d9096bfb4c">

**Comment by YyumeiZhang** [comment]
Skeleton.Image 和 Image 的圆角确实可以做下对齐，支持背景色设置指的是 Image 组件预览状态下的背景色？

**Comment by xmsz-stu** [comment]
> 支持背景色设置指的是 Image 组件预览状态下的背景色？

1. 图片还没完全加载的背景色
2. 透明图片的背景色

**Comment by YyumeiZhang** [comment]
”透明图片的背景色“： 我理解我们是没有设置相应颜色的；
“图片还没完全加载的背景色”：有以下方法可以尝试看是否达到你要的效果，
1. 可以通过Image 的style / className设置 background color，看下是否符合你预期；
2. 如果1不满足你的需求，那么应该指的是skeleton 的颜色问题，如果你的预期是全局的 skeleton 颜色改变，可以考虑通过 DSM 定制 skeleton的颜色。如果只是少数使用位置，可以考虑通过 css 覆盖 样式。或者通过 placeholder 参数传入一个背景色为白色的div，宽高 100%。
