### ISSUE TITLE
Rating 未根据 value 值显示与隐藏星星

### ISSUE THREAD

**Issue by shxinlei** [DouyinFE/semi-design#172]
### Which Component 出现bug的组件
  -Rating

### semi-ui version
  - latest
    2.0.0
### Expected result 期望的结果是什么
  - 
正常根据value 值的变更 显示与隐藏星星

### Actual result 实际的结果是什么
  - 
![image](https://user-images.githubusercontent.com/54462126/139834098-dba453aa-73dc-499c-b2fc-800fb87e16cf.png)

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```
https://gitee.com/shi_xinlei/semi-demo.git

```

**Comment by shxinlei** [comment]
鼠标放在星星上进行点击。
第一次星星隐藏, 值为 0  ,第二次点击激活星星值为4  ,但是星星无显示效果

**Comment by pointhalo** [comment]
Hi，你贴的gitee链接并非是公开的。可以贴一个简单的复现代码吗？（Ps：Semi官网的组件demo区是可实时编辑演示的，可以按照你的使用方式编辑一个demo，然后贴在这里）

**Comment by shxinlei** [comment]
import React, { useState } from 'react';
import { Rating } from '@douyinfe/semi-ui';

() => {
    const [value,  setValue] = useState(0);
    console.log(value)
    const change = (val) => setValue(val);
    const desc = ['terrible', 'bad', 'normal', 'good', 'wonderful'];
    return (
        <div>
            <span>How was the help you received: 
                {value ? <span>{desc[value - 1]}</span> : ''}
            </span>
            <br/>
            <Rating tooltips={desc} onChange={change} value={value} />
        </div>
    );
}

鼠标不移动 会出现这个情况

**Comment by tank0317** [comment]
同 #103
