### ISSUE TITLE
[Button] 是否可以默认不带margin

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1723]
### Which Component Need Enhancement 期望新增功能的组件
- Button

### What does the proposed API look like 期望支持的API
margin不设置

### Feature Description 功能描述
现在默认会有个margin，然后我用className覆盖经常被覆盖

**Comment by YyumeiZhang** [comment]
@xmsz-stu 默认是没有 margin 的
![image](https://github.com/DouyinFE/semi-design/assets/101110131/b2b7133d-1617-4f17-8e36-e1c30f91ee99)

**Comment by xmsz-stu** [comment]
> @xmsz-stu 默认是没有 margin 的 ![image](https://user-images.githubusercontent.com/101110131/255508632-b2b7133d-1617-4f17-8e36-e1c30f91ee99.png)

就是semi默认设置了一个margin
<img width="1464" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/1eff585a-67a9-4e83-9d1c-b4d7b6b0936c">
然后semi样式的优先级比我的样式(tailwindcss)高，会被覆盖掉
