### ISSUE TITLE
[INSTALL] 能否自行引入css

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1724]
### Which Component Need Enhancement 期望新增功能的组件
- 现在默认是自动引入了组件的css
- 但是很容易导致css引入顺序问题，比如引入tailwindcss的时候，刷新页面semi的优先级就比tailwindcss高

### What does the proposed API look like 期望支持的API
- 希望可以手动引入css

**Comment by pointhalo** [comment]
没有计划这么做。
这类lib的趋势就是资源整体控制，不会再做拆分。

**Comment by xmsz-stu** [comment]
> 



> webpack 里配置loader， include 写semi 在 node_modules 里的路径，然后loader 里加个 null-loader 这样就没 css 了，然后自己在项目里再手动import semi 的 全量 css

ok 我试一下
