### ISSUE TITLE
[Theme] 主题默认字体支持更换吗？

### ISSUE THREAD

**Issue by Jarvie789** [DouyinFE/semi-design#1733]
### Which Component Need Enhancement 期望新增功能的组件
- 主题默认字体更换

**Comment by pointhalo** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/88709023/ef94b773-79f9-4c7e-b9f3-dd1e6ba1fb6c)

https://semi.design/dsm 直接在 DSM 中配置就行。发布成npm包，在项目里使用。

**Comment by jiushiwoyuze** [comment]
貌似不可以新增字体，只能调整顺序

**Comment by Jarvie789** [comment]
> 貌似不可以新增字体，只能调整顺序

客制化就行了

**Comment by pointhalo** [comment]
字体配置本质上是一个  font-family 声明。你想用什么字体，就直接 inpu输入名称配置就行。
但要注意的是，Semi 并不直接提供字体资源，如果你声明的是非系统字体，是自定义字体，那你需要自己引入这个字体对应的ttf等资源。

**Comment by jiushiwoyuze** [comment]
感谢回复，我尝试在dsm新增了字体，但是没有效果，新增的字体不会被识别到
![image](https://github.com/DouyinFE/semi-design/assets/5416077/693f8859-4dc5-4251-b23b-0fdec842b372)
![image](https://github.com/DouyinFE/semi-design/assets/5416077/82216034-a220-4f34-b295-44369fb50084)

**Comment by jiushiwoyuze** [comment]
@pointhalo 感谢回复，我按照文档配置了，但自定义的样式还是被覆盖了，https://github.com/DouyinFE/semi-design/issues/1991，麻烦有空帮看下
