### ISSUE TITLE
[BUG] How can I load `svg` image from local cache directory?

### ISSUE THREAD

**Issue by PublicWorld** [DouyinFE/semi-design#1735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Image

### Semi Version

2.39.0

### Current Behavior

I want to load a svg file, but seems it's not support, could you help to check this?
> I can load png file from this `/var/folders/***`
e.g:
file:///var/folders/t9/rfcr5vmx4j93g923pl0z7st00000gn/T/fire/2f19e56695d9e2a0d05a254aaec3ec8fb151de05a581f1fae02a44bf5ba4bb63.svg

<img width="68" alt="image" src="https://github.com/DouyinFE/semi-design/assets/12987627/de39c339-ce4c-424b-a35f-bce52adad70d">

### Expected Behavior

expected it's work well.

Thanks!

### Environment

```markdown
- OS: macOS 13.5
- browser:
```

**Comment by YyumeiZhang** [comment]
Using the Image component cannot be used to display local images or svg, May you can upload local svg to the server

**Comment by pointhalo** [comment]
This is a build related engineering issue. It depends on what loader or plugin your svg will be processed by.
you can google it

**Comment by pointhalo** [comment]
file:// xxx  is the path only exist on your local dev environment (your computer), you can't use this path to declare as static source path.
