### ISSUE TITLE
[Form] formApi.setValue的类型如何支持多级对象

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1737]
### Which Component Need Enhancement 期望新增功能的组件
- Form

### What does the proposed API look like 期望支持的API
支持传入类型？

### Feature Description 功能描述
![image](https://github.com/DouyinFE/semi-design/assets/139225486/3a66cd78-5830-42e5-9eab-40a0196b8c6a)

**Comment by pointhalo** [comment]
support v2.59.0

**Comment by xmsz-stu** [comment]
如果我这些 
formApi.setValue(`messageList[${itemIdx}].role`, cur || '');
会提示
```
类型“`messageList[${number}].role`”的参数不能赋给类型“"messageList" | "schedule" | ... 8 more 的参数。ts(2345)
```

还有newFieldValue的类型any


能不能支持我自己传入value类型
setValue<T>(key: string, value: T)
formApi.setValue<STATE['messageList[0].role']>(`messageList[${itemIdx}].role`, cur || '');

**Comment by xmsz-stu** [comment]
还有希望useFieldState之类的也能支持类型传入，现在都是any
