### ISSUE TITLE
[BUG] <title>vite下使用vite-plugin-semi-theme插件然后使用主题导致Card阴影不生效

### ISSUE THREAD

**Issue by openSttcc** [DouyinFE/semi-design#1747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Card

### Semi Version

^2.40.0 | ^2.39.3

### Current Behavior

使用@semi-bot/semi-theme-doucreator 主题是按照官方指定操作进行配置 使用卡片组件时 阴影失效

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
给个实际渲染效果截图？

**Comment by openSttcc** [comment]
![1691025282508](https://github.com/DouyinFE/semi-design/assets/140360864/6d1e6b00-e0d5-49b1-a2f3-20a25f361426)

**Comment by openSttcc** [comment]
![1691025282516](https://github.com/DouyinFE/semi-design/assets/140360864/9fcb35cf-0cef-4a04-b3e1-cb1abd130b4c)
把那个插件去注掉就可以正常显示但是主题没了
![1691025282522](https://github.com/DouyinFE/semi-design/assets/140360864/4d58afcf-c168-407a-b8b2-a0ea7eb2391a)

**Comment by openSttcc** [comment]
我用的就是全部都是最新的 
![联想截图_20230810105843](https://github.com/DouyinFE/semi-design/assets/140360864/e7388125-1317-485b-bfd9-90d791644c2c)

**Comment by pointhalo** [comment]
验证了一下 1.0.20 没问题了
![image](https://github.com/DouyinFE/semi-design/assets/88709023/abc1d82f-cbcc-4998-bf30-e8d0e9812507)
![image](https://github.com/DouyinFE/semi-design/assets/88709023/4fa3fae0-dc86-4e5b-9d14-2a657010269b)
![image](https://github.com/DouyinFE/semi-design/assets/88709023/0e9201f0-31b6-40c4-99be-ea7a434194e3)
