### ISSUE TITLE
[BUG] <Step 组件在网页加载完之后有一个默认选中的框>

### ISSUE THREAD

**Issue by Bohan-J** [DouyinFE/semi-design#1755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Step 

### Semi Version

2.32.0

### Current Behavior

![image](https://github.com/DouyinFE/semi-design/assets/52446949/b655a32c-affa-461c-a99a-f3503fc3b9c9)

网页进入之后 Step 组件的第一步会有一个这个选中的状态

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
这个看起来是 焦点框的样式，有做 focus相关的逻辑吗

**Comment by Bohan-J** [comment]
没有 我就直接用的
` ``
<Steps current={steps} size="small" type="basic">
        <Steps.Step
          title="Select your interests"
          description={'Initialize personal Copilots'}
        />
        <Steps.Step title="Add Copilots" description={'Finished'} />
      </Steps>
```
应该也没什么全局的设置，只有一个全局的
```
  div::-webkit-scrollbar {
    display: none;
  }
```

**Comment by YannLynn** [comment]
### 为什么会有蓝色边框？
此处显示一个蓝色的边框是因为该 div 上 tabindex 属性为 0，并且浏览器的启发式引擎认为此时焦点应该可见所以使 :focus-visible 伪类生效。（详情可参考：https://developer.mozilla.org/zh-CN/docs/Web/CSS/:focus-visible ）

该行为在具体浏览器表现会稍有不同，比如 safari 浏览器不管鼠标还是键盘导致的聚集都会让使 :focus-visible 伪类生效，而火狐则比较严格地遵循了只有在键盘聚集时才使 :focus-visible 伪类生效。

### 我不想要蓝色边框怎么改？
综合之前收到的大多数例子，一般是某些组件和 Modal 搭配使用的时候会造成这种行为，如果确认自己在 Modal 打开前没有做过任何键盘操作，那这个表现大概率是和「启发式引擎」判断有关，我们建议的一个方案是通过样式覆盖的方式将 Step 上的 :focus-visible outline 设置为 none

**Comment by Bohan-J** [comment]
可以的 我加了一下
```
  .semi-steps-basic {
    div:focus-visible {
      outline: none;
    }
  }
 ```
 问题解决了
