### ISSUE TITLE
[Upload] listType = 'picture'下能否支持设置宽度高度

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1757]
### Which Component Need Enhancement 期望新增功能的组件
- Upload

### What does the proposed API look like 期望支持的API
- 支持设置高宽

### Feature Description 功能描述
- 现在是固定大小
- 但是有时候希望可以大一点或者小一点，甚至不是正方形，比如我希望这个高宽比例是固定的
![image](https://github.com/DouyinFE/semi-design/assets/139225486/57165128-551e-4717-9136-5666bf5c827e)

**Comment by pointhalo** [comment]
是指回显图片时的宽高度对吗？这个后续我们版本我们加一下。

**Comment by pointhalo** [comment]
support with [v2.42.0-beta.0](https://github.com/DouyinFE/semi-design/releases/tag/v2.42.0-beta.0)
