### ISSUE TITLE
[Upload] 能否支持设置图片预览的object-fit

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1758]
### Which Component Need Enhancement 期望新增功能的组件
- Upload

### What does the proposed API look like 期望支持的API
可以设置Upload预览图片的object-fit

### Feature Description 功能描述
- 现在是固定的cover
- 但是有时候希望完整展示图片，object-fit=contain

**Comment by pointhalo** [comment]
可以直接 css 选择器做就行了吧。DOM 类名都是固定的。这里再下探暴露出一个 style 配置不是很有必要。

<Upload className='fit-image-upload' />


css
```
.fit-image-upload {
   .semi-upload-xxx {


    }
}
```

**Comment by xmsz-stu** [comment]
> 可以直接 css 选择器做就行了吧。DOM 类名都是固定的。这里再下探暴露出一个 style 配置不是很有必要。
> 
> css
> 
> ```
> .fit-image-upload {
>    .semi-upload-xxx {
> 
> 
>     }
> }
> ```

我现在是用css写，但是有点麻烦
