### ISSUE TITLE
[Upload] 希望customRequest和fileList同时存在

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1759]
### Which Component Need Enhancement 期望新增功能的组件
- Upload

### What does the proposed API look like 期望支持的API
 希望customRequest和fileList同时存在

### Feature Description 功能描述
我将Upload组件包装成了受控组件
```
import { Upload, withField } from '@douyinfe/semi-ui';
import { UploadProps } from '@douyinfe/semi-ui/lib/es/upload';

const UploadSingle = ({
  value,
  onChange,
  ...props
}: {
  value?: string;
  onChange?: (payload?: string) => void;
} & UploadProps) => {
  return (
    <Upload
      limit={1}
      {...props}
      fileList={value ? [{ url: value, status: 'success', name: '', size: '', uid: '0' }] : []}
      onChange={(payload) => {
        onChange?.(payload.fileList[0]?.url);
      }}
    />
  );
};

export const UploadSingleField = withField(UploadSingle);

```
然后又设置了customRequest，但是这个时候customRequest的onSuccess/onError...都是无法被触发的
去除fileList以后就正常了
但是我又想fileList受控，请问如何解决

### Additional information 补充说明

或者有没有其他办法支持，不用customRequest
我现在的接口返回的是{data: {url:string}}，要如何把url赋值到之前的value?

**Comment by pointhalo** [comment]
customRequest 的用处是替代内置的默认浏览器原生 xhr 请求，所有回调都是要你主动触发才会生效。

例如你有一个第三方的上传 sdk，你通过 customRequest 拿到 file，然后调用 sdk.upload 之后，成功或者失败，或者进度更新，你都得主动调用 customRequest 入参里的 function，这样 upload才能拿到状态呀，不然它怎么感知得到呢（无法感知自然也触发不了任何状态回调呀）
![image](https://github.com/DouyinFE/semi-design/assets/88709023/4e9ae246-9659-4dec-91d9-80ee2f93f9cb)

**Comment by pointhalo** [comment]
customRequest 跟 fileList 本身就不是矛盾的。没有不能同时存在这一说。
我感觉你没有理解 customRequest 这个例子。

这个demo mock了一个网络请求，mock的假设每 500ms 就会上传 20%，5次后上传完毕。那么过程中每次进度更新，就得主动调用入参的 onProgress将状态同步给 Upload（这样它才能显示正确的进度）。

**Comment by pointhalo** [comment]
你是受控方式使用的话，其实你完全可以在 update props.fileList 之前去做修改呀。受控意味着你可以完全掌控数据结构和渲染的主动权。


```
import React from 'react';
import { Upload, Button } from '@douyinfe/semi-ui';
import { IconUpload } from '@douyinfe/semi-icons';

() => {
    const initList = [
        {
            uid: '1',
            name: 'dyBag.jpeg',
            status: 'success',
            size: '130KB',
            preview: true,
            url: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/root-web-sites/edit-bag.jpeg',
        },
    ];

    const [list, updateList] = useState(initList);

    const onChange = ({ fileList, currentFile, event }) => {

        let newFileList = [...fileList]; // spread to get new array

        // 这里能拿到你的server对于当前 file post request 的 reponse
        if (currentFile.response.data.url) {
            // 用currentFile的 uid 去找当前file在 newFileList 中是第几个
            // 然后你就可以改 url 了
            // newFileList[index].url = xxx;
        }
        updateList(newFileList);
    };

    return (
        <Upload
            action="https://api.semi.design/upload"
            onChange={onChange}
            fileList={list}
        >
            <Button icon={<IconUpload />} theme="light">
                点击上传
            </Button>
        </Upload>
    );
};

```

**Comment by xmsz-stu** [comment]
> 
我是直接直接调用customRequest入参里的onSuccess/onError，但是没有效果，如果我不设置fileList，就可以生效

**Comment by xmsz-stu** [comment]
> 你是受控方式使用的话，其实你完全可以在 update props.fileList 之前去做修改呀。受控意味着你可以完全掌控数据结构和渲染的主动权。
> 
> ```
> import React from 'react';
> import { Upload, Button } from '@douyinfe/semi-ui';
> import { IconUpload } from '@douyinfe/semi-icons';
> 
> () => {
>     const initList = [
>         {
>             uid: '1',
>             name: 'dyBag.jpeg',
>             status: 'success',
>             size: '130KB',
>             preview: true,
>             url: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/root-web-sites/edit-bag.jpeg',
>         },
>     ];
> 
>     const [list, updateList] = useState(initList);
> 
>     const onChange = ({ fileList, currentFile, event }) => {
> 
>         let newFileList = [...fileList]; // spread to get new array
> 
>         // 这里能拿到你的server对于当前 file post request 的 reponse
>         if (currentFile.response.data.url) {
>             // 用currentFile的 uid 去找当前file在 newFileList 中是第几个
>             // 然后你就可以改 url 了
>             // newFileList[index].url = xxx;
>         }
>         updateList(newFileList);
>     };
> 
>     return (
>         <Upload
>             action="https://api.semi.design/upload"
>             onChange={onChange}
>             fileList={list}
>         >
>             <Button icon={<IconUpload />} theme="light">
>                 点击上传
>             </Button>
>         </Upload>
>     );
> };
> ```

有试过 不过我想保留进度还有其他尽可能使用原来的组件的api实现

**Comment by pointhalo** [comment]
> > 
> 
> 我是直接直接调用customRequest入参里的onSuccess/onError，但是没有效果，如果我不设置fileList，就可以生效

在你贴出的代码里看不到 customRequest 的调用。

**Comment by xmsz-stu** [comment]
> > > 
> > 
> > 
> > 我是直接直接调用customRequest入参里的onSuccess/onError，但是没有效果，如果我不设置fileList，就可以生效
> 
> 在你贴出的代码里看不到 customRequest 的调用。

忘了贴了，然后这是我在https://semi.design/zh-CN/input/upload#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%B7%E6%B1%82里调试的

```
import React from 'react';
import { Upload, Button } from '@douyinfe/semi-ui';
import { IconUpload } from '@douyinfe/semi-icons';

() => {
    const mockRequest = ({ file, onProgress, onError, onSuccess }) => {
        let count = 0;
        let interval = setInterval(() => {
            if (count === 100) {
                clearInterval(interval);
                onSuccess();
                return;
            }
            onProgress({ total: 100, loaded: count });
            count += 20;
        }, 500);
    };

    return (
        <Upload fileList={[{
            uid: '1',
            name: 'first.png',
            status: 'success',
            size: '130KB',
            preview: true,
            url: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/root-web-sites/dy.png',
        },]} action="https://api.semi.design/upload" customRequest={mockRequest}>
            <Button icon={<IconUpload />} theme="light">
                点击上传
            </Button>
        </Upload>
    );
};

```
如果设置了fileList, customRequest里的回调就不生效

**Comment by pointhalo** [comment]
> > > > 
> > > 
> > > 
> > > 我是直接直接调用customRequest入参里的onSuccess/onError，但是没有效果，如果我不设置fileList，就可以生效
> > 
> > 
> > 在你贴出的代码里看不到 customRequest 的调用。
> 
> 忘了贴了，然后这是我在[https://semi.design/zh-CN/input/upload#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%B7%E6%B1%82里调试的](https://semi.design/zh-CN/input/upload#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%B7%E6%B1%82%E9%87%8C%E8%B0%83%E8%AF%95%E7%9A%84)
> 
> ```
> import React from 'react';
> import { Upload, Button } from '@douyinfe/semi-ui';
> import { IconUpload } from '@douyinfe/semi-icons';
> 
> () => {
>     const mockRequest = ({ file, onProgress, onError, onSuccess }) => {
>         let count = 0;
>         let interval = setInterval(() => {
>             if (count === 100) {
>                 clearInterval(interval);
>                 onSuccess();
>                 return;
>             }
>             onProgress({ total: 100, loaded: count });
>             count += 20;
>         }, 500);
>     };
> 
>     return (
>         <Upload fileList={[{
>             uid: '1',
>             name: 'first.png',
>             status: 'success',
>             size: '130KB',
>             preview: true,
>             url: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/root-web-sites/dy.png',
>         },]} action="https://api.semi.design/upload" customRequest={mockRequest}>
>             <Button icon={<IconUpload />} theme="light">
>                 点击上传
>             </Button>
>         </Upload>
>     );
> };
> ```
> 
> 如果设置了fileList, customRequest里的回调就不生效

这里都没有监听onChange去更新 fileList，受控的最基本用法呀都没有遵循呀。添加了文件，那得先触发onChange，下一步才是上传呀。现在这里添加都没法正常走。

**Comment by xmsz-stu** [comment]
> 这里都没有监听onChange去更新 fileList，受控的最基本用法呀都没有遵循呀。添加了文件，那得先触发onChange，下一步才是上传呀。现在这里添加都没法正常走。

受控完整的代码是问题描述里的

我先把文档调试代码改成
```

import React from 'react';
import { Upload, Button } from '@douyinfe/semi-ui';
import { IconUpload } from '@douyinfe/semi-icons';

() => {
   const [value, setValue] = useState()
    const mockRequest = ({ file, onProgress, onError, onSuccess }) => {
        let count = 0;
        let interval = setInterval(() => {
            if (count === 100) {
                clearInterval(interval);
                onSuccess();
                return;
            }
            onProgress({ total: 100, loaded: count });
            count += 20;
        }, 500);
    };

    return (
        <>
        <Upload fileList={value} action="https://api.semi.design/upload" customRequest={mockRequest} onChange={setValue}>
            <Button icon={<IconUpload />} theme="light">
                点击上传
            </Button>
        </Upload>
        </>
    );
};
```
onChange的时候赋值给value，还是不能触发

**Comment by pointhalo** [comment]
你给个完整的 codesandbox url吧，这基本可以肯定是写法没写对。这两API是没有矛盾的。以及你的场景其实我听下来不是很有必要去用到 customRequest，这类 API 是给那些希望沿用固定的上传 SDK的，例如云厂商的OSS 之类的场景用的。

**Comment by pointhalo** [comment]
写了个 codesandbox demo：https://codesandbox.io/s/quizzical-haze-tvzq29?file=/src/App.js

![20230811145128_rec_](https://github.com/DouyinFE/semi-design/assets/88709023/de3e32d6-e4cc-4f42-ad9c-6d79e6d0caa4)

**Comment by xmsz-stu** [comment]
> codesandbox

我发现大概问题了，因为我onChange赋值的不是整个fileList, 而只是fileList[0].url, 然后fiieList[0]的状态还是succes，所以不会触发?
```
<Upload
      fileList={value ? [{ url: value, status: 'success', name: '', size: '', uid: '0' }] : []}
      onChange={(payload) => {
        onChange?.(payload.fileList[0]?.url);
      }}
    />
```

不过这个确实我使用的问题。


> 你的场景其实我听下来不是很有必要去用到 customRequest
我的需求是上传后将返回值设置给fileList，替换掉默认blob那个地址

然后我又看一下其他组件库差异，我之前使用方法是用customRequest返回标准类型给组件就可以了

而semi的customRequest并不会修改值，我只能使用其他办法了


结案了
