### ISSUE TITLE
[BUG] resizable table colums are too sensitive to drag 

### ISSUE THREAD

**Issue by xuhen** [DouyinFE/semi-design#1762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

table

### Semi Version

2.39.3

### Current Behavior

I have two fixed column at first and last column respectively, and every column have width property. when i put resizable to the table component, the drag handler appeard at header of each column. then I drag any handler moving a bit, but the width of      
column change dramaticly which is hard to control.

### Expected Behavior

when drag the handler,  the width of column is smooth and easy to control.

### ReproducibleCode

```markdown
<Table
        columns={columns}
        dataSource={data?.list}
        pagination={{
          className: "pagination",
          currentPage: data?.page,
          pageSize: data?.pageSize,
          total: data?.total,
          showSizeChanger: true,
          formatPageText: false,
        }}
        loading={loading}
        rowSelection={rowSelection as RowSelection<JobModel>}
        rowKey="id"
        onChange={handleTableChange as OnChange<JobModel>}
        scroll={scroll}
        resizable
      />
```

### Environment

```markdown
- OS: Mac Pro
- browser: Chrome (latest)
```

**Comment by pointhalo** [comment]
Can you give us a reproduced screen recording or  reproduced demo codesandbox?

**Comment by xuhen** [comment]
https://codesandbox.io/s/async-smoke-ftscv5?file=/src/App.js

here you go :)

 Draging the last two column are hard to control, but other column are fine relatively speaking.

**Comment by shijiatongxue** [comment]
better to not use fixed columns and resize at same time.

<img width="1366" alt="image" src="https://github.com/DouyinFE/semi-design/assets/26477537/365d600f-6ed1-41a8-9d34-bbe55d5ee264">

**Comment by shijiatongxue** [comment]
> better to not use fixed columns and resize at same time.
> 
> <img alt="image" width="1366" src="https://user-images.githubusercontent.com/26477537/260705999-365d600f-6ed1-41a8-9d34-bbe55d5ee264.png">

or you can give one column without fixed width.

**Comment by xuhen** [comment]
well, it make sense in our situation, the first column is checkbox; the last column is operating buttons, so we hope the two column will sitck around when the rest of columns scroll horizontally. however the content of several columns are too long, we want give it a fixed width and user can drag to expand further. so I suppose it's resonable need to be fullfilled.

**Comment by xuhen** [comment]
> better to not use fixed columns and resize at same time.
> 
> <img alt="image" width="1366" src="https://user-images.githubusercontent.com/26477537/260705999-365d600f-6ed1-41a8-9d34-bbe55d5ee264.png">

Is it a bad idea to "automatically adjusted by the browser" when the width of one column are not set? cause we don't want the first and last fixed column to resize, however we do want to control the width of the two. or it's better to add resizable to specific column to control the drag functionality, then width stay the same?

**Comment by xuhen** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/8892755/ba3c6e4d-adf5-4c22-9620-4a2d9e3c9d5d)

I attached a table to illustrate the situation here.

**Comment by shijiatongxue** [comment]
> > better to not use fixed columns and resize at same time.
> > <img alt="image" width="1366" src="https://user-images.githubusercontent.com/26477537/260705999-365d600f-6ed1-41a8-9d34-bbe55d5ee264.png">
> 
> Is it a bad idea to "automatically adjusted by the browser" when the width of one column are not set? cause we don't want the first and last fixed column to resize, however we do want to control the width of the two. or it's better to add resizable to specific column to control the drag functionality, then width stay the same?

Yes, it is. Fixed column and resizable column both need a fixed width at this moment.

For fixed column, a fixed width is ok. But for resizable column, which has a fixed width seems like make no sense.

We are considering untying resize functionality from fixed width.

<img width="1368" alt="image" src="https://github.com/DouyinFE/semi-design/assets/26477537/eb724af5-4409-4ed5-b3d4-3433a6f4f2d9">

**Comment by xuhen** [comment]
> > > better to not use fixed columns and resize at same time.
> > > <img alt="image" width="1366" src="https://user-images.githubusercontent.com/26477537/260705999-365d600f-6ed1-41a8-9d34-bbe55d5ee264.png">
> > 
> > 
> > Is it a bad idea to "automatically adjusted by the browser" when the width of one column are not set? cause we don't want the first and last fixed column to resize, however we do want to control the width of the two. or it's better to add resizable to specific column to control the drag functionality, then width stay the same?
> 
> Yes, it is. Fixed column and resizable column both need a fixed width at this moment.
> 
> For fixed column, a fixed width is ok. But for resizable column, which has a fixed width seems like make no sense.
> 
> We are considering untying resize functionality from fixed width.
> 
> <img alt="image" width="1368" src="https://user-images.githubusercontent.com/26477537/260923951-eb724af5-4409-4ed5-b3d4-3433a6f4f2d9.png">

really appreciate your reply :)

**Comment by shijiatongxue** [comment]
We will support `column.resize` on next beta version.

You can set `column.resize=false` to disabeld resizable function of fixed column.

I think this issue can be closed. If you have any other question, feel free to leave a comment here.

**Comment by pointhalo** [comment]
release with [v2.42.0-beta.0](https://github.com/DouyinFE/semi-design/releases/tag/v2.42.0-beta.0)
