### ISSUE TITLE
[BUG] 2.40.0版本之后remix框架下所有弹层组件无法正常弹出

### ISSUE THREAD

**Issue by Jackeriss** [DouyinFE/semi-design#1769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

sidesheet、modal等弹层组件

### Semi Version

2.40.0

### Current Behavior

使用remix框架，在2.40.0版本之前sidesheet、modal等弹层组件可正常展示弹出。2.40.0之后点击弹出按钮后，无法展示弹出层，且页面卡死。
即使不点弹出按钮，切换到其他页面时也会报错：
`Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

根据更新日志，猜测与 https://github.com/DouyinFE/semi-design/issues/1703 有关

### Environment

```markdown
- OS: mac
- browser: chrome
```

**Comment by pointhalo** [comment]
啊这，我们没有任何关于这个问题的变更诶。

**Comment by reorx** [comment]
确认 next@13.4.10 下也存在这个问题，原本我的 semi-ui 版本是 2.39.2，今天尝试升级到 2.42.2 之后就会无法显示，并且会在切换到使用 SideSheet 的页面时报错。回滚到 2.39.2 后恢复正常。

**Comment by pointhalo** [comment]
React 18 createRoot + StrictMode 下特有的问题，striceMode导致某些生命周期执行了两次。但是存在不幂等的task。我们稍后会fix一下。也可以先通过关掉 strictMode 来绕过。

**Comment by lengband** [comment]
关掉了 strictMode 目前可以了，如果修复了请在issue回复下

**Comment by pointhalo** [comment]
fix v2.43.1
