### ISSUE TITLE
日期和时间为什么要选择而不是输入？

### ISSUE THREAD

**Issue by ifu25** [DouyinFE/semi-design#177]
看过好多 web 组件，几乎所有的日期时间都要滑动选择，而手动录入的体验非常的差，没有人有同感吗？

相比来看一个下图这种输入体验不香吗？
![20200415_160135](https://user-images.githubusercontent.com/5575008/139999374-b6aad6b9-f255-4a27-93f5-c0eb024034aa.gif)

**Comment by ifu25** [comment]
再来看看目前市面上清一色的选择模式：
![20200415_160136](https://user-images.githubusercontent.com/5575008/139999465-08a29876-4720-4815-9f00-2a4e363ea2e9.gif)

**Comment by pointhalo** [comment]
Datepicker、TimePicker都是同时支持通过Input输入或者通过Panel选择的。这个不会做强制的限制。更多的是用户习惯问题，两种操作模式本身并无绝对的优劣之分。

**Comment by ifu25** [comment]
> Datepicker、TimePicker都是同时支持通过Input输入或者通过Panel选择的。这个不会做强制的限制。更多的是用户习惯问题，两种操作模式本身并无绝对的优劣之分。

谢谢，我知道是可以支持 input 输入的，您可能没有理解我想表达的意思，我意思是现在的控件都设计的不支持 mask 方式输入，您仔细看下我发的第一个图片的输入方式。而我查看过 MDN 上关于 date 类型的 input 是支持 mask 录入的。
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/input/time
