### ISSUE TITLE
[BUG] 文档站链接指向错误

### ISSUE THREAD

**Issue by coding-ax** [DouyinFE/semi-design#1775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://semi.design/zh-CN/feedback/popconfirm#%E6%90%AD%E9%85%8D%20Tooltip%20%E6%88%96%20Popover%20%E4%BD%BF%E7%94%A8

点击搭配使用会跳转回semi首页。
正确地址应该为 https://semi.design/zh-CN/show/tooltip#%E6%90%AD%E9%85%8D%20Popover%20%E6%88%96%20Popconfirm%20%E4%BD%BF%E7%94%A8

### Environment

```markdown
- OS:macos 13.4.1 (c) (22F770820d)
- browser: Google Chrome 115.0.5790.170（正式版本） (x86_64)
```

**Comment by coding-ax** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/53092569/59a2bfbd-f628-4498-ad23-3aaba75dcda5)
看起来是生成文档站的时候，会把路径给加进去当地址的一部分

**Comment by pointhalo** [comment]
写少了一个/ ，导致跳转时会追加在当前path里。我们改一下。
