### ISSUE TITLE
[Tree] 增加showLine功能

### ISSUE THREAD

**Issue by lengfangbing** [DouyinFE/semi-design#1801]
### Which Component Need Enhancement 期望新增功能的组件
- Tree

### What does the proposed API look like 期望支持的API
showLine - 是否展示连接线，如果设置了`showLine`则在组件层级之间会有连接线，层级关系更明显

### Feature Description 功能描述
如果设置了`showLine`则在组件层级之间会有连接线，层级关系更明显

### Additional information 补充说明
如上

**Comment by YyumeiZhang** [comment]
这个功能我们有预期去做，10月之前没排不上，会在下个季度去做

**Comment by Yan-XiaoMing** [comment]
@pointhalo hello，我对这个pr很感兴趣，如果还没有开发的话，能否交给我来做~  可以帮忙提供一些设计规范相关的资料嘛

**Comment by YyumeiZhang** [comment]
> @pointhalo hello，我对这个pr很感兴趣，如果还没有开发的话，能否交给我来做~ 可以帮忙提供一些设计规范相关的资料嘛

稍等我这边定义下相关信息，内部通过给到你

**Comment by Yan-XiaoMing** [comment]
ok 谢谢~❤️

**Comment by YyumeiZhang** [comment]
@Yan-XiaoMing hello，我们这边对连接线部分的研发& 设计需求如下：
|  item  | value | 
| ------- | ------- | 
| API 名称  | showLine  | 
| 线条的默认宽度 |  1px  | 
| 线条颜色| --semi-color-text-3

其他：
- 是否使用连接线，展开和收起 icon保持现状，不需要使用其他的 icon


你看看还有什么需要补充的吗？

**Comment by Yan-XiaoMing** [comment]
@YyumeiZhang ok 基本get 我最近先做个初版的看看满不满足预期

**Comment by Yan-XiaoMing** [comment]
久等啦,前一段工作太忙了,拖了很久,改动挺大的看看单测什么的，有需要的吗？ 欢迎随时联系我补充 @YyumeiZhang

**Comment by YyumeiZhang** [comment]
v2.50.0
