### ISSUE TITLE
[BUG] Popover trigger contextmenu error

### ISSUE THREAD

**Issue by boenfu** [DouyinFE/semi-design#1819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Popover

### Semi Version

2.43.0

### Current Behavior

有报错但不影响使用
![image](https://github.com/DouyinFE/semi-design/assets/33797740/4fc24fe9-ab2c-4970-b2be-186cb59e9f98)

### Expected Behavior

不报错

### Steps To Reproduce

```
<Popover trigger="contextMenu" />
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
v2.43.1
