### ISSUE TITLE
库名的一点小小建议

### ISSUE THREAD

**Issue by hiql** [DouyinFE/semi-design#1824]
确实是一款国产优秀UI库👍

目前的库名空间为：
@douyinfe/semi-ui

个人觉得更名为以下更佳：
@semi-ui/react
@semi-ui/vue
或者是如：
@semi-ui/react-core
@semi-ui/react-charts
...

仅供参考:)

**Comment by pointhalo** [comment]
感谢建议。不过应该没有计划再更改了
1. semi design这个产品是由抖音前端团队建设维护的，在douyinfe这个 team org下其实还有一些其他产品属于内部使用未开源的状态。如果未来有合适机会将更多产品推向社区的话，我们希望都统一归属在同一个 org下，所以统一以 douyinfe 作为了前缀。

2. 这个 lib 是从 2019年开始建设的，然后在21 年的时候转为了开源 public 仓库。在未开源前（v0、v1），我们的内部包名是  @ies/semi-ui-react，在开源后v2版本进行了更名 @douyinfe/semi-ui 。
没有特殊情况的话，我们没有计划再修改包名了，因为对于已经在用的用户来说，始终会有一些升级的负担。
