### ISSUE TITLE
[BUG] nextjs13 app路由中，切换暗黑模式，本地缓存后，刷新页面后，页面由亮色模式自动切换到暗黑模式，存在闪烁

### ISSUE THREAD

**Issue by abstain23** [DouyinFE/semi-design#1827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

theme-mode'

### Semi Version

2.43.1

### Current Behavior

目前当切换到暗黑模式时，刷新页面，页面存在明显的闪烁，从亮色模式切换到暗黑模式

### Expected Behavior

期待页面不闪烁，直接是用户上次选择的暗黑模式

### Steps To Reproduce

1. 切换到暗黑模式
2. 刷新页面

### ReproducibleCode

```markdown
'use client'

import { IconMoon, IconSun } from '@douyinfe/semi-icons'
import { Button } from '@douyinfe/semi-ui'
import { useState, useEffect } from 'react'

function SwitchThemeMode() {
  const [isDarkMode, setIsDarkMode] = useState(false)

  useEffect(() => {
    if (localStorage.getItem('ThemeMode') === 'dark') {
      setIsDarkMode(true)
      document.body.setAttribute('theme-mode', 'dark')
    }
  }, [])

  const switchThemeMode = () => {
    const body = document.body
    if (body.hasAttribute('theme-mode')) {
      body.removeAttribute('theme-mode')
      localStorage.setItem('ThemeMode', 'light')
      setIsDarkMode(false)
    } else {
      body.setAttribute('theme-mode', 'dark')
      localStorage.setItem('ThemeMode', 'dark')
      setIsDarkMode(true)
    }
  }

  return isDarkMode ? (
    <Button
      onClick={switchThemeMode}
      theme='borderless'
      icon={<IconSun size='large' />}
      style={{
        color: 'var(--semi-color-text-2)'
      }}
    />
  ) : (
    <Button
      onClick={switchThemeMode}
      theme='borderless'
      icon={<IconMoon size='large' />}
      style={{
        color: 'var(--semi-color-text-2)'
      }}
    />
  )
}

export default SwitchThemeMode
```

### Environment

```markdown
- OS:18.14.2
- browser: 谷歌最新版本
```

**Comment by pointhalo** [comment]
前置你的 setAttribute操作。放在useEffect里那是这个组件 didMount后读取，更新。那避免不了的。

**Comment by abstain23** [comment]
> 前置你的 setAttribute操作。放在useEffect里那是这个组件 didMount后读取，更新。那避免不了的。

但是ssr模式中，只能在useEffect中去访问dom，如果是在服务端水合过程中操作dom的话，是没法操作的

**Comment by pointhalo** [comment]
我对nextjs用得不多，不是很熟悉。可以研究一下它是否支持更前置的钩子允许你去设置 body attribute。例如什么 rootlayout之类的
反正思路就是尽量前置，否则从渲染原理上，动态切换下，这个闪是无法避免的。

**Comment by abstain23** [comment]
> 直接加一段纯js 切换主题的逻辑 <script/> 在最终 SSR 后的 html string里，优先于全部js 执行

试过这样，会报水合的错误

**Comment by hamster1963** [comment]
> > 直接加一段纯js 切换主题的逻辑 <script/> 在最终 SSR 后的 html string里，优先于全部js 执行
> 
> 试过这样，会报水合的错误

目前我是通过搭配 nexttheme 与更改 css 实现的，将原semi 的 css 中 theme-mode 的判断由 body 移至HTML（nexttheme 将颜色模式参数绑定在 HTML 上），就可以解决闪白屏的问题。
可以参考一下我的仓库和页面

**Comment by hamster1963** [comment]
> > > 直接加一段纯js 切换主题的逻辑 <script/> 在最终 SSR 后的 html string里，优先于全部js 执行
> > 
> > 
> > 试过这样，会报水合的错误
> 
> 目前我是通过搭配 nexttheme 与更改 css 实现的，将原semi 的 css 中 theme-mode 的判断由 body 移至HTML（nexttheme 将颜色模式参数绑定在 HTML 上），就可以解决闪白屏的问题。 可以参考一下我的仓库和页面

https://github.com/hamster1963/HomeDash

**Comment by abstain23** [comment]
> > > 直接加一段纯js 切换主题的逻辑 <script/> 在最终 SSR 后的 html string里，优先于全部js 执行
> > 
> > 
> > 试过这样，会报水合的错误
> 
> 目前我是通过搭配 nexttheme 与更改 css 实现的，将原semi 的 css 中 theme-mode 的判断由 body 移至HTML（nexttheme 将颜色模式参数绑定在 HTML 上），就可以解决闪白屏的问题。 可以参考一下我的仓库和页面

多谢 看到了你的做法 主要是把css那里的主题判断模式改了，配合next-theme 感觉这样css文件真的大

**Comment by hamster1963** [comment]
> > > > 直接加一段纯js 切换主题的逻辑 <script/> 在最终 SSR 后的 html string里，优先于全部js 执行
> > > 
> > > 
> > > 试过这样，会报水合的错误
> > 
> > 
> > 目前我是通过搭配 nexttheme 与更改 css 实现的，将原semi 的 css 中 theme-mode 的判断由 body 移至HTML（nexttheme 将颜色模式参数绑定在 HTML 上），就可以解决闪白屏的问题。 可以参考一下我的仓库和页面
> 
> 多谢 看到了你的做法 主要是把css那里的主题判断模式改了，配合next-theme 感觉这样css文件真的大

文件确实很大，目前还没有找到更好的绑定的方法。。。

**Comment by abstain23** [comment]
> > > > > 直接加一段纯js 切换主题的逻辑 <script/> 在最终 SSR 后的 html string里，优先于全部js 执行
> > > > 
> > > > 
> > > > 试过这样，会报水合的错误
> > > 
> > > 
> > > 目前我是通过搭配 nexttheme 与更改 css 实现的，将原semi 的 css 中 theme-mode 的判断由 body 移至HTML（nexttheme 将颜色模式参数绑定在 HTML 上），就可以解决闪白屏的问题。 可以参考一下我的仓库和页面
> > 
> > 
> > 多谢 看到了你的做法 主要是把css那里的主题判断模式改了，配合next-theme 感觉这样css文件真的大
> 
> 文件确实很大，目前还没有找到更好的绑定的方法。。。

其实如果next-theme 支持在修改主题可以绑定在body上也能解决，但看了下，next-theme好像不打算支持，或者说semi这边支持修改主题绑定到html上也能实现，这样就不用引入那么大的css了

**Comment by hamster1963** [comment]
> > > > > > 直接加一段纯js 切换主题的逻辑 <script/> 在最终 SSR 后的 html string里，优先于全部js 执行
> > > > > 
> > > > > 
> > > > > 试过这样，会报水合的错误
> > > > 
> > > > 
> > > > 目前我是通过搭配 nexttheme 与更改 css 实现的，将原semi 的 css 中 theme-mode 的判断由 body 移至HTML（nexttheme 将颜色模式参数绑定在 HTML 上），就可以解决闪白屏的问题。 可以参考一下我的仓库和页面
> > > 
> > > 
> > > 多谢 看到了你的做法 主要是把css那里的主题判断模式改了，配合next-theme 感觉这样css文件真的大
> > 
> > 
> > 文件确实很大，目前还没有找到更好的绑定的方法。。。
> 
> 其实如果next-theme 支持在修改主题可以绑定在body上也能解决，但看了下，next-theme好像不打算支持，或者说semi这边支持修改主题绑定到html上也能实现，这样就不用引入那么大的css了

对 这也是我当初都尝试过后，发现目前如果基于 semi 的话，只能从引入 css 来下手了。希望官方后面会出新的绑定方式吧。
