### ISSUE TITLE
[Guide] 大佬，有类似新手引导的组件吗？比如这个库

### ISSUE THREAD

**Issue by Jarvie789** [DouyinFE/semi-design#1834]
### Which Component Need Enhancement 期望新增功能的组件
- Guide

### Feature Description 功能描述
https://github.com/bytedance/guide

**Comment by YyumeiZhang** [comment]
目前没有提供官方组件，如果是内部用户的，有相应的物料可以使用，去物料市场搜索 tour 即可找到

**Comment by Jarvie789** [comment]
> 目前没有提供官方组件，如果是内部用户的，有相应的物料可以使用，去物料市场搜索 tour 即可找到

好吧，知道了，谢谢。
