### ISSUE TITLE
[BUG] select option没有跟随select wrap

### ISSUE THREAD

**Issue by poyoho** [DouyinFE/semi-design#1839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

select

### Semi Version

laster

### Current Behavior

![image](https://github.com/DouyinFE/semi-design/assets/36070057/f9a60482-8224-44a2-91cc-3c9a02d93be1)

### Expected Behavior

select option跟随select wrap

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
1. 没看懂这个问题
2. 麻烦给下复现代码

**Comment by poyoho** [comment]
每个选择选都会有问题 https://semi.design/zh-CN/input/select

就在官网点开选择框 然后滚动 就会出现

选择框选项没有跟随选择框，滚动会有位移。

**Comment by pointhalo** [comment]
没有复现你说的问题。可以给个录屏吗？

**Comment by pointhalo** [comment]
![20230922141109_rec_](https://github.com/DouyinFE/semi-design/assets/88709023/1c990232-f6a4-41f3-89df-87392091327a)
