### ISSUE TITLE
[Typography] Typography.Text 等组件，接管内部的ellipsis的Tooltip/Popover组件渲染

### ISSUE THREAD

**Issue by lengfangbing** [DouyinFE/semi-design#1853]
### Which Component Need Enhancement 期望新增功能的组件
- Typography

### What does the proposed API look like 期望支持的API
![69b417f5-3abe-425d-b916-1d602471aa43](https://github.com/DouyinFE/semi-design/assets/46396510/07c2005e-711e-401e-bf07-989d9e44935f)
ShowTooltip的type支持业务封装的 Tooltip / Popover 组件（自定义render），不是Semi内部的 Tooltip / Popover 组件

### Feature Description 功能描述
如上
### Additional information 补充说明
无

**Comment by lengfangbing** [comment]
目前我们的ddl：10.28，还是希望可以如期完成此功能的 :D

**Comment by pointhalo** [comment]
support v2.46.0-beta.0
