### ISSUE TITLE
[BUG] Table 的行列合并，hover 的颜色高亮没有完全覆盖

### ISSUE THREAD

**Issue by coding-ax** [DouyinFE/semi-design#1866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Table

### Semi Version

latest

### Current Behavior

进行了行列合并的行，hover 到行列合并的列上，样式未能覆盖整行。
https://semi.design/zh-CN/show/table#%E8%A1%8C%E5%88%97%E5%90%88%E5%B9%B6

### Expected Behavior

进行了行列合并的行，hover 到行列合并的列上，均有hover的状态展示

### Steps To Reproduce

https://semi.design/zh-CN/show/table#%E8%A1%8C%E5%88%97%E5%90%88%E5%B9%B6
见文档即可

### Environment

```markdown
- OS: OSX
- browser: Chrome
```

### Anything else?

![image](https://github.com/DouyinFE/semi-design/assets/53092569/e8f82358-009f-4fa8-87b0-82d923802f6f)

**Comment by YyumeiZhang** [comment]
这个问题和 #1177 相同，先关闭这个issue，在 1177中跟进
