### ISSUE TITLE
抄袭专业户垃圾抖音你咋不叫ant-design 叫啥屎 semi-design

### ISSUE THREAD

**Issue by metaatom** [DouyinFE/semi-design#187]
抄袭专业户垃圾抖音你咋不叫ant-design 叫啥屎 semi-design

**Comment by pointhalo** [comment]
关于我们代码里测试用例里使用到Antd的demo的历史原因，哪些utils函数实现引用自Antd， 在相关的Commit和PR里已经说得非常很清楚了。

https://github.com/DouyinFE/semi-design/issues/70#issuecomment-952634888

Issue区是关于使用问题反馈以及意见收集的，无关问题或者情绪发泄请移步。
