### ISSUE TITLE
[Input] 输入类能否支持fill/pill

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1882]
### Which Component Need Enhancement 期望新增功能的组件
- Input

### What does the proposed API look like 期望支持的API
fill - 灰色填充背景
pill - 圆角

### Feature Description 功能描述
大部分情况下，大家的UI都是白色背景的输入框，在有些情况下才会使用灰色填充背景
使用semi情况下，同时只能存在一种
如果要改的话，要么整个换掉，要么自己得写一套css变量覆盖（麻烦）
圆角也同理

所以希望可以实现，组件默认是白色背景，然后支持fill和pill，这样简简单单就能满足99%的场景，写起来很方便

**Comment by xmsz-stu** [comment]
按钮默认希望是：线框(fill=false/border=true)
<img width="372" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/4c64b7a1-ad8d-438c-a4f2-46e57036f585">

支持fill=true,变为灰色背景
<img width="483" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/a56af716-c1c4-47d9-b1fa-e6349335afcf">



支持pill=true,变为全圆角样式
<img width="303" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/ac0acb81-685d-4ae4-998a-0e3b5e35b3f3">


这样使用最方便，基本都不需要自己或者添加样式

**Comment by pointhalo** [comment]
Semi Design 的默认风格是 面性的，同时也可以通过 DSM 调整 design token 配置成线性，但线性与面型的设计风格通常不会共存在一个设计系统里（可能有一两个特殊元素与整体有差异，但通常不会大规模共存），因此我们没有计划去增加上述举例的这种 API 去同时在一个组件中承载两种形态。
这个与设计系统的规范不符。

**Comment by xmsz-stu** [comment]
https://ant-design.antgroup.com/changelog-cn#5130 antDesign 5.13.0 已经支持变体了
