### ISSUE TITLE
Select 选择器点击展开后，再次点击收起

### ISSUE THREAD

**Issue by liamwang** [DouyinFE/semi-design#189]
### Which Component Need Enhancement 期望新增功能的组件
- Select

### What does the proposed API look like 期望支持的API
Select 选择器点击展开后，再次点击时没有反应，建议再次点击时收起下列列表。
![](https://user-images.githubusercontent.com/5000396/140266093-e5f9928e-65c1-4c80-8f37-b12fb48c2630.png)

**Comment by pointhalo** [comment]
这个交互有API开关控制
```
<Select clickToHide />
```
