### ISSUE TITLE
[Datepicker] 部分场景添加 disabledDate 之后，点击不触发 onChange

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#1891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

datePicker

### Semi Version

latest

### Current Behavior

点击11 月份，不触发 onChange

### Expected Behavior

触发 onChange

### Steps To Reproduce

点击 11 月

### ReproducibleCode

```markdown
https://codesandbox.io/p/sandbox/bold-driscoll-kngm7v?file=%2Fsrc%2FApp.jsx%3A9%2C19
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by Yan-XiaoMing** [comment]
想问一下这个不触发onChange应该是一个符合期望的行为吧？
![image](https://github.com/DouyinFE/semi-design/assets/51167564/9aa14305-1c38-44eb-b57a-fe0827774d2f)
