### ISSUE TITLE
[Popconfirm] 支持隐藏右上角关闭按钮

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1898]
### Which Component Need Enhancement 期望新增功能的组件
- Popconfirm

### What does the proposed API look like 期望支持的API
- hideCloseBtn

### Feature Description 功能描述
隐藏这个按钮，因为大部分情况下，confirm只需要存在取消按钮
<img width="250" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/ffcfb278-f203-4ee2-9c1b-59bcde09e136">

**Comment by pointhalo** [comment]
要不直接提个 PR？🙋 API 可以叫 showCloseIcon（Semi 的 API 更多是 show XXX，而不是 hideXXX，），默认值为true

**Comment by PaperGangsta** [comment]
hi,我为这个需求提交了一个pr,看一下是否有需要修改的地方或者文档需要补充~

**Comment by PaperGangsta** [comment]
hi,我为这个需求提交了一个pr,看一下是否有需要修改的地方或者文档需要补充~

**Comment by xmsz-stu** [comment]
> hi,我为这个需求提交了一个pr,看一下是否有需要修改的地方或者文档需要补充~

满足我的需求

**Comment by YyumeiZhang** [comment]
该需求跟版v2.47.0-beta.0 已发布
