### ISSUE TITLE
Select开启onChangeWithObject={true}后双向绑定失效了

### ISSUE THREAD

**Issue by jtong123** [DouyinFE/semi-design#1899]
"@douyinfe/semi-ui": "^2.45.1",

handleChange里value对象都能拿到，setValue失败

**Comment by jtong123** [comment]
![7d9329ca-4c80-4128-bdd5-a49f5a80996b](https://github.com/DouyinFE/semi-design/assets/148428316/a8895502-1714-468c-ba87-8ec38c250d63)

**Comment by jtong123** [comment]
`import React, { useState } from 'react';
import { Select } from '@douyinfe/semi-ui';

() => {
    let [value, setValue] = useState('xigua');
    const handleChange = (value) => {
        console.info('value', value, value.label)
        let val = value.label
        setValue(val)
    }
    return (
        <>
            <Select onChangeWithObject={true} value={value} style={{ width: '300px' }} onChange={handleChange} placeholder="受控的Select">
                <Select.Option value="abc">抖音</Select.Option>
                <Select.Option value="ulikecam">轻颜相机</Select.Option>
                <Select.Option value="jianying">剪映</Select.Option>
                <Select.Option value="xigua">西瓜视频</Select.Option>
            </Select>
        </>
    );
};
`

**Comment by pointhalo** [comment]
![Uploading image.png…]()
传的值格式不对。
