### ISSUE TITLE
[Typograph] 增大Text的font-size

### ISSUE THREAD

**Issue by alt1o** [DouyinFE/semi-design#1908]
### 期望优化 Text 组件

希望增大 Text 组件的文字大小，默认的字号 14px 和 12px 太小了，不适合长段文字阅读，例如官方文档主体就是 16px 的，参见下图。

<img width="1446" alt="image" src="https://github.com/DouyinFE/semi-design/assets/21084335/b7f9127e-c372-475d-8b39-283e348ed87c">

### 补充说明
React 旧文档默认字体大小是 17px
<img width="1439" alt="image" src="https://github.com/DouyinFE/semi-design/assets/21084335/6af14f4d-96ba-40aa-87fd-f772e10a9641">

以阅读著称的 Medium 的默认字体大小是 20px
<img width="1324" alt="image" src="https://github.com/DouyinFE/semi-design/assets/21084335/cb88b201-8123-4d5a-8f99-257a818b0940">

**Comment by pointhalo** [comment]
如果你的诉求是对默认值不太满意，这是可以在 DSM 主题平台 https://semi.design/dsm 自由定制的，目前提供了两档，默认是 12、14，可以按需调整，重新发布自己的主题并应用即可
![image](https://github.com/DouyinFE/semi-design/assets/88709023/e885dcc7-2979-48e8-ba3c-0dfcf4677886)

**Comment by alt1o** [comment]
试用了DSM主题平台，太好用了，点赞
