### ISSUE TITLE
[BUG] 在Astro.js中引用组件会报错

### ISSUE THREAD

**Issue by gxy5202** [DouyinFE/semi-design#1909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

all

### Semi Version

2.46.1

### Current Behavior

same as #1184 

目前Semi在Astro.js中使用会直接报错，原因就是引入的css导致的。

Semi在SSR框架中，使用了一些额外的包来处理，比如next和remix，但同样的问题是否能直接提供一个semi.config.js或者在package.json中增加一个semi字段来添加配置，直接让用户告诉是ssr环境，一些ssr公共的问题就可以统一处理了，也不需要单独根据框架去安装各种pacakge.

semi.config.js
```
{
    ssr: true,
    xxx
}
```

### Environment

```markdown
- OS: Ubuntu 22
- browser: Chrome
- Node: 18+
```

**Comment by pointhalo** [comment]
We have no plans to do additional processing for astro alone. It is reasonable to import css from js. It can simplify basic usage very well without forcing the binding of plugins such as babel-plugin-import. That's very convenient for the larger CSR user group.

As for the compatibility issue in the ssr framework, we believe that the compilation configuration should be exposed by the ssr framework, allowing us to declare the configuration. For example, the remix configuration is very good.

**Comment by gxy5202** [comment]
I see, thanks. So i guess i can't easily use Semi in Asrto right now, hope astro team and Semi team can figure out a good solution. Good luck to u guys. By the way, Semi is a beautiful UI framework, bad luck for me..

**Comment by gxy5202** [comment]
> We have no plans to do additional processing for astro alone. It is reasonable to import css from js. It can simplify basic usage very well without forcing the binding of plugins such as babel-plugin-import. That's very convenient for the larger CSR user group.
> 
> As for the compatibility issue in the ssr framework, we believe that the compilation configuration should be exposed by the ssr framework, allowing us to declare the configuration. For example, the remix configuration is very good.

I see, thanks. So i guess i can't easily use Semi in Asrto right now, hope astro team and Semi team can figure out a good solution. Good luck to u guys. By the way, Semi is a beautiful UI framework, bad luck for me..

**Comment by kirainmoe** [comment]
The following astro config works for me to using semi-design in astro SSR, but you need to import the full semi-design stylesheet file in your component.

```ts
// astro.config.mjs
import mdx from '@astrojs/mdx';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';
import { defineConfig } from 'astro/config';
import { cjsInterop } from 'vite-plugin-cjs-interop';

// https://astro.build/config
export default defineConfig({
  site: 'https://example.com',
  integrations: [mdx(), sitemap(), react()],
  vite: {
    plugins: [
      cjsInterop({
        dependencies: ['date-fns-tz'],
      }),
    ],
    ssr: {
      noExternal: [
        '@douyinfe/semi-ui',
        '@douyinfe/semi-foundation',
        '@douyinfe/semi-icons',
        'scroll-into-view-if-needed',
      ],
    },
  },
});

```

In your component entry:

```
import '@douyinfe/semi-ui/dist/css/semi.min.css';
