### ISSUE TITLE
[TagGroup] 希望支持自动计算maxCount

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1910]
### Which Component Need Enhancement 期望新增功能的组件
- TagGroup

### What does the proposed API look like 期望支持的API
- maxCount=auto

### Feature Description 功能描述
现在需要自己填写最大个数
但实际情况下会遇到
- tag的内容程度不确定
- tag外层容器宽度不确定
这个时候maxCount就无法填写了

### Additional information 补充说明
等同于Select.ellipsisTrigger = true

**Comment by pointhalo** [comment]
看上去你这种情况更适合使用这个组件：https://semi.design/zh-CN/show/overflowlist

**Comment by xmsz-stu** [comment]
> 看上去你这种情况更适合使用这个组件：https://semi.design/zh-CN/show/overflowlist

满足需求 
希望可以在Tag页文档关联Overflowlist
