### ISSUE TITLE
[Input] 单个前后缀时支持圆角

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1912]
### Which Component Need Enhancement 期望新增功能的组件
- Input

### What does the proposed API look like 期望支持的API
当只设置addonAfter/addonBefore的时候，input也能有圆角

### Feature Description 功能描述
<img width="423" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/290342c3-d8a2-4a78-9627-5d153702ffb2">

**Comment by pointhalo** [comment]
这应该是个bug

✅仅设置 affonBefore时有单边圆角的。
![image](https://github.com/DouyinFE/semi-design/assets/88709023/6a4314c7-e6cb-4da5-b7f7-688d551196e5)

❌当前仅设置 addOnAfter的样式不符合预期
![image](https://github.com/DouyinFE/semi-design/assets/88709023/b6e4928f-988c-4aae-beaa-56a1b0fdbe4c)

我们修下

**Comment by pointhalo** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/88709023/91145f0b-fae5-48cc-8b3d-0e546e31fffe)
