### ISSUE TITLE
[Avatar] 字符型的头像支持自动调整字符大小

### ISSUE THREAD

**Issue by YyumeiZhang** [DouyinFE/semi-design#1917]
### Which Component Need Enhancement 期望新增功能的组件
- Avatar

### Feature Description 功能描述

对于字符型的头像，当字符串较长时，字体大小可以根据头像宽度自动调整。

**Comment by LonelySnowman** [comment]
@YyumeiZhang 你好，这个 feature 我有兴趣完成，需要加一个 gap 参数用于调整字符距离左右两侧的像素大小么。

**Comment by YyumeiZhang** [comment]
欢迎 PR，gap 参数可以加

**Comment by YyumeiZhang** [comment]
跟版本 2.48.0-beta.0
![image](https://github.com/DouyinFE/semi-design/assets/101110131/d13d299c-4774-49c7-b1a0-0abe209a751d)
