### ISSUE TITLE
[BUG] Select search no highlight when use OptGroup

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#1930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

select

### Semi Version

latest

### Current Behavior

搜索没高亮

### Expected Behavior

有

### Steps To Reproduce

import React from 'react';
import { Select, Popover } from '@douyinfe/semi-ui';

() => {
    function searchLabel(sugInput, option) {
        let label = option.vLabel.toUpperCase();
        let sug = sugInput.toUpperCase();
        return label.includes(sug);
    }
    return (
        <Select filter={searchLabel} style={{ width: '180px' }} placeholder="try abc">
            <Select.OptGroup label='AAAA'>
                <Select.Option value="abc" vLabel='ABC'><div>ABC</div></Select.Option>
                <Select.Option value="ulikecam" vLabel='HOTSOON'><div>HOTSOON</div></Select.Option>
            </Select.OptGroup>
            <Select.OptGroup label='BBB'>
                <Select.Option value="jianying" vLabel='PIPIXIA'><div>PIPIXIA</div></Select.Option>
                <Select.Option value="xigua" vLabel='XIGUA'><div>XIGUA</div></Select.Option>
            </Select.OptGroup>
        </Select>
    );
};

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
https://codesandbox.io/p/sandbox/condescending-sammet-ggknv7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpgxswd200073b6h62qbhy3s%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpgxswd100033b6h2kuafvv1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpgxswd200043b6hy3y028nf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpgxswd200063b6hkxglgv4a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpgxswd100033b6h2kuafvv1%2522%253A%257B%2522id%2522%253A%2522clpgxswd100033b6h2kuafvv1%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpgxswd200063b6hkxglgv4a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpgxswd200053b6h3fssaks2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpgxswd200063b6hkxglgv4a%2522%252C%2522activeTabId%2522%253A%2522clpgxswd200053b6h3fssaks2%2522%257D%252C%2522clpgxswd200043b6hy3y028nf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpgxswd200043b6hy3y028nf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
