### ISSUE TITLE
[sidesheet] 支持定制closeIcon

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1948]
### Which Component Need Enhancement 期望新增功能的组件
- sidesheet

### What does the proposed API look like 期望支持的API
支持设置closeIcon和modal一样

### Additional information 补充说明
我看到DEMO示例有，但不生效

**Comment by LonelySnowman** [comment]
@pointhalo 我有意向完成这个PR，正在跟进😀。

**Comment by pointhalo** [comment]
support v2.49.0-beta.0
