### ISSUE TITLE
[BUG] [Popover] How to close  Uncontrolled popover when click at inner button

### ISSUE THREAD

**Issue by xuhen** [DouyinFE/semi-design#1949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Popover

### Semi Version

2.44.0

### Current Behavior

There are no doc about how to close Uncontrolled popover when click at inner button, And I don't want to use `clickToHide` config prop to close it when click anywhere inside, cause there is a select to chose from.

### Expected Behavior

I try to imiate esc button click to close it, but failed.

`
const escapeEvent = new KeyboardEvent("keydown", {
  key: "Escape",
  code: "Escape",
  keyCode: 27,
  which: 27,
});

document.dispatchEvent(escapeEvent);
`
![image](https://github.com/DouyinFE/semi-design/assets/8892755/6096a832-72af-471f-b220-346e7f063dde)

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
Controlled visible is for this scenario. Without controlled visible prop, we have no way of knowing which element you want to click to close and which element you don't want to close.

But I think you can use the popconfirm component directly here.

**Comment by xuhen** [comment]
thanks, it help a lot, popconfirm is the way to go
