### ISSUE TITLE
[RadioGroup] type=button在Form里为什么要加边距

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1954]
### Which Component Need Enhancement 期望新增功能的组件
- RadioGroup

### What does the proposed API look like 期望支持的API
不加边距

### Feature Description 功能描述
<img width="191" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/a4b7a1e6-2a64-4b73-9c7d-ceaa80611f82">
如果type="button" 会加上下边距，但和原来的就不同高度了

### Additional information 补充说明
相关：https://github.com/DouyinFE/semi-design/issues/677

**Comment by pointhalo** [comment]
这是一个非预期行为，我们会修复它。
#677只改了 labelPosition=left 的情况，没考虑到 labelPoition=top的情况，相当于只做了部分修复。

**Comment by pointhalo** [comment]
fix v2.56.0-beta.0
![image](https://github.com/DouyinFE/semi-design/assets/88709023/c352ab70-6fe3-462c-8971-f0cdf5eace7b)
