### ISSUE TITLE
希望有一个优质的解决tailwindCSS样式冲突的方案

### ISSUE THREAD

**Issue by printfCYQ** [DouyinFE/semi-design#1963]
![image](https://github.com/DouyinFE/semi-design/assets/44568105/779fd8c4-42b1-489e-ac3e-085f46d99793)

我在查的时候找到这个issue [https://github.com/DouyinFE/semi-design/issues/817](https://github.com/DouyinFE/semi-design/issues/817)。感觉不是很好。

在开发VUE时使用的NaiveUI 提供了一个方案 [https://www.naiveui.com/zh-CN/light/docs/style-conflict](https://www.naiveui.com/zh-CN/light/docs/style-conflict)。

希望有这样的解决方案。

**Comment by pointhalo** [comment]
还是建议关掉tailwind 的 prelight，本质上是他设置的不合理，样式给得太粗暴了。
单独控制样式插入点，我们不计划提供这样的功能。

**Comment by pointhalo** [comment]
update :
 v2.59.0 通过编译插件支持了css @layer ，可通过 layer 更自由地控制样式层级优先级
使用方式详见：https://semi.design/zh-CN/start/tailwind

![image](https://github.com/DouyinFE/semi-design/assets/88709023/b5f44935-b28c-44c4-8b9f-a3cb6a15905d)
