### ISSUE TITLE
[BUG] Popconfirm 超出屏幕，出现横向滚动条，滚动一下后回到屏幕内

### ISSUE THREAD

**Issue by ForgQi** [DouyinFE/semi-design#1967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Popconfirm 

### Semi Version

2.48.0

### Current Behavior

![image](https://github.com/DouyinFE/semi-design/assets/34411314/c79734a6-179d-4502-b8b3-119ec0beeb01)

### Expected Behavior

不出现在屏幕外

### Environment

```markdown
- OS: windows
- browser: chrome 119
```

**Comment by pointhalo** [comment]
麻烦给一个能复现问题的 codesandbox，否则我们无法追查，信息量缺失太多
