### ISSUE TITLE
[Nav.Sub] 希望添加link属性

### ISSUE THREAD

**Issue by Yaxnice301** [DouyinFE/semi-design#1975]
谁说父级菜单就不能拥有自己的页面的？？？
它可以是一个总览性的，概括性的页面，对吧。

**Comment by YannLynn** [comment]
你可以通过 nav 的 onclick 事件来完成打开对应页面的行为。

**Comment by Yaxnice301** [comment]
我已经尝试过了，事实上，这样做会对nav的别的事件造成影响。

**Comment by YannLynn** [comment]
> 我已经尝试过了，事实上，这样做会对nav的别的事件造成影响。

能举例说明一下吗

**Comment by Yaxnice301** [comment]
大致就是 但Nav.Sub。添加on-click 跳转页面， 不仅不会跳转，还会导致 无法展开子菜单
我使用。react-router-dom.  中的 usenavigate. 中 的 navigate('...')进行页面跳转

**Comment by YannLynn** [comment]
> 大致就是 但Nav.Sub。添加on-click 跳转页面， 不仅不会跳转，还会导致 无法展开子菜单 我使用。react-router-dom. 中的 usenavigate. 中 的 navigate('...')进行页面跳转

[demo](https://codesandbox.io/p/devbox/semi-navigation-with-react-router-subnav-3r5dxt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq6920hl00083b6gsve9ri9o%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq6920hl00033b6glpbkv6nv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq6920hl00053b6ggvs0avge%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq6920hl00073b6gqprw4giv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq6920hl00033b6glpbkv6nv%2522%253A%257B%2522id%2522%253A%2522clq6920hl00033b6glpbkv6nv%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq6920hl00073b6gqprw4giv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq6920hl00063b6gfoco9znm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fnothing-here%2522%257D%255D%252C%2522id%2522%253A%2522clq6920hl00073b6gqprw4giv%2522%252C%2522activeTabId%2522%253A%2522clq6920hl00063b6gfoco9znm%2522%257D%252C%2522clq6920hl00053b6ggvs0avge%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq6920hl00043b6gxp0lvkbq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522clq6920hl00053b6ggvs0avge%2522%252C%2522activeTabId%2522%253A%2522clq6920hl00043b6gxp0lvkbq%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)  同学，你看看这个 demo 符不符合你的需求

**Comment by Yaxnice301** [comment]
📣What!!!   玩瑞古德👏
but。 虽然父组件 正常跳转到单独的页面，但是副组件却没有高亮
可能就是这个原因，是的我没有注意到，这算个小小的会让用户体验差的地方吧，🥺

**Comment by YannLynn** [comment]
我们这个组件在设计之初，应该就没有考虑支持 「父级菜单拥有自己的页面」 这样的功能，而且在实际的应用场景中也确实很少有用户提过类似的反馈，点击父级菜单没有高亮是符合我们预期的，同学你有需要的话，建议自己根据 onclick 行为定制一下父级菜单样式。
