### ISSUE TITLE
创建主题失败

### ISSUE THREAD

**Issue by jiushiwoyuze** [DouyinFE/semi-design#1976]
### Anything else?

![image](https://github.com/DouyinFE/semi-design/assets/5416077/a76a049b-8ee5-44e4-9f48-73ced1276377)

预览正常，创建不了
![image](https://github.com/DouyinFE/semi-design/assets/5416077/ed1bf003-654a-4af0-9337-faf0cf1b645c)

**Comment by pointhalo** [comment]
为什么你需要创建基于 semi v1.x的版本，非字节跳动内部用户不应该有这种需求。外网都是 v2 起步的

**Comment by pointhalo** [comment]
重新刷新后试试，感觉这里是网络问题，没有获取到正确的版本号列表，导致没法继续发布
