### ISSUE TITLE
[BUG] Select 面板未展开的情况下点击删除按钮，再点击outside，未触发onBlur事件

### ISSUE THREAD

**Issue by jiushiwoyuze** [DouyinFE/semi-design#1989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select

### Environment

```markdown
- OS:
- browser:
```

### Anything else?

复现步骤
![image](https://github.com/DouyinFE/semi-design/assets/5416077/8a9ef0fd-0036-4261-a059-5be65658113c)
![image](https://github.com/DouyinFE/semi-design/assets/5416077/4dcae5f1-2db6-4d33-95e6-626eae22b1c6)
理论上点击旁白时应该触发onBlur事件

**Comment by pointhalo** [comment]
fix 2.52.0
