### ISSUE TITLE
[BUG] semi-next没有生效

### ISSUE THREAD

**Issue by jiushiwoyuze** [DouyinFE/semi-design#1991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Semi Version

 "@douyinfe/semi-icons": "^2.45.1",     "@douyinfe/semi-next": "^2.49.1",     "@douyinfe/semi-ui": "2.45.1",

### Current Behavior
引入的自定义样式被覆盖了
![image](https://github.com/DouyinFE/semi-design/assets/5416077/8ca49c11-14dc-414b-b2eb-968142154db5)

semi默认样式
![image](https://github.com/DouyinFE/semi-design/assets/5416077/f9a38295-5031-4fb6-a4cf-856ed15fb60d)

dsm样式
![image](https://github.com/DouyinFE/semi-design/assets/5416077/a4da6031-b817-4f4a-a532-2794300a10ad)
![image](https://github.com/DouyinFE/semi-design/assets/5416077/1b280e8b-2ee0-4a30-a76d-8cdf483aecd7)
这里我有两个问题，
1.我想自定义字体，所以创建了semi-theme-console这个主题，但这个主题只是改了body的font-family，组件内部的font-family还是原来的，导致字体无法生效
2.配置了semi/next插件，但还是被默认的css覆盖了，next.config配置如下
<img width="703" alt="image" src="https://github.com/DouyinFE/semi-design/assets/5416077/7a0284a1-08f9-47b6-b3fc-b621707a390a">
<img width="824" alt="image" src="https://github.com/DouyinFE/semi-design/assets/5416077/51c220bf-db0f-4bc0-869d-478610741923">

**Comment by jiushiwoyuze** [comment]
@DaiQiangReal 感谢！第一个问题解决了，但是第二个样式覆盖的问题还存在，我用的semi-next看起来没有移除默认的样式引用。
![image](https://github.com/DouyinFE/semi-design/assets/5416077/a7272dd0-af45-4eb8-9c9a-70dc5ec218c1)
next.config配置如图
![image](https://github.com/DouyinFE/semi-design/assets/5416077/6cbef6e7-5889-4584-86cc-b440808accb2)

**Comment by pointhalo** [comment]
> 如果你用插件的话，就不要全量引入主题包里的 semi.min.css 了，插件会给你插

不不不，semi的nextjs的插件不会干插入css这个操作的。他们对于css的import控制的干预有很多自己生态内的规则。这个确实是要用户自己引的。文档也是这么引导的。

**Comment by pointhalo** [comment]
https://stackblitz.com/edit/stackblitz-starters-qjpftp?file=app%2Fpage.tsx

我们没法直接给你排查问题。因为不知道你项目里的具体配置是否还有其他影响因子。上面是一个能正常使用主题的 nextjs项目，你可以对比一下你的使用写法是否有什么特殊。

如果还是找不出原因，给一个跟你项目配置一样的 stackblitz 复现online demo，我们再看看

**Comment by jiushiwoyuze** [comment]
找到原因了，文档里面少了这个配置呀
![image](https://github.com/DouyinFE/semi-design/assets/5416077/7821f00d-77a8-4f87-8d63-cf776c901656)
![image](https://github.com/DouyinFE/semi-design/assets/5416077/4824d3fe-fc64-4c3a-ad41-9d7804710f3e)

**Comment by pointhalo** [comment]
囧，上次给的stackblitz 残留了一些我之前调试的配置。
![image](https://github.com/DouyinFE/semi-design/assets/88709023/1709599e-06cd-4b7e-ad96-f35f0cc337c8)
这个注释掉也没影响的。

**Comment by pointhalo** [comment]
I can't reproduce the problem at my local project. It has not been updated for a while, so I will close this issue first. If other users encounter similar problems, please reopen and i will continue to follow up🤝
