### ISSUE TITLE
[Select ] 单选受控，点击外部空白区域失去焦点后，再次点击选项无法选上

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#1992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select

### Current Behavior

偶现，反复快速点击 options，会突然出现 点击无效，然后下次点击某个选项，但上屏了上次点击无效的选项。

```jsx
() => {
  const [value, setValue] = useState("1");
  return (
    <Select
      value={value}
      onChange={(v) => {
        setValue(v);
        console.log(v);
      }}
      placeholder="受控的Select"
    >
      <Select.Option value={"1"}>抖音</Select.Option>
      <Select.Option value={"2"}>轻颜相机</Select.Option>
      <Select.Option value={"3"}>剪映</Select.Option>
    </Select>
  );
};
```

### Expected Behavior

正常触发正确的 option 上屏

### Environment

```markdown
- OS:
- browser:
```

**Comment by YannLynn** [comment]
补充一个 稳定的复现路径
点击选项 ➡️ 点击外部空白区域让组件失去焦点 ➡️ 再次选择选项，发现选项选择不上。

![20231225192755_rec_](https://github.com/DouyinFE/semi-design/assets/101160769/cb75d1dc-3517-4b59-bad6-7f6c2474f53e)

**Comment by pointhalo** [comment]
这个Title不应该叫 点击事件顺序错误吧，从现象上来说，这就是 某些情况下点击Option不生效

**Comment by YannLynn** [comment]
> 这个Title不应该叫 点击事件顺序错误吧，从现象上来说，这就是 偶现点击Option不生效

已修改 title
