### ISSUE TITLE
[Form] 多个组件如何使用同个field key?

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#1995]
### Which Component Need Enhancement 期望新增功能的组件
- Form
```
<Form.Input field='a' label='第一个' />
<Form.Input field='a' label='第二个' />
```

### What does the proposed API look like 期望支持的API

支持同个fieldKey，同时更新两个组件的值

### Additional information 补充说明

现在，只会更新其他一个
然后其他第三方都支持同个key，同步值

**Comment by pointhalo** [comment]
Field 是唯一标识符，不允许重复。没有做支持的计划。

多个控件双向绑定同一个值，这个交互我们不认为是合理的操作。
