### ISSUE TITLE
[Image] 如何不默认创建预览弹窗

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2004]
### Which Component Need Enhancement 期望新增功能的组件
- Image

### What does the proposed API look like 期望支持的API
默认不创建预览弹窗

### Feature Description 功能描述
现在图片有多少张，就会提前创建多少弹窗dom，
<img width="460" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/cd2ae568-56bd-4eb8-b20f-95764e1eeb4f">
我有个瀑布流，直接搞爆了
能否先不创建这个dom，真正预览再创建

**Comment by pointhalo** [comment]
visible 不为true 的情况下也创建portal dom这个行为不太合理，我们改一下。

**Comment by pointhalo** [comment]
抱歉，review比较慢，拖了一些事件。

2.51.0-beta.0 已 fix
