### ISSUE TITLE
[建议] 添加 python 支持

### ISSUE THREAD

**Issue by monkeycc** [DouyinFE/semi-design#2009]
希望增加python 支持
python也能使用

Flutter
https://github.com/flet-dev/flet
实现了 Flutter 的 python 框架
直接调用 组件 即可

gradio
https://www.gradio.app/
人工智能领域火爆的WEB GUI框架
直接调用 组件 即可

semi-design 是否也能实现
比如设计稿转代码
python就能用上？

**Comment by pointhalo** [comment]
python与我们自身团队的业务技术栈不重合，所以不会有做这个方向的计划 😂 做一个新的lib投入是比较大的，我们没有足够的人力去做这个初始化以及保证后续的长久维护。
