### ISSUE TITLE
[Form.AutoComplete] 设置 onSelectWithObject，输入框中值被清空会触发 TypeError

### ISSUE THREAD

**Issue by YyumeiZhang** [DouyinFE/semi-design#2013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

AutoComplete

### Semi Version

2.50.1

### Current Behavior

输入值，清空输入框，触发 TypeError

### Expected Behavior

输入值，清空输入框，行为正常

### ReproducibleCode

```markdown
import React from 'react';
import { Form } from '@douyinfe/semi-ui';

() => {
    return (
        <Form>
            <Form.AutoComplete
                onSelectWithObject
                data={[]}
                showClear
                style={{ width: 200 }}
            />
        </Form>
    );
};
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
文档上可以优化强调一下。

**Comment by YyumeiZhang** [comment]
上面给的 demo 中的数据源确实有问题，demo 已修改

**Comment by pointhalo** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/88709023/d69779cb-af3e-4840-a73b-8e46d5646734)
