### ISSUE TITLE
[Input]How to solve the problem of automatically prompting for password

### ISSUE THREAD

**Issue by guoChopper** [DouyinFE/semi-design#202]
### Which Component Need Enhancement 期望新增功能的组件
- Input

### What does the proposed API look like 期望支持的API
Could you provide another autocomplete attribute to the Input box
### Feature Description 功能描述
When I focus on the password input box, it will pop up using the password in the xxx account

**Comment by shijiatongxue** [comment]
you can try `autocomplete="off"` directly, Input will passing it to input.

```jsx
<Input autocomplete="off" />
```

**Comment by guoChopper** [comment]
It has no effect in version 2.0.1

**Comment by guoChopper** [comment]
> you can try `autocomplete="off"` directly, Input will pass it to native input.
> 
> ```js
> <Input autocomplete="off" />
> ```
> 
> https://developer.mozilla.org/zh-CN/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

It has no effect in version 2.0.1

**Comment by shijiatongxue** [comment]
Can you post your browser environment and reproduction code? I have not reproduced this problem here.

**Comment by guoChopper** [comment]
> Can you post your browser environment and reproduction code? I have not reproduced this problem here.

Thanks, resolved
