### ISSUE TITLE
希望增加chat组件

### ISSUE THREAD

**Issue by Axbros** [DouyinFE/semi-design#2054]
### Which Component Need Enhancement 期望新增功能的组件
- Chat

### Feature Description 功能描述
如antd的组件https://github.com/ant-design/pro-chat

### Additional information 补充说明
看过issues的history 2021年回复暂时不考虑 但是现在已经2024年 大语言模型的快速发展 现在很有必要新增chat相关的组件

**Comment by pointhalo** [comment]
现在需求量确实跟之前会有区别。
我们有新增组件的计划，不仅仅是 chat 类，24年整体大概会再追加10+组件左右，完整的todo 列表还在内部讨论。但这个也在其中。

**Comment by linpan** [comment]
> 现在需求量确实跟之前会有区别。 我们有新增组件的计划，不仅仅是 chat 类，24年整体大概会再追加10+组件左右，完整的todo 列表还在内部讨论。但这个也在其中。

可以roadmap.md ?

**Comment by pointhalo** [comment]
https://semi.design/zh-CN/plus/chat
support after v2.63
![image](https://github.com/user-attachments/assets/97abd3a0-2a3e-4c5f-9d76-7762fceded80)
