### ISSUE TITLE
[Modal] 支持传递className/style给.semi-modal-content

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2055]
### Which Component Need Enhancement 期望新增功能的组件
- Modal

### What does the proposed API look like 期望支持的API
modelContentClassName
modelContentStyle

### Feature Description 功能描述
我想要改变弹窗的背景，但是只能传递给这3个层
<img width="753" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/32498b01-fcff-4ac6-9609-a1a1a33c6caa">
而真正控制背景的却是.semi-modal-content这一层

**Comment by xmsz-stu** [comment]
> 其实你可以用上层的className 然后 className 里面的样式再选中semi 的 .semi-modal-content 的className 来修改样式

这样需要在css里文件写，管理有点麻烦。

**Comment by zhuba-Ahhh** [comment]
[命令式调用](https://semi.design/zh-CN/show/modal#%E5%91%BD%E4%BB%A4%E5%BC%8F%E8%B0%83%E7%94%A8)会多一层div，预期应该是要想作用到这个 `.semi-modal-confirm-content`上叭

<img width="1204" alt="image" src="https://github.com/DouyinFE/semi-design/assets/84793349/1e6f8993-5918-4fa8-9404-f749a1446405">

<img width="1187" alt="image" src="https://github.com/DouyinFE/semi-design/assets/84793349/7733b180-44bf-44f8-b4ab-f7de0850b5ba">

**Comment by 18852819321** [comment]
@pointhalo 大佬您好，对于新增属性modalContentClass我已经提交PR，请查看并给出指正，感谢~

**Comment by pointhalo** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/88709023/ebcc0ef3-2664-4d9b-802c-c186da662d09)
