### ISSUE TITLE
@tailwind base中的样式，有一些会跟组件冲突

### ISSUE THREAD

**Issue by HXSlimeng** [DouyinFE/semi-design#2057]
### Feature Description 功能描述
可以兼容tailwind base 
### Additional information 补充说明
以下是我开发过程中遇到的问题
1. 引入@tailwind base
2. 使用Button组件
`<Button theme="solid" type="primary" block></Button>`
3. 背景默认透明
![image](https://github.com/DouyinFE/semi-design/assets/80499761/51f3a97f-2fa8-4601-bb30-6ead7c50deb9)

**Comment by hb1707** [comment]
把tailwind base相关引用前置，放在所有import组件引用代码的最上面，可以解决这个问题
