### ISSUE TITLE
[Timepicker] type=timeRange受控的value值类型如何支持undefined？

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2058]
### Which Component Need Enhancement 期望新增功能的组件
- Timepicker
```
<TimePicker  type='timeRange' value={[Date(), undefined]}/>
```

现在会显示`不能将类型“undefined”分配给类型“BaseValueType”。`;

为什么会有undefined是因为用户选择的时候，受控组件会更新value，而选了开始时间还没选择结束时间就会是undefined

### Feature Description 功能描述
支持传递undefined类型

### Additional information 补充说明
如果我传了空字符串就报错，如果传了0显示的又是8:00

**Comment by pointhalo** [comment]
@YannLynn 改下 interface？

**Comment by pointhalo** [comment]
fix 2.52.0
