### ISSUE TITLE
[Timepicker] type=timeRange能否默认处理一下结束时间比开始时间早的场景

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2059]
### Which Component Need Enhancement 期望新增功能的组件
- Timepicker

### Feature Description 功能描述
比如用户开始时间选择了12:00，结束时间选了10:00，这种情况

想象中有几种解决方案
第一种：自动调整位置，把10:00变为开始时间，好像antDesign是这样
第二种：自动设置禁止时间，比如选了12:00，就不能选小于12:00的时间
第三种：结束时间设置为默认值

### Additional information 补充说明

一方面是给用户防呆，避免设置失误
一方面是避免比较傻的同事说他找到了我们一个天大的bug

**Comment by pointhalo** [comment]
考虑一下  23：00 - 01:00 类似这种跨天的场景。单纯的Timepicker是缺少日期表达的，做所谓的disabled自动判断是不合理的。没法知道endTime 到底是否合法。

在Datepicker 的range 中我们会自动对 start 跟end 的合法性做判断，但是Timepicker 无法做。

**Comment by xmsz-stu** [comment]
> 考虑一下 23：00 - 01:00 类似这种跨天的场景，如果按照上述的做法，那就没法选了。单纯的Timepicker是缺少日期表达的，做所谓的disabled自动判断是不合理的。没法知道endTime 到底是否合法。
> 
> 在Datepicker 的dateRange 、dateTimeRange 中我们会自动对 start 跟end 的合法性做判断，但是单纯的Timepicker 无法做。

就是默认是有排序的，跨天关掉排序就行 https://ant.design/components/time-picker-cn#rangepicker
我们的场景基本都是当天内的选择

**Comment by pointhalo** [comment]
暂时没有做这个改动的计划。这个在我们内部有过较多反馈不是一个好的实践。Timepicker无法体现日期，这个前提下对用户的操作做干预，很容易引起用户误解，他得试几次才能感知到这个逻辑，并且假如默认打开这个开关，等于默认加了限制，研发不介入的情况下就压根没法选了。
即使默认值不是true，而是false，但这种props.xxx 开关只是研发层级的api 感知，无法显式体现在界面交互上。 这个“防呆”并不适用所有场景，我们的业务场景里，跨天还是非常高频的，不是一个极小众的需求。

如果你们对这个先后顺序有要求，建议在 Form Validate or  TimePicker onChange 里去做这个check或者swap

**Comment by xmsz-stu** [comment]
好吧 那和其他库默认表现不同 国内都是默认帮用户倒回来(这个做法我也不认同)，国外比如MUI就是可以选但是会报错

然后我们之前用户都没反馈这些（很神奇...  可能最多只是吐槽），但是这次有些用户反馈选错了怎么没提示

那现在我们只能自己处理了
第一种：禁用部分时间选项，有效防呆和刁民，但有点麻烦，因为开始和结束时间都要判断，用户可能先选了结束时间...
第二种：增加检验，如果结束时间大于开始时间就显示错误，和现在只选了一半时间会显示的一样，但可能对普通用户不够直观
第三种：提交时检验并提示，这个其实最简单和直观，但是会增加用户烦躁

**Comment by pointhalo** [comment]
可以在 blur 时校验就行

```
import React from 'react';
import { Form } from '@douyinfe/semi-ui';

() => {
    return (
        <Form>
            <Form.TimePicker
                field='time'
                type='timeRange'
                trigger='blur'
                validate={(val) => {
                    if (val && val.length === 1) {
                        return '请选择开始与结束时间，必须同时选择，不能为空'
                    }
                    if (val && val.length === 2) {
                        let startTime = val[0].valueOf();
                        let endTime = val[1].valueOf();
                        if (startTime >= endTime) {
                            return '开始时间晚于结束时间，请确认是否合理'
                        }
                    }
                }}
                style={{ width: 176 }}
            />
        </Form>
    );
};

```
