### ISSUE TITLE
关于在TS 中使用内部的静态检查 需要再次引用单独组件包中的类型检查

### ISSUE THREAD

**Issue by shxinlei** [DouyinFE/semi-design#206]
### Which Component Need Enhancement 期望新增功能的组件
- 所有

### What does the proposed API look like 期望支持的API
interface 检查

### Feature Description 功能描述
![image](https://user-images.githubusercontent.com/54462126/140469891-100f2980-b375-4347-b6c9-eb99fdfd53c7.png)
在 直接使用模块导入属性静态检查的时候在总模块是引用不到的必须使用单独模块倒入静态检查
![image](https://user-images.githubusercontent.com/54462126/140470043-2e1547c5-d58c-4fcb-bcd3-1c6bc5ca6810.png)

### Additional information 补充说明

是否能将 ts 静态类型 也加入到主模块统一导出

**Comment by shijiatongxue** [comment]
将 TS 类型定义在主文件默认导出可能会有命名冲突问题，因此没有将类型定义从主入口导出。当然这牺牲了部分便捷性。❤
