### ISSUE TITLE
[BUG] Tree组件传入keyMaps后，loadData的参数ts类型会报错

### ISSUE THREAD

**Issue by basonwoo** [DouyinFE/semi-design#2064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Tree

### ReproducibleCode

```markdown
import { Tree } from "@douyinfe/semi-ui";

interface Organization {
 Code: string;
 Id: string;
 Name: string;
}

renderGroup() {
  return <Tree loadData={(node) => fetchSubNode} keyMaps={{label: "Name", key: "Id", value: "Id"}}>
}
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by YyumeiZhang** [comment]
给个更加具体的 demo？ 我这边没有复现出来

**Comment by pointhalo** [comment]
No valid reproduction steps provided, the issue cannot be followed up. 
Will close this issue. If have more information, can reopen it.
