### ISSUE TITLE
[TagInput] 希望给TagInput添加readonly属性

### ISSUE THREAD

**Issue by lokiyun** [DouyinFE/semi-design#2081]
### Which Component Need Enhancement 期望新增功能的组件
- TagInput

### What does the proposed API look like 期望支持的API
- readonly
### Feature Description 功能描述
希望可以在禁止输入的情况下可以删除tag

### Additional information 补充说明
![123](https://github.com/DouyinFE/semi-design/assets/43512104/f06286d7-6091-4541-894f-ade3d7bee289)
添加readonly后是可以达到这个效果的

**Comment by lokiyun** [comment]
> @lokiyun readOnly 从用户理解的角度来说，可能会被理解为只可以读，无法进行其他操作（包括删除）。 想先问下，是在什么样的业务场景下需要只删除 tag，而无法添加呢？
确实，readonly时不该删除。
业务的话类似于飞书审批里条件分支的条件组里配置提交人的那个吧。
正常的readonly还是应该需要的

**Comment by lokiyun** [comment]
> @lokiyun readOnly 从用户理解的角度来说，可能会被理解为只可以读，无法进行其他操作（包括删除）。 想先问下，是在什么样的业务场景下需要只删除 tag，而无法添加呢？



> @lokiyun readOnly 从用户理解的角度来说，可能会被理解为只可以读，无法进行其他操作（包括删除）。 想先问下，是在什么样的业务场景下需要只删除 tag，而无法添加呢？

确实，readonly时不该删除。
业务的话类似于飞书审批里条件分支的条件组里配置提交人的那个吧。
正常的readonly还是应该需要的

**Comment by lokiyun** [comment]
> @lokiyun readOnly 从用户理解的角度来说，可能会被理解为只可以读，无法进行其他操作（包括删除）。 想先问下，是在什么样的业务场景下需要只删除 tag，而无法添加呢？

确实，readonly时不该删除。
业务的话类似于飞书审批里条件分支的条件组里配置提交人的那个吧。
正常的readonly还是应该需要的

**Comment by pointhalo** [comment]
readonly 下如果支持删除是不太合理的，跟这个api的命名就是矛盾的。
如果是其他自定义的逻辑，例如某个 tag不希望被删除，可以使用受控value + renderTagItem 来实现。
