### ISSUE TITLE
Semi Pro 海量模版 什么时候发布

### ISSUE THREAD

**Issue by 501956430** [DouyinFE/semi-design#209]

**Comment by wuhw** [comment]
Pro 我们在内部的定位，重点不是在于提供海量模板，类似于Ant Design这种。而是提供中后台设计案例、Design  to Code、在线调试等能力，能够支持用户从需要的设计案例中，生成代码，完成在线调试后，将代码生成到本地。这部分的工作我们目前还没有在内部大范围落地，还没有得到验证，所以发布时间的话暂时不能确定

**Comment by 501956430** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
