### ISSUE TITLE
年月选择后，弹出面板不自动关闭

### ISSUE THREAD

**Issue by hubo1990** [DouyinFE/semi-design#2102]
正常情况下，希望年月选择完成后自动关闭弹窗面板，而不是手动再点击一下屏幕其他地方才关闭。
就是因为这么一个组件，不得不被迫使用功能强大同时也很笨重的antd
我看了官方文档的案例也是，日期选择时，选择完了日期就正常关闭了，但是年月选择的时候就不会自动关闭，让人费解，这个是基于什么考虑

**Comment by YannLynn** [comment]
当前的设计逻辑下，年月选择涉及多列+滚动，和单纯选择日期的 DatePicker 暗含的交互逻辑不一样，一般不能通过一次选择就确定用户当前的选择值，所以「需要手动再点击一下屏幕其他地方才关闭」

**Comment by shijiatongxue** [comment]
> 当前的设计逻辑下，年月选择涉及多列+滚动，和单纯选择日期的 DatePicker 暗含的交互逻辑不一样，一般不能通过一次选择就确定用户当前的选择值，所以「需要手动再点击一下屏幕其他地方才关闭」

是的，感谢 @YannLynn 的回答。如果想实现确认后直接关闭的效果，可以通过 open + bottomSlot 实现。

<img width="1221" alt="image" src="https://github.com/DouyinFE/semi-design/assets/26477537/a3f4f017-154e-4efc-a010-d84235951a3f">


```
import React, { useState, useMemo } from 'react';
import { DatePicker } from '@douyinfe/semi-ui';

function MyMonthPicker() {
    const [open, setOpen] = useState(false);

    const handleFocus = () => {
        setOpen(true);
    };

    const handleClickOutside = () => {
        setOpen(false);
    };

    const MonthBottomSlot = function (props) {
        return (
            <div style={{ display: 'flex', justifyContent: 'end', padding: 12 }}>
                <Button theme="primary" onClick={() => setOpen(false)}>确定</Button>
            </div>
        );
    };

    return (
        <div>
            <DatePicker onClickOutSide={handleClickOutside} onFocus={handleFocus} open={open} type="month" bottomSlot={<MonthBottomSlot />} placeholder="请选择年月" />
        </div>
    );
}
```

**Comment by hubo1990** [comment]
@shijiatongxue 多谢，我试试。
