### ISSUE TITLE
[Theme] 我做了一个To B 的项目，如何让可以自定义主题

### ISSUE THREAD

**Issue by Xwudao** [DouyinFE/semi-design#2112]
### Which Component Need Enhancement 期望新增功能的组件

Theme

### Feature Description 功能描述

我想让用户在后台可以自定义自己网站的主题风格，类似于 semi.design 主站这种，可以一键切换主题色

想询问一个思路，谢谢

**Comment by YyumeiZhang** [comment]
一键切换主题色如果指的是切换明暗模式的话，可以参考https://semi.design/zh-CN/start/dark-mode

如果是想要自己配置主题中的具体 css 变量，可以参考https://semi.design/zh-CN/start/customize-theme

**Comment by Xwudao** [comment]
> 一键切换主题色如果指的是切换明暗模式的话，可以参考https://semi.design/zh-CN/start/dark-mode
> 
> 如果是想要自己配置主题中的具体 css 变量，可以参考https://semi.design/zh-CN/start/customize-theme

我想找一个相对优雅的方法让用户自定义一些 css 变量，有相关根据一个 brand 颜色生成其余颜色的库吗？

谢谢啦
