### ISSUE TITLE
[BUG] 在 SSR 渲染下，Tabs 组件的 TabBar 渲染成空

### ISSUE THREAD

**Issue by nekocode** [DouyinFE/semi-design#2117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Tabs

### Semi Version

2.53.3

### Current Behavior

目前 SSR 渲染的 TabBar 内容为空：

![img_v3_028o_e1d8fb6a-ca87-4a53-85fc-bffc6adefd0h](https://github.com/DouyinFE/semi-design/assets/4783781/1b88c809-5a7a-49fb-845c-830bb0d987d4)

### Expected Behavior

SSR 能正常渲染 TabBar 

### Environment

```markdown
- OS: MacOS
- browser: Chrome
```

**Comment by nekocode** [comment]
已提交 PR，望帮忙 Review 一下 #2118

**Comment by YannLynn** [comment]
> 已提交 PR，望帮忙 Review 一下 #2118
请问有这个示例 demo 的代码嘛～

**Comment by nekocode** [comment]
> > 已提交 PR，望帮忙 Review 一下 #2118
> > 请问有这个示例 demo 的代码嘛～

稍等，我构造一个能复现的 live demo。

**Comment by nekocode** [comment]
> > > 已提交 PR，望帮忙 Review 一下 #2118
> > > 请问有这个示例 demo 的代码嘛～
> 
> 稍等，我构造一个能复现的 live demo。

@YannLynn 复现的 [demo](https://codesandbox.io/p/devbox/agitated-hellman-56hn5w?workspaceId=ffa52a79-7f19-497d-8790-7c33054e221c&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltwrzdcu00073b6k96bm4083%2522%252C%2522sizes%2522%253A%255B68.25653798256536%252C31.743462017434638%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltwrzdcu00023b6kq5u060dm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltwrzdcu00043b6kduqo0ehx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltwrzdcu00063b6kw7xshegt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltwrzdcu00023b6kq5u060dm%2522%253A%257B%2522id%2522%253A%2522cltwrzdcu00023b6kq5u060dm%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltwrzdcu00063b6kw7xshegt%2522%253A%257B%2522id%2522%253A%2522cltwrzdcu00063b6kw7xshegt%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltwrzdcu00053b6kl424o8hv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltwrzdcu00053b6kl424o8hv%2522%257D%252C%2522cltwrzdcu00043b6kduqo0ehx%2522%253A%257B%2522id%2522%253A%2522cltwrzdcu00043b6kduqo0ehx%2522%252C%2522activeTabId%2522%253A%2522cltwrzdcu00033b6k2tvy9jy7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltwrzdcu00033b6k2tvy9jy7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522install%2522%252C%2522id%2522%253A%2522cltws8r2i012d3b6klzf5vosx%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
