### ISSUE TITLE
增加内置主题或者简化主题使用方式

### ISSUE THREAD

**Issue by williamnie** [DouyinFE/semi-design#212]
现在想要更换主题需要设计好主题以后发布npm包，也就是每个主题都需要有对应的npm包，使用起来比较麻烦，主题只是一些scss或者less的变量，期望是支持直接生成对应的文件，直接能引入或者是约定好在放到指定目录下即可。现在想在umi这样的高度集成框架内使用自定义主题还是比较麻烦的，希望能简化下使用流程。

**Comment by pointhalo** [comment]
在Semi 体系中，主题包会作为配置包同时被 Figma 插件 & 代码编译过程消费，是关联设计链路与研发链路的重要配置项，我们需要考虑双端的消费，而不仅仅是研发侧的使用。

不计划提供其他的消费方式了。并且即使是约定路径，也依然需要编译Plugin支持，并不会与现有的消费方式有明显的差别。

**Comment by tucke** [comment]
@pointhalo 我觉得这种方式虽然实现了双端消费，但是感觉同时也对npm造成了污染！极端一点计数，假如有10万人使用semi，每人又运用到10个项目中，那么直接对公网npm库造成100万的压力。虽然npm公网目前是免费的，但是还是希望我们开发者能合理使用，共同维护我们来之不易的免费资源，不应过度消耗。以上纯粹个人见解！并没有想着要改变点什么，只是想探讨有没有别的方式，比如支持主题推送到私有npm库之类的
