### ISSUE TITLE
[业务组件] 支持Keyboard Key

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2129]
### Which Component Need Enhancement 期望新增功能的组件
- Keyboard Key

### Feature Description 功能描述
显示快捷键

### Additional information 补充说明
比如告诉用户有哪些快捷键可以使用

还有如果可以同时支持快捷键输入就更好了，很多场景比如设置回复的快捷键
<img width="404" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/7d954cb5-7088-4642-ab41-183783b79713">

其他UI库
https://chakra-ui.com/docs/components/kbd/usage
https://nextui.org/docs/components/kbd
https://ui.nuxt.com/components/kbd

**Comment by pointhalo** [comment]
v2.66.0 已增加 Hotkeys 组件
https://semi.bytedance.net/zh-CN/input/hotkeys
