### ISSUE TITLE
[业务组件] 支持验证码输入框 PinInput / VerificationCode

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2130]
### Which Component Need Enhancement 期望新增功能的组件
- 验证码输入框

### Feature Description 功能描述
用户可以输入指定长度的内容
<img width="291" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/301a0699-e7ee-44f3-ab48-46d09f86e782">

### Additional information 补充说明
比如要求用户输入短信验证码，如果是普通的input，会出现
1. 用户输入莫名其妙的字符
2. 用户输入了空格
3. 用户输入了错误的长度
4. ....
而且通过样式，用户也比较好看懂

**Comment by pointhalo** [comment]
https://semi.design/zh-CN/input/pincode

support after v2.62.0-beta.0
