### ISSUE TITLE
UMD 方式使用Icon组件没有生效

### ISSUE THREAD

**Issue by sunmouren** [DouyinFE/semi-design#215]

**Comment by hushilin** [comment]
同问。

**Comment by aiwenForGit** [comment]
同问，不知道怎么引入icon图表，老是报错，请关注解决下。

**Comment by aiwenForGit** [comment]
import { IconBell, IconHelpCircle, IconBytedanceLogo, IconHome, IconHistogram, IconLive, IconSetting } from '@douyinfe/semi-icons';
转化umd，我定义为：{ IconBell, IconHelpCircle, IconBytedanceLogo, IconHome, IconHistogram, IconLive, IconSetting }=Icon或者Icons都不对，不知道如何定义

**Comment by H3lloTom** [comment]
> import { IconBell, IconHelpCircle, IconBytedanceLogo, IconHome, IconHistogram, IconLive, IconSetting } from '@douyinfe/semi-icons'; 转化umd，我定义为：{ IconBell, IconHelpCircle, IconBytedanceLogo, IconHome, IconHistogram, IconLive, IconSetting }=Icon或者Icons都不对，不知道如何定义

是报了什么错呢？

**Comment by aiwenForGit** [comment]
没有定义

**Comment by aiwenForGit** [comment]
是网页里面采用引入js的方式，
      <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
	    <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
        <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
        <script  src="https://cdn.jsdelivr.net/npm/@douyinfe/semi-ui@2.0.3/dist/umd/semi-ui.min.js"></script>
        <link rel="stylesheet" href="https://unpkg.com/@douyinfe/semi-ui@2.0.0/dist/css/semi.css">
在一开始定义const { IconBell, IconHelpCircle, IconBytedanceLogo, IconHome, IconHistogram, IconLive, IconSetting } =？，？到底是什么，因为没有文档和相关的示例，麻烦告知下。

**Comment by aiwenForGit** [comment]
是否没有打包进去还是要引入单独的js文件？

**Comment by H3lloTom** [comment]
> 是网页里面采用引入js的方式， <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script> <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script> <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script> <script src="https://cdn.jsdelivr.net/npm/@douyinfe/semi-ui@2.0.3/dist/umd/semi-ui.min.js"></script> 在一开始定义const { IconBell, IconHelpCircle, IconBytedanceLogo, IconHome, IconHistogram, IconLive, IconSetting } =？，？到底是什么，因为没有文档和相关的示例，麻烦告知下。

这里只是引用了semi-ui的cdn文件，没有引入semi-icons这个包。目前还未提供semi-icons的cdn版本，会在近期评估后考虑引入，如果是npm包管理开发，是直接安装@douyinfe/semi-icons这个包就可以使用的，例如
https://codesandbox.io/s/intelligent-perlman-0wet6?file=/src/index.js

**Comment by aiwenForGit** [comment]
急切需要提供cdn版本的，目前所有图标都不能用。刚好有个项目上需要，还请理解。

**Comment by H3lloTom** [comment]
> 急切需要提供cdn版本的，目前所有图标都不能用。刚好有个项目上需要，还请理解。

是需要@douyinfe/semi-icons的cdn版本，还是semi-ui的cdn版本内的图标无法使用呢？

**Comment by aiwenForGit** [comment]
我在web页面内JavaScript如何引用，需要umd打包后的图标js引入文件。具体引用的时候
const { IconBell, IconHelpCircle, IconBytedanceLogo, IconHome, IconHistogram, IconLive, IconSetting }=？里面的？具体是什么？

**Comment by aiwenForGit** [comment]
> > 是网页里面采用引入js的方式， <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script> <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script> <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script> <script src="https://cdn.jsdelivr.net/npm/@douyinfe/semi-ui@2.0.3/dist/umd/semi-ui.min.js"></script> 在一开始定义const { IconBell, IconHelpCircle, IconBytedanceLogo, IconHome, IconHistogram, IconLive, IconSetting } =？，？到底是什么，因为没有文档和相关的示例，麻烦告知下。
> 
> 这里只是引用了semi-ui的cdn文件，没有引入semi-icons这个包。目前还未提供semi-icons的cdn版本，会在近期评估后考虑引入，如果是npm包管理开发，是直接安装@douyinfe/semi-icons这个包就可以使用的，例如 https://codesandbox.io/s/intelligent-perlman-0wet6?file=/src/index.js

你在上面也说了，目前没有打包进去，怎么又说里面有图标？

**Comment by H3lloTom** [comment]
> > > 是网页里面采用引入js的方式， <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script> <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script> <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script> <script src="https://cdn.jsdelivr.net/npm/@douyinfe/semi-ui@2.0.3/dist/umd/semi-ui.min.js"></script> 在一开始定义const { IconBell, IconHelpCircle, IconBytedanceLogo, IconHome, IconHistogram, IconLive, IconSetting } =？，？到底是什么，因为没有文档和相关的示例，麻烦告知下。
> > 
> > 
> > 这里只是引用了semi-ui的cdn文件，没有引入semi-icons这个包。目前还未提供semi-icons的cdn版本，会在近期评估后考虑引入，如果是npm包管理开发，是直接安装@douyinfe/semi-icons这个包就可以使用的，例如 https://codesandbox.io/s/intelligent-perlman-0wet6?file=/src/index.js
> 
> 你在上面也说了，目前没有打包进去，怎么又说里面有图标？

目前确实没有提供semi-icons的cdn版本，codesandbox是模拟的npm方式，不是web方式

**Comment by aiwenForGit** [comment]
问下官方大概什么时候能够提供semi-icons的cdn版本？

**Comment by wuhw** [comment]
本周可以支持下

**Comment by aiwenForGit** [comment]
不知道官方大概什么时候发布？好像还是没看到。

**Comment by aiwenForGit** [comment]
@H3lloTom

**Comment by aiwenForGit** [comment]
问下，官方什么是发布icon的umd版本？

**Comment by H3lloTom** [comment]
正在开发中了哈，PR很快会提

**Comment by pointhalo** [comment]
fix 2.1.1
![image](https://user-images.githubusercontent.com/88709023/143853262-f5b1166f-d153-44aa-b123-951b1e6e4f8d.png)
