### ISSUE TITLE
[ Select ] 当两个 Option 有相同名称时，UI 上都会被选中

### ISSUE THREAD

**Issue by DongZhe93** [DouyinFE/semi-design#216]
### Which Component 出现bug的组件
  - Select

### semi-ui version
  - 2.0.2
    
### Expected result 期望的结果是什么
  -  根据 value 进行选中

### Actual result 实际的结果是什么
  - ![image](https://user-images.githubusercontent.com/14680559/140594475-c38b4401-945b-4b8e-945f-a9b160060a47.png)

**Comment by shijiatongxue** [comment]
可以看下这里 ❤

![image](https://user-images.githubusercontent.com/26477537/140909653-5a3599b4-0940-484e-9728-854291c3d3af.png)

**Comment by DongZhe93** [comment]
OK
