### ISSUE TITLE
table组件，当外层网页有滚动的时候，table也有滚动，如何阻止当在table中时，不滚动外层

### ISSUE THREAD

**Issue by sundalingg** [DouyinFE/semi-design#2164]
table组件，当外层网页有滚动的时候，table也有滚动，如何阻止当在table中时，不滚动外层。
我通过virtualized这个配置项的onscroll来配置了阻止冒泡事件，
  const virtualized = {
        onScroll: () => {
            var mapContainer = document.getElementById('detail-content');
            mapContainer.addEventListener('mousewheel', function (event) {
                event.stopPropagation();
            });
        }
    }
但我发现表格列的  ellipsis: true,我发现每一个宽度都定死了

![Uploading 企业微信截图_17128181482145.png…]()

**Comment by sundalingg** [comment]
我发现就是ellipsis，virtualized 就是这两个一起使用会有问题。我之后采用了，在table外面加了一层div，通过，useEffect获取该元素，然后阻止冒泡，不使用virtualized 配置项。
 useEffect(() => {
        var mapContainer = document.getElementById('detail-content');
        if(mapContainer){
            mapContainer.addEventListener('mousewheel', function (event) {
                event.stopPropagation();
            });
        }
       
    },[])，
其实我这里完全没有必要使用这个virtualized

**Comment by pointhalo** [comment]
1. 图片看不到 
2. 麻烦提供一个可复现问题的最小demo codesandbox
3. 上面的描述比较模糊，我们没法跟进处理

**Comment by sundalingg** [comment]
您好，就是最简单的，你声明一个table，然后某一个列配置了ellipsis属性，然后给table，加一个&nbsp;virtualized配置项，然后渲染出来之后，表格的每列都会定宽，展示不下的内容就会被压住。
const colums=[{
key:1,
dataIndex:'name',
ellipsis:true
}]
const data=[{
name:'ppppppppppppppppppppppp'
}]
<Table dataSource=data&nbsp;columns={colums}&nbsp;virtualized={}/&gt;


&nbsp;


赵云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月15日(星期一) 中午11:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DouyinFE/semi-design] table组件，当外层网页有滚动的时候，table也有滚动，如何阻止当在table中时，不滚动外层 (Issue #2164)














  
图片看不到
 
麻烦提供一个可复现问题的最小demo codesandbox
 
上面的描述比较模糊，我们没法跟进处理
