### ISSUE TITLE
[Tag] Tag component add default avatar

### ISSUE THREAD

**Issue by LonelySnowman** [DouyinFE/semi-design#2168]
### Which Component Need Enhancement 期望新增功能的组件
- Tag

### What does the proposed API look like 期望支持的API

- (avatarSrc, avatarShape) -> avatarProps

### Feature Description 功能描述

- Tag 组件里直接引用的 Avatar 组件，希望可以支持全部的 Avatar 组件 Props。

### Additional information 补充说明

- 此功能支持需要使用 Tag 组件展示用户，用户未上传头像时无 avatarSrc，新增此 API 可以将用户名作为默认头像。
- 如果没有这个 API 的话，当前的解决方案是判断有无 avatarSrc，然后在 Tag 中自行加入 Avatar，体验上直接加一个 avatarProps 更好一些。
- 直接换成 avatarProps 有点破坏性更新，可以先 avatarProps 和 avatarSrc，avatarShape 共存。

**Comment by pointhalo** [comment]
tag本身就能传reactNode，这里有这种更复杂的自定义需求场景直接自己在 children 里放其他组件就行了。就是你这里补充说明的第二行。
支持传reactNode 类型的api初衷就是给一些自定义场景使用的。非不要不倾向于不断新增api。
