### ISSUE TITLE
[Modal] footerFill的最左边按钮有间距看起来很奇怪

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2173]
### Which Component Need Enhancement 期望新增功能的组件
- Modal

### What does the proposed API look like 期望支持的API
希望在footerFill的时候，最左边的按钮没有边距和标题内容齐平

### Feature Description 功能描述
<img width="488" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/514bd647-09b2-47c6-8a8d-4f97977d9f69">

**Comment by pointhalo** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/88709023/8a3abf07-c277-4f7f-b9ee-966f89bf4ef5)
