### ISSUE TITLE
[BUG] Breadcrumb组件会提示Warning: findDOMNode is deprecated in StrictMode警告

### ISSUE THREAD

**Issue by Luckypolo2** [DouyinFE/semi-design#2198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Breadcrumb

### Semi Version

2.56.2

### Current Behavior

Breadcrumb组件会提示Warning: findDOMNode is deprecated in StrictMode警告

### ReproducibleCode

```markdown
<Breadcrumb>
          <Breadcrumb.Item icon={<IconHome size="small" />}></Breadcrumb.Item>
          <Breadcrumb.Item icon={<IconArticle size="small" />}>手术信息</Breadcrumb.Item>
          <Breadcrumb.Item>手术申请</Breadcrumb.Item>
        </Breadcrumb>
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
详见 #201 目前无法彻底移除该API，会导致使用上有很多不便。该wanring也不影响实际使用。建议关掉strict mode或忽略该warning。

**Comment by hq-zh** [comment]
关掉strict mode 也是一样的findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference
