### ISSUE TITLE
是否可以支持Angular？Angular有计划支持吗？？？？

### ISSUE THREAD

**Issue by heihuhei2013** [DouyinFE/semi-design#221]
### Which Component Need Enhancement 期望新增功能的组件
- Button

**Comment by KimYangOfCat** [comment]
@heihuhei2013 
see #56

**Comment by shijiatongxue** [comment]
> @heihuhei2013 see #56

Thanks for your comment!

**Comment by pointhalo** [comment]
https://github.com/DouyinFE/semi-design/blob/02401f10d58014a1c6f20d628912f007c67b7eb0/content/start/introduction/index.md?plain=1#L109

关于多框架方向的roadmap，我们在官网的介绍中已经有过相关介绍了。我们团队目前的重点工作依然会围绕React体系展开。对于不同上层技术栈的兼容，我们更倾向于在未来通过WebComponent的方式进行解决。    
Angular不在我们官网计划提供的范畴内，但是欢迎社区通过复用Foundation的方式进行共建（仅需实现dom声明层即可，逻辑以及样式均可大规模复用）
