### ISSUE TITLE
[Button] 如何组合Tooltip使用

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2215]
### Which Component Need Enhancement 期望新增功能的组件
- Button

### What does the proposed API look like 期望支持的API
组合Tooltip使用

### Feature Description 功能描述
有些场景下，单从按钮文字看不懂功能，所以需要Tooltip的提示，但是我加在ButtonGroup里的话，会失去theme的效果
<img width="225" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/1b263f0e-6bb4-4bf3-a03a-6e4e0523917d">

**Comment by pointhalo** [comment]
我们设计上并不推荐这种交互。
更建议给 ButtonGroup内的单个button 放置 问号 icon，tooltip仅当hover icon时出现，而不是整个button都是交互热区。

**Comment by xmsz-stu** [comment]
> 我们设计上并不推荐这种交互。 更建议给 ButtonGroup内的单个button 放置 问号 icon，tooltip仅当hover icon时出现，而不是整个button都是交互热区。

好吧 我们是有问号icon的，但是很多用户根本不会去触碰它，所以一般都是偷懒直接整个区域来触发
