### ISSUE TITLE
[Tree] icon 支持传入  (props)=>ReactNode

### ISSUE THREAD

**Issue by shaoerkuai** [DouyinFE/semi-design#2236]
### Which Component Need Enhancement 期望新增功能的组件
- Tree

### What does the proposed API look like 期望支持的API

Icon除了支持ReactNode以外还能支持(props)=>ReactNode

### Feature Description 功能描述

我是在做一个文件在线浏览的一个web应用，所以icon希望能根据文件扩展名来变换展示，比如.js的文件展示js的图标，py的文件展示py的图标。

我可以根据props带参来判断文件格式决定返回什么Icon，但是目前发现Semi.design的Icon只能传ReactNode，希望还是支持下

**Comment by pointhalo** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/88709023/d8df2e73-e6a1-485f-877d-c1e5da12a0b6)
v2.59.0-beta.0
