### ISSUE TITLE
nextjs use client

### ISSUE THREAD

**Issue by linpan** [DouyinFE/semi-design#2242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

是否影响性能， 放在客户端渲染

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
没看明白想问什么。性能这个词太含糊了。

**Comment by pointhalo** [comment]
next 的client component 跟 server component应对的是不同业务场景，跟性能就没有什么主要联系。

**Comment by linpan** [comment]
semi +nextjs,  must be "use client"

**Comment by pointhalo** [comment]
任何带状态的组件都只能是 client component。但不等于说任何组件都会有性能损耗。
这不是一个对等的概念。

**Comment by pointhalo** [comment]
server component本身就不是所有场景都适用的。
