### ISSUE TITLE
Nav.Header. logo support static files(images) ?

### ISSUE THREAD

**Issue by linpan** [DouyinFE/semi-design#2249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Nav.Header. logo support static files(images) 
from local image or url 

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
logo本身就支持 reactNode传入。你传本地图片还是传远端图片都是可以的。这个不需要组件做额外支持。
