### ISSUE TITLE
[BUG] NextJs 最新版 Form表单无法执行表单规则校验

### ISSUE THREAD

**Issue by hb1707** [DouyinFE/semi-design#2251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Form

### Semi Version

2.58.1

### Current Behavior

见下图，直接复制的[Semi官网文档代码案例](https://semi.design/zh-CN/input/form#%E9%85%8D%E7%BD%AE%E5%88%9D%E5%A7%8B%E5%80%BC%E4%B8%8E%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99)，点提交后，前端没反应，调试日志有输出：
![屏幕截图 2024-05-23 232914](https://github.com/DouyinFE/semi-design/assets/19995502/73f2f7e4-f458-4ad2-97eb-1f96baad4b20)

### Expected Behavior

![屏幕截图 2024-05-23 232946](https://github.com/DouyinFE/semi-design/assets/19995502/4e3bcf93-c94f-4294-80ae-ac7807fe932b)

### Steps To Reproduce

直接运行我下文提供的代码仓库，或者按以下步骤操作：

1. 直接用 *npx create-next-app@latest react_demo* 命令创建一个全新的react项目，安装选项全部默认，因此会自动安装有nextJs
2. 复制Semi UI官网文档里面的 Form组件代码到项目首页，有带校验规则的那种
3. 运行 yarn dev

### ReproducibleCode

```markdown
我已经创建了一个demo 代码仓库，可codespaces在线直接运行:
https://github.com/hb1707/issues_demo
Semi UI代码部分:
https://github.com/hb1707/issues_demo/blob/master/app/page.tsx
```

### Environment

```markdown
- OS: windows 11
- browser: 版本 125.0.6422.60
```

**Comment by pointhalo** [comment]
把 StrictMode关一下。

```
module.exports = {
  reactStrictMode: false,
}
```

**Comment by pointhalo** [comment]
与 #2210 相关。

**Comment by pointhalo** [comment]
Fix v2.59.0
