### ISSUE TITLE
[Table] virtualized后align失效

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Table

### Current Behavior

<img width="946" alt="image" src="https://github.com/DouyinFE/semi-design/assets/139225486/9d74f254-940b-4941-82d5-d4ce79127020">
开启虚拟化后，align就无效了，只有表格头还是正常的

### Environment

```markdown
- OS:
- browser:
```

**Comment by shijiatongxue** [comment]
这是个 Bug，用的人比较少，所以没发现。原因是，虚拟化的使用使用的 inline-flex，align 失效了。
