### ISSUE TITLE
[Slider] Callback function after the value is completely changed

### ISSUE THREAD

**Issue by SmaIIstars** [DouyinFE/semi-design#2278]
### Which Component Need Enhancement 期望新增功能的组件
- Slider

### What does the proposed API look like 期望支持的API
- onChangeComplete

### Feature Description 功能描述
- Fired when the mouse is released (dragged or clicked) or the keyboard is released

### Additional information 补充说明
- For example, if you want to implement click and drag interaction when the component is controlled, but you can drag the slider but the value is not changed immediately, the combination of onMouseUp, onAfterChange, and onChange cannot meet the needs.

**Comment by pointhalo** [comment]
Due to long period of inactivity, we will close it. 
If you have further information, please reopen it.

**Comment by SmaIIstars** [comment]
Sorry for taking so long to reply, I have already completed my previous requirements.

For example, if I want to make a music player, I want to keep the music playing while dragging, so I need to keep it unchanged during this operation. onAfterChange does not completely wait until the triggering event is completely completed before triggering.
