### ISSUE TITLE
[DatePicker] 支持渲染左右两侧额外区域

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2283]
### Which Component Need Enhancement 期望新增功能的组件
- DatePicker

### What does the proposed API look like 期望支持的API
支持渲染左右两侧额外区域

### Feature Description 功能描述
现在只能上下，希望可以左右

场景
- 比如自定义present样式，显示只能传递固定格式和固定展示，但是我想实现这种同时显示【3天后-具体日期】就不行
![image](https://github.com/DouyinFE/semi-design/assets/139225486/16adac9f-6562-4bda-90ab-0d7c37e7aab0)
- 比如右边放一个时间选择器

**Comment by shijiatongxue** [comment]
是想要 leftSlot 和 rightSlot 吗

**Comment by xmsz-stu** [comment]
> 是想要 leftSlot 和 rightSlot 吗

没错

**Comment by shijiatongxue** [comment]
> > 是想要 leftSlot 和 rightSlot 吗
> 
> 没错

好的，我们排期支持下。如果有兴趣的话，也可以看下是否提个 PR。参考 topSlot 和 bottomSlot 的实现。

**Comment by pointhalo** [comment]
![image](https://github.com/user-attachments/assets/432c51bd-6bb0-481f-8101-782c5929ebfa)

datepicker leftSlot、rightSlot 已于 24.08 发布的 2.65.0-beta.0 版本之后支持
