### ISSUE TITLE
[Tabs] 新增 api 用于控制可折叠 tabs Dropdown 面板的展示

### ISSUE THREAD

**Issue by YannLynn** [DouyinFE/semi-design#2286]
### Which Component Need Enhancement 期望新增功能的组件
- Tabs

### What does the proposed API look like 期望支持的API
showRestInDropdown

### Feature Description 功能描述
当 collapsible 为 true 时，用 showRestInDropdown 控制 Dropdown 面板的显隐。
showRestInDropdown 为 true，左右箭头按钮 hover 展示 Dropdown 面板，
showRestInDropdown 为 false，左右箭头按钮 hover 不展示 Dropdown 面板，按钮仅有点击将上/下一个 tab scrollIntoView 功能。

### Additional information 补充说明
无

**Comment by lmsccc** [comment]
为什么不直接支持传递props到这个dropdown组件当中去呢？

**Comment by pointhalo** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/88709023/9fad3c69-2d3e-4db1-a78c-327230944089)
