### ISSUE TITLE
[Tabs] 希望tabs在collapsible的时候，可以提供一种方式传递dropdownProps，目前的more并不支持

### ISSUE THREAD

**Issue by lmsccc** [DouyinFE/semi-design#2295]
### Which Component Need Enhancement 期望新增功能的组件
- Tabs

### Feature Description 功能描述
tabs在collapsible的时，支持传递props到tab两边的dropdown组件当中去，目前的more无法支持

**Comment by pointhalo** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/88709023/d17c5011-9d25-4612-9364-e0ed41bc52ee)
![image](https://github.com/DouyinFE/semi-design/assets/88709023/85d649cd-f034-46dc-ba4d-e1e9d11d0c39)

可以使用 2.61.0-beta.0 开始提供的 renderArrow直接掌控整个 arrow node的渲染
