### ISSUE TITLE
[Theme] provide compact theme

### ISSUE THREAD

**Issue by GoldSubmarine** [DouyinFE/semi-design#2312]
### Feature Description 功能描述

虽然semi团队已经做了很好用的主题定制功能，但是作为一个不懂设计的开发人员，依然希望官方提供一个紧凑型的主题（自己始终调整不好比例）紧凑型主题在一些复杂功能的领域里是很有用的，因为功能组件很多，所以必须紧凑，举例来说我要开发一个代码编辑器或一个功能稍微复杂一点的桌面客户端，目前的组件size都太大了

竞品的支持 [antd compact](https://ant.design/docs/react/customize-theme-cn)

**Comment by pointhalo** [comment]
这个 compat 的范围比较模糊，而且它不是一个所有人都需要的东西，自由度偏高的事情还是建议自己通过 DSM 去做。这也是我们提供主题定制工具的原因。

**Comment by GoldSubmarine** [comment]
没有太理解范围模糊是什么意思。

的确不是所有人都需要这个主题，但是这的确是一个非常通用的需求，而不是个性化的，当做一些功能复杂的需求时，这个确实是刚需。比如webstorm的settings里你就可以看到compact ui按钮。

就像dark模式也不是所有人都需要（大部分网站都不支持切换到dark）但是dark的确是一个通用的需求。所以官方提供light / dark / compat 我觉得是很合理的

**Comment by pointhalo** [comment]
主要指：哪些 Component 需要紧凑布局。这个在不同的业务场景里很难拉齐。有的仅需要 Table ，有的希望某几个组件。
所以我们不太会计划说自己做这类事情，设计或者研发自己调 Token 会更自由一些。

**Comment by pointhalo** [comment]
我们会考虑在 Table 给出 compat 布局 ，但是其他组件我们很难敲定合适的 Token Value，因为我们业务本身没有这类诉求，比较难去做设计验证。
