### ISSUE TITLE
[Table] Table.Column支持传递RecordType类型

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2314]
### Which Component Need Enhancement 期望新增功能的组件
- Table.Column

### What does the proposed API look like 期望支持的API
<Table.Column<{a:1}> />

### Feature Description 功能描述
现在只能给Table传递类型
但是Table.Column里拿到的record并没传递，全部都是any

不知道能不能实现传递给Table.Column

如果不能实现，希望可以手动给Column传递类型
然后现在不能手动传递，因为Column不是个泛型，这就导致我在用的地方都得手动在赋值一次，比如render里，sorter里，太麻烦了

### Additional information 补充说明

还有不知道能不能做到
1. 传了dataindex,理论上render里的val类型应该是 RecordType<dataindex>， 现在也是个any，还是得手动赋类型
2. RowSelectionOnChange现在返回的类型是 (string | number)[], 能不能指定是number[],因为我现在这些会有类型错误
```
const [value, setValue] = useState<number[]>([]);
{
 onChange: setValue
}
```
我只能写成
```
const [value, setValue] = useState<number[]>([]);
{
 onChange: (e: number[]) => setValue(e)
}
```
每次都得怎么写，很麻烦。而且如果1能显示的话，理论上这个类型就是RecordType['id'] || RecordType[rowKey]

**Comment by shijiatongxue** [comment]
可以这么写。

<img width="790" alt="image" src="https://github.com/DouyinFE/semi-design/assets/26477537/a9296a16-e169-404b-a8a8-1b4b72b7274e">

**Comment by xmsz-stu** [comment]
> 可以这么写，定义好 data 的类型，ColumnProps 可以传入泛型。
> 
> <img alt="image" width="1024" src="https://private-user-images.githubusercontent.com/26477537/341368661-a8b82a80-43f9-4467-b741-736ac559070d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTc4MzEsIm5iZiI6MTcxOTE5NzUzMSwicGF0aCI6Ii8yNjQ3NzUzNy8zNDEzNjg2NjEtYThiODJhODAtNDNmOS00NDY3LWI3NDEtNzM2YWM1NTkwNzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAyNTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMzQ4OGUxZjQ5YzUzZTY1MTUwNDlmNDYxNTUyOGYzZTRlZGJiOTRmZWQ2ZDU5OGYzODU0OWU4YTVhMmEzYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p8LLmNlz-v3QcweCkxmfwMht6ccEyMDK_vUMZURqhGE"> <img alt="image" width="790" src="https://private-user-images.githubusercontent.com/26477537/341367892-a9296a16-e169-404b-a8a8-1b4b72b7274e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTc4MzEsIm5iZiI6MTcxOTE5NzUzMSwicGF0aCI6Ii8yNjQ3NzUzNy8zNDEzNjc4OTItYTkyOTZhMTYtZTE2OS00MDRiLWE4YTgtMWI0YjcyYjcyNzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAyNTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MzA4YmZkYzI4NWY1MDkxNjM1ODM5ZWM0NGEwM2RkZjg2MDJjN2VjYmVlZDQ3MTI4YjRlZTFlMGM2MmRlMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ulFdC7ZPYfmedSUKJM2mNQsjZioxd9Y7zNHgwyT8Oc">

我比较习惯在jsx里写column

**Comment by shijiatongxue** [comment]
> > 可以这么写，定义好 data 的类型，ColumnProps 可以传入泛型。
> > <img alt="image" width="1024" src="https://private-user-images.githubusercontent.com/26477537/341368661-a8b82a80-43f9-4467-b741-736ac559070d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTc4MzEsIm5iZiI6MTcxOTE5NzUzMSwicGF0aCI6Ii8yNjQ3NzUzNy8zNDEzNjg2NjEtYThiODJhODAtNDNmOS00NDY3LWI3NDEtNzM2YWM1NTkwNzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAyNTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMzQ4OGUxZjQ5YzUzZTY1MTUwNDlmNDYxNTUyOGYzZTRlZGJiOTRmZWQ2ZDU5OGYzODU0OWU4YTVhMmEzYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p8LLmNlz-v3QcweCkxmfwMht6ccEyMDK_vUMZURqhGE"> <img alt="image" width="790" src="https://private-user-images.githubusercontent.com/26477537/341367892-a9296a16-e169-404b-a8a8-1b4b72b7274e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTc4MzEsIm5iZiI6MTcxOTE5NzUzMSwicGF0aCI6Ii8yNjQ3NzUzNy8zNDEzNjc4OTItYTkyOTZhMTYtZTE2OS00MDRiLWE4YTgtMWI0YjcyYjcyNzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAyNTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MzA4YmZkYzI4NWY1MDkxNjM1ODM5ZWM0NGEwM2RkZjg2MDJjN2VjYmVlZDQ3MTI4YjRlZTFlMGM2MmRlMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ulFdC7ZPYfmedSUKJM2mNQsjZioxd9Y7zNHgwyT8Oc">
> 
> 我比较习惯在jsx里写column

可以。如果用 Table.Column 可以传泛型，每次用 Table.Column 的时候，都要 <Table.Column<RecordType> 是有点繁琐的。

**Comment by shijiatongxue** [comment]
> > 可以这么写，定义好 data 的类型，ColumnProps 可以传入泛型。
> > <img alt="image" width="1024" src="https://private-user-images.githubusercontent.com/26477537/341368661-a8b82a80-43f9-4467-b741-736ac559070d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTc4MzEsIm5iZiI6MTcxOTE5NzUzMSwicGF0aCI6Ii8yNjQ3NzUzNy8zNDEzNjg2NjEtYThiODJhODAtNDNmOS00NDY3LWI3NDEtNzM2YWM1NTkwNzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAyNTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMzQ4OGUxZjQ5YzUzZTY1MTUwNDlmNDYxNTUyOGYzZTRlZGJiOTRmZWQ2ZDU5OGYzODU0OWU4YTVhMmEzYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p8LLmNlz-v3QcweCkxmfwMht6ccEyMDK_vUMZURqhGE"> <img alt="image" width="790" src="https://private-user-images.githubusercontent.com/26477537/341367892-a9296a16-e169-404b-a8a8-1b4b72b7274e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTc4MzEsIm5iZiI6MTcxOTE5NzUzMSwicGF0aCI6Ii8yNjQ3NzUzNy8zNDEzNjc4OTItYTkyOTZhMTYtZTE2OS00MDRiLWE4YTgtMWI0YjcyYjcyNzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAyNTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MzA4YmZkYzI4NWY1MDkxNjM1ODM5ZWM0NGEwM2RkZjg2MDJjN2VjYmVlZDQ3MTI4YjRlZTFlMGM2MmRlMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ulFdC7ZPYfmedSUKJM2mNQsjZioxd9Y7zNHgwyT8Oc">
> 
> 我比较习惯在jsx里写column

Table.Column 目前确实不支持传入泛型。可以支持一下。不过用起来还是有点繁琐的，每个 Table.Column 都需要 `<Table.Column<RecordType> />`。

**Comment by shijiatongxue** [comment]
v2.62.0 supported
