### ISSUE TITLE
[Pagination] <分页组件悬浮到中间页码黑色popover>

### ISSUE THREAD

**Issue by xu756** [DouyinFE/semi-design#2326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Pagination

### Semi Version

2.61.0

### Current Behavior

<img width="1070" alt="image" src="https://github.com/DouyinFE/semi-design/assets/84982391/53078b4b-5dde-49ec-a697-1f42c060eb9e">
就像上面悬浮黑色

### Steps To Reproduce

官网例子
```
import React from 'react';
import { Pagination } from '@douyinfe/semi-ui';

() => (
    <div>
        <Pagination total={80} showTotal style={{ marginBottom: 12 }}></Pagination>
        <Pagination total={200} showTotal style={{ marginBottom: 12 }}></Pagination>
    </div>
);

```
<img width="1070" alt="image" src="https://github.com/DouyinFE/semi-design/assets/84982391/48b76f71-450f-4180-b367-99cd31224af3">

### Environment

```markdown
- OS: macos
- browser: chrome
```

**Comment by pointhalo** [comment]
![20240703102949_rec_](https://github.com/DouyinFE/semi-design/assets/88709023/272a8461-8647-4f89-9c57-70092ef54a43)

没有复现你截图的问题。会不会是你开启了什么浏览器插件导致的，可以进入隐身模式再试一下是否正常？
