### ISSUE TITLE
[DatePicker] 如何设置value为时间戳

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2348]
### Which Component Need Enhancement 期望新增功能的组件
- DatePicker

### What does the proposed API look like 期望支持的API
value={时间戳}
onChange={(payload: 时间戳)=>void}

### Feature Description 功能描述
因为我的数据结构类型是时间戳，但是现在DatePicker输出的是Date类型，我需要自己转换一次，有点麻烦

**Comment by shijiatongxue** [comment]
> ### Which Component Need Enhancement 期望新增功能的组件
> * DatePicker
> 
> ### What does the proposed API look like 期望支持的API
> value={时间戳} onChange={(payload: 时间戳)=>void}
> 
> ### Feature Description 功能描述
> 因为我的数据结构类型是时间戳，但是现在DatePicker输出的是Date类型，我需要自己转换一次，有点麻烦
> 
> ### Additional information 补充说明

Date 可以很简单地转换为时间戳，转换一次是符合预期的。不准备单独输出参数为 number 类型。

**Comment by xmsz-stu** [comment]
> Date 可以很简单地转换为时间戳，转换一次是符合预期的

我现在转一次是
在给initValues的时候，将时间戳 -> 日期
在提交数据的时候，将日期 -> 时间戳
有点麻烦，有没有什么好办法处理
