### ISSUE TITLE
[typo] <navigation> 组件的示例参数有 typo

### ISSUE THREAD

**Issue by Kros-ZERO** [DouyinFE/semi-design#2356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Navigation

### Current Behavior

https://github.com/DouyinFE/semi-design/blob/5d380ab3497242cb5c4324fee611b9cda577b4ca/content/navigation/navigation/index-en-US.md?plain=1#L41

### ReproducibleCode

```markdown
bodyStyle={{ height: 320 }}
```

**Comment by YyumeiZhang** [comment]
已修改
