### ISSUE TITLE
[BUG] <select optGroup 组件有问题，数据更新时，视图不重新渲染>

### ISSUE THREAD

**Issue by jiushiwoyuze** [DouyinFE/semi-design#2364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select

### Semi Version

2.54.0

### Current Behavior

数据更新时，视图不更新，且发现数据length变化时能正确更新（必须是组变化，比如原来三个分组变为4个了，这种情况能正常更新）

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/27627ffa-b8e5-4c01-8f61-4664ef51df3c)

### Environment

```markdown
- OS:mac
- browser:chrome
```

### Anything else?

另外补充一下，不使用optGroup，直接用Select.Option完全没有问题

**Comment by pointhalo** [comment]
给一下完整的复现demo  code

**Comment by jiushiwoyuze** [comment]
> 给一下完整的复现demo code

这个demo可以复现出来https://codesandbox.io/p/live/f5d02090-9c88-491a-9b0a-70afb3214cda

**Comment by pointhalo** [comment]
![image](https://github.com/user-attachments/assets/62b7f080-2090-4ecb-a12f-281d79b924f9)

需要给不同的key，见文档注意事项。

**Comment by dragooncjw** [comment]
virtualize 和 OptGroup 是不是不能同时使用？

**Comment by pointhalo** [comment]
> virtualize 和 OptGroup 是不是不能同时使用？

对。分组仅支持 jsx方式传入后选项。不支持虚拟化。
