### ISSUE TITLE
[BUG]  Rollup failed to resolve import "#minpath" from 

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

vfile

### Semi Version

2.62.1

### Current Behavior

构建的时候提示
```
16:27:03 [31m[vite]: Rollup failed to resolve import "#minpath" from "../../node_modules/.pnpm/vfile@6.0.2/node_modules/vfile/lib/index.js".
16:27:03 This is most likely unintended because it can break your application at runtime.
16:27:03 If you do want to externalize this module explicitly add it to
16:27:03 `build.rollupOptions.external`[39m
16:27:03 Vite Failed to build.
16:27:03 ERR! [vite]: Rollup failed to resolve import "#minpath" from "../../node_modules/.pnpm/vfile@6.0.2/node_modules/vfile/lib/index.js".
16:27:03 This is most likely unintended because it can break your application at runtime.
16:27:03 If you do want to externalize this module explicitly add it to
16:27:03 `build.rollupOptions.external` 
16:27:03 Error: [vite]: Rollup failed to resolve import "#minpath" from "../../node_modules/.pnpm/vfile@6.0.2/node_modules/vfile/lib/index.js".
16:27:03 This is most likely unintended because it can break your application at runtime.
16:27:03 If you do want to externalize this module explicitly add it to
16:27:03 `build.rollupOptions.external`
```

vfile的链路
 - unified@11.0.5
 - @mdx-js/mdx@3.0.1
 - @douyinfe/semi-foundation@2.62.1

应该是markdown的组件依赖，原先依赖中的vfile@4.2.1正常
盲猜是vfile在某个版本的时候，只能使用esm

请问要如何解决？

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
`npm create vite@latest vite-react-ts2407 -- --template react-ts` 新建了一个 vite项目，然后 npm i @douyinfe/semi-ui@2.62.1

引入 makrdownRender 、button组件后构建，一切正常，没有复现上述错误。

先排查下影响因子？搞个能复现的 Stackblitz 链接给我们查一下。

![image](https://github.com/user-attachments/assets/71aef6a5-4d76-41a0-87e4-cdf516102a7d)

![image](https://github.com/user-attachments/assets/2dc06f28-f024-4d40-a5d0-5b4d76e7ea4b)

**Comment by xmsz-stu** [comment]
> Stackblitz 链接

https://stackblitz.com/~/github.com/xmsz/demo-202407242

```
npm i 
npm run build
```

**Comment by xmsz-stu** [comment]
> 低版本打包工具不兼容 package.json 里的 import 和 export 字段就会有这个问题（这个是nodejs 规范 [https://nodejs.org/api/packages.html#conditional-exports），webpack4](https://nodejs.org/api/packages.html#conditional-exports%EF%BC%89%EF%BC%8Cwebpack4) 也会报这个，webpack5和 vite 不会。这是 mdxjs 的依赖的 vfile 里带进来的，我们作为下游的下游，不太好解决这个问题 @pointhalo

有没有什么我项目里能用的临时解决方案

**Comment by pointhalo** [comment]
![image](https://github.com/user-attachments/assets/8cb29208-f46a-4d6e-82bc-f8bd18c91f48)

![image](https://github.com/user-attachments/assets/bff207b1-9d25-43cc-9875-152fdb224567)

你的构建工具的版本太低了。

**Comment by pointhalo** [comment]
> `npm create vite@latest vite-react-ts2407 -- --template react-ts` 新建了一个 vite项目，然后 npm i @douyinfe/semi-ui@2.62.1
> 
> 引入 makrdownRender 、button组件后构建，一切正常，没有复现上述错误。
> 
> 先排查下影响因子？搞个能复现的 Stackblitz 链接给我们查一下。
> 
> ![image](https://private-user-images.githubusercontent.com/88709023/351600042-038f55e7-ed9c-408f-ade5-6f0fcd88283c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODQ4NTgsIm5iZiI6MTcyMTk4NDU1OCwicGF0aCI6Ii84ODcwOTAyMy8zNTE2MDAwNDItMDM4ZjU1ZTctZWQ5Yy00MDhmLWFkZTUtNmYwZmNkODgyODNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA5MDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNDllNDc1MGU2YjhlNDY5OTBkMmMyOGNlMTU3ZjMwNjFkZmU1NTU4MzI0OWZkNjhlNDk0MWEzNzE0ZDU0M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F5kI9FaMllN_E2qo95nvYKu_jEvhRylw7C987lb2RvA)
> 
> ![image](https://private-user-images.githubusercontent.com/88709023/351599924-e2d3152d-3ab3-48ef-a13b-014b04ea47a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODQ4NTgsIm5iZiI6MTcyMTk4NDU1OCwicGF0aCI6Ii84ODcwOTAyMy8zNTE1OTk5MjQtZTJkMzE1MmQtM2FiMy00OGVmLWExM2ItMDE0YjA0ZWE0N2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA5MDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YWI1YmIxOWQ3N2U3MThkODE2MDMxOWI0YWQzYjI0NjZkNTQ3YjRkYTc3Y2E1YjkxZmQ5ODc1OTZhOTIxMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LGf4BYQGQwuAozukHQZSnjLOZ8fZoYwuvgFR0sIHVJQ)
> 
> ![image](https://private-user-images.githubusercontent.com/88709023/351599647-71aef6a5-4d76-41a0-87e4-cdf516102a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODQ4NTgsIm5iZiI6MTcyMTk4NDU1OCwicGF0aCI6Ii84ODcwOTAyMy8zNTE1OTk2NDctNzFhZWY2YTUtNGQ3Ni00MWEwLTg3ZTQtY2RmNTE2MTAyYTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA5MDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZWRiZGZiMTVmMmQ3NTIxZTg5NDE0YjBjMTcxNzg1YzI3ZmYyYTU0NDAyMWQ3YzhlZDIyYzRkMzc0Y2MwMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l6_2Q0OVwmKS_vltjVqomEjRwbfOo2nWh_a--xt2g8A)
> 
> ![image](https://private-user-images.githubusercontent.com/88709023/351599234-2dc06f28-f024-4d40-a5d0-5b4d76e7ea4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODQ4NTgsIm5iZiI6MTcyMTk4NDU1OCwicGF0aCI6Ii84ODcwOTAyMy8zNTE1OTkyMzQtMmRjMDZmMjgtZjAyNC00ZDQwLWE1ZDAtNWI0ZDc2ZTdlYTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA5MDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ODdjY2QxM2JkODEzYzQ0NzIwMDliNDJmZTBhNGJlNjkwYjQ2M2M2YjE3MDRjNGM5NTMxY2QzYWRlMTk0MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ABVmr3k9PtswZ0hxlzzRQ1H_hGI0dqViDWU9k9w-6uQ)
> 
> https://stackblitz.com/edit/vitejs-vite-npe6az?file=src%2FApp.tsx

这个case里rollup 是4.19.0，新版实测是能正常处理的。

**Comment by xmsz-stu** [comment]
> 你的scaffold 是三年前的东西 [https://www.npmjs.com/package/@alifd/scaffold-simple，建议升级你的版本，比如你这里用的ice，就用](https://www.npmjs.com/package/@alifd/scaffold-simple%EF%BC%8C%E5%BB%BA%E8%AE%AE%E5%8D%87%E7%BA%A7%E4%BD%A0%E7%9A%84%E7%89%88%E6%9C%AC%EF%BC%8C%E6%AF%94%E5%A6%82%E4%BD%A0%E8%BF%99%E9%87%8C%E7%94%A8%E7%9A%84ice%EF%BC%8C%E5%B0%B1%E7%94%A8) ice 新建一个项目迁移过去，消灭技术债,我们已经尝试了最新版的ice是ok 的。如果迁移有成本，也可以用打包好的 umd 版本的 semi，来规避掉这个问题，代价是没有treeshaking。

只能先用umd版本了 因为这个项目也是好几年的 改不动了

**Comment by xmsz-stu** [comment]
还有一直非常临时的解决方法
```
 "pnpm": {
    "overrides": {
      "@mdx-js/mdx>vfile": "^4.2.1",
      "remark-rehype>vfile": "^4.2.1",
      "unified>vfile": "^4.2.1",
      "mdast-util-to-hast>vfile": "^4.2.1"
    }
  }
```
可以正常构建，但是不确定使用相关组件的时候会有什么问题，毕竟锁了旧版本
