### ISSUE TITLE
[BUG] 升级v2.63.0报"找不到模块"

### ISSUE THREAD

**Issue by Memoyu** [DouyinFE/semi-design#2378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Semi Version

v2.63.0

### Current Behavior

![image](https://github.com/user-attachments/assets/1b6893ce-8d45-44b6-b785-a8249ec9c4f0)
TypeScript 版本下升级到v2.63.0版本后无法引用类型
`import { FormApi } from '@douyinfe/semi-ui/lib/es/form';`
build 报错：
`Cannot find module '@douyinfe/semi-ui/lib/es/tag' or its corresponding type declarations`
切换回v2.62.1后正常

### Environment

```markdown
- OS:
- browser:
```

**Comment by ilxqx** [comment]
我也遇到了语言模块导入无法识别的问题：
![image](https://github.com/user-attachments/assets/656d0523-4986-4604-b59e-f90c865ec347)

**Comment by ilxqx** [comment]
发现回退到：2.62.1 这个版本就不报错了

**Comment by pointhalo** [comment]
@DaiQiangReal package.json 这个 export 似乎有影响，可能需要回退一下 #2363

**Comment by pointhalo** [comment]
v2.63.1 已回退。

**Comment by SudoUserReal** [comment]
还是需要添加 exports 的 ，否则用户的 tsconfig 的 moduleResolution 为 bundler 的时候会有问题。 这个 locale 找不到类型是因为 之前的 exports 写残缺了，应当：

```js
"exports": {
        ".": {
            "types": "./lib/es/index.d.ts",
            "import": "./lib/es/index.js",
            "require": "./lib/cjs/index.js"
        },
        "./*": {
            "types": "./lib/es/*/index.d.ts",
            "import": "./lib/es/*/index.js",
            "require": "./lib/cjs/*/index.js"
        },
        "./lib/es/*": {
            "types": [
                "./lib/es/*.d.ts",
                "./lib/es/*/index.d.ts"
            ],
            "import": "./lib/es/*.js",
            "default": "./lib/es/*.js"
        },
        "./lib/cjs/*": {
            "types": [
                "./lib/cjs/*.d.ts",
                "./lib/cjs/*/index.d.ts"
            ],
            "require": "./lib/cjs/*.js",
            "default": "./lib/cjs/*.js"
        }
    },
```
这个 fix 会在下个版本生效, 另外为了让传统的没有 bunder 模式的 tsconfig 配置，比如edenx, 需要这样 https://github.com/DouyinFE/semi-design/commit/92e40b5f18a908d709e003dd85db5575c573141b
