### ISSUE TITLE
VUE怎么用？

### ISSUE THREAD

**Issue by qzuozhu** [DouyinFE/semi-design#2385]
VUE怎么用？

**Comment by pointhalo** [comment]
https://github.com/DouyinFE/semi-design/issues/56

![image](https://github.com/user-attachments/assets/ddc224c0-3b8e-43c4-8b73-f4b9be82596d)
![image](https://github.com/user-attachments/assets/708de2ab-89bc-42a9-8e3d-9949f2a0a559)
