### ISSUE TITLE
[BUG] <Datapicker> two calendars with the same month appear when clicking

### ISSUE THREAD

**Issue by suedar** [DouyinFE/semi-design#2403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Datapicker

### Current Behavior

<img width="1416" alt="image" src="https://github.com/user-attachments/assets/bd1ac56a-5a21-46c7-ae29-690806898f9a">

### Expected Behavior

It should be two different month

### Environment

```markdown
- OS:
- browser:
```

### Anything else?

There is another question. When setting the needConfirm attribute, clicking on the area outside the calendar will not automatically close the popup.

**Comment by pointhalo** [comment]
By default, we do not enforce the month distribution between the two panels.

But if you want it to always be different for the upper and lower months, you can control it with this switch


`syncSwitchMonth `  

![image](https://github.com/user-attachments/assets/6f103c41-3eea-4cc2-86be-15ef4230300a)
