### ISSUE TITLE
[BUG] Upload组件上传失败

### ISSUE THREAD

**Issue by Memoyu** [DouyinFE/semi-design#2410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Semi Version

2.64.0

### Current Behavior

**当文件较大时（100多kb）,上传直接报错：**
![Snipaste_2024-08-14_17-36-15](https://github.com/user-attachments/assets/29a36bd2-045a-4883-a60a-01099afd8f49)

**当文件小时（1kb左右）,上传响应200，但是进度条一直存在：**
![Snipaste_2024-08-14_17-37-22](https://github.com/user-attachments/assets/f2a73c39-4edb-4d1f-9596-6d628e1b0cd1)

**当我回退到v2.63.1时，功能正常**

### Environment

```markdown
- OS:
- browser:
```

**Comment by Memoyu** [comment]
![image](https://github.com/user-attachments/assets/52e0aaea-791c-4819-a9e0-7dfb3f845570)
抓包后发现请求正常

**Comment by pointhalo** [comment]
无法复现这个问题。能否提供一个可复现的codesandbox demo

**Comment by Memoyu** [comment]
> 无法复现这个问题。能否提供一个可复现的codesandbox demo

感谢您的回复，烦请您移步这个项目下的demo分支：
https://github.com/Memoyu/Memo.Blog.Admin/tree/demo

> 1、初始化项目包
> 2、启动项目
> 3、 访问路径：http://localhost:11011/demo

**Comment by Memoyu** [comment]
![image](https://github.com/user-attachments/assets/4d15f1ee-7159-422e-bc97-2e0b46ad5e7a)
注释 严格模式后，正常上传

**Comment by pointhalo** [comment]
这个行为合理的。组件都卸载了，网络请求是需要 abort的。

**Comment by Memoyu** [comment]
> 这个行为合理的。组件都卸载了，网络请求是需要 abort的。

那这么说来，我在严格模式下岂不是就没法正常使用了？😂

**Comment by pointhalo** [comment]
你的请求是在严格模式导致的两次 mount 之间的发出的吗？

**Comment by Memoyu** [comment]
> 你的请求是在严格模式导致的两次 mount 之间的发出的吗？

应该不是的，他的两次mount触发间隔应该很小，我没有卡着时间去操作;
你可以看看demo，页面很纯粹，就是一个Upload，页面加载显示后操作上传就会无法触发；

**Comment by pointhalo** [comment]
好的，get，我晚些再看下这个例子。

**Comment by Memoyu** [comment]
> 好的，get，我今天晚些再看下这个例子。

辛苦了😆
