### ISSUE TITLE
[BUG] TextArea showClear will trigger  onChange！

### ISSUE THREAD

**Issue by linpan** [DouyinFE/semi-design#2420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

  <TextArea
                    onChange={handlerData}
                    value={text}
                    className={
                        'w-[900px] rounded-xl border-gray-200 bg-transparent text-sm hover:bg-transparent active:bg-white'
                    }
                    showClear
                    onClear={handlerClear}
                    rows={8}
                    maxCount={100}
                />

### ReproducibleCode

```markdown
<TextArea
                    onChange={handlerData}
                    value={text}
                    className={
                        'w-[900px] rounded-xl border-gray-200 bg-transparent text-sm hover:bg-transparent active:bg-white'
                    }
                    showClear
                    onClear={handlerClear}
                    rows={8}
                    maxCount={100}
                />


onClear.type = click

onChange.type = change.

当clear 会onChange 触发。
```

### Environment

```markdown
- OS:
- browser:
```

### Anything else?

当clear 会onChange 触发。

**Comment by linpan** [comment]
```
 <div className={'mt-0 py-0'}>
                <TextArea
                    onChange={handlerData}
                    value={text}
                    className={
                        'w-[900px] rounded-xl border-gray-200 bg-transparent text-sm hover:bg-transparent active:bg-white'
                    }
                    showClear
                    onClear={handlerClear}
                    rows={8}
                    maxCount={100}
                />
            </div>
```

**Comment by linpan** [comment]
onClear.type = click 
onChange.type = change. 
当clear 会onChange 触发。

**Comment by YyumeiZhang** [comment]
我理解点击 clear 按钮的时候触发onChange 是符合预期的行为，因为 clear 时候，会清空输入内容，因此需要通过 onChange 传递出去。对你的使用带来的问题具体是什么呢？

**Comment by YyumeiZhang** [comment]
未收到进一步反馈，暂时关闭此 issue，有更新再重开
