### ISSUE TITLE
[BUG] <CSS can't treeshaking in Vitejs>

### ISSUE THREAD

**Issue by Xwudao** [DouyinFE/semi-design#2421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Any Components

### Semi Version

latest

### Current Behavior

All CSS will be imported in All mode: Dev, Prod

![image](https://github.com/user-attachments/assets/89ad2b87-2a7d-4835-842b-21ff134a9d4e)

### Expected Behavior

Shoud be TreeShaking

### Steps To Reproduce

1. pnpm create vite
2. install semi-design
3. import any component like Button in App.tsx
4. F12 with Network tab

### ReproducibleCode

```markdown
import './App.css';
import { Button } from '@douyinfe/semi-ui';

function App() {
  return (
    <>
      <div>
        <Button>TEst</Button>
      </div>
    </>
  );
}

export default App;
```

### Environment

```markdown
- OS: Win11
- browser: Chrome
```

**Comment by Xwudao** [comment]
update: In my test, I found the problem.

Add below code in `vite.config.ts` in `build` section:

```ts
  build: {
    rollupOptions: {
      output: {
        manualChunks: (id) => {
          if (id.endsWith('.css') || id.endsWith('.scss')) {
            console.log('css--->>', id);
            return 'styles';
          }
          const admins = ['Admin'];
          if (admins.some((admin) => id.includes(admin))) {
            console.log('id--->>', id);
            return 'admin';
          }
        },
      },
    },
  },
```


Will case could not treeshaking.

![image](https://github.com/user-attachments/assets/1facc392-9423-408b-8f43-b77ba179e974)

**Comment by pointhalo** [comment]
![image](https://github.com/user-attachments/assets/8f412501-6af3-4eb2-a199-9c2aa126f24b)

1. Not very familiar with the rollup configuration. But from the official documentation, it should be designed for this kind of setting, not using shaking when set manulChunks.
3. This problem is beyond our control. It depends more on your build configuration.

**Comment by Xwudao** [comment]
> ![image](https://private-user-images.githubusercontent.com/88709023/359083609-8f412501-6af3-4eb2-a199-9c2aa126f24b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjcwNDksIm5iZiI6MTcyNDA2Njc0OSwicGF0aCI6Ii84ODcwOTAyMy8zNTkwODM2MDktOGY0MTI1MDEtNmFmMy00ZWIyLWExOTktOWMyYWExMjZmMjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDExMjU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NmFhMThiZDg0OTFjMzY5Y2Y3ODFhZDE4MmFjZTRjZTUzOGMwMzVlNzUyZjUxYzUzOTA3YzQ5ZDVjZTU4ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HoYdt6kFJyMTtqk2o-0ya96K2L9J_l_NiSctEbFJx5w)
> 
> 1. Not very familiar with the rollup configuration. But from the official documentation, it should be designed for this kind of setting, not using shaking when set manulChunks.
> 2. This problem is beyond our control. It depends more on your build configuration.

Thanks.
