### ISSUE TITLE
[BUG]  React Class Components only works in Client Components.

### ISSUE THREAD

**Issue by Luckypolo2** [DouyinFE/semi-design#2424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Nav,Layout

### Semi Version

latest

### Current Behavior

 Class extends value undefined is not a constructor or null

This might be caused by a React Class Component being rendered in a Server Component, React Class Components only works in Client Components. Read more: https://nextjs.org/docs/messages/class-component-in-server-component

在nextjs app路由模式下的服务端渲染会提示上述错误。
我看semi组件很多都是使用class构建，是否可认为组件不支持nextjs的服务端渲染？

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
'use client' please，带逻辑带状态的组件不适合 server component

**Comment by pointhalo** [comment]
这个不是 class component 跟 functional component的区别，即使是 functional component，如果里面带了 useState之类的状态（事实上只要是带点逻辑的组件，内部状态基本都是有的），你也没法作为server component 使用
