### ISSUE TITLE
[BUG] <title>semi.css 文件 .semi-chat-chatBox的margin-bottom属性名称错误

### ISSUE THREAD

**Issue by acccccccb** [DouyinFE/semi-design#2429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

semi.css -> .semi-chat-chatBox

### Semi Version

2.64.0

### Current Behavior

打包时，构建工具提示警告信息：
`
rendering chunks (4)...warnings when minifying css:
▲ [WARNING] "margin-Bottom" is not a known CSS property [unsupported-css-property]

    <stdin>:23081:2:
      23081 │   margin-Bottom: 8px;
            │   ~~~~~~~~~~~~~
            ╵   margin-bottom

  Did you mean "margin-bottom" instead?

`

### Expected Behavior

semi.css 第4076行

margin-Bottom: 8px;  应该为 margin-bottom: 8px;

### Steps To Reproduce

执行build命令时

### Environment

```markdown
- OS: windows
- browser: Chrome
```

**Comment by YyumeiZhang** [comment]
Fixed in https://github.com/DouyinFE/semi-design/commit/dd415953728921b05c3d7329a0b782ee2da0eec4。正式版本预计本周五
