### ISSUE TITLE
[BUG] Avatar组件文档上写支持自定义尺寸，但实际使用中却不支持

### ISSUE THREAD

**Issue by viilon** [DouyinFE/semi-design#2443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Avatar

### Semi Version

2.64.0

### Expected Behavior

<img width="594" alt="image" src="https://github.com/user-attachments/assets/6cebdbb2-d29b-468e-82d2-f54f9aefb902">
<img width="438" alt="image" src="https://github.com/user-attachments/assets/4cc12e3c-53d6-4d01-bd5a-81021c59426f">
<img width="823" alt="image" src="https://github.com/user-attachments/assets/02a4433b-af0a-4858-a529-bab11285b30c">

### Environment

```markdown
- OS:
- browser:
```

**Comment by YannLynn** [comment]
@viilon  我们改一下

**Comment by YyumeiZhang** [comment]
![image](https://github.com/user-attachments/assets/c41029e9-4dca-4af4-a822-854434465ca1)
