### ISSUE TITLE
[BUG] <title> Popover在表格/特殊渲染层中时 hover离开dom依然保留

### ISSUE THREAD

**Issue by wooktao** [DouyinFE/semi-design#2456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Popover

### Semi Version

2.55.1

### Current Behavior

Popover组件在Table（antd）或者svg层中渲染时 鼠标离开trigger popover消失  但是dom依然存在
![image](https://github.com/user-attachments/assets/952b01a1-5b23-461d-a89e-05e777c998d8)

![image](https://github.com/user-attachments/assets/0c8f75e9-55be-4720-b611-3e076ed11c8a)

### Expected Behavior

Popover消失且不影响页面

### Environment

```markdown
- OS:
- browser:
使用的是antd的自定义Table
    <Popover
            content={content}
            showArrow
          >
            <tr {...props} className={`${props.className || ''}`}>
              {props.children}
            </tr>
          </Popover>
```

**Comment by pointhalo** [comment]
麻烦给个可复现的 codesandbox 链接，这个信息太简略了
