### ISSUE TITLE
[BUG] <title> 使用 @codesandbox/sandpack-react报错

### ISSUE THREAD

**Issue by rxyshww** [DouyinFE/semi-design#2469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Something went wrong

/App.js: Could not find module in path: 'vfile/lib/#minpath' relative to '/node_modules/vfile/lib/index.js' (3:0)

  1 | 
  2 | import React from "react";
> 3 | import { Button } from '@douyinfe/semi-ui';
      ^
  4 | 
  5 | export default function App() {
  6 |   return (

### Steps To Reproduce

https://codesandbox.io/p/sandbox/r7gdwm

### ReproducibleCode

```markdown
"use client";
import React from "react";
import { Sandpack } from "@codesandbox/sandpack-react";

const code = `
import React from "react";
import { Button } from '@douyinfe/semi-ui';

export default function App() {
  return (
    <>
        <Button type='primary'>primary button</Button>
    </>
  );
}
`;

const SandpackExample = () => {
  return (
    <Sandpack
      template="react"
      files={{
        "/App.js": code,
      }}
      customSetup={{
        dependencies: {
          "@douyinfe/semi-ui": "latest",
        },
      }}
    />
  );
};

export default SandpackExample;
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
这个是 codesandbox 它内置的构建器的问题，我们无法解决。
它可能使用的低版本bundle，例如rollup的低版本，webpack的低版本，没法识别 Subpath imports语法，就会有问题。

mdx的依赖 vfile 使用了这种语法。
![image](https://github.com/user-attachments/assets/1a42b493-653f-44e8-8637-de874bc7681c)
![image](https://github.com/user-attachments/assets/b4e0db7c-ec68-4d86-9876-ad9a38d7c1b0)

**Comment by pointhalo** [comment]
我对@codesandbox/sandpack-react这个包不是很熟悉，如果你能干预它的构建的话，也可以配置alias来解决。这个问题本质上是它的bundle没法正确识别这个 import path。

**Comment by pointhalo** [comment]
The examples here all have the same problem： https://codesandbox.io/examples/package/vfile

**Comment by pointhalo** [comment]
![image](https://github.com/user-attachments/assets/0e445526-e570-4807-a954-cff1f2e44b8a)
Another solution is to try to lock the vfile version to 6.0.1
This syntax is used in versions 6.0.2 and later.
Explicitly declaring the version of this dependency to be 6.0.1 should also solve this problem
![image](https://github.com/user-attachments/assets/4760b3a7-9863-439d-971f-982e913b7d11)

**Comment by pointhalo** [comment]
We have reported this issue to codesandbox. Whether it will be fixed later depends on their team's decision.

https://github.com/codesandbox/codesandbox-client/issues/8625
