### ISSUE TITLE
[Semver] 关于patch版本号发布问题

### ISSUE THREAD

**Issue by rashagu** [DouyinFE/semi-design#2470]
### Which Component Need Enhancement 期望新增功能的组件
- All

### What does the proposed API look like 期望支持的API
最近发的版本很少有patch版本号，一些bug修复都集中在了minor版本号。希望一些fix更新可以及时发布在patch版本号

**Comment by pointhalo** [comment]
我们是双周更新一次 minor。中间会发布beta版本灰度一周左右。
所有 feature都会跟在 beta版本发布，patch版本只会有 style、fix、chore之类的更新。

每周会根据 CodeReview完成的实际情况决定跟哪个版本，如果一个 fix 它的 CR完成时间刚好是在minor beta发布后（eg 2.65-beta.0），minor 正式（2.65.0）发布前。那就大概率会跟随 minor 正式版（2.65.0）的时间（一般是周五）一同发布。

如果你对某些fix 有特殊诉求的话，可以在对应issue下单独说一下。我们可以单独发patch。
但应该不太会为所有的 fix 都发 patch（操作频次带来的问题问题）

**Comment by rashagu** [comment]
OK
