### ISSUE TITLE
[Table] 支持自定义表头

### ISSUE THREAD

**Issue by huruji** [DouyinFE/semi-design#2479]
参考 elementui，或者有现有的手段来做这个事情吗
![image](https://github.com/user-attachments/assets/a30dd9d1-a2bd-4eaa-8de6-1d666a907302)

**Comment by pointhalo** [comment]
![image](https://github.com/user-attachments/assets/7e1d630e-d5b0-4c2b-935a-9b5844732437)

看下这个demo是否满足？

**Comment by huruji** [comment]
> ![image](https://private-user-images.githubusercontent.com/88709023/365503830-7e1d630e-d5b0-4c2b-935a-9b5844732437.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjU3OTMsIm5iZiI6MTcyNjAyNTQ5MywicGF0aCI6Ii84ODcwOTAyMy8zNjU1MDM4MzAtN2UxZDYzMGUtZDViMC00YzJiLTkzNWEtOWI1ODQ0NzMyNDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAzMzEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MjdlNWY1ZjU2YTg2MDk1NWU0MzdhMGI1YTcxNmM1MTY5MzdmY2JkYTQ3MjUyNDFmYjM3OTFkYmVkZTdkODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MrvYbJWTC5_B8to-40a132d3HnbYkLzHk4VO0TXhT5g)
> 
> 看下这个demo是否满足？

@pointhalo 可以了，看了一下可以传人 reactNode 自定义，我的场景是表头有很多图片和按钮，谢谢大佬～
