### ISSUE TITLE
Select 组件需求归总

### ISSUE THREAD

**Issue by lsq168564164** [DouyinFE/semi-design#248]
1. +n 折叠方式可选自适应容器宽度
![image](https://user-images.githubusercontent.com/22464472/141075994-e4ab2cbc-0044-4b79-921f-bc9130e5b70b.png)

2. 清空按钮允许自定义常驻在下箭头左侧
![image](https://user-images.githubusercontent.com/22464472/141076149-b4e6b4f9-c446-4ff0-ba94-b1af828a89d8.png)

3. 新建选项在搜索无结果时展示 “未找到选项”
![image](https://user-images.githubusercontent.com/22464472/141076589-c3c947bd-e1c7-4333-9906-ffd31111a7c9.png)

**Comment by zwlafk** [comment]
如果可以的话请尽量一个issue只描述一个问题，这样有助于开发者和贡献者通过PR解决问题
新建issue的时候也请标明您的反馈的是bug还是feature request
感谢理解

**Comment by pointhalo** [comment]
> 如果可以的话请尽量一个issue只描述一个问题，这样有助于开发者和贡献者通过PR解决问题 新建issue的时候也请标明您的反馈的是bug还是feature request 感谢理解

这几个feature 之前胜青已经跟我这边内部对过，所以写得相对简略一些~ 我这边清楚相关上下文，所以也没有重新编辑😂 不过确实拆分一下比较好，我这边后续拆一下到具体版本里。

**Comment by Carlosfengv** [comment]
问题1 会在后续版本中提供;
问题2 可以通过设置 showArrow  和 suffix  的方式来解决。

```
      showArrow={false}
      suffix={<IconChevronDown />}
```
问题3 会有我们会把示例更新在文档的中

**Comment by lsq168564164** [comment]
> 问题1 会在后续版本中提供; 问题2 可以通过设置 showArrow 和 suffix 的方式来解决。
> 
> ```
>       showArrow={false}
>       suffix={<IconChevronDown />}
> ```
> 
> 问题3 会有我们会把示例更新在文档的中

关于问题 2, 这个问题是在做审核团队组件的时候遇到的, 组件层面希望可以使用 showClear api 实现上述效果

**Comment by lsq168564164** [comment]
> > 问题1 会在后续版本中提供; 问题2 可以通过设置 showArrow 和 suffix 的方式来解决。
> > ```
> >       showArrow={false}
> >       suffix={<IconChevronDown />}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 问题3 会有我们会把示例更新在文档的中
> 
> 关于问题 2, 这个问题是在做审核团队组件的时候遇到的, 组件层面希望可以使用 showClear api 实现上述效果

@Carlosfengv

**Comment by so2liu** [comment]
想问一下问题1， 很长的`option.label`,有解决方案或者workaround吗
