### ISSUE TITLE
[BUG] <Select> select 在使用getPopupContainer 之后，点击空白处不能调用 onBlur 

### ISSUE THREAD

**Issue by JamesLi-dev** [DouyinFE/semi-design#2485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select

### Semi Version

^2.64.0

### Current Behavior

select 在使用getPopupContainer 之后，点击空白处不能调用 onBlur ， 只能通过再次点击select 隐藏下拉列表
![1](https://github.com/user-attachments/assets/f06ac4c3-f4b2-42e8-a66f-f297a3a6aa09)

### Expected Behavior

点击空白处可以收起下拉，或者有个状态控制下拉展开收起

### Environment

```markdown
- OS:macos
- browser:google
```

**Comment by pointhalo** [comment]
没有办法复现你的问题
1. 检查一下是否你的dom上有阻止事件传播之类的逻辑
2. 我们需要一个能复现问题的 codesandbox 链接


这段代码直接粘贴到官网上，无论 getPopupContainer 使用哪一行，行为都是正常的。
```
import React, { useRef } from 'react';
import { Select } from '@douyinfe/semi-ui';

() => {
    const divRef = useRef();
    return (
    <div ref={divRef} style={{position:'relative'}}>
        <div id='id' style={{position: 'relative'}}></div>
        <Select
            clickToHide
            showClear
            // getPopupContainer={() => document.getElementById('id')}
            getPopupContainer={() => divRef.current || document.body}
            style={{ width: '180px' }}
            placeholder="try abc"
            onBlur={() => Toast.info('on blur')}
        >
            <Select.Option value="abc">ABC</Select.Option>
            <Select.Option value="ulikecam">HOTSOON</Select.Option>
            <Select.Option value="jianying">PIPIXIA</Select.Option>
            <Select.Option value="xigua">XIGUA</Select.Option>
        </Select>
    </div>
    );
};

```

![20240919163637_rec_](https://github.com/user-attachments/assets/b7f8a6a4-80bc-4c7d-86f6-5a9586554cbb)
