### ISSUE TITLE
[InputGroup] 如果是inputNumber圆角没有变为0

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

InputGroup

### Current Behavior

<img width="404" alt="image" src="https://github.com/user-attachments/assets/3e691916-656e-4258-8759-1aa79d7d54a8">

### ReproducibleCode

```markdown
<InputGroup>
            <Input placeholder="Name" style={{ width: 100 }} />
            <InputNumber placeholder="Score" style={{ width: 140 }} innerButtons />
               <Input placeholder="Name" style={{ width: 100 }} />
        </InputGroup>
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
这个应该是考虑不周，我们改一下。
