### ISSUE TITLE
[BUG] [Chat] 组件传入的chats属性的content如果含有字符串类型的对象会白屏

### ISSUE THREAD

**Issue by iwgyyyy** [DouyinFE/semi-design#2507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Chat

### Semi Version

2.65.0

### Current Behavior

当chats属性传入的以下的数组

```js
const messages = [
  {
    id: 1,
    role: 'user',
    content: '测试',
  },
  {
    id: 2,
    role: 'assistant',
    content: '{ "error": {} }'
  }
]
```

就会白屏了 报错信息如下
![image](https://github.com/user-attachments/assets/d77c8739-7178-4588-980f-6453b6d4fc1b)

### Expected Behavior

理论上应该可以正常显示这个字符串类型的错误信息

**Comment by YyumeiZhang** [comment]
@iwgyyyy 升级到 2.66.0试试，
![image](https://github.com/user-attachments/assets/7758424e-124b-4c5d-ac43-ca1e342e9688)

**Comment by iwgyyyy** [comment]
> @iwgyyyy 升级到 2.66.0试试， ![image](https://private-user-images.githubusercontent.com/101110131/369736953-7758424e-124b-4c5d-ac43-ca1e342e9688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTk2OTIsIm5iZiI6MTcyNzA1OTM5MiwicGF0aCI6Ii8xMDExMTAxMzEvMzY5NzM2OTUzLTc3NTg0MjRlLTEyNGItNGM1ZC1hYzQzLWNhMWUzNDJlOTY4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMjQzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzUwOTM2NzhhMmM3NWFkNzBmMTE1MjM3MzZiY2U5MWE1OGEyNWIyNDU2MTQ0NjYxNWRlYzg0NDdlOTNjNmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JpzQhyQBeK9vyCfJCj8LNbSlmFrTIEb48SvAroLzyJM)

还是一样的，我的完整的 `content` 如下

```txt
Error: OpenAI error 400: {"error":{"message":"This model's maximum context length is 128000 tokens. However, your messages resulted in 254877 tokens. Please reduce the length of the messages. (request id: 2024092300292695706066466933524) (request id: 202409230029256140199406KSr28x6)","type":"invalid_request_error","param":"messages","code":"context_length_exceeded"}}
```

![image](https://github.com/user-attachments/assets/356a45bb-61ac-473c-b77a-ede235cb6ba9)

**Comment by iwgyyyy** [comment]
升级之后还有另一个问题，本地启动报如下错误，无奈只能换回2.65.0了

![image](https://github.com/user-attachments/assets/db2ad06d-8682-4567-b6c9-bd9048d49ccf)

**Comment by YyumeiZhang** [comment]
> 升级之后还有另一个问题，本地启动报如下错误，无奈只能换回2.65.0了
> 
> ![image](https://private-user-images.githubusercontent.com/55680034/369800387-db2ad06d-8682-4567-b6c9-bd9048d49ccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODE2MjIsIm5iZiI6MTcyNzA4MTMyMiwicGF0aCI6Ii81NTY4MDAzNC8zNjk4MDAzODctZGIyYWQwNmQtODY4Mi00NTY3LWI2YzktYmQ5MDQ4ZDQ5Y2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA4NDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NmIxY2MyNTZjZDc5MGE0Y2QzNmE2NTFhM2FkY2NjZjEzOWFiZjQ3YzcwNjM4MDQ0OTdmMjA3MWQ4ZWQwMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I6Yo4O8PpCYobi-rOcfd_Zp2up3hQt3OM3utDcuLU4Y)

@DaiQiangReal 看看这个问题？

**Comment by iwgyyyy** [comment]
> 主题包装了吗

肯定是装的了


```tsx
// vite.config.ts
import semi from 'vite-plugin-semi-theme';

export default defineConfig({
  plugins: [
    react(),
    semi({
      theme: '@semi-bot/semi-theme-we-assist',
      options: { cssLayer: true }
    })
  ],
});
```

但实际上我主要是要解决Chat组件白屏问题

**Comment by iwgyyyy** [comment]
发现将 ```@douyinfe/semi-ui``` 升级到  `2.66.0` 及以上的版本能够修复白屏的问题，然后本地启动的报错 是因为安装了 ```vite-plugin-semi-theme```插件的原因，今天无意间发现 需要将 ```@douyinfe/semi-ui``` 、```@douyinfe/semi-illustrations```和```@douyinfe/semi-icons```同时升级到相同版本才会不报错。两个问题都解决了
