### ISSUE TITLE
[BUG] <title>下拉框组件，value值不一样，选择名称相同，选中其中一个，名称一样的下拉项都会被选中

### ISSUE THREAD

**Issue by merrylmr** [DouyinFE/semi-design#2510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

select

### Semi Version

2.66.1

### Current Behavior

如下图所示，两个选项的名称相同 ，但是value不同，选中其中一个另外一个也被选中了
![image](https://github.com/user-attachments/assets/9c4ef760-b2d5-490b-8db3-498a1985882a)

### Expected Behavior

希望根据选中的value值，回显对应的下拉选项即可

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
可以拉到文档最后看下 FAQ。
