### ISSUE TITLE
[BUG] 在chrome85版本中，部分组件如Tabs组件，点击会出现黑框

### ISSUE THREAD

**Issue by Luckypolo2** [DouyinFE/semi-design#2520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Tabs

### Semi Version

latest

### Current Behavior

在chrome85版本中，部分组件如Tabs组件，点击会出现黑框。
部分弹出框在选中过程中也会有黑框

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
1. 麻烦给个截图
2. 反馈的这个现象跟浏览器版本是强相关的吗？有测试过别的浏览器或者更新的版本表现是否一致？
