### ISSUE TITLE
[Timeline] 有考虑列表过长的渲染方案么？

### ISSUE THREAD

**Issue by NickJiangDev** [DouyinFE/semi-design#2530]
### Which Component Need Enhancement 期望新增功能的组件
- Timeline

### What does the proposed API look like 期望支持的API
useVirual?

### Feature Description 功能描述
如果数据一直通过动态数据源滚动累加，就会一直不断插入dom节点，可能会造成渲染卡顿等问题。

**Comment by pointhalo** [comment]
对大部分用户来说，timeline都不会有非常多的节点。需要用到虚拟化的概率太低了，我们不计划对这块做改造支持，如果你的场景下有强诉求的话，欢迎提交PR共建。
