### ISSUE TITLE
[BUG] <为什么Select组件多选情况下，删除选中tag时不会自动focus啊，手动补上focus逻辑还会触发onBlur，聚焦后的事件无法使用>

### ISSUE THREAD

**Issue by HandsomeBrother** [DouyinFE/semi-design#2533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select

### Semi Version

^2.65.0

### Current Behavior

为什么Select组件多选情况下，删除选中tag时不会自动focus啊，手动补上focus逻辑还会触发onBlur，聚焦后的事件无法使用

### Expected Behavior

删除选中tag会自动focus

### ReproducibleCode

```markdown
<Select onBlur={XXX}></Select>
```

### Environment

```markdown
- OS:
- browser: chrome
```

### Anything else?

none

**Comment by pointhalo** [comment]
没看明白这个问题。麻烦给个复现demo以及录屏。
