### ISSUE TITLE
[BUG] `@douyinfe/semi-foundation@2.68.0` scss变量丢失导致编译失败

### ISSUE THREAD

**Issue by haoming29** [DouyinFE/semi-design#2539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

@douyinfe/semi-foundation

### Semi Version

2.68.0

### Current Behavior

编译失败，提示：

```
2024/10/19 05:34:25 [1m[31mERROR[39m[22m in [1m./node_modules/.pnpm/@douyinfe+semi-foundation@2.68.0/node_modules/@douyinfe/semi-foundation/lib/es/resizable/resizable.scss[39m[22m (./node_modules/.pnpm/css-loader@4.3.0/node_modules/css-loader/dist/cjs.js?{"sourceMap":false}!./node_modules/.pnpm/sass-loader@10.5.2_sass@1.80.2/node_modules/sass-loader/dist/cjs.js!./node_modules/.pnpm/@douyinfe+semi-webpack-plugin@2.68.0/node_modules/@douyinfe/semi-webpack-plugin/lib/semi-theme-loader.js?{"name":"@ies/semi-theme-bytehi-semi2","prefixCls":"csp_tools","variables":"","include":"~@ies/semi-theme-bytehi-semi2/scss/local.scss"}!./node_modules/.pnpm/@douyinfe+semi-foundation@2.68.0/node_modules/@douyinfe/semi-foundation/lib/es/resizable/resizable.scss)
2024/10/19 05:34:25 [1mModule build [1m[31mfailed[39m[22m[1m (from ./node_modules/.pnpm/sass-loader@10.5.2_sass@1.80.2/node_modules/sass-loader/dist/cjs.js):
2024/10/19 05:34:25 SassError: Undefined variable.
2024/10/19 05:34:25    ╷
2024/10/19 05:34:25 15 │         z-index: $z-resizable_handler;
2024/10/19 05:34:25    │                  ^^^^^^^^^^^^^^^^^^^^
2024/10/19 05:34:25    ╵
2024/10/19 05:34:25   node_modules/.pnpm/@douyinfe+semi-foundation@2.68.0/node_modules/@douyinfe/semi-foundation/lib/es/resizable/resizable.scss 15:18  root stylesheet[39m[22m
2024/10/19 05:34:25 SassError: SassError: Undefined variable.
2024/10/19 05:34:25    ╷
2024/10/19 05:34:25 15 │         z-index: $z-resizable_handler;
2024/10/19 05:34:25    │                  ^^^^^^^^^^^^^^^^^^^^
2024/10/19 05:34:25    ╵
**2024/10/19 05:34:25   node_modules/.pnpm/@douyinfe+semi-foundation@2.68.0/node_modules/@douyinfe/semi-foundation/lib/es/resizable/resizable.scss 15:18  root stylesheet**
2024/10/19 05:34:25     at 
.....
2024/10/19 05:34:25  @ ./node_modules/.pnpm/@douyinfe+semi-foundation@2.68.0/node_modules/@douyinfe/semi-foundation/lib/es/resizable/resizable.scss 2:26-516
2024/10/19 05:34:25  @ ./node_modules/.pnpm/@douyinfe+semi-ui@2.68.0_react-dom@17.0.2+react@17.0.2/node_modules/@douyinfe/semi-ui/lib/es/resizable/single/resizable.js 9:0-67
2024/10/19 05:34:25  @ ./node_modules/.pnpm/@douyinfe+semi-ui@2.68.0_react-dom@17.0.2+react@17.0.2/node_modules/@douyinfe/semi-ui/lib/es/resizable/index.js 6:0-43 7:0-21
2024/10/19 05:34:25  @ ./node_modules/.pnpm/@douyinfe+semi-ui@2.68.0_react-dom@17.0.2+react@17.0.2/node_modules/@douyinfe/semi-ui/lib/es/index.js 97:0-80 97:0-80 97:0-80 97:0-80 97:0-80
2024/10/19 05:34:25  @ ./src/components/FormRenderSDK.tsx
2024/10/19 05:34:25  @ container entry ./FormRenderSDK[0]
2024/10/19 05:34:25 
2024/10/19 05:34:25 webpack 5.79.0 compiled with [1m[31m1 error[39m[22m and [1m[33m1 warning[39m[22m in 22084 ms
```

### Expected Behavior

正常编译

### Steps To Reproduce

1. 安装以下包依赖：

```
"@douyinfe/semi-ui": "2.68.0",
```

2. 调用 `import { Spin } from '@douyinfe/semi-ui';`
3. 编译项目

### Environment

```markdown
- Node: 16
- pnpm@6.24.2
```

**Comment by hb1707** [comment]
2.67.0 同样遇到这个问题

**Comment by hb1707** [comment]
重新发布自定义主题之后，能解决。

**Comment by pointhalo** [comment]
v2.68.0 新增了 Resziable 组件。对应地，它新增了一个 全局Design Token的声明
![image](https://github.com/user-attachments/assets/73a21dcc-1ddb-45c7-bc07-14f7f5adab86)
- 如果使用默认主题，这块是同步版本更新的。
- 如果使用了自定义主题，由于自定义主题发布时，还不包含这个Token，它是没有这个变量的，需要 去 https://semi.design/dsm重新发布一次
- @douyinfe/semi-theme-default 与你的自定义主题包，是替换关系。如果使用了自定义主题包，就不会再消费默认主题包。

**Comment by haoming29** [comment]
> v2.68.0 新增了 Resziable 组件。对应地，它新增了一个 全局Design Token的声明 ![image](https://private-user-images.githubusercontent.com/88709023/378264799-73a21dcc-1ddb-45c7-bc07-14f7f5adab86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0ODIzMDksIm5iZiI6MTcyOTQ4MjAwOSwicGF0aCI6Ii84ODcwOTAyMy8zNzgyNjQ3OTktNzNhMjFkY2MtMWRkYi00NWM3LWJjMDctMTRmN2Y1YWRhYjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDAzNDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjOWZhYWE5ZGIzMmVmMTYyY2ZhOGY0NjUyNGVhMmNlZjg5ZmEwNTVlNTEyZDRjM2Y0NzMyNDM5M2MyZTQ4ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JhkbNmphpDWl0vXUfUL0MNw541CkMpIRldphKSUR7Qs)
> 
> * 如果使用默认主题，这块是同步版本更新的。
> * 如果使用了自定义主题，由于自定义主题发布时，还不包含这个Token，它是没有这个变量的，需要 去 [https://semi.design/dsm重新发布一次](https://semi.design/dsm%E9%87%8D%E6%96%B0%E5%8F%91%E5%B8%83%E4%B8%80%E6%AC%A1)
> * @douyinfe/semi-theme-default 与你的自定义主题包，是替换关系。如果使用了自定义主题包，就不会再消费默认主题包。

@pointhalo  内部沟通之后发现是依赖包版本问题，升级到[2.68.1](https://github.com/DouyinFE/semi-design/releases/tag/v2.68.1)应能解决问题。对于自定义主题的breaking change，这个以后发版备注里可以高亮通知一下吗？目前2.68.0里没有提及这块变动。

**Comment by pointhalo** [comment]
@YyumeiZhang 这个changelog需要改一下，强调一下这个信息。

**Comment by YannLynn** [comment]
> @YyumeiZhang 这个changelog需要改一下，强调一下这个信息。
这个我直接加一下吧～

**Comment by YannLynn** [comment]
![image](https://github.com/user-attachments/assets/2d50b4f5-c1c7-4846-9d26-c65881df31d4)
z-resizable_handler token 是在 2.68.0-beta 版本加上的，但是在 2.68.0-beta ～ 2.68.0 版本的 @douyinfe/semi-ui 包的依赖项 @douyinfe/semi-theme-default 版本都不对（都为 2.61.0 ，该版本并不包含 token z-resizable_handler），用户可以将 @douyinfe/semi-ui 版本升级到 2.68.1 来获取最新的修复。

**Comment by boliangleung** [comment]
@douyinfe/semi-theme-default

但是我没有使用这个包，我装了2.68.1. 编译也会报错

**Comment by YannLynn** [comment]
> @douyinfe/semi-theme-default
> 
> 但是我没有使用这个包，我装了2.68.1. 编译也会报错
升级到 2.68.2 版本试试

**Comment by haoming29** [comment]
@YannLynn 可以辛苦同步更新下github的release notes吗？https://github.com/DouyinFE/semi-design/releases 这里现在2.68.1/2都没有notes

**Comment by YannLynn** [comment]
> @YannLynn 可以辛苦同步更新下github的release notes吗？https://github.com/DouyinFE/semi-design/releases 这里现在2.68.1/2都没有notes

✅ done
