### ISSUE TITLE
Slider 组件在拖动中鼠标样式支持 grabbing

### ISSUE THREAD

**Issue by Carlosfengv** [DouyinFE/semi-design#254]
### Which Component Need Enhancement 期望新增功能的组件
- Slider 滑动选择器

### What does the proposed API look like 期望支持的API
-  在拖动过程中  Cursor:  grabbing
-  [优化]  在范围选择时，对 semi-slider-handle 重合时，可以根据拖拽的方向确认 semi-slider-handle 层级
--

<br class="Apple-interchange-newline">

### Feature Description 功能描述
原型图
![cursor](https://user-images.githubusercontent.com/23092051/141429644-7734be31-0db0-455e-a0e8-45e0ffc6a5d7.png)

**Comment by pointhalo** [comment]
2.3.0-beta.0 supported
