### ISSUE TITLE
[feature] 希望提供以web components接入semi组件库的demo

### ISSUE THREAD

**Issue by TerryChenUI** [DouyinFE/semi-design#2550]

**Comment by pointhalo** [comment]
1. 我们只提供 React 版本 lib
2. WebCompoennt适配是指，我们可以在 WebComponent 中被引入使用，shadow dom下不做特殊处理的话，大部分ui lib都护会有问题的。关于这里的详细解释可以看这个文档 https://semi.design/zh-CN/start/web-components

**Comment by ycx0303** [comment]
> 1. 我们只提供 React 版本 lib
> 2. WebCompoennt适配是指，我们可以在 WebComponent 中被引入，搭配使用，shadow dom下不做特殊处理的话，大部分ui lib都护会有问题的。关于这里的详细解释可以看这个文档 https://semi.design/zh-CN/start/web-components

请问vite打包的项目要怎么使用插件转换呢？

**Comment by pointhalo** [comment]
> > 1. 我们只提供 React 版本 lib
> > 2. WebCompoennt适配是指，我们可以在 WebComponent 中被引入，搭配使用，shadow dom下不做特殊处理的话，大部分ui lib都护会有问题的。关于这里的详细解释可以看这个文档 https://semi.design/zh-CN/start/web-components
> 
> 请问vite打包的项目要怎么使用插件转换呢？

这个不在我们支持范围内，目前仅提供rspack/webpack plugin。你可以自己参考 webpack插件的原理自己实现一个对等的plugin。webpack 插件具体干了什么事情的工作原理在文档里有详细解释。

![Image](https://github.com/user-attachments/assets/d92ed28b-8016-4c90-8b64-8dc5c0a91a54)
