### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by ZinkWu** [DouyinFE/semi-design#2552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Nav or Button

### Semi Version

2.68.3

### Current Behavior

在Nav组件中点击收起侧边栏时warning
<img width="665" alt="image" src="https://github.com/user-attachments/assets/fcb0a3a2-69c8-44c8-b350-3aeeed8a80ae">

### ReproducibleCode

```markdown
<Nav
    header={{
      logo: <IconSemiLogo className="text-3xl" />,
      text: '工作台',
    }}
    footer={{
      collapseButton: true,
    }}
    selectedKeys={[pathname]}
    defaultSelectedKeys={[pathname]}
    items={items}
  ></Nav>
```

### Environment

```markdown
- OS: macOS 14.6.1
- browser: chrome 130.0.6723.71
```

**Comment by pointhalo** [comment]
已知问题。目前没有计划进行处理。
会放在后续做大版本breaking change时再做。
https://github.com/DouyinFE/semi-design/issues/201

**Comment by ZinkWu** [comment]
> 已知问题。目前没有计划进行处理。 会放在后续做大版本breaking change时再做。 #201

补充一个，Nav在收缩状态下，hover到有子菜单的item上时也会有这个warning

**Comment by pointhalo** [comment]
这是dev 阶段的warning，React 计划在19移除这个api。但是这个api对某些场景下是breaking change，我们没法在常规版本里做这种变动。
