### ISSUE TITLE
[BUG] 按文档rsbuild配置tailwind插件，构建出错

### ISSUE THREAD

**Issue by fankaiLiu** [DouyinFE/semi-design#2562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Semi Version

    "@douyinfe/semi-rspack-plugin": "^2.68.4",     "@douyinfe/semi-ui": "^2.68.4",  

### Current Behavior

semi design是一个优秀的十分有帮助的库，但是在使用中遇到了问题，来此请教一下。按照https://semi.design/zh-CN/start/tailwind 配置rspack插件
``` ts
import { defineConfig } from "@rsbuild/core";
import { pluginReact } from "@rsbuild/plugin-react";
const { SemiRspackPlugin } = require("@douyinfe/semi-rspack-plugin");
export default defineConfig({
  plugins: [pluginReact()],
  html: {
    template: "./static/index.html",
  },
  tools: {
    rspack: {
      plugins: [
        new SemiRspackPlugin({
          cssLayer: true,
        }),
      ],
    },
  },
});

```
但是构建出错
```
  × Module parse failed:
  ╰─▶   × JavaScript parsing error: Expression expected
         ╭─[1:0]
       1 │ @layer semi{@import "~@douyinfe/semi-theme-default/scss/index.scss";
         · ─
       2 │ $prefix: 'semi';
       3 │ //@import '../theme/variables.scss';
         ╰────
      
  help: 
        File was processed with these loaders:

```
是配置文件写的不对吗？

### Expected Behavior

正常构建

### Steps To Reproduce

bun create rsbuild@latest
按照tailwind插件配置

import { defineConfig } from "@rsbuild/core";
import { pluginReact } from "@rsbuild/plugin-react";
const { SemiRspackPlugin } = require("@douyinfe/semi-rspack-plugin");
export default defineConfig({
  plugins: [pluginReact()],
  html: {
    template: "./static/index.html",
  },
  tools: {
    rspack: {
      plugins: [
        new SemiRspackPlugin({
          cssLayer: true,
        }),
      ],
    },
  },
});

### Environment

```markdown
- OS:mac
```

**Comment by pointhalo** [comment]
你的loader配置不对吧，这感觉就不是 scss loader在处理，走到了 js的loader了

**Comment by fankaiLiu** [comment]
> 你的loader配置不对吧，这感觉就不是 scss loader在处理，走到了 js的loader了

感谢提醒

**Comment by hcxcomeon** [comment]
> > 你的loader配置不对吧，这感觉就不是 scss loader在处理，走到了 js的loader了
> 
> 感谢提醒

where add this code😢 i met the same problem

**Comment by zhongjiaguo001** [comment]
> > 你的loader配置不对吧，这感觉就不是 scss loader在处理，走到了 js的loader了
> 
> 感谢提醒

请问一下如何解决的，我也有这样的问题
