### ISSUE TITLE
[BUG] <title> chat组件动态更新时的滚动条问题

### ISSUE THREAD

**Issue by hey-sm** [DouyinFE/semi-design#2563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

chat

### Semi Version

2.68.3

### Current Behavior

chat 组件的动态更新数据  内容出现滚动条时  在滚动条滑动后  在输入框内输入发送  滚动条会滑动到最底部   但是直接调用onMessageSend  不通过输入框调用时  滚动条不会滑动到最底部     
![20241108151015](https://github.com/user-attachments/assets/ff9e83c1-8a1f-4e98-8119-c35485e348ae)

### Expected Behavior

不通过输入发送   直接调用onMessageSend发送新消息时始终保持滚动条滚动到最底部

### Environment

```markdown
- OS:
- browser:
```

**Comment by YyumeiZhang** [comment]
@hey-sm 如果有手动发送的消息，可以使用 ref 上的 sendMessage 方法。
![image](https://github.com/user-attachments/assets/5c027dd9-dcc1-4974-839c-f8f441a3c37c)
因为当滚动信息列表后，组件内部将【点击输入框的发送新消息】以及【sendMessage】的调用作为用户想要查看最新消息的信号，才会滚动到最底部。
单纯改变 消息对象的话，组件内部无法确定用户的意图查看被滚动到的位置的消息，还是查看最新消息。因此目前组件的行为是没有滚动。
如果你的需求中，点击后，更新的是多条消息，无法使用  sendMessage 方法的话，可以考虑手动调用 ref 上的 scrollToBottom方法来达成滚动到底部的效果
![image](https://github.com/user-attachments/assets/ba806417-ea19-4e2e-87bc-48ed6e39ae3d)
