### ISSUE TITLE
[BUG] nextjs15 turbopack throw Parsing css source code failed

### ISSUE THREAD

**Issue by majian159** [DouyinFE/semi-design#2587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Chat

### Semi Version

2.27.0

### Current Behavior

Build Error
Next.js (15.0.3) (Turbopack)
Failed to compile

./node_modules/.pnpm/@douyinfe+semi-foundation@2.70.0_acorn@8.14.0/node_modules/@douyinfe/semi-foundation/lib/es/codeHighlight/codeHighlight.css:31:57
Parsing css source code failed
  29 | .semi-codeHighlight-defaultTheme pre[class*=language-]::selection,
  30 | .semi-codeHighlight-defaultTheme code[class*=language-]::selection,
> 31 | .semi-codeHighlight-defaultTheme pre[class*=language-]::mozselection,
     |                                                         ^
  32 | .semi-codeHighlight-defaultTheme code[class*=language-]::mozselection {
  33 |   text-shadow: none;
  34 |   background: #b3d4fc;

'mozselection' is not recognized as a valid pseudo-element. Did you mean ':mozselection' (pseudo-class) or is this a typo? at [project]/node_modules/.pnpm/@douyinfe+semi-foundation@2.70.0_acorn@8.14.0/node_modules/@douyinfe/semi-foundation/lib/es/codeHighlight/codeHighlight.css:30:56
This error occurred during the build process and can only be dismissed by fixing the error.

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
Is it normal in webpack build mode? webpack and rspack are our officially supported build tools.
Turbopack is not within our support scope. We are not aware of and do not plan to study its special compilation logic.
If the problem only occurs under turopack, we do not plan to deal with it.
If possible, verify it first.

**Comment by majian159** [comment]
It is normal under webpack

**Comment by pengwenan** [comment]
我也遇到了同样的问题
Turbopack现在是内置在 Next.js 中的，能支持下吗

**Comment by YDHusky** [comment]
我使用了pnpm的[patch](https://pnpm.io/zh/cli/patch)对
./node_modules/.pnpm/DouyinFE+semi-foundation@2.70.0_acorn@8.14.0/node_modules/@douyinfe/semi-foundation/lib/es/codeHighlight/codeHighlight.css:31:57的css进行了修改并生成了对应补丁，问题就修复了，过程可以查看
https://husky.yudream.online/?p=172
