### ISSUE TITLE
[BUG] Performance issue of <Select />

### ISSUE THREAD

**Issue by imhele** [DouyinFE/semi-design#2598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select

### Semi Version

2.42.2

### Current Behavior

`<Select />` will perform `this.renderOptions(children)` during render phase, even if popover hasn't been opened yet.

This will cause a performance issue when hundreds of `<Select />`s with thousands of options are rendered at the same time, where the `createElement()` will take too much time to verify `propTypes`.

### Expected Behavior

Delay the execution of `this.renderOptions(children)` until `<Popover />` visible.

After test, time costs of rendering 100 `<Select />`s with 3000 options could reduce from 1.3s to 0.3s.

```diff
- const optionList = this.renderOptions(children);
  <Popover
-   content={optionList}
+   content={() => this.renderOptions(children)}
  >
    {selection}
  </Popover>
```

### Steps To Reproduce

1. Create 3000 options in advance.
2. Render 100 `<Select />`s with these options.

### ReproducibleCode

```markdown
import React from 'react';
import { Select, Space } from '@douyinfe/semi-ui';

class VirtualizeDemo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            optionList: Array.from({ length: 3000 }, (v, i) => ({ label: `option-${i}`, value: i })),
        };
    }

    render() {
        const { optionList, value } = this.state;
        const onChange = (nextValue) => this.setState({ value: nextValue });
        return (
            <Space vertical>
                {Array.from({ length: 100 }, (v, i) => (
                    <Select
                        key={i}
                        onChange={onChange}
                        optionList={optionList}
                        style={{ width: 180 }}
                        value={value}
                        virtualize={{ itemSize: 36 }}
                    />
                ))}
            </Space>
        );
    }
}
```

### Environment

```markdown
- OS: MacOS 15.1.1
- browser: Chrome 131.0.6778.86
```

**Comment by pointhalo** [comment]
thanks for report . we will change it in next beta version
