### ISSUE TITLE
[OverflowList] 支持自定义展示前 n 行

### ISSUE THREAD

**Issue by pandoralink** [DouyinFE/semi-design#2604]
### Which Component Need Enhancement 期望新增功能的组件
- Button

### What does the proposed API look like 期望支持的API

支持自定义传参，展示前 n 行

### Feature Description 功能描述

至少展示 1 个 tag，比如

![image](https://github.com/user-attachments/assets/4dcf728d-f34c-49c1-93ff-d56bf20684cf)

或者展示 2 行，比如

![image](https://github.com/user-attachments/assets/d8a6ec3d-6b67-4ed4-9394-66ce8f516c90)

**Comment by pointhalo** [comment]
不计划做这个feature。行不太适合用来度量，尤其是在内容宽度动态可变的情况下，有非常多的边界case。
