### ISSUE TITLE
[Table] 支持自定义 table 的排序切换顺序

### ISSUE THREAD

**Issue by meixg** [DouyinFE/semi-design#2609]
### Which Component Need Enhancement 期望新增功能的组件

Table

### What does the proposed API look like 期望支持的API

支持一个自定义顺序的 API，不知现在是否有其他方案来实现？

### Feature Description 功能描述

目前顺序是 不排序 -> 升序 -> 降序，希望可以支持 不排序 -> 降序 -> 升序，业务场景看降序需求远大于升序，每次都要切换两次。

**Comment by pointhalo** [comment]
自己受控 sortOrder就能实现。

**Comment by meixg** [comment]
> 自己受控 sortOrder就能实现。
> 
> ![image](https://private-user-images.githubusercontent.com/88709023/392210988-d7a23b35-0411-4970-95d1-0cfc23e1f1df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODMwNzMsIm5iZiI6MTczMzI4Mjc3MywicGF0aCI6Ii84ODcwOTAyMy8zOTIyMTA5ODgtZDdhMjNiMzUtMDQxMS00OTcwLTk1ZDEtMGNmYzIzZTFmMWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDAzMjYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNWYxZWM5M2VkMzMxMmM5MmUwZjI2MGRjMWFjZWNmODAxMzM1ZDRmMDJlZjUxMWFkMTU2NTliOTZlNjU5YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P-WvHo1eDxNRlcVw1gA2Y0ucpBMYU5elx7fwqNBgJgM)

请问该如何监听排序 icon 的点击事件？

**Comment by pointhalo** [comment]
table props.onChange里有这个回调
![image](https://github.com/user-attachments/assets/75fad277-7841-4903-a464-dbaaeef71941)

另外你也可以选择不使用默认的 排序icon，自己接管渲染也是ok的。这样你也可以不管回调，都自己掌控。

**Comment by meixg** [comment]
> table props.onChange里有这个回调 ![image](https://private-user-images.githubusercontent.com/88709023/392263345-75fad277-7841-4903-a464-dbaaeef71941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDMwMjIsIm5iZiI6MTczMzc0MjcyMiwicGF0aCI6Ii84ODcwOTAyMy8zOTIyNjMzNDUtNzVmYWQyNzctNzg0MS00OTAzLWE0NjQtZGJhYWVlZjcxOTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDExMTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NGQ1MTMzYjkzNzMxMWZiNTAyYjc4MDA1OWM5ZWYyNDBlMzA4NzE3NzhkZTllN2ZiYmE3NTZhMzlhOTcxZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GWpuaFagq28R270PZB5oTOe9yWx_tvPZea3xUMt2RJo)
> 
> 另外你也可以选择不使用默认的 排序icon，自己接管渲染也是ok的。这样你也可以不管回调，都自己掌控。

onChange 在点击 filter navigator 的时候，也会回调 sorter 内容，无法判断是否点击了 sorter。自己渲染该如何渲染一个与之前一样的 sorter？

**Comment by pointhalo** [comment]
> > table props.onChange里有这个回调 ![image](https://private-user-images.githubusercontent.com/88709023/392263345-75fad277-7841-4903-a464-dbaaeef71941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDMwMjIsIm5iZiI6MTczMzc0MjcyMiwicGF0aCI6Ii84ODcwOTAyMy8zOTIyNjMzNDUtNzVmYWQyNzctNzg0MS00OTAzLWE0NjQtZGJhYWVlZjcxOTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDExMTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NGQ1MTMzYjkzNzMxMWZiNTAyYjc4MDA1OWM5ZWYyNDBlMzA4NzE3NzhkZTllN2ZiYmE3NTZhMzlhOTcxZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GWpuaFagq28R270PZB5oTOe9yWx_tvPZea3xUMt2RJo)
> > 另外你也可以选择不使用默认的 排序icon，自己接管渲染也是ok的。这样你也可以不管回调，都自己掌控。
> 
> onChange 在点击 filter navigator 的时候，也会回调 sorter 内容，无法判断是否点击了 sorter。自己渲染该如何渲染一个与之前一样的 sorter？

sortOrder是受控的属性，你自己会存在state里，从onChange里拿到的不一致，那就代表点击了。这个就跟一个受控input你怎么去判断值是不是要改变是一样的。

**Comment by pointhalo** [comment]
一个受控的属性，组件怎么告诉你下一步是什么：通过onChange告诉你，至于你要不要接受这个 operation去更新受控 props，就是你可以决定的逻辑。

**Comment by meixg** [comment]
> 一个受控的属性，组件怎么告诉你下一步是什么：通过onChange告诉你，至于你要不要接受这个 operation去更新受控 props，就是你可以决定的逻辑。

不是要知道下一步是什么，而是想要知道排序按钮被点击。现在是无法通过 onChange 知道排序按钮被点击这个事情，点击 sorter、filter、navigator 都会触发 onChange。

**Comment by meixg** [comment]
> > > table props.onChange里有这个回调 ![image](https://private-user-images.githubusercontent.com/88709023/392263345-75fad277-7841-4903-a464-dbaaeef71941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDMwMjIsIm5iZiI6MTczMzc0MjcyMiwicGF0aCI6Ii84ODcwOTAyMy8zOTIyNjMzNDUtNzVmYWQyNzctNzg0MS00OTAzLWE0NjQtZGJhYWVlZjcxOTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDExMTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NGQ1MTMzYjkzNzMxMWZiNTAyYjc4MDA1OWM5ZWYyNDBlMzA4NzE3NzhkZTllN2ZiYmE3NTZhMzlhOTcxZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GWpuaFagq28R270PZB5oTOe9yWx_tvPZea3xUMt2RJo)
> > > 另外你也可以选择不使用默认的 排序icon，自己接管渲染也是ok的。这样你也可以不管回调，都自己掌控。
> > 
> > 
> > onChange 在点击 filter navigator 的时候，也会回调 sorter 内容，无法判断是否点击了 sorter。自己渲染该如何渲染一个与之前一样的 sorter？
> 
> sortOrder是受控的属性，你自己会存在state里，从onChange里拿到的不一致，那就代表点击了。这个就跟一个受控input你怎么去判断值是不是要改变是一样的。

由于受控了，所以从 onChange 里拿到的值永远与 state 存的值是一致的。

**Comment by pointhalo** [comment]
【由于受控了，所以从 onChange 里拿到的值永远与 state 存的值是一致的】是不一样的😓。如果按这个说法，那受控组件你永远都拿不到更新的值......

你类比一下受控 input怎么用。
<Input value={val} onChange={handleChange} />.   你这里handleChnge里的肯定也不是跟val一样的呀……

**Comment by pointhalo** [comment]
```diff
import React, { useState, useMemo } from 'react';
import { Table, Avatar } from '@douyinfe/semi-ui';
import * as dateFns from 'date-fns';

const DAY = 24 * 60 * 60 * 1000;
const figmaIconUrl = 'https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/figma-icon.png';


function App() {
    const [dataSource, setData] = useState([]);
+   const [sortOrder, setSortOrder] = useState('ascend');

    const getData = () => {
        const data = [];
        for (let i = 0; i < 46; i++) {
            const isSemiDesign = i % 2 === 0;
            const randomNumber = (i * 1000) % 199;
            data.push({
                key: '' + i,
                name: isSemiDesign ? `Semi Design 设计稿${i}.fig` : `Semi D2C 设计稿${i}.fig`,
                owner: isSemiDesign ? '姜鹏志' : '郝宣',
                size: randomNumber,
                status:  isSemiDesign ? 'success' : 'wait',
                updateTime: new Date().valueOf() + randomNumber * DAY,
                avatarBg: isSemiDesign ? 'grey' : 'red',
            });
        }
        return data;
    };


const columns = [
    {
        title: '标题',
        dataIndex: 'name',
        width: 400,
        render: (text, record, index) => {
            return (
                <div>
                    <Avatar size="small" shape="square" src={figmaIconUrl} style={{ marginRight: 12 }}></Avatar>
                    {text}
                </div>
            );
        },
        filters: [
            {
                text: 'Semi Design 设计稿',
                value: 'Semi Design 设计稿',
            },
            {
                text: 'Semi D2C 设计稿',
                value: 'Semi D2C 设计稿',
            },
        ],
        onFilter: (value, record) => record.name.includes(value),
    },
    {
        title: '大小',
        dataIndex: 'size',
        sorter: (a, b) => (a.size - b.size > 0 ? 1 : -1),
+        sortOrder: sortOrder,
        render: text => `${text} KB`,
    },
    { 
        title: '交付状态',
        dataIndex: 'status',
        render: (text) => {
            const tagConfig = {
                success: { color: 'green', prefixIcon: <IconTickCircle />, text: '已交付' },
                pending: { color: 'pink', prefixIcon: <IconClear />, text: '已延期' },
                wait: { color: 'cyan', prefixIcon: <IconComment />, text: '待评审' },
            };
            const tagProps = tagConfig[text];
            return <Tag shape='circle' {...tagProps} style={{ userSelect: 'text' }}>{tagProps.text}</Tag>
        }
    },
    {
        title: '所有者',
        dataIndex: 'owner',
        render: (text, record, index) => {
            return (
                <div>
                    <Avatar size="small" color={record.avatarBg} style={{ marginRight: 4 }}>
                        {typeof text === 'string' && text.slice(0, 1)}
                    </Avatar>
                    {text}
                </div>
            );
        },
    },
    {
        title: '更新日期',
        dataIndex: 'updateTime',
        sorter: (a, b) => (a.updateTime - b.updateTime > 0 ? 1 : -1),
        render: value => {
            return dateFns.format(new Date(value), 'yyyy-MM-dd');
        },
    },
];
+    const handleTableChange = (data) => {
+       console.log(data)
+        let nextSortOrder = data.sorter.sortOrder;
+        if (nextSortOrder !== sortOrder) {
+            // 你在这里可以随便按你自己想要的顺序去控制怎么切换
+           console.log(`from ${sortOrder} to ${nextSortOrder}`)
+            setSortOrder(nextSortOrder);
+       }
+    }

    useEffect(() => {
        const data = getData();
        setData(data);
    }, []);

    return <Table columns={columns} dataSource={dataSource}  onChange={(data) => handleTableChange(data)} />;
}

render(App);

```
