### ISSUE TITLE
[BUG] package.json的SideEffects里，加入lib/es/index.js的原因是什么

### ISSUE THREAD

**Issue by Sinpo96** [DouyinFE/semi-design#2612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Semi Version

2.56.1

### Current Behavior

打包时，由于副作用，lib/es/index.js中re-export的内容无法被真正使用到的模块按需导入

比如，入口页面用到了LocalProvider，业务页面用到了DatePicker
打包时，都被打在了入口bundle里
![image](https://github.com/user-attachments/assets/55b1889c-c07f-44a3-96b0-52dee31edec4)

### Expected Behavior

入口页面用到了LocalProvider，业务页面用到了DatePicker

打包时，入口只剩下LocalProvider，DatePicker被打在了业务页面中

![image](https://github.com/user-attachments/assets/96ec1fa7-a39f-43b1-bcf7-cc3927168e31)
当我在package.json的sideEffects下移除lib/es/index.js，就能把对应组件打到各自的页面bundle中

去掉sideEffects之后，入口只留下了localProvider
![image](https://github.com/user-attachments/assets/c77eddeb-b4a0-4283-a4b1-73d159919f40)
业务页面才会引入Datepicker
![image](https://github.com/user-attachments/assets/9fe4701e-bd9d-4dd1-adf9-d0bfccc7a51b)

### Environment

```markdown
- OS: 
- browser:
```

**Comment by Sinpo96** [comment]
补充下，确实tree-shaking移除了未使用的代码

但是由于副作用，shaking无法将对应模块打到对应页面中

**Comment by pointhalo** [comment]
![image](https://github.com/user-attachments/assets/52f7ab3f-baf7-4b13-886b-b1af1322e0f5)
因为本身就会有的。任何组件都会依赖global design token。这里是负责插入的。如果不声明sideeffect，这个会被摇掉，是不符合我们预期的。

另外在pc场景里，除了首屏在乎体积，更高频的做法往往是 ui-libs是单独拆chunk的，并且做dll之类的构建缓存，比较少关注某个组件跟某一个特定的page。所以这个行为对绝大多数用户来说，都是没有影响的。

**Comment by Sinpo96** [comment]
**「加sideEffects的原因」这点我理解**

看起来，base.scss由于被所有组件依赖，才放在入口，这样任何组件使用无需关注这个基础样式。

---

**『单独拆chunk』这点我感到困惑**

如果把semi-ui在项目里的实际使用内容单独拆分到一个chunk中
那么在业务加载时，即使是非当前业务所需的组件，由于要引入这个chunk，浏览器也会解析一次（尽管用户几乎察觉不到，因为时间非常短，只有毫秒级别）
这个方案并不太完美，我对这块研究不深，是否还有其他我不太了解的方案？
除了改sideEffects，webpack是否还有其他方案可以优化它以减少这部分性能消耗？

**Comment by pointhalo** [comment]
怎么拆包是跟你项目配置走的。libs它不决定这部分。
