### ISSUE TITLE
[TextArea] 是不是也可以支持preventScroll，来避免onFocus时页面滚动的问题？

### ISSUE THREAD

**Issue by rouxianmantou** [DouyinFE/semi-design#2629]
### Which Component Need Enhancement 期望新增功能的组件
- TextArea

### What does the proposed API look like 期望支持的API
preventScroll

### Feature Description 功能描述
当TextArea获取到focus时，如果TextArea行数过长，页面会滚到最上面。这个是不是可以通过支持preventScroll来实现？

### Additional information 补充说明
无。

**Comment by shijiatongxue** [comment]
TextArea 没有手动调用 focus 方法，没法传 preventScroll。

**Comment by rouxianmantou** [comment]
@shijiatongxue 不好意思，我还不太熟悉前端，我目前遇到这样一个问题，我在实现：
1. 使用TextArea编辑markdown，在用户手动点击TextArea的父元素时，我手动`inputRef.current.focus()`了一下；
2. 当用户点击其他区域，会用`MarkdownRender`来展示内容，这个时候TextArea就没了；
3. 如果`MardownRender`比较长，但是`TextArea`比较短，TextArea重新开始编辑的时候，整个区域就滚动到最上面了；

我搜了搜只搜到了preventScroll。可能是我的实现不太对。

**Comment by shijiatongxue** [comment]
> @shijiatongxue 不好意思，我还不太熟悉前端，我目前遇到这样一个问题，我在实现：
> 
> 1. 使用TextArea编辑markdown，在用户手动点击TextArea的父元素时，我手动`inputRef.current.focus()`了一下；
> 2. 当用户点击其他区域，会用`MarkdownRender`来展示内容，这个时候TextArea就没了；
> 3. 如果`MardownRender`比较长，但是`TextArea`比较短，TextArea重新开始编辑的时候，整个区域就滚动到最上面了；
> 
> 我搜了搜只搜到了preventScroll。可能是我的实现不太对。

你可以这样做。

```
inputRef.current.focus({preventScroll: true });
```

**Comment by shijiatongxue** [comment]
[preventScroll](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) 的原理是这样的，element 触发 focus 的时候(通过 element.focus())，需要给传 preventScroll 以阻止滚动。

如果 focus 是组件内部调用的，组件需要支持传 preventScroll 作为参数。

如果 focus 是你自己手动通过 ref.focus 调用的，可直接给 focus 方法传 preventScroll: true。

**Comment by rouxianmantou** [comment]
好嘞`inputRef.current.focus({preventScroll: true });`昨天我是这么干的不过没有生效，我觉得有可能因为滚动区域是局部，而不是整个页面，让这个属性并没有什么用。我再继续看一下原因，谢谢！
