### ISSUE TITLE
[semi-ui] missing peer acorn

### ISSUE THREAD

**Issue by xggz** [DouyinFE/semi-design#2630]
使用pnpm更新依赖时有个警告：
✕ missing peer acorn@"^6.0.0 || ^7.0.0 || ^8.0.0"
Peer dependencies that should be installed:
  acorn@"^6.0.0 || ^7.0.0 || ^8.0.0"

这个对项目是否有影响，因为我不加acorn好像也没有什么问题，现在我是否需要在项目上加上acorn呢

**Comment by pointhalo** [comment]
你这个x是啥，这个报错看不出什么有效信息……堆栈信息不全。
![image](https://github.com/user-attachments/assets/4e1e6945-179d-481c-b849-0a7d9ca312a6)

**Comment by xggz** [comment]
> 你这个x是啥，这个报错看不出什么有效信息……堆栈信息不全。 ![image](https://private-user-images.githubusercontent.com/88709023/395408850-4e1e6945-179d-481c-b849-0a7d9ca312a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTU0NzQsIm5iZiI6MTczNDMxNTE3NCwicGF0aCI6Ii84ODcwOTAyMy8zOTU0MDg4NTAtNGUxZTY5NDUtMTc5ZC00ODFjLWI4NDktMGE3ZDljYTMxMmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAyMTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmM2Y1OTFlOTVkODZmNjFkOTE3OTkxNjk0NjI5MTM2OTdjMWMzNDQ2YWE2NGUzMzRkYWVhYWNiNWMwNDg0ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9POwg3H5DFuC709wN7GbEKnvFKo6jg2Rc5_-INndsZ4)

 WARN  Issues with peer dependencies found
.
└─┬ @douyinfe/semi-ui 2.71.1
  └─┬ @douyinfe/semi-foundation 2.71.1
    └─┬ @mdx-js/mdx 3.1.0
      └─┬ recma-jsx 1.0.0
        └─┬ acorn-jsx 5.3.2
          └── ✕ missing peer acorn@"^6.0.0 || ^7.0.0 || ^8.0.0"
Peer dependencies that should be installed:
  acorn@"^6.0.0 || ^7.0.0 || ^8.0.0"

**Comment by pointhalo** [comment]
这是 mdx-js的底层依赖，我们控制不了。也不影响你使用。只是他们底层utils类包的 peer 而已。可以忽略。
