### ISSUE TITLE
[BUG] Select triggerRender 意外消费了用户事件

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#2641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Select

### Semi Version

latest

### Current Behavior

https://github.com/user-attachments/assets/315f42db-f646-423c-9c81-1d6a40fea604

给 demo 加上事件阻止逻辑可绕过
![image](https://github.com/user-attachments/assets/8a4409ac-a472-438b-9e5c-9dd07413f26f)

### Expected Behavior

删除时，已选中tag 不消失

### Steps To Reproduce

消失

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
这个不太适合在组件侧做，主要是无法判断这个事件用户想要还是不想要。

在本例 Demo中， TriggerRender的 tagInput、 Select内部都监听了键盘事件 backspace、enter回车；
对于 tagInput来说，回车代表将 input当前输入作为 item，添加一个 tag进去。backspace则是删除当前input字符，若input为空，则删除最后一个 item；
对于 select来说，回车代表将后选项当前 active 项选中，或打开 optionList（在聚焦但浮层未打开的情况下），backspace代表删除最后一个选项。他们都同时消费这个键盘事件。

假设如果在 select组件内增加 event 来源判断，如果是默认的 trigger内带的input，则消费 backspace、enter、上下左右等事件，使用了自定义 triggerRender就不消费这些事件。
那么无论它triggerRender return div还是什么，用户都将失去 enter、backspace等键盘能力，都影响范围并不好控制。

这里倾向于改一下 demo引导。自行stop 事件冒泡，防止重复消费。
