### ISSUE TITLE
semi-design Pro啥时候安排？就antdPro那样色的

### ISSUE THREAD

**Issue by 82pj** [DouyinFE/semi-design#271]
### Which Component Need Enhancement 期望新增功能的组件
- Button

**Comment by pointhalo** [comment]
Semi 体系内的Pro的定位与其他组件库提供的 XX Pro不太一样，其他组件库的 xx Pro一般为脚手架+页面模板（表单页、表格页、etc）集合，这类产品我们在内部之前已经有过较长时间的实践验证，没有取得太明显的收益以及复用价值。
因此我们并不计划单独提供这种类型的模板（实际上这种模板也仅仅是一些组件的使用Demo集合，社区也可以自行拼装）。

我们规划的Pro会更多地与上游设计工具进行打通，目前还在内部打磨。后续有明确的milestone后会再开放给社区。

**Comment by pointhalo** [comment]
duplicate #209
