### ISSUE TITLE
datePicker  ts定义报错

### ISSUE THREAD

**Issue by ZeroCodeLin** [DouyinFE/semi-design#274]
### Which Component 出现bug的组件
  - datePicker  

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 正常编译启动

### Actual result 实际的结果是什么
  - TS2345: Argument of type 'BaseValueType' is not assignable to parameter of type 'string'.
  - TS2569: Type 'Set<any>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```


```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by shijiatongxue** [comment]
可以提供下报错的具体位置吗？（哪个文件，哪一行）❤

**Comment by ZeroCodeLin** [comment]
> 可以提供下报错的具体位置吗？（哪个文件，哪一行）❤

你好，我这边使是这两个文件，2.0.8版本

@douyinfe\semi-foundation\datePicker\foundation.ts(285,40)
@douyinfe\semi-foundation\datePicker\monthsGridFoundation.ts(528,38)

**Comment by shijiatongxue** [comment]
> > 可以提供下报错的具体位置吗？（哪个文件，哪一行）❤
> 
> 你好，我这边是这两个文件，2.0.8版本
> 
> @DouyinFE\semi-foundation\datePicker\foundation.ts(285,40) @DouyinFE\semi-foundation\datePicker\monthsGridFoundation.ts(528,38)

第一个报错我们改下。
第二个报错可以在 tsconfig 文件里配置下。`"downlevelIteration": true`。我们暂不做处理。❤

**Comment by shijiatongxue** [comment]
v2.1.0-beta.0 fixed
