### ISSUE TITLE
有考虑做兼容移动端嘛  我觉得你们的这个ui库 很好看 

### ISSUE THREAD

**Issue by lovesL** [DouyinFE/semi-design#279]
### Which Component Need Enhancement 期望新增功能的组件
- Button

**Comment by boomboomchen** [comment]
响应式和跨端是semi后续的一个重点考虑方向，具体的规划后续会同步给大家哈

**Comment by lovesL** [comment]
> 响应式和跨端是semi后续的一个重点考虑方向，具体的规划后续会同步给大家哈

期待 +1

**Comment by shijiatongxue** [comment]
此问题迁移到 discussion，大家可以去这里讨论与代码无关的话题 ❤
