### ISSUE TITLE
可以在组件官网添加全局的查找框吗？

### ISSUE THREAD

**Issue by baiziyu-fe** [DouyinFE/semi-design#28]
# 全局查找
> 希望能提供一个全局查找的输入框，可以支持快速查找api和组件名称就行

- 1. 希望能支持树状展示搜索结果，例如搜索"field"
    - Form
        - field: 表单的……
- 2. 希望加入一些类型定义的链接查找
![image](https://user-images.githubusercontent.com/77950278/138823142-43c43b2b-e656-4d94-92c4-6db2de982449.png)

通过点击这个类型链接直接查看详情

**Comment by shijiatongxue** [comment]
duplicate issue with #17

**Comment by pointhalo** [comment]
Originally planned to access algolia, but it has a limit on the frequency of calls, which cannot better meet the pv of this site.
We are now based on our own internal search service, so the delivery is much later than originally planned.
We made an update last Friday and it's available now🔍 . Support Chinese and English search and recent browsing, search history.
Hope this can improve your experience🌟
