### ISSUE TITLE
不支持vite嗎？打包各種報錯

### ISSUE THREAD

**Issue by LRboyz** [DouyinFE/semi-design#283]
node_modules/@douyinfe/semi-foundation/datePicker/monthsGridFoundation.ts:617:26 - error TS2532: Object is possibly 'undefined'.

617                     if (!this._adapter.isAnotherPanelHasOpened('rangeStart') || !rangeEnd) {
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@douyinfe/semi-foundation/datePicker/monthsGridFoundation.ts:617:26 - error TS2722: Cannot invoke an object which is possibly 'undefined'.

617                     if (!this._adapter.isAnotherPanelHasOpened('rangeStart') || !rangeEnd) {
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@douyinfe/semi-foundation/datePicker/monthsGridFoundation.ts:618:25 - error TS2722: Cannot invoke an object which is possibly 'undefined'.

618                         this._adapter.setRangeInputFocus('rangeEnd');
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@douyinfe/semi-foundation/datePicker/monthsGridFoundation.ts:631:39 - error TS2322: Type 'Date | null' is not assignable to type 'Date'.
  Type 'null' is not assignable to type 'Date'.

631             let date: [Date, Date] = [startDate, endDate];
                                          ~~~~~~~~~

node_modules/@douyinfe/semi-foundation/datePicker/monthsGridFoundation.ts:631:50 - error TS2322: Type 'Date | null' is not assignable to type 'Date'.
  Type 'null' is not assignable to type 'Date'.

631             let date: [Date, Date] = [startDate, endDate];
                                                     ~~~~~~~

**Comment by pointhalo** [comment]
vite 版本，tsconfig麻烦提供一下~

**Comment by pointhalo** [comment]
我这边用vite新建了一个ts项目，无法复现你的问题。如果方便地话，麻烦提供更多的上下文。

**Comment by DaiQiangReal** [comment]
我們是官方支持Vite構建的，可以提供下你的 semi 版本和 ts vite 配置文件嗎？

**Comment by Xwudao** [comment]
很简单，我觉得你的"build"命令是："tsc && vite"

上面的警告是tsc的吧

应该不影响编译结果，但是过程很多警告...

**Comment by Xwudao** [comment]
> 我們是官方支持Vite構建的，可以提供下你的 semi 版本和 ts vite 配置文件嗎？

你可以试一下，最新版本 `"@douyinfe/semi-ui": "^2.0.8",`， 然后打包命令是："tsc && vite build"

应该可以复现了

**Comment by pointhalo** [comment]
直接原因
1、是 datepicker里的index.d.ts里直接引用了  semi-foundation 而不是 semi-foundation/lib/es/xxx 里的interface，然后这里在strict: true时也被检查了，对函数参数双向协变进行了严格校验。
2、部分interface的定义不够严谨，strict:true，且没有skipLibCheck 时会有error。

下个patch版本修复一下。

**Comment by pointhalo** [comment]
可以试下 v2.1.0-beta.3 ，所有semi自身的类型定义问题已修复。

但由于有两个我们依赖的上游第三方包的类型定义存在问题，如下图（我们也无法直接修复）比如resize-observer-polyfill 。所以需要将ts.config.json的skipLibCheck置为true，否则依然会有以下两个error。
![image](https://user-images.githubusercontent.com/88709023/143245532-eb8f5a63-fd47-497b-a12c-1ababfbea2c2.png)
