### ISSUE TITLE
rowspan cant work with virtualized

### ISSUE THREAD

**Issue by WeiShengv99** [DouyinFE/semi-design#290]
### Which Component 出现bug的组件
  - Table

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - rowspan can work with virtualized table

### Actual result 实际的结果是什么
  - [demo](https://codesandbox.io/s/react-or-react-query-bug-version-2-forked-wwolt?file=/src/example.js)

### Steps to reproduce 复现步骤
  - toggle virtualized props in codesandbox

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景
- i have a table , it  has  fixed column / header Group/  rowSpan  features.

**Comment by shijiatongxue** [comment]
你好，虚拟化 Table 暂不支持 rowSpan。原因是虚拟化列表的 cell 是 div，没有行列合并能力。❤

**Comment by WeiShengv99** [comment]
@shijiatongxue 

我还有另外一个问题
i have other problem with Table component

这是demo [codesandbox](https://codesandbox.io/s/semi-design-bug-column-resize-egc6c?file=/src/example.js)
this is demo


resize column 如果我把它扩大到超出` scroll x `，样式会有点不符合预期
resize column work not good when i let it grow to  overflow  prop ` scroll x`


![image](https://user-images.githubusercontent.com/35689628/142800775-c2139b7b-51e1-4522-be74-bb3ac8dbcc2b.png)

or  its my fault, what should i do ?

**Comment by shijiatongxue** [comment]
> 
上面这个 demo 确实对不齐。

不推荐虚拟化表格和 resizable 一起使用。resizable 会改变列宽，这无法与 scroll.x 良好兼容。Table 无法根据 scroll.x 计划剩余宽度如何分配。建议虚拟化表格用在固定列宽的场景。

**Comment by shijiatongxue** [comment]
> @shijiatongxue 这里还有一个问题 当数据是空的时候,右边样式不正确 （还是用那个demo就可以看到，当然取消了 列合并 和 resize 功能） ![image](https://user-images.githubusercontent.com/35689628/144025960-40f85878-68a0-4994-a3f7-ce4e0430c284.png)

是的，这个问题可以复现。我们修下。

**Comment by shijiatongxue** [comment]
https://github.com/DouyinFE/semi-design/issues/441 跟进 border bug
