### ISSUE TITLE
什么时候会支持 a11y 呢，这个很重要，国内大部分组件库支持的都不好

### ISSUE THREAD

**Issue by EchoZhaoH** [DouyinFE/semi-design#292]
### Which Component Need Enhancement 期望新增功能的组件
- A11y

**Comment by shijiatongxue** [comment]
已存在相同 issue ，可以在 #205 补充你对 a11y 的期望。组件部分，a11y 预计在 v2.2 版本有比较好的支持。站点可能会晚于这个时间。

**Comment by pointhalo** [comment]
Update latest progress ，for more info please refer to https://github.com/DouyinFE/semi-design/issues/205#issuecomment-1039999713
