### ISSUE TITLE
有构建后台模板工具吗

### ISSUE THREAD

**Issue by YC725968** [DouyinFE/semi-design#296]
### Which Component 出现bug的组件
  - Button

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 

### Actual result 实际的结果是什么
  - 

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```
class Demo extends React.component {

    render() {
        return (
            <Button>bug</Button>
        )
    }

}

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
如果是feature request可以详细描述你的期望需求。如果是问题咨询，可以加入我们的用户群。通过issue方式咨询也可以，但Issue内容请尽量跟标题切合，简单抛个标题我们无法得知想要的是什么，上下文是什么。
