### ISSUE TITLE
[Tree] typo:'ExpanedOtherProps' should be 'ExpandedOtherProps'

### ISSUE THREAD

**Issue by Heasn** [DouyinFE/semi-design#297]
### Which Component 出现bug的组件
  - Tree

### semi-ui version
  - 2.0.8
    
### Expected result 期望的结果是什么
  - ExpandedOtherProps

### Actual result 实际的结果是什么
  - ExpanedOtherProps

**Comment by boomboomchen** [comment]
感谢反馈，我们修一下

**Comment by boomboomchen** [comment]
2.1.0-beta.1 fixed
