### ISSUE TITLE
关于semi.design的一点小建议

### ISSUE THREAD

**Issue by codthing** [DouyinFE/semi-design#298]
我打开看了一眼文档，立马关掉了。
只因为React的写法还用Class，如果不看github的创建时间，还以为是五六年前的产品呢。
hooks那么好用直观，为何还在用class，是不是特别喜欢写一堆模板文件？

**Comment by pointhalo** [comment]
可以多点几个文档看看，这里我们是根据实际用例灵活决定，并不会限死Demo一定要写hooks类型或者class类型。简单类型写hooks demo更方便，一些复杂case 如果以hooks写法，对于API的展示示例而言可能更不直观。

组件的Demo文档是hooks还是class并不影响使用，它只是用于展示这个props API具体是怎么使用的。

hooks与class并无绝对优劣之分，对于react开发者来说两者是可以随时转换的。
