### ISSUE TITLE
[Docs] Added the usage instructions and Demo of using the dark mode of partial DOM

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#301]
### Which document do you want to be improved
- DarkMode
   - https://semi.design/zh-CN/start/dark-mode
   - https://semi.design/en-US/start/dark-mode

### Feature Description
- Currently only shows how to switch to dark mode, but this is for global page.  Hope there are instructions and code demos for only switching a certain DOM element on the page to dark mode.

**Comment by shijiatongxue** [comment]
Add later
