### ISSUE TITLE
对于 Cascader 级联选择器中，对末级节点支持整行热区

### ISSUE THREAD

**Issue by Carlosfengv** [DouyinFE/semi-design#302]
### Which Component Need Enhancement 期望新增功能的组件
-  Cascader

### Feature Description 功能描述
Rt: 对于 Cascader 级联选择器中，对末级节点支持整行热区;
目前对Cascader 末级的热区在 Checkbox 上，**希望可以点击整行** (.semi-cascader-option) 实现CheckBox的 选中/反选 操作

![image](https://user-images.githubusercontent.com/23092051/142821085-fbf19343-2091-4b7e-9167-67275d57016e.png)

**Comment by pointhalo** [comment]
2.2.0-beta.0
