### ISSUE TITLE
希望官方支持 Vue 版本

### ISSUE THREAD

**Issue by liamwang** [DouyinFE/semi-design#311]
semi-design 的设计非常漂亮，优质且精美，很想把它应用到我们下个版本的通用管理系统模板中。但 semi-design 目前只有 React 版本，而我们团队大多数开发者更熟悉 Vue。考虑到全团队（包括熟悉 Vue 的后端开发）的学习成本，无耐计划只能搁置。

看了关于 semi-design 支持 Vue 的相关 Issue，得知抖音前端内部支持 Vue 的可能性极小，很有可能交给外部去实现。关于这一点，我想表达一下个人的看法：

- 第一，交给外部去实现过程将会非常慢长，人员不稳定，很难吸引更多的优秀开发者参与，除非有社区比较有声望的知名大佬牵头。
- 第二，目前 UI 框架众多，不论是官方和外部实现，都有不少已经发展成熟，在这种竞争情况下，依靠外部实现的 semi-design 很难有较好的采用率，更难后来居上。
- 第三，考虑到采用率、成熟度、稳定性和后续的支持维护，团队项目的技术选型肯定还是优先考虑有官方维护的开源框架或者已经非常成熟的外部实现，而依靠外部实现的 Vue 版本很难在这几方面短期内取得市场的信赖。

所以就目前的市场环境来看，我个人认为依靠外部实现 semi-design 的 Vue 版本没有太大的意义。只有官方实现 Vue 版本，才能真正吸引更多原先熟悉 Vue 的开发团队采用，也会吸引更多开发者参与到开源贡献中，甚至会反过来一定程程度的扩大 semi-design 的 React 版本影响范围。

以上个人浅见，希望得到采纳。

感谢抖音前端团队和众多开源贡献者的付出！

**Comment by Eve-Sama** [comment]
确实说的有些道理. 但是官方应该就是不会做的, 他们不是不知道vue现在用的人多, 但是因为他们做开源是拿工资的, 不是个人开源项目, 除非抖音决策层支持, 否则也是拿不出精力做这个事情的.

**Comment by pointhalo** [comment]
@liamwang 首先非常感谢你的建议以及对 Semi Design的认可。关于不同框架的支持以及未来一段时间的roadmap，在我们[官方介绍文档里](https://github.com/DouyinFE/semi-design/blob/6271ca78b491f2bdf0306d5d621293e621997ecd/content/start/introduction/index.md?plain=1#L79)其实已经有过说明。

【我们的工作重点依然是React体系。没有计划去重新实现一个Vue版本】

这个决策主要出于以下几个因素：

- Semi 本身的 [Foundation / Adapter的架构划分](https://bytedance.feishu.cn/docs/doccnTgc0iGOVPubHZkwPpxXSNh)已经能保证不同框架实现的一致性 以及 低成本移植能力。
   - 一致性：
      由于组件所有核心交互逻辑、css都已经在semi-foundation中，相当于开发范式已经固定，不管是我们团队自身实现还是社区实现，最终呈现效果、质量都是能达到一致的。  基于semi-foudation实现的不同体系的semi 组件，质量与功能丰富度都取决于我们官方维护的semi-foundation。这个是与其他design system最大的区别。   
   - 移植成本  
     社区实现其他框架版本的 semi 成本是较低的，只需要写一遍render层 template即可。

- 现阶段我们团队本身依然有很多需要聚焦人力突破的方向，包括但不限于 Semi 组件本身定制能力的增强、Semi DSM的打磨（Become a more flexable design system）、Semi D2C等等，这些都需要我们团队投入大量人力去推进。

- 期望有更面向未来的路径
   我们其实从一开始就想搞一个WebComponent的组件库，彻底解决技术栈的限制。但是由于现阶段生态实在不够成熟，我们的人力也不允许做这种大规模的探索，F/A方案实际上是我们的一个降级，目标是满足我们自身现有业务的同时，如果时机成熟，我们能具备快速迁移的能力。我们会更倾向于通过未来基于WebComponent 方向去探索实现，而不是现阶段去将每个框架都重新实现一遍。

**Comment by pointhalo** [comment]
duplicate #56 #162
related #243

**Comment by Eve-Sama** [comment]
很不戳! 格局大了! 加油加油.

**Comment by lizy0329** [comment]
Foundation 层有相关的开发文档吗？我们需要自建 Vue 组件库 @Eve-Sama

**Comment by zhongbo320104** [comment]
我有尝试用vuera去接入semi，但是遇到问题了。。。Popconfirm 打包后没法用，本地是可以的，有点劝退了。。。有能解答的大佬吗？为什么

**Comment by reorx** [comment]
没有 Vue 版本是我选择 Semi 而非 Arco 的原因，希望开发者团队继续坚持初心，做自己团队需要用的东西。我坚信只有聚焦和吃自己的狗粮才能产出精品，为了开源 KPI 而去兼容其他框架是不可持续的。

**Comment by shen774411223d** [comment]
> 国内互联网环境，用 React 也只是大厂用的多，从各大招聘网站也能知道，这么好的一套 UI 没有一个好的受众群体确实很可惜，也可能官方支持受众国外或者本身产品只限于 React 而又没有任何资金支持 Vue 版本，其实 Vue3 完善很多了，Vue 已经大势所趋了

大势所趋指的是vue3借鉴react的思想？ 既然都是借鉴了为什么不用react？
