### ISSUE TITLE
select 组件内多选超出部分+N ，增加 hover +n 能用 poover 显示具体内容

### ISSUE THREAD

**Issue by Ramones2333** [DouyinFE/semi-design#317]
### Which Component Need Enhancement 期望新增功能的组件
- select

### Feature Description 功能描述
select 组件内多选超出部分+N ，业务方希望能增加 hover「 +n」后， 用 poover 显示出具体隐藏内容
![image](https://user-images.githubusercontent.com/46084033/143394370-2b5f6e57-54fe-4d2b-be81-05e10cf26d6c.png)

### Additional information 补充说明
当前 级联组件内同场景下是有的，如图所示
![image](https://user-images.githubusercontent.com/46084033/143394488-d3a8163b-435e-4f70-b29d-dfdf37e1bed0.png)

**Comment by pointhalo** [comment]
需要确定下Popover的这里的换行逻辑，是否有最大宽度限制，是否有最大高度限制 @Ramones2333

**Comment by pointhalo** [comment]
v 2.22.0-beta.0 支持
