### ISSUE TITLE
[Select] renderSelectedItem 返回的 isRenderInTag 为 false 时会报 key 的 warning

### ISSUE THREAD

**Issue by boomboomchen** [DouyinFE/semi-design#320]
### Which Component 出现bug的组件
  - Select

### semi-ui version
  - latest
    
### 问题描述
  - renderSelectedItem 返回的 isRenderInTag 为 false 时，需要用户给返回的content指明key，否则会报warning。希望用户可以不用指明key。

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
2.2.0-beta.0
