### ISSUE TITLE
[Docs] Document optimization

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#321]
### Documents which need improve
- Getting Started
  - 模块化使用：增加按需加载会自动被处理，无需手动配置任何插件的说明（可以直接链接到FAQ）

- Design Token
  - 组件【设计变量】模块，标题右侧可以增加<IconHelp />，点击后跳转使用说明文档
  - https://semi.design/zh-CN/basic/tokens 页面，增加如何使用style-lint工具为现有系统一键匹配semi颜色变量的说明 @shijiatongxue 

- 命名统一
   - 主题管理平台、主题商店 -> Semi DSM / Semi 设计系统管理站点 

- Layout
  - 增加FAQ，说明 Layout组件只控制布局，不包含边框、背景色等样式

- 路由为 start/xxx  相关的页面，右侧也增加anchor 目录快速跳转
![image](https://user-images.githubusercontent.com/88709023/143408860-59bff53d-e87a-4431-b164-ea8be45a8ac8.png)

**Comment by pointhalo** [comment]
- Add badge about size of dist (semi.js & semi.min.js) in readme  & getting start - umd usage

**Comment by shijiatongxue** [comment]
![image](https://user-images.githubusercontent.com/26477537/143855004-3cadbcec-c5ae-4d97-a1b8-fcc86dc79cd3.png)
