### ISSUE TITLE
Form 组件中 label extra 中为 Icon时 ，文字与Icon 没有对齐

### ISSUE THREAD

**Issue by Carlosfengv** [DouyinFE/semi-design#324]
### Which Component 出现bug的组件
  - Form 

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
 - 视觉上，期望Icon 与标题文字水平垂直居中对齐
![image](https://user-images.githubusercontent.com/23092051/143532922-a5278c49-445b-4216-ad23-78c1b9189886.png)

### Actual result 实际的结果是什么
  - 
![image](https://user-images.githubusercontent.com/23092051/143532962-8d19edcb-59e0-4655-8232-7b1ebbafe0ce.png)

**Comment by shijiatongxue** [comment]
v2.8.0 fixed
