### ISSUE TITLE
InputNumber webstorm无法提示属性

### ISSUE THREAD

**Issue by Xwudao** [DouyinFE/semi-design#327]
### Which Component 出现bug的组件
  - InputNumber

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 提示属性

### Actual result 实际的结果是什么
  - 不提示属性

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```
<InputNumber step={4} />

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

![Snipaste_2021-11-29_11-50-53](https://user-images.githubusercontent.com/31327868/143814848-992ce019-84a1-453b-9db9-a6621f524d8d.png)

![22](https://user-images.githubusercontent.com/31327868/143814843-56461cb6-07c5-4410-bee2-c252112c4f27.png)

**Comment by DaiQiangReal** [comment]
我们正在修复

**Comment by shijiatongxue** [comment]
v2.1.2 fixed
