### ISSUE TITLE
[TreeSelect]When filterTreeNode is turned on, expandedKeys is not completely controlled

### ISSUE THREAD

**Issue by boomboomchen** [DouyinFE/semi-design#328]
### Which Component 出现bug的组件
  - TreeSelect

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - expandedKeys is not completely controlled

### Actual result 实际的结果是什么
  - expandedKeys is completely controlled

### Steps to reproduce 复现步骤
  - 1. Set expandedKeys to an empty array
  - 2. open filterTreeNode, and input value that is included some child-option
  - 3. parent-option will be expanded

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
fix 2.7.0-beta.0
