### ISSUE TITLE
Unused css is also packaged in, when use semi in vite 

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#337]
### Which Component 出现bug的组件
  - Semi

### semi-ui version
  - 2.1.1
    
### Expected result 期望的结果是什么
  - When only the button is used, only the button is included in the css of the build product, and no other components are included

### Actual result 实际的结果是什么
  - The css of all components will be packaged when run `npm run build`

### Additional information 补充说明
- Using the same code, webpack is normal

**Comment by pointhalo** [comment]
### Additional information

- vite.config.js
```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()]
})
```


- package.json
```
{
  "name": "vite-ts-semi2.x",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "@douyinfe/semi-ui": "2.1.2",
    "react": "^17.0.0",
    "react-dom": "^17.0.0"
  },
  "devDependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@vitejs/plugin-react": "^1.0.0",
    "typescript": "^4.3.2",
    "vite": "^2.6.4"
  }
}

```

- app.tsx
```
import React, { useState } from 'react'
import logo from './logo.svg'

import { Button } from '@douyinfe/semi-ui';                                   // not work
// import Button from '@douyinfe/semi-ui/lib/es/button/index';   // work

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <header className="App-header">
        {/* <Input style={{ width: 300 }} /> */}
        <Button>Test</Button>
      </header>
    </div>
  )
}

export default App

```

**Comment by JokerQyou** [comment]
Is there any ETA for a solution to this bug? I also suspect unused JS is also bundled into final product when using vite.

**Comment by pointhalo** [comment]
> Is there any ETA for a solution to this bug? I also suspect unused JS is also bundled into final product when using vite.

js is not affected, you can check through the final bundled product.  (eg import button only)

**Comment by pointhalo** [comment]
https://github.com/vitejs/vite/issues/4389
When the sideeffect contains css, webpack and vite have different processing logic.

Personally, I think this behavior is a controversial point, and vite does not remove files with side effects from a certain point of view.

semi does not plan to make changes on the component side for the time being, otherwise it will cause breaking changes in webpack usage

**Comment by pointhalo** [comment]
i test with vite `v2.6.4`&  v3 again. 
The test found that the vite of v3, the packaging behavior has been consistent with webpack.
This issue can be closed.
