### ISSUE TITLE
新增 Image 组件

### ISSUE THREAD

**Issue by Tenodec** [DouyinFE/semi-design#344]
### 没有Image组件啊。arco都有的呢
- Image

**Comment by DaiQiangReal** [comment]
可以详细描述下你需要的功能吗？ 可以重点描述下原生 img 标签不是很容易实现，但是业务需求频繁的 feature，便于我们分析场景，设计api

**Comment by JunfengHu1996** [comment]
图片组件，可以点击预览

**Comment by laozhu** [comment]
预览功能比较重要，包括一张图或者一组图的预览。

**Comment by 13751139402** [comment]
+1

**Comment by pointhalo** [comment]
support v2.20.0-beta.0
