### ISSUE TITLE
代码内部传参

### ISSUE THREAD

**Issue by Lindysen** [DouyinFE/semi-design#345]
https://github.com/DouyinFE/semi-design/blob/alpha/packages/semi-foundation/tree/foundation.ts#L776

**Comment by Lindysen** [comment]
![image](https://user-images.githubusercontent.com/33708359/144381332-211fad7f-4ab1-4e28-ac65-c880b2f15088.png)

**Comment by shijiatongxue** [comment]
欢迎提个 PR  解决这个问题 ❤

**Comment by pointhalo** [comment]
@boomboomchen 单独发个patch修一下这个问题吧。

**Comment by pointhalo** [comment]
v2.1.5
