### ISSUE TITLE
【Icon】希望 icon 大小受父级 font-size 控制

### ISSUE THREAD

**Issue by tank0317** [DouyinFE/semi-design#360]
### Which Component Need Enhancement 期望新增功能的组件
- Icon

### What does the proposed API look like 期望支持的API
Icon size 添加 'inherit' 枚举值

### Feature Description 功能描述
当 icon 设置 size='inherit'，此时 icon 大小受父级 font-size 控制

### Additional information 补充说明
demo
```
<IconStar size='inherit' />
```

**Comment by shijiatongxue** [comment]
![image](https://user-images.githubusercontent.com/26477537/146748144-8654329f-f19b-4f11-98c2-edddbba0c6ad.png)
