### ISSUE TITLE
umd引用的时候网页所有的下拉列表框显示层错位了

### ISSUE THREAD

**Issue by aiwenForGit** [DouyinFE/semi-design#363]
下拉列表框的位置都是错的，默认都被显示再表格的最下面
![image](https://user-images.githubusercontent.com/241340/144703077-2a461aec-8f93-4726-9a69-6a329ed36d21.png)

**Comment by aiwenForGit** [comment]
`<!DOCTYPE html>
    <html lang="zh-cn">
    <head>
        <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
       <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
       <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>

       <script src="https://unpkg.com/@douyinfe/semi-ui@2.0.0/dist/umd/semi-ui.min.js"></script>
       <link rel="stylesheet" href="https://unpkg.com/@douyinfe/semi-ui@2.0.0/dist/css/semi.css">

 <script src="https://unpkg.com/@douyinfe/semi-icons@latest/dist/umd/semi-icons.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@douyinfe/semi-icons@latest/dist/css/semi-icons.css">
<script src="https://unpkg.com/@douyinfe/semi-illustrations@latest/dist/umd/semi-illustrations.min.js"></script>

    </head>
        <body>
        <div id="root">1</div>
    </body>
        <script type="text/babel">
 	const { AutoComplete,Input, Toast, Icon, Form, Col, Row, Button } = SemiUI;
    const { IconUpload,IconHome } = SemiIcons;
    const { IllustrationConstruction } = SemiIllustrations;
    const types = [<IconSearch />, <IconHelpCircle />, <IconAlertCircle />, <IconMinusCircle />, <IconPlusCircle />, <IconPlus />, <IconRefresh />];


    ReactDOM.render(   
        <div><AutoComplete
            data={[1, 2, 3, 4]}
            size="small"
            placeholder={'small'}
            style={{ width: 200 }}
        ></AutoComplete>
        <br />
        <br />
        <AutoComplete
            data={[1, 2, 3, 4]}
            size="default"
            placeholder={'default'}
            style={{ width: 200 }}
        ></AutoComplete>
        <br />
        <br />
        <AutoComplete
            data={[1, 2, 3, 4]}
            size="large"
            placeholder={'large'}
            style={{ width: 200 }}
        ></AutoComplete>
        </div>
 , document.getElementById("root"));
</script>

    
</html>`

**Comment by aiwenForGit** [comment]
这是代码

**Comment by pointhalo** [comment]
umd产物的css样式 v2.0.0与v2.0.1有一些问题。可以直接使用最新的  2.1.4，不会有浮层定位错误的问题
