### ISSUE TITLE
Tree 组件右键菜单冒泡问题

### ISSUE THREAD

**Issue by GoldSubmarine** [DouyinFE/semi-design#364]
### Which Component 出现bug的组件
  - Tree

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 右击tree组件的某一个节点，自定义右键菜单

### Actual result 实际的结果是什么
  - 虽然提供了 onContextMenu 方法，但是因为某些原因，我的现有需求方案是通过冒泡到 body 元素，在body元素捕获右击事件的，可是通过 `onContextMenu={e => console.log(e.isPropagationStopped())}`，查看到当前组件默认是阻止冒泡的

**Comment by boomboomchen** [comment]
我比较倾向于保留这里的阻止冒泡。
一是兼容之前版本，二是在另外一些使用场景中，用户可能并不希望触发冒泡。
这里用户如果希望冒泡到body元素上，触发body的右键点击事件，可以考虑将事件处理放到 onContextMenu 回调来做？
@pointhalo zhijing 帮忙看一下？

**Comment by GoldSubmarine** [comment]
我觉得 dom 默认的行为最好能够保留。

> 二是在另外一些使用场景中，用户可能并不希望触发冒泡

如果用户不希望触发冒泡，应该手动禁止，就像写原生 html, js 那样，如果组件内部禁止冒泡，就会发生我上面说的这种情况或者其他的业务场景，的确需要冒泡，但是却无法做到。

我现在在 body 捕获右击事件，为了兼容这里的不冒泡，也可以通过 store 去触发菜单，做也可以做，只是没有那么舒服。

> 一是兼容之前版本

如果对之前版本有一些 api 上的明显破坏，那可能暂时的确改不了，如果只是默认行为有所改变，我觉得还是可以尝试更改一下的。

**Comment by boomboomchen** [comment]
好的，目前有外部用户正在修复，我们尽快上哈

**Comment by pointhalo** [comment]
fix v2.1.5
