### ISSUE TITLE
新增聊天组件

### ISSUE THREAD

**Issue by uvd** [DouyinFE/semi-design#366]
### Which Component Need Enhancement 期望新增功能的组件
- Chat

### What does the proposed API look like 期望支持的API
大概像这个
https://quasar.dev/vue-components/chat

### Feature Description 功能描述
看你们截图里面的聊天系统的就很漂亮

**Comment by pointhalo** [comment]
暂不计划提供。这个在我们内部是以物料形式存在的，而不是基础组件。
主要考虑到，这个模块，样式与交互上均带有很强的业务特性，往往都需要进行二次修改（不仅是通过design token层次能满足的定制），因此感觉不太适宜作为原子组件提供默认的交互/样式约束。
