### ISSUE TITLE
新增开箱即用的Pro admin

### ISSUE THREAD

**Issue by uvd** [DouyinFE/semi-design#367]
### Which Component Need Enhancement 期望新增功能的组件
- Admin

### What does the proposed API look like 期望支持的API
类似隔壁的那个

### Feature Description 功能描述
开箱即用的后端模板 方便后端狗写前端

**Comment by cuibty** [comment]
附议

**Comment by pointhalo** [comment]
duplicate #271 #209

不计划单独提供这类模板产品。会与上下游工具链打通后，与更多设计资源联动，作为其中一部分能力提供。目前在内部推进中，能力得到验证成熟后再对外提供。

**Comment by pointhalo** [comment]
如果是单纯的admin系统page demo集合，社区里有一些个人开发者根据自己需求搭建的示例，例如https://github.com/xieyezi/semi-design-pro

**Comment by vipwan** [comment]
咋说呢 如果能提供一个官方的脚手架 对社区吸粉很有帮助 尤其是前端菜菜 :)  👀

**Comment by pointhalo** [comment]
> 咋说呢 如果能提供一个官方的脚手架 对社区吸粉很有帮助 尤其是前端菜菜 :) 👀

我们的目标是做设计链路与研发链路的打通。其中会包括 Design System Management、Code to Design、Design to Code。
而项目模板类的template或者脚手架不在我们的规划路线里。后续也没有计划推进。

这里面能跟模板相关的只有 Design to Code，但这个更多是关于 page 或者 block 级别的模板。不会做项目脚手架级别的模板。

项目脚手架级别的模板的可复用性、定制性都太弱，多人团队中往往都会自己再封一个跟自身业务属性强相关的模板。我们来提供这类产品的ROI 其实非常低。如果一个产品做出来后，我们自己内部都不用的话，即使做了也没法保证有足够的人力去维护。

**Comment by mitoop** [comment]
2024年 有计划了吗 我们后端能用用 semi design 吗

**Comment by yqcs** [comment]
2025年 有计划了吗 我们后端能用用 semi design 吗

**Comment by chenzhiguo** [comment]
2026年有计划了吗？没有脚手架，会劝退很多小白

**Comment by YYInTheDark** [comment]
有计划了吗？本来看好的组件的，但是admin框架，直接劝退了
