### ISSUE TITLE
源码中同时出现了 lodash 和 lodash-es 的引用

### ISSUE THREAD

**Issue by xiguaxigua** [DouyinFE/semi-design#371]
从 package.json https://github.com/DouyinFE/semi-design/blob/main/package.json#L63 中看应该是想统一引 `lodash-es` ，不过源码中同时有 lodash 和 lodash-es 的引用

https://github.com/DouyinFE/semi-design/blob/main/packages/semi-ui/dropdown/index.tsx#L18

https://github.com/DouyinFE/semi-design/blob/main/src/components/IconList/index.jsx#L5

**Comment by pointhalo** [comment]
说下背景吧。
这里是一个monorepo项目。包含组件库的源代码以及一些plugin（eg：semi-webpack-plugin、或者文档站gatsby ssg场景消费的代码）的源码，因此会存在esm、cjs两种不同的使用场景。
前者prefer lodash-es，后者lodash。

组件库本身的源码（即semi-foundation、semi-ui）之前是统一使用lodash-es的，为了更方便地构建esm产物。
然后为了支持Next.js中消费Semi（详见 #245 ），又将组件库的中的lodash-es统一回退到了lodash（由于next也会走一次ssg，cjs产物中如果保留lodash-es的引用，会有相关报错 https://github.com/vercel/next.js/issues/706）
