### ISSUE TITLE
ButtonGroup+Popconfirm theme丢失

### ISSUE THREAD

**Issue by nieoding** [DouyinFE/semi-design#382]
### Which Component 出现bug的组件
  - ButtonGroup
  - Popconfirm

### semi-ui version
  - 2.1.1
    
### Expected result 期望的结果是什么
  - ButtonGroup的theme能影响到所有子按钮

### Actual result 实际的结果是什么
  -  如果子按钮被Popconfirm包裹，则theme失效

### Reproducible code 复现代码
```
<ButtonGroup theme="borderless">
    <Button>编辑</Button>
    <Popconfirm title="确认删除？" content="此操作不可逆">
        <Button>删除</Button>
    </Popconfirm>
</ButtonGroup>
```

### Additional information 补充说明
- 暂时只能在Popconfirm里面的Button节点也设置theme="borderless"

**Comment by shijiatongxue** [comment]
简单来说，不能这么用。不然就要遍历所有的子级。theme 只对直接子级生效。

**Comment by pointhalo** [comment]
TODO：ButtonGroup的文档上增加直接子级的说明 @shijiatongxue
