### ISSUE TITLE
Table的render如果使用ButtonGroup，按钮组会变成垂直排列

### ISSUE THREAD

**Issue by nieoding** [DouyinFE/semi-design#383]
### Which Component 出现bug的组件
  - Table
  - ButtonGroup

### semi-ui version
  - 2.1.1
    
### Expected result 期望的结果是什么
  - 在表格内水平显示 编辑/删除 按钮组

### Actual result 实际的结果是什么
  -  column如果设置了width，按钮组会变成垂直排列

### Reproducible code 复现代码
```javascript
import React from 'react'
import { Card, Button, ButtonGroup, Table} from "@douyinfe/semi-ui"

export default function Index() {
  const columns = [
    {
      title: 'id',
      dataIndex: 'id'
    },
    {
      title: 'name',
      dataIndex: 'name'
    },
    {
      width: 100,
      render: (_,record) => {
        return (<ButtonGroup>
          <Button>编辑</Button>
          <Button>删除</Button>
        </ButtonGroup>)
      }
    }
  ]
  const datas = [
    {id: 1, name:'a1'},
    {id: 2, name:'a2'}
  ]
  return <Card>
    <Table columns={columns} dataSource={datas}/>
  </Card>
}
```

### Additional information 补充说明
- 临时解决方案1：给每个column都设置width
- 临时解决方案2：操作列不设置width
- 临时解决方案3:  操作列的width设置足够大数值，例如300

**Comment by shijiatongxue** [comment]
这个问题本质上不是 Table 和 ButtonGroup 的 bug。


一个 div 内放两个原生的 button，空间不够也会折行。❤


![image](https://user-images.githubusercontent.com/26477537/145522033-f4122a7d-ba6e-462b-b203-c173355d9621.png)


```
() => (
    <div style={{ width: 100, border: '1px solid red' }}>
        <button style={{ width: 60 }}>编辑</button>
        <button style={{ width: 60 }}>删除</button>
    </div>
)
```

**Comment by nieoding** [comment]
为什么把ButtonGroup换成使用flex显示的div就可以了呢？
为什么我要这么折腾呢，因为官方没有divider组件，只有ButtonGroup和divider有点像
@shijiatongxue

```javascript
import React from 'react'
import { Card, Button, Table} from "@douyinfe/semi-ui"

export default function Index() {
  const columns = [
    {
      title: 'id',
      dataIndex: 'id'
    },
    {
      title: 'name',
      dataIndex: 'name'
    },
    {
      width: 100,
      render: (_,record) => {
        return (<div style={{display:'flex'}}>
          <Button>编辑</Button>
          <Button>删除</Button>
        </div>)
      }
    }
  ]
  const datas = [
    {id: 1, name:'a1'},
    {id: 2, name:'a2'}
  ]
  return <Card>
    <Table columns={columns} dataSource={datas}/>
  </Card>
}
```

**Comment by shijiatongxue** [comment]
> 为什么把ButtonGroup换成使用flex显示的div就可以了呢？ 为什么我要这么折腾呢，因为官方没有divider组件，只有ButtonGroup和divider有点像 @shijiatongxue
> 
> ```js
> import React from 'react'
> import { Card, Button, Table} from "@douyinfe/semi-ui"
> 
> export default function Index() {
>   const columns = [
>     {
>       title: 'id',
>       dataIndex: 'id'
>     },
>     {
>       title: 'name',
>       dataIndex: 'name'
>     },
>     {
>       width: 100,
>       render: (_,record) => {
>         return (<div style={{display:'flex'}}>
>           <Button>编辑</Button>
>           <Button>删除</Button>
>         </div>)
>       }
>     }
>   ]
>   const datas = [
>     {id: 1, name:'a1'},
>     {id: 2, name:'a2'}
>   ]
>   return <Card>
>     <Table columns={columns} dataSource={datas}/>
>   </Card>
> }
> ```

让用户方便使用也是我们的初衷。

display: flex 和 display: block 对子元素是否换行的处理不一样。 你的这个示例是 display: flex，子项目不会换行。ButtonGroup 是 display: block，会换行。

这两个没有对错之分。Semi 支持你对组件样式的自定义，可以给 `.semi-button-group` 加个 display: flex 让它不换行。

```scss
.semi-button-group {
   display: 'flex'
}
```

![image](https://user-images.githubusercontent.com/26477537/145709542-9a8464d1-6192-4277-ac10-57a8fe3c832f.png)

（为了方便，直接在开发工具加到了 style 上，ButtonGroup 没有透传 style 到这个元素上。在实际项目中，可以直接覆盖 .semi-button-group 类）
![image](https://user-images.githubusercontent.com/26477537/145709551-16d386c3-4ac3-447f-ad1e-65e466a9976c.png)


---

[Flex 布局](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox)

![image](https://user-images.githubusercontent.com/26477537/145709616-ecd1788a-20dd-4bcb-ba5c-c30e8502ca4a.png)
