### ISSUE TITLE
Select组件，如果Option的value为空字符串，则无法显示选中状态

### ISSUE THREAD

**Issue by nieoding** [DouyinFE/semi-design#385]
### Which Component 出现bug的组件
  - Select

### semi-ui version
  - 2.1.1
    
### Expected result 期望的结果是什么
  -  想在下拉框里面增加一个“全部”的选项，value为空

### Actual result 实际的结果是什么
  - “全部”选项无法选中

### Reproducible code 复现代码
```javascript
import React from 'react'
import { Card, Form} from "@douyinfe/semi-ui"

export default function Index() {
  const {Select} = Form
  return <Card>
    <Form initValue={{city:''}}>
        <Select field='city' style={{ width:100}}>
            <Select.Option value=''>全部</Select.Option>
            <Select.Option value='shanghai'>上海</Select.Option>
            <Select.Option value='beijing'>北京</Select.Option>
        </Select>
    </Form>
  </Card>
}
```

### Additional information 补充说明
- 临时解决方案1: Select 里面设置隐藏参数 allowEmpty
- 临时解决方案2: 去除“全部”选项卡，使用showClear参数，这种用户体验有点强制性

**Comment by shijiatongxue** [comment]
上面的复现代码有一个地方错了。Form 有 initValues 属性，没有 initValue 属性。

Form 有 allowEmpty 可以实现你说的效果。❤

![image](https://user-images.githubusercontent.com/26477537/145522355-14a93b27-52e9-4fa3-9cd2-90c8f5eff92f.png)
