### ISSUE TITLE
Modal组件使用命令式调用时多语言设置不起作用

### ISSUE THREAD

**Issue by Mueat** [DouyinFE/semi-design#387]
### Which Component 出现bug的组件
  - Modal
  - 使用命令行方式调用时，取消和确认按钮一直显示的是中文
 
 ### semi-ui version
  - latest

    
### Expected result 期望的结果是什么
  -  能够根据LocaleProvider设置的语言正确显示默认的取消和确定按钮对应的文字

**Comment by pointhalo** [comment]
Modal FAQ有写。
Locale是依赖Contenxt机制工作的，命令式调用是无法影响React Tree的。无法消费到对应的Context。

**Comment by pointhalo** [comment]
![image](https://user-images.githubusercontent.com/88709023/145509668-21a4ba97-7fe2-4ea6-a495-ccc3df425b83.png)
![image](https://user-images.githubusercontent.com/88709023/145509684-acce12d5-42c1-49bb-a1de-42a03db8502f.png)
