### ISSUE TITLE
按需加载是失效了吗？

### ISSUE THREAD

**Issue by popovich2021** [DouyinFE/semi-design#392]
### Which Component 出现bug的组件
  - @douyinfe/semi-ui

### semi-ui version
  - 214
    
### Expected result 期望的结果是什么
  -  webpack dev时候，不要全部都打包编译，不要影响dev时候开发体验速度，否则刷新一次就要2-3秒
  - 最好是给一套像react样的es.dev+prd的cjs包

### Actual result 实际的结果是什么
  - bunlde size很大

### Steps to reproduce 复现步骤
 ```
官方文档
2、模块化方式使用组件
在 Webpack、create-react-app 或 Vite 项目中使用时，无需进行任何编译项配置，直接使用即可。构建时所有相关资源均会按需打包。
```

### Reproducible code 复现代码
同上

### Additional information 补充说明
- 我尝试了直接挂 umd+external，还是撑大了dev时候的bundle size
- npm库里的dist ，似乎没有按组件打包，也没有cjs2+es56的包，导致无法启用 bable-plugin-import的能力
- 如果强行ts import 组件目录，会出现tsconfig need multi loader的报错

**Comment by pointhalo** [comment]
webpack dev是不会tree shaking的。tree shaking是production build才有的能力。
https://webpack.js.org/guides/tree-shaking/#minify-the-output

**Comment by pointhalo** [comment]
dist里的是es module。不需要babel plugin import之类的插件就已经能按需。
