### ISSUE TITLE
When building and packaging with Vite's default configuration, css-related warnings will be thrown

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#403]
### semi-ui version
  - v2.1.5
    
### Expected result 期望的结果是什么
  - No warning

### Actual result 实际的结果是什么
![image](https://user-images.githubusercontent.com/88709023/145746979-bda16d4e-eedf-4194-8069-b188f941fe5c.png)

### Steps to reproduce 复现步骤
  - create ts project with default setting
  - import any semi component
  - npm run build

### Reproducible code 复现代码
![image](https://user-images.githubusercontent.com/88709023/145747098-fffa3e8c-1ee5-4e9d-b222-deb6d5c350dd.png)

### Additional information 补充说明
- As you can see in the above figure, there are four components of the scss file header that declares utf-8, and according to the MDN css description, only the file header needs to be declared. When Vite composites and packs the css of multiple components, it will cause multiple charset declarations in the file. The utf-8 declaration of the component product css should be removed (checked that the declaration does not exist in the scss code, it should be automatically inserted during the compile-css process)

**Comment by pointhalo** [comment]
It seems that we can adjust related configuration in `@douyinfe/semi-scss-compile` to solve this problem @DaiQiangReal

**Comment by DaiQiangReal** [comment]
yeal

**Comment by DaiQiangReal** [comment]
https://github.com/DouyinFE/semi-design/pull/411

**Comment by DaiQiangReal** [comment]
Not fixed. #411 fixed nothing since compiling semi.css not throw warning in the first place  before fixed.

**Comment by DaiQiangReal** [comment]
Please check packages/semi-foundation/gulpfile.js that it is possible to remove @charset in each css output file.

**Comment by pointhalo** [comment]
fix v2.2
