### ISSUE TITLE
[Description]align='plain'是key不支持ReactNode，其他对齐方式是支持的

### ISSUE THREAD

**Issue by boomboomchen** [DouyinFE/semi-design#406]
### Which Component 出现bug的组件
  - Description

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 

### Actual result 实际的结果是什么
  - 

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
2.2.0-beta.0
