### ISSUE TITLE
[Site] 站点代码编辑器依赖 CDN 失效，正在修复中❤

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#439]
[Site] The site code editor relies on the CDN link to fail and is under repair

![image](https://user-images.githubusercontent.com/26477537/146725578-ce748c00-5d1f-420f-bc87-1b01f9e427ef.png)

**Comment by DaiQiangReal** [comment]
Fixed. Please force flash your page to disable former cache.
