### ISSUE TITLE
想拥有一个semi风格的富文本编辑器

### ISSUE THREAD

**Issue by Axiano** [DouyinFE/semi-design#454]
### 希望拥有的功能
- 适配暗黑主题
- 可以自带上传图片/视频的功能
- 可以添加自定义表情
- 菜单可以自定义

**Comment by pointhalo** [comment]
富文本编辑器整体的复杂度 & 独立性较高，我们没有计划在这方面进行投入。在我们团队内部，这类需求也一般都是通过二次封装社区内的现有富文本库或者飞书文档的编辑器（内部使用，暂未开源，所以也没法直接提供）来实现。建议可以考虑 draft.js、或者 https://bytedance.github.io/syllepsis/#/zh-cn/about
