### ISSUE TITLE
上游 resize-observer-polyfill 依赖在 ts 项目中报错问题

### ISSUE THREAD

**Issue by onsummer** [DouyinFE/semi-design#455]
### 关联 issue

https://github.com/DouyinFE/semi-design/issues/141

### 环境
  - ts 4.5
  - pnpm 6.20^
  - vite2.7
  - react17

### 出现bug的组件
  - any

### semi-ui version
  - 2.1.5

### 现有解决方案
  - `tsc --skipLibCheck` 添加此编译参数

### 期待的结果

  - 不需要 `--skipLibCheck` 参数也可以打包，希望官方团队能想办法在依赖引用时就解决这个问题

### Actual result 实际的结果是什么

```
> tsc && vite build

node_modules/.pnpm/mirrors.tencent.com+resize-observer-polyfill@1.5.1/node_modules/resize-observer-polyfill/src/index.d.ts:19:18 - error TS2717: Subsequent property declarations must have the same type.  Property 'contentRect' must be of type 'DOMRectReadOnly', but here has type 'DOMRectReadOnly'.

19         readonly contentRect: DOMRectReadOnly;
                    ~~~~~~~~~~~

  node_modules/.pnpm/mirrors.tencent.com+typescript@4.5.4/node_modules/typescript/lib/lib.dom.d.ts:11115:14
    11115     readonly contentRect: DOMRectReadOnly;
                       ~~~~~~~~~~~
    'contentRect' was also declared here.


Found 1 error.
```

### Steps to reproduce 复现步骤
  - 使用 `pnpm init vite` 创建 react-ts 模板项目
  - 在 App 组件中使用任意 semi 组件
  - build

**Comment by pointhalo** [comment]
这个是由于resize-observer-polyfill 它的d.ts里直接定义了一个global，与ts的冲突了。  
我们后续再看下能否移掉这个库吧（可能需要再后续的几个minor版本）

**Comment by pointhalo** [comment]
@zwlafk OverflowList的优化过程中顺便关注下 resize-observer-polyfill 这个是否可被替代的问题吧

**Comment by H3lloTom** [comment]
需要关注一下Safari13的兼容性问题
