### ISSUE TITLE
[Progress] 支持线性渐变背景颜色

### ISSUE THREAD

**Issue by H3lloTom** [DouyinFE/semi-design#456]
### Which Component Need Enhancement 期望新增功能的组件
- Progress

### What does the proposed API look like 期望支持的API

stroke属性支持渐变色

### Feature Description 功能描述

Progress支持线性渐变颜色

### Additional information 补充说明
目前type="line"，stroke传入到background-color属性，然而该属性并不支持渐变色。

**Comment by shijiatongxue** [comment]
v2.12.0-beta.0 supported
