### ISSUE TITLE
[Datepicker] 日期选择器在关闭时，回显行为与回调行为不一致

### ISSUE THREAD

**Issue by Carlosfengv** [DouyinFE/semi-design#457]
### Which Component 出现bug的组件
  - DatePicker

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 输入框内的回显日期在关闭选择器时与回调行为保持一致。

### Actual result 实际的结果是什么
  - 日期在选择时即回显在了输入框内，即使不对已选择的日期进行确认  

### Steps to reproduce 复现步骤
![image](https://user-images.githubusercontent.com/23092051/147329864-7922c62b-cd21-475d-8080-6b7a353c9c13.png)

**Comment by shijiatongxue** [comment]
v2.2.1 fixed
