### ISSUE TITLE
Space组件间距无效

### ISSUE THREAD

**Issue by ZeroCodeLin** [DouyinFE/semi-design#459]
### Which Component 出现bug的组件
  - Space

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 

### Actual result 实际的结果是什么
  - 

### Steps to reproduce 复现步骤
  - 官网Space组件demo就可以复现

### Reproducible code 复现代码
```
官网Space组件demo就可以复现
<Space spacing='tight'>
                <Button theme='solid' type='primary'>按钮</Button>
                <Button theme='solid' type='primary'>按钮</Button>
                <Button theme='solid' type='primary'>按钮</Button>
                <Button theme='solid' type='primary'>按钮</Button>
            </Space>
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by boomboomchen** [comment]
没有复现出来。麻烦给一下你那边的复现效果的截图哈～

**Comment by ZeroCodeLin** [comment]
发下在chrome 80.0.3987.132 版本下会有问题，换了edge就正常了

**Comment by ZeroCodeLin** [comment]
> 没有复出来。麻烦给一下你一下子现的复现效果的截图哈～

chrome 80.0.3987.132  是不兼容么？

**Comment by pointhalo** [comment]
升下chrome版本吧。可能是某个特定版本的bug。

**Comment by ZeroCodeLin** [comment]
> 升下chrome版本吧。可能是某个特定版本的bug。

column-gap 兼容性的问题吧好像要84以后的版本，考虑换中css实现么？

**Comment by ZeroCodeLin** [comment]
用户不一定会升级chrome

**Comment by shijiatongxue** [comment]
> 用户不一定会升级chrome

由于需要支持暗色模式等特性，Semi 与业界组件库类似，支持的浏览器版本为现代浏览器，last 2 version。

![image](https://user-images.githubusercontent.com/26477537/147440676-ebdc713c-7daa-4d11-ac23-2e7b6fd7faf6.png)

如果要兼容历史版本的浏览器。建议自己 polyfill 一下（通过覆盖类名下的样式），或者直接使用 flex 布局（不使用 Space 组件）。如果其他组件使用过程中也有类似的问题，我们很抱歉❤，请考虑下业界其他优秀的组件库。

**Comment by shijiatongxue** [comment]
上下文再补充下。

之前 Space 使用的 margin 来控制 item 之间的间距，但是存在一个问题（也有业务方反馈），一行的最右边的一个元素总是会有一个 margin-right，然而我们也无法判断哪一个元素是一行的最右边的一个，所以无法通过 JS 或者 CSS 控制。后面选择了 gap 方案解决这个问题。

![image](https://user-images.githubusercontent.com/26477537/147800899-7de85f6b-38fd-41c5-90d3-3d8c68c8893d.png)

如果有任何疑问欢迎在下面讨论~
