### ISSUE TITLE
bug(Select) filter bug when having variable substitution in template literal

### ISSUE THREAD

**Issue by jiahao-c** [DouyinFE/semi-design#476]
### Which Component 出现bug的组件
Select

### semi-ui version
2.2.1 (latest)
    
### Expected result 期望的结果是什么
![image](https://user-images.githubusercontent.com/8275280/147714722-f1ce1e58-1542-4d35-8f8f-f599b140ce7e.png)

### Actual result 实际的结果是什么
![image](https://user-images.githubusercontent.com/8275280/147714745-5aa1b0d0-18d9-44bd-95f2-03cac41ef46e.png)

### Steps to reproduce 复现步骤
1. 打开 [Codesandbox Link](https://codesandbox.io/s/semi-select-bug-reproduce-2l5bl?file=/src/App.tsx) 或使用下面的复现代码
2. 在 Select 中输入  `ABCD 123` 
3. 应当搜索到结果，但却没有搜索到

### Reproducible code 复现代码

```typescript
import { Select } from "@douyinfe/semi-ui";
export default function App() {
  let i = 123;
  let j = 321;
  return (
      <Select
        filter
        multiple
        placeholder="This is buggy"
      >
        <Select.Option value={`ABCD ${i}`}>ABCD {i}</Select.Option>
        <Select.Option value={`WXYZ ${j}`}>WXYZ {j}</Select.Option>
      </Select>
  );
}

```

**Comment by jiahao-c** [comment]
另外，我尝试了把变量写为 string 而不是 number，即
```typescript
let i = "123";
let j = "321";
```

但仍会存在上述问题。

**Comment by jiahao-c** [comment]
试了下， [Arco](https://codesandbox.io/s/great-euler-bv04w?file=/index.js) 是没有这个bug的～ 希望 Semi 可以尽早修复

**Comment by jiahao-c** [comment]
试了下，即使不用 children 只用 value，也还是会出现这个bug～
```typescript
      <Select
        filter
        multiple
        style={{ width: 300 }}
        placeholder="This is also buggy"
      >
        <Select.Option value={`ABCD ${i}`} />
        <Select.Option value={`WXYZ ${j}`} />
      </Select>
```

![image](https://user-images.githubusercontent.com/8275280/147719513-02c6a03b-1898-4025-a2a1-0c3377bae568.png)

**Comment by pointhalo** [comment]
在React中，<Component>abc {i}</Component> 这种写法。对于Component来说，它从props.children读取到的就已经是 [abc, ${i}] ，而不是一个字符串了。搜索的默认策略是将label 先执行 toLowerCase，再与 input值进行include对比。  

非string类型的label（例如当label/ children传reactNode时），可以自行定义filter

```
const TestComponent = (props) => {
  console.log(props); // will be ['ABCD ', 123] , not 'ABCD 123'
  return <div>ccc</div>
}

const Demo = () => {
  let i = 123;
  return (
      <TestComponent>ABCD {i}</TestComponent>
  );
};
```

改成这种写法 <Option>{`ABCD ${i}`} </Option> 或者 自定义 props.filter 也可以解决。

**Comment by jiahao-c** [comment]
谢谢！的确，用 label 而不是 children 的话就不会出现这个问题了。我先close了～
