### ISSUE TITLE
输入框文字，placeholder如何居中

### ISSUE THREAD

**Issue by nieoding** [DouyinFE/semi-design#481]
### Which Component 出现bug的组件
  - Input

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  -  文字如何居中
<img width="242" alt="WX20211231-144815@2x" src="https://user-images.githubusercontent.com/12727335/147808352-cb1e0446-0b03-42c7-8851-71e6850daa63.png">
  -

### Reproducible code 复现代码
```javascript
<Input placeholder="请输入文字" style={{ width: 200, textAlign:'center' }}/>

```
在这里设置textAlign无效

**Comment by pointhalo** [comment]
自行css覆盖吧。目前没有关于placeholder位置的相关token或api。

**Comment by boomboomchen** [comment]
> 自行css覆盖吧。目前没有关于placeholder位置的相关token或api，这类的设计比较低频。

+1 覆盖样式即可实现，相对低频，不建议在组件侧额外支持
