### ISSUE TITLE
Support Document Global Search

### ISSUE THREAD

**Issue by nothinginterested** [DouyinFE/semi-design#482]
### Feature Description 功能描述

文档站希望对齐arco，ant-design ，支持全局搜索

### Additional information 补充说明

找个组件还得翻菜单，体验并不是很好

**Comment by boomboomchen** [comment]
duplicate issue with #17

**Comment by pointhalo** [comment]
Originally planned to access algolia, but it has a limit on the frequency of calls, which cannot better meet the pv of this site.
We are now based on our own internal search service, so the delivery is much later than originally planned.
We made an update last Friday and it's available now🔍 . Support Chinese and English search and recent browsing, search history. 
Hope this can improve your experience🌟
