### ISSUE TITLE
bug(Select) Dropdown box overflow

### ISSUE THREAD

**Issue by jiahao-c** [DouyinFE/semi-design#486]
### Which Component 出现bug的组件
Select

### semi-ui version
2.2.2 (latest)
    
### Expected result 期望的结果是什么
No Overflow. Just like Arco: https://codesandbox.io/s/arco-select-dropdown-8thdl?file=/src/App.tsx
![image](https://user-images.githubusercontent.com/8275280/147864466-62468bd8-57d7-4349-818e-e1950897adac.png)

### Actual result 实际的结果是什么
Overflow.  See here: https://codesandbox.io/s/semi-select-dropdown-bug-28dyr?file=/src/App.tsx
![image](https://user-images.githubusercontent.com/8275280/147864510-11bf1ad0-683f-4c8e-b499-d91cf88fad96.png)

### Steps to reproduce 复现步骤
See codesandbox link above

### Reproducible code 复现代码
```typescript
<Select
    style={{ width: "80vw", maxWidth: "500px" }}
    dropdownStyle={{
      maxHeight: "20vh"
    }}
    size="large"
    filter={true}
    multiple={true}
  >
        .....
</Select>
```

**Comment by pointhalo** [comment]
这是因为你在dropdownStyle中自定义了maxHeight：20vh。这个是附加在父级wrapper上的
![image](https://user-images.githubusercontent.com/88709023/148005822-6632fa7e-4396-42aa-84de-9c5d57eca7e5.png)

你要自定义下拉层高度的话，我们已经直接提供了 API：maxHeight
![image](https://user-images.githubusercontent.com/88709023/148005889-b4aa75e0-0b4e-4c31-b27f-34298139fe8f.png)

```diff
import { Select } from "@douyinfe/semi-ui";
import { range } from "lodash";
const Option = Select.Option;
export default function App() {
  return (
    <div>
      <Select
        style={{ width: "80vw", maxWidth: "500px" }}
+      maxHeight={200}
        size="large"
        filter={true}
        multiple={true}
      >
        {range(1, 20).map((i) => (
          <Option value={i}>option {i}</Option>
        ))}
      </Select>
    </div>
  );
}

```
