### ISSUE TITLE
【Table】tbody在开启虚拟化之后在resize时没有变化

### ISSUE THREAD

**Issue by PoleGS** [DouyinFE/semi-design#508]
### Which Component 出现bug的组件
  - Table

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - tbody应该与表头一起更新，数据与表头对应的上

### Actual result 实际的结果是什么
  - 只有表头变化，表格内容的宽度没变化

### Steps to reproduce 复现步骤
  - import table 开启虚拟化，浏览器大小变动。
 ## codesandbox链接：https://codesandbox.io/s/semi-tablexu-ni-hua-yan-zheng-dm4bl?file=/src/App.js:65-719

### Reproducible code 复现代码
```
const mockDataKey = ['a', 'b', 'c'];

const mockData = [...Array(100).keys()].map(item => mockDataKey.reduce((result, key) => {
  result[key] = item;
  return result;
}, {}));

export default function App() {
  const column = [
    {
      title: '字段a',
      dataIndex: 'a',
    },
    {
      title: '字段b',
      dataIndex: 'b',
    },
    {
      title: '字段c',
      dataIndex: 'c',
    }
  ];
  return (
    <div className="App">
      <Table 
        dataSource={mockData} 
        columns={column} 
        pagination={false} 
        virtualized={true}
        scroll={{
          y: 500,
          x: '100%',
      }}
        />
    </div>
  );
}

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by shijiatongxue** [comment]
你好，虚拟化表格需要固定宽度 💖

![image](https://user-images.githubusercontent.com/26477537/148337321-d84f636a-9fbc-4db9-a94c-b5e3dde171e2.png)
