### ISSUE TITLE
使用vite如何引入自定义主题呢？

### ISSUE THREAD

**Issue by zilan830** [DouyinFE/semi-design#511]
### Which Component Need Enhancement 期望新增功能的组件
- 使用Vite引入自定义主题

### Additional information 补充说明
目前只看到引用自定义主题的webpack构建的插件，如果用vite构建，该如何引入呢？

**Comment by DaiQiangReal** [comment]
你好，关于 Vite 主题插件我们正在内测。 在对外正式放出之前，可以手动调用我们的编译命令行，将主题包编译为css，在你的网站的html里全量引用来使用主题。

semi 主题编译工具: https://github.com/DouyinFE/semi-design/tree/main/packages/semi-scss-compile

**Comment by zilan830** [comment]
> 
请问使用方法，是先全局安装 @douyinfe/semi-scss-compile ，
再自定义主题项目目录里执行命令行
```semi-build-scss --foundation="path/to/foundation" --theme="path/to/theme" --icon="path/to/'@douyinfe/semi-icons'" --output="path/to/output.css" --min```
是么？
文档里的JS API和Advanced API不需要用到吧？
我没看懂这个如何使用。

**Comment by zilan830** [comment]
> > 
> 
> 请问使用方法，是先全局安装 @douyinfe/semi-scss-compile ， 再自定义主题项目目录里执行命令行 `semi-build-scss --foundation="path/to/foundation" --theme="path/to/theme" --icon="path/to/'@douyinfe/semi-icons'" --output="path/to/output.css" --min` 是么？ 文档里的JS API和Advanced API不需要用到吧？ 我没看懂这个如何使用。
> 
> 还有请问这个 path/to/foundation path/to/theme 等等路径是什么路径啊？我如何填写？

解决了，还需要装@douyinfe/semi-foundation和@douyinfe/semi-icons这两个插件，路径是这两个插件的地址。

**Comment by laozhu** [comment]
同样需要 vite 自定义主题的功能，先用默认的主题好了，等出来了我再定制。

**Comment by boenfu** [comment]
> 同样需要 vite 自定义主题的功能，先用默认的主题好了，等出来了我再定制。

正好有需求，就顺手做了（ ps：基本搬的 webpack 版代码
[vite-plugin-semi-theme](https://github.com/boenfu/vite-plugin-semi-theme)

**Comment by DaiQiangReal** [comment]
> vite-plugin-semi-theme
🐂🍺 ！
