### ISSUE TITLE
[Anchor] 锚点文本前的间距无法触发选中

### ISSUE THREAD

**Issue by Carlosfengv** [DouyinFE/semi-design#512]
### Which Component 出现bug的组件
  - Anchor

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  -  锚点文本整行都可以被触发

### Actual result 实际的结果是什么
  多级锚点时，锚点文本前的区域无法被触发
![image](https://user-images.githubusercontent.com/23092051/148348055-1203fcb8-6915-4a5e-9aa1-edd8610b4fd0.png)

### Steps to reproduce 复现步骤
  - 1

**Comment by YannLynn** [comment]
fixed in 2.19.0
