### ISSUE TITLE
[Table] 支持搜索筛选

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#516]
### Which Component Need Enhancement 期望新增功能的组件
- Table

### Feature Description 功能描述

- 列支持搜索筛选功能
- 增加自定义搜索示例

![image](https://user-images.githubusercontent.com/26477537/148509089-bd44689d-bb1b-465a-aecd-65ec0875a953.png)

适用于 filter value 不固定的场景

### 目前为啥不支持

虽然有 `filterDropdown` API，但是没有接受任何参数。相当于自己处理所有的筛选逻辑。使用起来不方便。

![image](https://user-images.githubusercontent.com/26477537/148509470-9d19a063-0418-448d-bc90-37d362692f6e.png)

**Comment by pointhalo** [comment]
- 基础做法是支持在 title中增加一个input 作为filter，并内置一些筛选相关的处理逻辑
- 不过可能并非是最优解，在列信息越来越多的时候，复合的筛选会是更合理的交互（最近看到一个Medium上的分享：https://medium.com/@lodestar-design/process-doc-how-i-polish-micro-interactions-for-search-filters-in-a-table-bd729a55895c），这个可能作为 Table外置挂件更合理

**Comment by shijiatongxue** [comment]
在 https://github.com/DouyinFE/semi-design/issues/2015 跟进
