### ISSUE TITLE
[Tag] 有父级包裹时，父元素存在3px留白

### ISSUE THREAD

**Issue by zwlafk** [DouyinFE/semi-design#518]
### Which Component 出现bug的组件
  - Tag

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 正常展示，父级高度自适应

### Actual result 实际的结果是什么
![image](https://user-images.githubusercontent.com/24400915/148534483-f8474ccd-2935-4740-b805-3e8fc099697b.png)

### Reproducible code 复现代码
```
<div><Tag>1111</Tag></div>
```

**Comment by shijiatongxue** [comment]
问题原因可参考：https://bytedance.feishu.cn/docs/doccnq2sowCgaSyPgdlf77Gjy3g

**Comment by pointhalo** [comment]
fix after v2.6.0
