### ISSUE TITLE
[DatePicker] type=month时，设置跨年份的disabledDate，表现不符合预期

### ISSUE THREAD

**Issue by zwlafk** [DouyinFE/semi-design#520]
### Which Component 出现bug的组件
  - DatePicker

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 根据设置的disabledDate显示

### Actual result 实际的结果是什么
  - disabledDate存在跨年份情况时，表现不符合预期

### Steps to reproduce 复现步骤
  - 设置disabledDate禁用2021年12月以前的年月，预期2021年12月能够选择
  - 选择2022年时，选择12月份，能够选择2021年
  - 选择2022年时，选择其他月份，无法选到2021年，不符合预期

### Reproducible code 复现代码
```jsx
const disabledTime = date => date.getFullYear() < 2021 || (date.getFullYear() == 2021 && date.getMonth() < 11);
<DatePicker disabledDate={disabledDate} defaultValue={new Date()} type="month" style={{ width: 140 }} />
```

### Additional information 补充说明
![datepicker](https://user-images.githubusercontent.com/24400915/148548754-c6991d5e-15e3-4163-b84e-d03b83112965.gif)

**Comment by shijiatongxue** [comment]
v2.24.1 fixed
