### ISSUE TITLE
用create-react-app创建应用，引入后使用layout组件，样式不生效

### ISSUE THREAD

**Issue by sunsou1** [DouyinFE/semi-design#526]
### Which Component 出现bug的组件
  - Layout

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 能够想官网demo一样出现样式
  - ![image](https://user-images.githubusercontent.com/23651876/148751322-bb7f15a6-6a8d-47df-a847-94ea08d7026a.png)

### Actual result 实际的结果是什么
<img width="526" alt="企业微信20220110-183429@2x" src="https://user-images.githubusercontent.com/23651876/148751984-8c5c0a69-496a-4e75-9531-a7f5f069ceb7.png">

### Steps to reproduce 复现步骤
  - 1 npx create-react-app my-app
  - 
![image](https://user-images.githubusercontent.com/23651876/148751429-07a33959-a727-4357-add7-78dad88ba2ad.png)
实际出现的结果

### Reproducible code 复现代码
```
import { Layout } from '@douyinfe/semi-ui';

function App() {
  const { Header, Footer, Content } = Layout;

    return (
        <Layout className="components-layout-demo">
            <Header>Header</Header>
            <Content>Content</Content>
            <Footer>Footer</Footer>
        </Layout>
    );
}

export default App;

```

### Additional information 补充说明
- 是不是没有引入相关样式？ 希望能够给与一个小白入门的教程，按官网的快速入门，很难进行使用。最好能够有个做好的demo或者脚手架。谢谢

**Comment by pointhalo** [comment]
Layout是布局组件，它本身并不会包含 color、backgroundColor、text-align等样式（因为这些都是根据用户自己实际需求，不同场景不一致的，你可以通过style自行传入）官网的demo仅是为了准确展示 header、content、footer之间的布局位置关系单独在演示时添加了背景色。

**Comment by pointhalo** [comment]
![image](https://user-images.githubusercontent.com/88709023/148874936-fcab866e-1bb1-4f0a-b348-b4835d7b3f3f.png)
