### ISSUE TITLE
[TreeSelect] triggerRender 入参的 TS 类型不应为可选

### ISSUE THREAD

**Issue by boomboomchen** [DouyinFE/semi-design#532]
### Which Component 出现bug的组件
  - TreeSelect

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 

### Actual result 实际的结果是什么
  - 

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
Type '(triggerProps: TriggerRenderProps) => JSX.Element' is not assignable to type '(props?: TriggerRenderProps | undefined) => ReactNode'.
  Types of parameters 'triggerProps' and 'props' are incompatible.
    Type 'TriggerRenderProps | undefined' is not assignable to type 'TriggerRenderProps'.
      Type 'undefined' is not assignable to type 'TriggerRenderProps'.ts(2322)
```
<TreeSelect
            value={value}
            onChange={(value) => setValue(value as string)}
            triggerRender={triggerRender} //此处会ts报错
            treeData={treeData}
            defaultOpen
            filterTreeNode
          />
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by YyumeiZhang** [comment]
ts v4.9.5未复现该问题
