### ISSUE TITLE
InputNumber使用 defaultValue报错

### ISSUE THREAD

**Issue by mtsee** [DouyinFE/semi-design#537]
### Which Component 出现bug的组件
  - InputNumber

### semi-ui version
  - latest 2.2.2
    
### Expected result 期望的结果是什么
  - InputNumber 使用 defaultValue非受控组件的时候，会提示同时使用了 defaultValue 和 value 参数，会报错。

### Actual result 实际的结果是什么
  - 使用 defaultValue不提示warn错误

### Steps to reproduce 复现步骤
  - 1 使用 <InputNumber defaultValue={1} /> 控制台报错
![image](https://user-images.githubusercontent.com/12293810/149490782-257de25a-ed0d-4b47-8b79-1983d1f6e4d3.png)

### Reproducible code 复现代码
```
class Demo extends React.component {

    render() {
        return (
            <InputNumber defaultValue={1} /> 
        )
    }

}

```

### Additional information 补充说明
- 发现是InputNumber中写死了value

**Comment by shijiatongxue** [comment]
已复现此问题，稍后我们修复下。

**Comment by chenc041** [comment]
@shijiatongxue 这种已经解决掉的问题  issue 关掉吧

**Comment by shijiatongxue** [comment]
> @shijiatongxue 这种已经解决掉的 issue 需要及时关掉

一般在会发版后关

**Comment by shijiatongxue** [comment]
v2.3.1 fixed

**Comment by chenc041** [comment]
> 

那可以加个 新的 label 标识一下
比如 fixed
