### ISSUE TITLE
[DatePicker] 自定义 trigger 点击进去不能先选结束日期再选开始日期

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#538]
### Which Component 出现bug的组件
  - DatePicker

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 如果是只能先选开始日期，希望有明显提示。

没有自定义 trigger 时，开始日期前的日期是禁用的。

![image](https://user-images.githubusercontent.com/26477537/149501390-21364013-9ee6-4ce1-b69f-d56010945325.png)

### Actual result 实际的结果是什么

- 选择 1 月 15 日，向前选择，如选择 1 月 3 日，效果很奇怪

![image](https://user-images.githubusercontent.com/26477537/149501059-e3fc4b12-1525-4150-9035-6d79fb1d22dd.png)

- 点击 1 月 3 日后如下

![image](https://user-images.githubusercontent.com/26477537/149501251-3ff6d0a0-74ce-4da8-8fb3-2e5bfdf11977.png)

### Reproducible code 复现代码
```jsx
import React from 'react';
import { DatePicker, Button } from '@douyinfe/semi-ui';

function Demo() {

    return (
        <DatePicker
            type="dateRange"
            triggerRender={({ placeholder }) => (
                <Button theme={'light'}>
                  Select Date
                </Button>
            )}
        />
    );
}
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by lin2006yuo** [comment]
我这里有一个期望结果是每次都从开始日期开始选择

**Comment by crazyxhz** [comment]
DateRangePicker 交互有点反人类，能不能第一下点击都是开始，第二下点击都是结束？
需要用户点击对应的开始结束框才进入选择对应开始或者结束日期模式，很不直观啊

**Comment by crazyxhz** [comment]
或者给一个可以设置的selectionMode属性也行

**Comment by shijiatongxue** [comment]
> DateRangePicker 交互有点反人类，能不能第一下点击都是开始，第二下点击都是结束？ 需要用户点击对应的开始结束框才进入选择对应开始或者结束日期模式，很不直观啊



> 我这里有一个期望结果是每次都从开始日期开始选择

这个问题在优化了。优化后自定义 trigger，打开面板会先选开始日期，后选结束日期。

**Comment by shijiatongxue** [comment]
> 

DatePicker range 选择，在 1.x 时就是这个设计，每次选择都是先选开始，后选结束。后来因为有用户反馈无法单独修改开始或者结束，我们把输入框拆成了两个，点击开始就是选择开始，点击结束就是选择结束。

范围选择目前分为两种。

- 在 dateRange type 时，点击完开始会自动切到结束选择，不需要点击结束日期输入框。
- 在 dateTimeRange type 时，因为点击完日期后，用户可能会选择时间，所以不会跳转到结束日期选择。我猜你说是这种场景。

**Comment by shijiatongxue** [comment]
> 

当然目前这个交互也存在问题。选择开始日期后，开始日期之前的日期就禁用了，这个体验不是很好。

**Comment by shijiatongxue** [comment]
> 我这里有一个期望结果是每次都从开始日期开始选择



> > DateRangePicker 交互有点反人类，能不能第一下点击都是开始，第二下点击都是结束？ 需要用户点击对应的开始结束框才进入选择对应开始或者结束日期模式，很不直观啊
> 
> > 我这里有一个期望结果是每次都从开始日期开始选择
> 
> 这个问题在优化了。优化后自定义 trigger，打开面板会先选开始日期，后选结束日期。

v2.15.0 版本自定义 trigger 场景已优化为每次都从开启日期开始选择。

**Comment by shijiatongxue** [comment]
> 或者给一个可以设置的selectionMode属性也行

这个特性在这里跟进哈~ https://github.com/DouyinFE/semi-design/issues/1205
