### ISSUE TITLE
Dropdown组件menu props类型定义异常

### ISSUE THREAD

**Issue by H3lloTom** [DouyinFE/semi-design#541]
### Which Component 出现bug的组件
  - Dropdown

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 

### Actual result 实际的结果是什么
  - 

### Reproducible code 复现代码
```
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
need more infomation
