### ISSUE TITLE
[TimePicker] TimePicker打开后闪烁一次

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#548]
### Which Component 出现bug的组件
  - TimePicker

### semi-ui version
  - maybe after v2.1？
    
### Expected result 期望的结果是什么
  - 正常打开不闪烁

### Actual result 实际的结果是什么
  - 闪烁较明显

### Steps to reproduce 复现步骤
  - 官网TimePicker任一 Demo

**Comment by oddguan** [comment]
这里是由这个改动造成的：

**Comment by oddguan** [comment]
这里是由这个改动造成的：
#505
202行这里加了个setTimeout导致了重新渲染，删掉setTimeout能解决。
![image](https://user-images.githubusercontent.com/14129720/159426660-2f5e39e8-68ac-4ce5-96ce-8b2ed709b76a.png)
请问当时加这个setTimeout有什么特殊原因吗

**Comment by pointhalo** [comment]
> 这里是由这个改动造成的： #505 202行这里加了个setTimeout导致了重新渲染，删掉setTimeout能解决。 ![image](https://user-images.githubusercontent.com/14129720/159426660-2f5e39e8-68ac-4ce5-96ce-8b2ed709b76a.png) 请问当时加这个setTimeout有什么特殊原因吗

是为了确保portal & children已经被插入到dom里后，再触发eventBus。

这个写法可能改成_portal.jsx内增加回调比较合适。看起来这个写法导致了几个问题。#587

**Comment by oddguan** [comment]
#715 应该也是这个问题

**Comment by shijiatongxue** [comment]
v2.9.1 fixed
