### ISSUE TITLE
后面有计划支持Vue吗？

### ISSUE THREAD

**Issue by heroFan** [DouyinFE/semi-design#56]
### Which Component Need Enhancement 期望新增功能的组件
- Button

**Comment by cfancc** [comment]
笑死，原来adapter就是个幌子

**Comment by xiangshouding** [comment]
@cfancc 笑死，难道提供扩展的能力没有把所有的扩展全部实现，就该被吐槽么。
能不能用过以后再说？

**Comment by ChenWeihua123** [comment]
简单补充几个热门框架适配器实现的小demo，应该会更好，各自实现起来也更规范一点（狗头保命）

**Comment by rashagu** [comment]
vue3版 开源 
[https://github.com/rashagu/semi-design-vue](https://github.com/rashagu/semi-design-vue)
vue3 + tsx + vite
只完成了 一小部分，没时间做
