### ISSUE TITLE
通过引入svg使用自定义icon-图标过大

### ISSUE THREAD

**Issue by lainswork** [DouyinFE/semi-design#562]
### 如题，按照官网的教程引入svg，使用<Icon svg=<xxxx/>/>
图标会显示的非常大，比如button中使用时，图标显示的与8个图标大小相当了
图标svg来源是https://www.iconfont.cn/

**Comment by tank0317** [comment]
![image](https://user-images.githubusercontent.com/16872030/150717214-3948fd65-e0c3-4a6d-af41-597b4df69844.png)

svg 自身的大小由 width height 属性决定，也可以设置 width height 为 1em，跟随字体大小
