### ISSUE TITLE
[Navigation] 子菜单数量叠加高度超过 999 px 不显示

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#563]
### Which Component 出现bug的组件
  - Navigation

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 正常显示

### Actual result 实际的结果是什么
  - 高度被截断

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```
import React from 'react';
import { Nav } from '@douyinfe/semi-ui';
import { IconUser, IconStar, IconSetting } from '@douyinfe/semi-icons';

class NavApp extends React.Component {
    render() {
        return (
            <Nav
                bodyStyle={{ height: 320 }}
                items={[
                    { itemKey: 'user', text: '用户管理', icon: <IconUser /> },
                    { itemKey: 'union', text: '公会中心', icon: <IconStar /> },
                    {
                        text: '任务平台',
                        icon: <IconSetting />,
                        itemKey: 'job',
                        items: (()=>{
                            let a=[];
                            for(let i=0;i<=100;i++){
                                a.push(i)
                            }
                            return a
                        })(),
                    },
                ]}
                onSelect={data => console.log('trigger onSelect: ', data)}
                onClick={data => console.log('trigger onClick: ', data)}
            />
        );
    }
}



```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by DaiQiangReal** [comment]
![udgatKOx7C](https://user-images.githubusercontent.com/29626873/150718256-ebd5de8a-fd9c-48c4-8c7c-f649b62eed1a.png)

**Comment by DaiQiangReal** [comment]
User can override maxHeight in items array, as same level of itemKey.

**Comment by 43374166** [comment]
短时间内点击nav，nav有点击事件，里面有navigate跳转，短时间点击会直接报错，提示Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by pointhalo** [comment]
> 短时间内点击nav，nav有点击事件，里面有navigate跳转，短时间点击会直接报错，提示Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

可以单独建个issue，附上复现的codesandbox~
