### ISSUE TITLE
Theming support for Next.js

### ISSUE THREAD

**Issue by Saul-BT** [DouyinFE/semi-design#565]
### Which Component Need Enhancement 期望新增功能的组件
- All

### What does the proposed API look like 期望支持的API
Specify the already published theme in `next.config.js` or somewhere to use the custom theme.
Maybe add instructions for it in the docs (like for pure Webpack)

I'm trying this (but it doesn't work):

```javascript
const SemiWebpackPlugin = require ('@douyinfe/semi-webpack-plugin').default;
const semi = require('@douyinfe/semi-next').default({/* the extension options */});

const nextConfig = semi({
  reactStrictMode: true,
  webpack(config, options) {

    config.plugins.push(
      new SemiWebpackPlugin({
        theme: '@semi-bot/semi-theme-test',
        include: '~@semi-bot/semi-theme-test/scss/local.scss',
      })
    );

    return config;
  },
})

module.exports = nextConfig;
```

### Feature Description 功能描述
Use custom themes with Next.js.

### Additional information 补充说明
Next.js version: 12.0.8
Semi version: 2.3.0

**Comment by DaiQiangReal** [comment]
Notice, that nextjs not allow import css files in node_modules as for third-party package. So what semi nextjs plugin done is omitting all import code in semi component. So that your will need to import semi global css file in your code ([So as our official doc says](https://semi.design/en-US/start/getting-started#Step3]). 

For the reason above, to use theme of semi , all you need to do is to import global css files from your own theme package instead of offical theme package(/dist/semi.min.css), that's all.

**Comment by Saul-BT** [comment]
Oh, yeah, it works 😃 .

Thanks for your fast response, you are doing an amazing work.

And... sorry for my silly question (I missed that part of the "Getting started" section).

**Comment by DaiQiangReal** [comment]
> Oh, yeah, it works 😃 .
> 
> Thanks for your fast response, you are doing an amazing work.
> 
> And... sorry for my silly question (I missed that part of the "Getting started" section).

Thank you for your understanding about our work. There is indeed a lack of detailed explanations about theme using in nextjs of our docs. We will link this issue in our doc's nextjs part for later people.

**Comment by DaiQiangReal** [comment]
Docs update.

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/162556673-b0fec100-9db8-4a88-8c2e-a3ed8ad38225.png)

some problem dont fixed

**Comment by pointhalo** [comment]
> ![image](https://user-images.githubusercontent.com/38668796/162556673-b0fec100-9db8-4a88-8c2e-a3ed8ad38225.png)
> 
> some problem dont fixed

**nextjs does not allow importing css or scss from node_modules**. Therefore, we can onlyremove the import statement of css/scss in the next plugin of semi, and then the user needs to import the packaged css product by himself.

The setting of next makes it impossible for us to specify the theme package in the plugin like a normal webpack project.


1. use semi next plugin 
```
const SemiWebpackPlugin = require ('@douyinfe/semi-webpack-plugin').default;

const nextConfig = semi({
 ....
})
module.exports = nextConfig;
```

2. import css by yourself
```
/* styles/globals.css */

@import '~@douyinfe/semi-ui/dist/css/semi.min.css'; // if you use default semi theme
or
@import '@semi-bot/semi-theme-nyx-c/semi.min.css'.    // if you use custom theme which publish by semi dsm
or
@import 'YOUR_PACKAGE_NAME/semi.min.css'
```
