### ISSUE TITLE
[TimePicker] 弹出面板时会自动选择一个默认值

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#575]
### Which Component 出现bug的组件
  - TimePicker

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么

这个行为是否是预期的行为？看起来与其他输入+弹出层类组件不同。

### Steps to reproduce 复现步骤

![timepicker-select](https://user-images.githubusercontent.com/26477537/151482557-f3f70d7d-6593-455d-b348-660fe84d6fb8.gif)

### Reproducible code 复现代码
```
import React from 'react';
import { TimePicker } from '@douyinfe/semi-ui';

function Demo() {
    return <TimePicker />;
}

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
与设计师对齐结论：单纯点开后再clickoutside，不自动填入值更符合规范，也与datepicker对齐

**Comment by shijiatongxue** [comment]
v2.22.0 版本，TimePicker 默认情况下不会自动选择一个日期，开启无限滚动模式后，会默认选择日期。用户可以根据使用场景选择。
