### ISSUE TITLE
[TimePicker] 面板展开后会自动填入默认值

### ISSUE THREAD

**Issue by zwlafk** [DouyinFE/semi-design#578]
### Which Component 出现bug的组件
  - TimePicker

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 与其他输入类组件对齐(比如DatePicker)，保证交互体验的一致性

### Actual result 实际的结果是什么
  - 面板展开后会自动填入默认值   
  
![origin_img_v2_5324b61f-8d4e-474c-b0f7-d32ffc77e9cg](https://user-images.githubusercontent.com/24400915/151501762-c6c8d31e-29d3-44eb-8a28-cbdff9c135bf.gif)

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
与#575 重复
