### ISSUE TITLE
[TimePicker] 浮层计算弹出方向时闪烁

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#586]
### Which Component 出现bug的组件
  - TimePicker

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 不闪烁

### Actual result 实际的结果是什么
  - 

### Steps to reproduce 复现步骤
  - 见视频

https://user-images.githubusercontent.com/29626873/152735597-bf7d1ee9-006d-4e11-a419-4b8c09f3d6ea.mov

### Reproducible code 复现代码

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by shijiatongxue** [comment]
v2.9.1 fixed
