### ISSUE TITLE
[Select] 浮层闪烁，手动指定弹出方向后仍然闪烁

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#587]
### Which Component 出现bug的组件
  - Select

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 不闪烁

### Actual result 实际的结果是什么
  - 概率性闪烁，注意观察对勾

### Steps to reproduce 复现步骤
  - 1

https://user-images.githubusercontent.com/29626873/152736009-261b98d2-b5f5-4836-9787-897c4c02c9e6.mov

### Reproducible code 复现代码
```
import React from 'react';
import { Select } from '@douyinfe/semi-ui';

() => (
    <>
        <Select defaultValue='abc' style={{ width: 120 }} position="bottom">
            <Select.Option value='abc'>抖音</Select.Option>
            <Select.Option value='hotsoon'>火山</Select.Option>
            <Select.Option value='jianying' disabled>剪映</Select.Option>
            <Select.Option value='xigua'>西瓜视频</Select.Option>
        </Select>
        </>
);

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by YannLynn** [comment]
fixed in 2.18.0-beta
