### ISSUE TITLE
[Tooltip] 在 React17 里如果父级有阻止点击事件冒泡 Tooltip 收起会失效

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#593]
### Which Component 出现bug的组件
  - Tooltip

### semi-ui version
  - latest
    
### Actual result 实际的结果是什么
- 在 div 里点击 Button，tooltip 没有收起

![image](https://user-images.githubusercontent.com/26477537/152960247-c69122c0-d60f-416a-a670-172867b2bc35.png)

### Reproducible code 复现代码

https://codesandbox.io/s/react-event-dispath-f3l6y?file=/src/App.jsx:0-737

```
import "./styles.css";
import React, { useEffect } from "react";
import { Button, Tooltip } from "@douyinfe/semi-ui";
import { IconSemiLogo } from "@douyinfe/semi-icons";

function preventEvent(e) {
  e.stopPropagation();
}

/**
 *  stopPropagation 导致 document 没有触发 click，可能与 React 17 事件触发方式变更有关
 *
 * 点击 click me 展示 tooltip
 * 点击 hello semi 无法关闭 tooltip
 * 点击空白区域可以关闭 tooltip
 */
export default function App() {
  useEffect(() => {
    document.addEventListener("click", () => console.log("document click"));
  }, []);

  return (
    <div className="App" onClick={preventEvent} style={{ background: "red" }}>
      <Button icon={<IconSemiLogo />}>hello semi</Button>
      <Tooltip trigger="click">click me</Tooltip>
    </div>
  );
}
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by chenc041** [comment]
没有问题吧? 我用那个 code sandbox 的链接没有复现

mac os: 12.1 
chrome: 98.0.4758.80

**Comment by shijiatongxue** [comment]
> 没有问题吧? 我用那个 code sandbox 的链接没有复现
> 
> mac os: 12.1 chrome: 98.0.4758.80

这里换成 react 17

![image](https://user-images.githubusercontent.com/26477537/153759177-f8b3cb9f-5ec5-4c97-af7a-f13c2e8f7bbd.png)

**Comment by shijiatongxue** [comment]
## React 给出的解决办法

https://reactjs.org/blog/2020/08/10/react-v17-rc.html#fixing-potential-issues

不确定对于 Tooltip 组件是否有其他副作用

![image](https://user-images.githubusercontent.com/26477537/153791801-05d2b0dd-06e0-46fd-8c43-84ef23acc023.png)

**Comment by chenc041** [comment]
我也找到了这个解决办法
正准备提个 pr ...🐯

**Comment by shijiatongxue** [comment]
> 我也找到了这个解决办法 正准备提个 pr ...🐯

React 提出的方法 + document 监听 mousedown 会是一个解决办法。

监听 mousedown 的好处是，一般用户会在父级元素绑定 click 事件，Tooltip 作为子级触发 mousedown 事件即使向上冒泡也不会触发父级的 mousedown。

**Comment by shijiatongxue** [comment]
> 我也找到了这个解决办法 正准备提个 pr ...🐯

等你的 PR，haha

**Comment by chenc041** [comment]
> > 我也找到了这个解决办法 正准备提个 pr ...🐯
> 
> React 提出的方法 + document 监听 mousedown 会是一个解决办法。
> 
> 监听 mousedown 的好处是，一般用户会在父级元素绑定 click 事件，Tooltip 作为子级触发 mousedown 事件即使向上冒泡也不会触发父级的 mousedown。
> 
> 可以参考下 Select 的 clickoutside 的处理。
> 
> <img alt="image" width="1611" src="https://user-images.githubusercontent.com/26477537/153793464-6d5a24ef-b31f-4fdb-8bf0-22c4e33667b5.png">

那我到没有看到监听 mousedown 的解决方法
其实这这种问题一看就是事件流, 所以我早上 试着把绑定事件那边的第三个参数改成  true 就可以正常解决了  😂

**Comment by shijiatongxue** [comment]
> > > 我也找到了这个解决办法 正准备提个 pr ...🐯
> > 
> > 
> > React 提出的方法 + document 监听 mousedown 会是一个解决办法。
> > 监听 mousedown 的好处是，一般用户会在父级元素绑定 click 事件，Tooltip 作为子级触发 mousedown 事件即使向上冒泡也不会触发父级的 mousedown。
> > 可以参考下 Select 的 clickoutside 的处理。
> > <img alt="image" width="1611" src="https://user-images.githubusercontent.com/26477537/153793464-6d5a24ef-b31f-4fdb-8bf0-22c4e33667b5.png">
> 
> 那我到没有看到监听 mousedown 的解决方法 其实这这种问题一看就是事件流的问题, 所以我早上试着把绑定事件那边的第三个参数改成 true 就可以正常解决了 😂

是的，事件流的方式也可以解决。

**Comment by shijiatongxue** [comment]
2.5.0 fixed
