### ISSUE TITLE
Semi Pro何时发布

### ISSUE THREAD

**Issue by strongyc** [DouyinFE/semi-design#603]
### Which Component Need Enhancement 期望新增功能的组件
- Button
Semi Pro何时发布
### What does the proposed API look like 期望支持的API
Semi Pro何时发布
### Feature Description 功能描述
Semi Pro何时发布
### Additional information 补充说明
Semi Pro何时发布

**Comment by shijiatongxue** [comment]
这个问题在 discussion 区有讨论哦，可以移步 discussion 区。

https://github.com/DouyinFE/semi-design/discussions/288
https://github.com/DouyinFE/semi-design/discussions/195

这个 issue 我觉得可以关掉了
