### ISSUE TITLE
[Select]键盘上下切换选项时，希望有滚动条的情况会自动跟着向下滚动

### ISSUE THREAD

**Issue by boomboomchen** [DouyinFE/semi-design#607]
### Which Component 出现bug的组件
  - Select

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 键盘上下切换选项时，有滚动条的情况不会自动跟着向下滚动

### Actual result 实际的结果是什么
  - 键盘上下切换选项时，希望有滚动条的情况会自动跟着向下滚动

### Steps to reproduce 复现步骤
  - 1 打开下拉框，键盘按上下键切换到底部 item，滚动条不会随之滚动

### Reproducible code 复现代码
```
import React from 'react';
import { Select } from '@douyinfe/semi-ui';

() => (
    <Select defaultValue='abc' style={{ width: 120 }}>
        <Select.Option value='abc'>抖音</Select.Option>
        <Select.Option value='hotsoon'>火山</Select.Option>
        <Select.Option value='jianying'>剪映</Select.Option>
        <Select.Option value='xigua'>西瓜视频</Select.Option>
        <Select.Option value='asd'>asd</Select.Option>
        <Select.Option value='sdf'>sdf</Select.Option>
        <Select.Option value='qwe'>qwe</Select.Option>
        <Select.Option value='zxc'>zxc</Select.Option>
        <Select.Option value='xcv'>xcv</Select.Option>
        <Select.Option value='cvb'>cvb</Select.Option>
        <Select.Option value='dfg'>dfg</Select.Option>
        <Select.Option value='ert'>ert</Select.Option>
    </Select>
);
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
https://github.com/DouyinFE/semi-design/blob/5865d5ce4c7e10edea4c625b2d247a97df08a9bb/packages/semi-foundation/select/foundation.ts#L707

理论上这个地方需要加下 scrollIntoView 就可以解决

**Comment by chenzn1** [comment]
https://github.com/DouyinFE/semi-design/pull/653
