### ISSUE TITLE
读书人的事？

### ISSUE THREAD

**Issue by SlenderMan-D** [DouyinFE/semi-design#61]
孔乙己便涨红了脸，额上的青筋条条绽出，争辩道，“窃书不能算偷……窃书！……读书人的事，能算偷么？”接连便是难懂的话，什么“君子固穷”，什么“者乎”之类，引得众人都哄笑起来：店内外充满了快活的空气。

**Comment by jasonHzq** [comment]
蚂蚁前端跳到字节之后的作品？

**Comment by xiangshouding** [comment]
@jasonHzq 感兴趣请看代码，不要冷嘲热讽；如果你觉着你更优秀，你可以 share 一下你的成果出来。

**Comment by Bosn** [comment]
@xiangshouding 感兴趣请自己上世界杯，不要冷嘲热讽；如果你觉着你踢的更好，你可以 share 一下你世界杯的名次出来。
