### ISSUE TITLE
[Slider]希望增大触发位移的热区，支持点击marks也能够触发滑块改变位置

### ISSUE THREAD

**Issue by boomboomchen** [DouyinFE/semi-design#618]
### Which Component Need Enhancement 期望新增功能的组件
- Slider

### What does the proposed API look like 期望支持的API
希望支持点击marks也能够触发滑块改变位置

<img width="455" alt="截屏2022-02-14 下午3 37 05" src="https://user-images.githubusercontent.com/36157654/153820281-1a7aff77-a930-44cc-9ba1-21773a3cc5e9.png">

**Comment by huruji** [comment]
@boomboomchen I made a MR，see https://github.com/DouyinFE/semi-design/pull/871

**Comment by shijiatongxue** [comment]
v2.12.0-beta.0 supported
