### ISSUE TITLE
[Anchor]在某些使用场景下，灰色导航线不显示

### ISSUE THREAD

**Issue by boomboomchen** [DouyinFE/semi-design#625]
### Which Component 出现bug的组件
  - Anchor

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 导航条正常显示

### Actual result 实际的结果是什么
  - 导航条不显示

### Steps to reproduce 复现步骤
  - 1 

### Reproducible code 复现代码
灰色导航线消失，但在官网暂时没复现。项目中的使用代码类似如下

```
import React from 'react';
import { Anchor } from '@douyinfe/semi-ui';

() => {
    const MyComponent = React.memo(function MyComponent(props) {
        return (
            <Anchor scrollMotion offsetTop={100}>
                <Anchor.Link href="#基本示例" title="基本示例" />
                <Anchor.Link href="#组件" title="组件" />
                <Anchor.Link href="#设计语言" title="设计语言" />
                <Anchor.Link href="#物料平台" title="物料平台" />
                <Anchor.Link href="#主题商店" title="主题商店" />
            </Anchor>

        )
    });
    return <MyComponent/>;
};
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by shijiatongxue** [comment]
## 原因分析

![image](https://user-images.githubusercontent.com/26477537/154192446-16cdb0e3-a26b-43e4-845d-2a1cf47e50f7.png)

Anchor 中导轨的高度是根据内容的高度动态计算的，这样做的原因是确保 Anchor 有 max-height 时，导轨的高度与内容的高度一致。

出现这个不显示是因为这个高度计算错了，获取的 scrollHeight 为 0。为啥是 0 需要排查一下。

![image](https://user-images.githubusercontent.com/26477537/154192564-9046804e-62d3-4235-9941-91bb7db21fae.png)
