### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by H3lloTom** [DouyinFE/semi-design#626]
### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - @douyinfe/semi-ui没有声明@douyinfe/semi-animation这个依赖，但是在代码内直接引用了，不符合包依赖规范

### Actual result 实际的结果是什么
  - 

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```
class Demo extends React.component {

    render() {
        return (
            <Button>bug</Button>
        )
    }

}

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
fix v2.4.1
