### ISSUE TITLE
semi-next 导致 原来next.config.js 中部分配置失效

### ISSUE THREAD

**Issue by geekpeng** [DouyinFE/semi-design#630]
### Which Component 出现bug的组件
  - semi-ui  

### semi-ui version
  - latest

### Actual result 实际的结果是什么
  - 
<img width="978" alt="image" src="https://user-images.githubusercontent.com/5426866/154426093-43120805-10ee-440b-8b67-1c2f6a0c4e1b.png">

### Steps to reproduce 复现步骤
  - nextjs 中使用 semi-ui   引入 semi-next  按官网文档修改  next.config.js  文件之后 导致原来配置 路径别名不能解析了

### Reproducible code 复现代码
```
const { i18n } = require('./next-i18next.config');
const path = require('path');

const semi = require('@douyinfe/semi-next').default({
    /* the extension options */
});

module.exports = semi({
    i18n,
    webpack: config => {
        config.resolve.alias['@'] = path.resolve(__dirname);
        return config;
    },
    async rewrites() {
        return [
            {
                source: '/api/:path*',
                destination: `http://127.0.0.1:9001/:path*`,
            },
        ]
    }
})

```

**Comment by pointhalo** [comment]
本地试了下可以复现，我跟进下~ 

semi-next内并没有修改alias相关的配置，只是简单地追加了push了一个plugin，并且追加一下exclude。但log了一下，我们在plugin内部只能获取到next 内部自带的alias，所以你自定义配置的失效了。具体怎么解决我需要时间研究一下next

![image](https://user-images.githubusercontent.com/88709023/154636512-34003e04-9706-4395-a24b-317dfbcbafad.png)

或者你可以先试下以官网文档推荐的这个方式来指定 alias：https://nextjs.org/docs/advanced-features/module-path-aliases

**Comment by pointhalo** [comment]
已定位问题，下个版本修复。

**Comment by pointhalo** [comment]
可以试下最新版的插件。应该ok了 @geekpeng

**Comment by geekpeng** [comment]
> 

好的 谢谢
