### ISSUE TITLE
自定义 Icon 并用在 Input 的 prefix 时不符合预期

### ISSUE THREAD

**Issue by laozhu** [DouyinFE/semi-design#633]
### Which Component 出现bug的组件
  - Icon
  - Input

### semi-ui version
  - "@douyinfe/semi-icons": "^2.4.0",
  - "@douyinfe/semi-ui": "^2.4.0",
    
### Expected result 期望的结果是什么
  - 将自定义的 Icon 组件传给 Input 的 prefix 属性，和 semi 自带的 Icon 组件样式保持一致

### Actual result 实际的结果是什么
  - 实际上，两种 Icon 的样式并不一致

### Steps to reproduce 复现步骤

1. 自定义一个 Icon，传入 svg 属性
2. 在 Input 组件传入该 Icon 作为 prefix

### Reproducible code 复现代码

<https://codesandbox.io/s/semi-ui-custom-icon-bug-r9zj3w>

### Additional information 补充说明

- 效果截图

<img width="541" alt="image" src="https://user-images.githubusercontent.com/1212457/154629057-f9a59d38-b7ec-4d19-9935-c63580c1bf38.png">

[点击预览](https://r9zj3w.csb.app/)

- 可能的原因

自定义的 Icon 比自带的 Icon 少了一个 className: `semi-input-prefix-icon`，导致缺少了样式

```css
color: var(--semi-color-text-2);
margin: 0 8px;
```

**Comment by shijiatongxue** [comment]
可以使用 Semi Icon 包裹一下。

```
import { Input } from '@ies/semi-ui-react';

() => (
  <Input defaultValue='hi' prefix={<Icon type={YOUR_SVG} />}></Input>
)

```

**Comment by shijiatongxue** [comment]
这里我理解是符合预期的，prefix 如果是自定义，不会包含 icon 的样式在里面。所以用 Semi Icon 包裹起来也合适。

**Comment by pointhalo** [comment]
@shijiatongxue 可以统一补充一下文档说明（Select、Input、TreeSelect、Cascader、AutoComplete……）吧。现在可能某些组件内有写，input看了下，好像漏了关于 prefix、suffix为字符串、semi自带 icon、自定义reactNode时的padding说明。

**Comment by laozhu** [comment]
@shijiatongxue 您好，我就是用 Icon 组件包装了一遍，您看下 [codesandbox](https://codesandbox.io/s/semi-ui-custom-icon-bug-r9zj3w) 里的代码，并不是直接传 svg 给 prefix 的。

**Comment by laozhu** [comment]
@pointhalo 如果是自定义 Icon 的话，那正确的做法是什么呢，是自己给 icon 传样式或者 className 吗，像下面这样的？

```jsx
<Input prefix={<IconSms style={{ margin: '0 8px' }} />} />
```

**Comment by shijiatongxue** [comment]
> @pointhalo 如果是自定义 Icon 的话，那正确的做法是什么呢，是自己给 icon 传样式或者 className 吗，像下面这样的？
> 
> ```js
> // 这里的 `IconSms` 是我用 Icon 封装过的
> <Input prefix={<IconSms style={{ margin: '0 8px' }} />} />
> ```

代码里的判断比较严格，如果你用一个组件包裹的话，其实就识别不出来了。

![image](https://user-images.githubusercontent.com/26477537/154639688-ff94a744-d499-4bdd-bb91-7242104a2b97.png)


这样写就好了。

![image](https://user-images.githubusercontent.com/26477537/154639072-d7eca38a-cda3-4d0d-8afc-6fa29cbfb8eb.png)

**Comment by shijiatongxue** [comment]
> @pointhalo 如果是自定义 Icon 的话，那正确的做法是什么呢，是自己给 icon 传样式或者 className 吗，像下面这样的？
> 
> ```js
> // 这里的 `IconSms` 是我用 Icon 封装过的
> <Input prefix={<IconSms style={{ margin: '0 8px' }} />} />
> ```

这么做 ok。

**Comment by laozhu** [comment]
谢谢啦，其实我本来是想基于 semi 的`Icon` 组件和 svgr 封装一个内部的 icons 扩展包，然后在多个公司项目里消费，不想直接写到页面里面。现在我给自定义 Icon 组件统一加上了 `className` 和 `style` 属性，然后按需要加样式好了，这样能解决问题了，就是不够简洁，和 semi 内部 icons 使用上有些不一样😄

**Comment by shijiatongxue** [comment]
> 谢谢啦，其实我本来是想基于 semi 的`Icon` 组件和 svgr 封装一个内部的 icons 扩展包，然后在多个公司项目里消费，不想直接写到页面里面。现在我给自定义 Icon 组件统一加上了 `className` 和 `style` 属性，然后按需要加样式好了，这样已经能解决我的问题了。就是不够简洁，和 semi 内部 icons 使用上有些不一致，稍微有点不完美 😄

赞

**Comment by laozhu** [comment]
@shijiatongxue 对了，这个 `isSemiIcon` 的函数判断条件如果放松一点，是不是可以呢？

```js
get(icon.type, 'elementType').startsWith('Icon')
```

**Comment by shijiatongxue** [comment]
> 

不太可能遍历一遍里面的节点类型。

**Comment by laozhu** [comment]
@shijiatongxue 👌明白了，谢谢你
