### ISSUE TITLE
[Table] 表头文字支持选择复制

### ISSUE THREAD

**Issue by zwlafk** [DouyinFE/semi-design#638]
### Which Component Need Enhancement 期望新增功能的组件
- Table

### What does the proposed API look like 期望支持的API
enableTableHeaderUserSelect?
### Feature Description 功能描述
期望表文字能够选择复制, 目前semi table 表头默认样式是 `user-select : none`
### Additional information 补充说明
![image](https://user-images.githubusercontent.com/24400915/154674971-a7ed6474-3385-4d8c-89d8-61a8d5e3f6ef.png)

**Comment by pointhalo** [comment]
fix. 2.6.0-beta.0
