### ISSUE TITLE
[Form] 增加 readOnly, stopValidateWithError, trigger 等属性

### ISSUE THREAD

**Issue by laozhu** [DouyinFE/semi-design#640]
### Which Component Need Enhancement 期望新增功能的组件
- Form

### What does the proposed API look like 期望支持的API
期望 Form 能多支持一些统一的表单设置，而无需针对每一个表单组件来设置，如：

- readOnly
- stopValidateWithError
- trigger

就像现在在表单上设置 `disabled` 会禁用整个表单一样，以上属性可以简化大表单的代码。

**Comment by pointhalo** [comment]
1、readOnly 这个暂不考虑在Form层级添加，因为并非所有组件都提供这个接口。透传下去可能会对 Field 级别的组件造成影响（例如透传至原生dom上造成额外的waring）
2、stopValidateWithError、trigger 可以在后续版本加上

**Comment by pointhalo** [comment]
support [v2.42.0-beta.0](https://github.com/DouyinFE/semi-design/releases/tag/v2.42.0-beta.0)
