### ISSUE TITLE
反馈类 · Notification

### ISSUE THREAD

**Issue by CasualMing** [DouyinFE/semi-design#65]
### Which Component Need Enhancement 期望新增功能的组件
- Notification

### Additional information 补充说明
> notification 当有多个显示在页面上的时候，不应该是先进先出嘛？现在的展示效果是先进后出，最后展示的却最先消失，这个设计不太对啊，很可能我还没看清楚，就消失了

**Comment by shijiatongxue** [comment]
v2.3.0 已修复此问题

![image](https://user-images.githubusercontent.com/26477537/157447117-c7fbc4fe-4508-4a81-b85d-c5c4013d3c71.png)
