### ISSUE TITLE
[Table]动态修改 columns ，列宽设置失效

### ISSUE THREAD

**Issue by adwerrd** [DouyinFE/semi-design#650]
### Which Component 出现bug的组件
  - Table

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 动态减少列，不影响其他指定宽度的列

### Actual result 实际的结果是什么
  - 减少列时，第一列宽度过大

### Steps to reproduce 复现步骤
  - 初始状态，第一列宽度 设定为 300
![image](https://user-images.githubusercontent.com/8522625/155084715-0b22d45c-8902-437a-8d65-e7f07b50f1af.png)
  - 点击减少一列，宽度变成 344
![image](https://user-images.githubusercontent.com/8522625/155084747-b0ab99aa-4202-4625-8241-3db91c12bfc3.png)

### Reproducible code 复现代码

https://codesandbox.io/s/autumn-fast-h0e2hx?file=/src/App.js

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by shijiatongxue** [comment]
看起来是缓存错了，我们修下。

**Comment by shijiatongxue** [comment]
> 看起来是缓存错了，我们修下。

暂时可以通过给 column 添加一个 key 解决此问题。

**Comment by shijiatongxue** [comment]
## 问题原因

使用了缓存的 width，这里使用缓存的 width 是因为 column resize 后，如果表格刷新，应该保持住这个宽度。

![image](https://user-images.githubusercontent.com/26477537/155093761-9c8fde64-1890-4167-becd-3a7d48616304.png)

这里使用缓存的列匹配的是 column.key，如果没有给定 key Table 会分配一个，这里应该是没有 key，按照顺序分配了一个，结果匹配到了删除列之前那个 column 的 width。

![image](https://user-images.githubusercontent.com/26477537/155093626-91ccd79b-76ff-490f-be7e-4b14b5bcb763.png)

![image](https://user-images.githubusercontent.com/26477537/155092076-828b96b1-d83e-4118-a281-a29bb8f261cf.png)
