### ISSUE TITLE
[Input] 按下态 bg color 与 Select 对齐

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#662]
### Which Component 出现bug的组件
  - Input

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
 
![image](https://user-images.githubusercontent.com/26477537/155666835-9f937abc-d9ea-4621-9197-76b41435e05c.png)

### Actual result 实际的结果是什么

![image](https://user-images.githubusercontent.com/26477537/155666751-d69f008b-6fcd-4472-9a0b-9593a330b7f8.png)

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by MaplePudding** [comment]
Maybe recently I can fix it
