### ISSUE TITLE
NavItem 工具提示无样式

### ISSUE THREAD

**Issue by zsmatrix62** [DouyinFE/semi-design#665]
请问我的nav item的提示会出现这种情况是怎么回事？ 自己用popover tooltip 组建也是这种透明的没有颜色

<img width="226" alt="image" src="https://user-images.githubusercontent.com/2951879/155761059-2599b4ce-3d42-4d1f-bb79-2cdc931733cf.png">

**Comment by DaiQiangReal** [comment]
可以给出复现 demo 吗

**Comment by zsmatrix62** [comment]
> 可以给出复现 demo 吗

我的demo在这个网站上 https://echoo.app 或者需要源代码嘛？

**Comment by pointhalo** [comment]
<img width="1786" alt="image" src="https://user-images.githubusercontent.com/88709023/155919392-737f25d7-a60d-47ab-aa1c-63d4d879baa7.png">

你是不是用了自定义主题？然后你的主题里删除了  --semi-grey-7 这个颜色的定义（事实上不仅是grey-7，看了下你这里整个grey 的色阶都不存在），所以这里透明了。

可以调整下你的主题。自定义的变量可以添加，但是原始的不需要删除。

<img width="601" alt="image" src="https://user-images.githubusercontent.com/88709023/155919547-39eaf103-5753-4a5d-9788-19b7354bb81d.png">

**Comment by pointhalo** [comment]
> <img alt="image" width="1786" src="https://user-images.githubusercontent.com/88709023/155919392-737f25d7-a60d-47ab-aa1c-63d4d879baa7.png">
> 
> 你是不是用了自定义主题？然后你的主题里删除了 --semi-grey-7 这个颜色的定义（事实上不仅是grey-7，看了下你这里整个grey 的色阶都不存在），所以这里透明了。
> 
> 可以调整下你的主题。自定义的变量可以添加，但是原始的不需要删除。
> 
> <img alt="image" width="601" src="https://user-images.githubusercontent.com/88709023/155919547-39eaf103-5753-4a5d-9788-19b7354bb81d.png">

诶，你是直接用的  @semi-bot/semi-theme-universedesign 整个主题对吗？

**Comment by Carlosfengv** [comment]
如果是引用了主题包 @semi-bot/semi-theme-universedesign  ，请更新至 1.0.1 版本

**Comment by zsmatrix62** [comment]
果然升级了包就好了 ... 谢谢。

![image](https://user-images.githubusercontent.com/2951879/155926051-73205d59-4bde-4e7e-8847-6be34ce77555.png)
