### ISSUE TITLE
[TimePicker] 1.17 版本在某些场景下会抖动并选择负值

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#681]
### Which Component 出现bug的组件
  - TimePicker

### semi-ui version
  - v 1.17
    
### Expected result 期望的结果是什么
  - 

### Actual result 实际的结果是什么
  - 

### Steps to reproduce 复现步骤

- [ ] 复现起来比较难，待补充

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by YannLynn** [comment]
复现条件比较苛刻，且没有稳定复现路径，先关闭issue，有稳定复现路径后再开启
