### ISSUE TITLE
DatePicker 下拉框闪烁

### ISSUE THREAD

**Issue by limenglin0717** [DouyinFE/semi-design#69]
### Which Component 出现bug的组件
  - DatePicker

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 向上展开日期选择框

### Actual result 实际的结果是什么
  - 会向下展开闪烁一次，再向上展开
![Kapture 2021-10-27 at 11 14 39](https://user-images.githubusercontent.com/21357883/138994238-97d4ae35-66b6-4d42-9e13-355602e0e719.gif)

### Steps to reproduce 复现步骤
  - 1 将组件滚动到页面底部
  - 2 点击展开日期选择框

### Additional information 补充说明
- 官网demo

**Comment by pointhalo** [comment]
![image](https://user-images.githubusercontent.com/88709023/149883150-18c2df1e-03b5-4712-a97e-25e3436a64c9.png)

fix after v2.3.0-beta.0
