### ISSUE TITLE
The ButtonGroup let its "className" prop set to its children buttons,.

### ISSUE THREAD

**Issue by NsGFr** [DouyinFE/semi-design#690]
### Which Component 出现bug的组件
  - ButtonGroup

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - reserve its self className by developer given

### Actual result 实际的结果是什么
  -  the className prop used in its children Buttons

**Comment by shijiatongxue** [comment]
这是一个 Bug，有兴趣提交一个 PR 解决这个问题吗？

问题：

![image](https://user-images.githubusercontent.com/26477537/157367462-7b0af0fe-6a95-4d78-afcb-39570ab7b0c8.png)

问题位置：

![image](https://user-images.githubusercontent.com/26477537/157367559-a3a241a6-3035-485c-b9f9-d60abe3abf2f.png)
