### ISSUE TITLE
[Tabs] mouseDown 事件触发导致 TabItem 卸载，onTabClick 点击失效

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#693]
### Which Component 出现bug的组件
  - Tabs

### semi-ui version
  - 2.5 ~
    
### Expected result 期望的结果是什么
  - 点击 TabItem 正常切换 Tab

### Actual result 实际的结果是什么
  - mouse down 导致 Dropdown 直接关闭

### Steps to reproduce 复现步骤

使用 mouse down 而不触发 mouse up，例如使用触控板按下
 
![image](https://user-images.githubusercontent.com/26477537/157407821-521032c3-8f38-4613-a8e3-decb0de8ac60.png)

### Reproducible code 复现代码
```
import React from 'react';
import { Tabs, TabPane } from '@douyinfe/semi-ui';

class App extends React.Component {
    render() {
        return (
            <Tabs style={{ width: '60%', margin: '20px' }} type="card" collapsible>
                {[0, 1, 2, 3, 4, 5, 6, 7, 8, 9].map(i => (
                    <TabPane tab={`Tab-${i}`} itemKey={`Tab-${i}`} key={i}>
                        Content of card tab {i}
                    </TabPane>
                ))}
            </Tabs>
        );
    }
}
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

问题出现的原因，mouse down 触发了 Tooltip 的 hide 行为，然后 TabItem 卸载了

![image](https://user-images.githubusercontent.com/26477537/157408253-fd02122e-0014-41bc-9669-f49423ddc72e.png)

**Comment by pointhalo** [comment]
> 在 2.10.1 发布后验证一下这个问题

昨天发过了2.10.1，待会我更新下changelog

**Comment by pointhalo** [comment]
直接在官网试了下，问题依旧。
