### ISSUE TITLE
[Tag] Tag 组件的 onClick 方法 入参 Event 没有 target 

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#698]
### Which Component 出现bug的组件
  - Tag

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - onClick 入参没有 target

### Actual result 实际的结果是什么
  - 有 target

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```
import React from 'react';
import { Tag, Space } from '@douyinfe/semi-ui';

() => (
    <div>
        <Space>
            <Tag onClick={(...args)=>console.log(args)}> default tag </Tag>
            
        </Space>
    </div>
);

```

### Additional information 补充说明
![middle_img_v2_a02fd692-844c-4299-b702-858a1303045g](https://user-images.githubusercontent.com/29626873/157796365-8bab1e0f-8d4a-49a5-a1f9-75f3c52455c5.png)

**Comment by oddguan** [comment]
这里看了一下，直接log `event.target`是可以拿到的：
<img width="527" alt="image" src="https://user-images.githubusercontent.com/14129720/159233900-b5077e5a-7eb5-4d71-89ff-d405c3a0c1d0.png">
<img width="409" alt="image" src="https://user-images.githubusercontent.com/14129720/159234028-b74c1509-fef9-4732-ac46-84c0ff7cbbb7.png">
上图中的bug是不是只是因为在控制台拿target值的时候，可能event中的各种指针被故意设置成了null（应该是为了垃圾回收？）导致所有的成员都指向null。这个算bug嘛

**Comment by DaiQiangReal** [comment]
> 这里看了一下，直接log `event.target`是可以拿到的： <img alt="image" width="527" src="https://user-images.githubusercontent.com/14129720/159233900-b5077e5a-7eb5-4d71-89ff-d405c3a0c1d0.png"> <img alt="image" width="409" src="https://user-images.githubusercontent.com/14129720/159234028-b74c1509-fef9-4732-ac46-84c0ff7cbbb7.png"> 上图中的bug是不是只是因为在控制台拿target值的时候，可能event中的各种指针被故意设置成了null（应该是为了垃圾回收？）导致所有的成员都指向null。这个算bug嘛

确实是这个原因。应该不算bug。
