### ISSUE TITLE
[Typography] ellipsis fails after page resize

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#706]
### Which Component Need Enhancement 期望新增功能的组件
- Typography

### What does the proposed API look like 期望支持的API
Recalculate ellipsis chars after window or Typography container resized.
### Feature Description 功能描述
Recalculate ellipsis chars after window or Typography container resized.
### Additional information 补充说明
Resizing window or Typography container will cause Typography ellipsis at wrong char. User have to remount Typography.

**Comment by pointhalo** [comment]
这个可以参考现在最新 Collapsible 的做法做改进？

**Comment by YyumeiZhang** [comment]
问题已修复
