### ISSUE TITLE
[TagInput] 编辑态需要支持拖拽排序

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#707]
### Which Component Need Enhancement 期望新增功能的组件
- TagInput

### What does the proposed API look like 期望支持的API
[TagInput] 编辑态需要支持拖拽排序
### Feature Description 功能描述
[TagInput] 编辑态需要支持拖拽排序  且不挤占相邻元素位置

**Comment by pointhalo** [comment]
v2.17.0-beta.0 已提供
