### ISSUE TITLE
[请教]代码实时预览功能

### ISSUE THREAD

**Issue by HBSI-baijinhao** [DouyinFE/semi-design#710]
对semi官网的代码实时预览功能很感兴趣,
请问monaco-editor编辑器输出的字符串是如何被渲染成react组件的,
方便透露一下吗?

**Comment by HBSI-baijinhao** [comment]
https://github.dev/DouyinFE/semi-design/blob/main/plugins/gatsby-remark-unwrap/index.js  貌似找到了

**Comment by pointhalo** [comment]
并不是二楼里的这个自定义plugin。主要是react-live这个库

**Comment by m7yue** [comment]
> 并不是二楼里的这个自定义plugin。主要是react-live这个库

haha, 一直在想怎么实现的，解答了我的疑惑，搞了一个接入的 [demo](https://github.com/m7yue/react-component-live)，可以考虑用在我们自己的组件库上了
