### ISSUE TITLE
Collapsible 点击其他区域，能够自动关闭

### ISSUE THREAD

**Issue by Rabbitzzc** [DouyinFE/semi-design#711]
### Which Component Need Enhancement 期望新增功能的组件
- Collapsible 

### What does the proposed API look like 期望支持的API
增加一个 autoClose 配置

### Feature Description 功能描述
类似于 select，点击其他区域会自动隐藏

**Comment by Rabbitzzc** [comment]
目前通过 react-cool-onclickoutside hook 可以解决这个问题

**Comment by pointhalo** [comment]
一般来说，我们只会给带有浮层的组件（如select、datepicker）增加clickOutSide 自动关闭浮层的操作（因为对用户来说，此时做clickOutSide的判断相对繁琐，需要同时判断 event触发 是否处于 浮层+ trigger两个区域）

对于collapsible来说，点击外部收起这个并非是通用交互，更多的是偏业务逻辑。而且能相对简单地通过react-clickoutside之类的库或者自己document上添加事件监听来实现。所以暂不计划追加🤝
