### ISSUE TITLE
[Select] when optionList is empty & turn on virtualize, there is extra white space in the floating layer

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#714]
### Which Component 出现bug的组件
  - Select

### semi-ui version
  - 2.6.0
    
### Expected result 期望的结果是什么
  - Direct display No data yet
  - 直接展示暂无结果
<img width="248" alt="image" src="https://user-images.githubusercontent.com/88709023/159625970-9b2dc9b6-66db-429f-832f-03c5024dc0b3.png">

### Actual result 实际的结果是什么
  - there is extra white space in the floating layer
  - 浮层中依然有一个空白的list，占据了高度。需滚动后才能展示 【暂无结果】
<img width="320" alt="image" src="https://user-images.githubusercontent.com/88709023/159626004-756d31ea-3f8d-403b-9d9a-767209e36fd1.png">

### Reproducible code 复现代码
```
import React from 'react';
import { Select } from '@douyinfe/semi-ui';
class VirtualizeDemo extends React.Component {
    constructor(props) {
        super(props);
        let newOptions = Array.from({ length: 3000 }, (v, i) => ({ label: `option-${i}`, value: i }));
        this.state = {
            optionList: newOptions,
        };
    }
    render() {
        let { groups, optionList } = this.state;
        let virtualize = {
            height: 300,
            width: '100%',
            itemSize: 36, // px
        };
        return (
            <>
                <Select
                    placeholder="拥有3k个Option的Select"
                    style={{ width: 260 }}
                    filter
                    onSearch={this.handleSearch}
                    virtualize={virtualize}
                    optionList={[]}
                ></Select>
            </>
        );
    }
}```

**Comment by Suvern** [comment]
👍

**Comment by oddguan** [comment]
这里不是因为virtualize给了一个`height: 300`才空出来了一片空白嘛？期望表现是忽略这个传进来的`height`？
