### ISSUE TITLE
table组件支持动态展示列名

### ISSUE THREAD

**Issue by strongyc** [DouyinFE/semi-design#722]
table组件支持动态展示列名，通过勾选可以展示需要和排除展示的列名

**Comment by pointhalo** [comment]
这个应该是可以通过自定动态更新 columns来实现的吧（而且对于列的勾选这类交互的操作，应该是在table外部，而非是table内），是遇到了什么使用上的问题吗？

**Comment by pointhalo** [comment]
The details of the requirements are not clear and will not be processed.
Close this issue, can reopen it if have additional information
