### ISSUE TITLE
DatePicker 可以加个type="year" 年份选择吗？

### ISSUE THREAD

**Issue by baiachen** [DouyinFE/semi-design#729]
### Which Component Need Enhancement 期望新增功能的组件
- DatePicker

### What does the proposed API look like 期望支持的API
type="year"
### Feature Description 功能描述
只限于年份选择

**Comment by pointhalo** [comment]
暂时没有这个打算。如果是仅仅进行年选择的时候，其实交互上跟Select已经没有区别了，有需求的用户可以通过简单封装Select实现亦可。

**Comment by baiachen** [comment]
好的
