### ISSUE TITLE
[ArrayField]希望ArrayField支持更多field props属性

### ISSUE THREAD

**Issue by Xieyongshen** [DouyinFE/semi-design#732]
### Which Component Need Enhancement 期望新增功能的组件
- Form.ArrayField

### What does the proposed API look like 期望支持的API
支持label、rules等其他field props的设置

### Feature Description 功能描述
支持直接在ArrayField组件上设置label、rules等信息，方便对表单项进行控制与校验

### Additional information 补充说明
如上

**Comment by pointhalo** [comment]
### Label
   这个如果要加比较简单，除布局外，也不会有其他附带影响

### Rules
在 ArrayField  支持 validate或者 rules 配置，这个暂时没有明确的处理计划。
主要考虑以下问题：

1. ErrorMessage展示位置的考虑，可能会有整体ArrayField级别的错误信息，但可能有的又是需要注入到行Field级别的，这个不好统一

2. 如果要支持 整体 ArrayField 级别的错误信息，它在 formState.errors中如何表达，是比较麻烦的问题。
- 当 ArrayField的 某一行children配置了 validate或rules，触发校验后该行存在 errorMessage、而ArrayField 整体又存在errorMessage时，两者无法共存
- 当同时存在 ArrayField 级别的校验器、Field级别的校验器时，顺序如何触发

**Comment by Xieyongshen** [comment]
> ### Label
> 这个如果要加比较简单，除布局外，也不会有其他附带影响
> 
> ### Rules
> 在 ArrayField  支持 validate或者 rules 配置，这个暂时没有明确的处理计划。 主要考虑以下问题：
> 
> 1. ErrorMessage展示位置的考虑，可能会有整体ArrayField级别的错误信息，但可能有的又是需要注入到行Field级别的，这个不好统一
> 2. 如果要支持 整体 ArrayField 级别的错误信息，它在 formState.errors中如何表达，是比较麻烦的问题。
> 
> * 当 ArrayField的 某一行children配置了 validate或rules，触发校验后该行存在 errorMessage、而ArrayField 整体又存在errorMessage时，两者无法共存
> * 当同时存在 ArrayField 级别的校验器、Field级别的校验器时，顺序如何触发

既然现在ArrayField和行Field都可以显式地指定不同的field标记（例如"array"和"array[0].text"），rules感觉也是可以按照对应指定的field进行设置的。例如ArrayField的field对应的是整个数组，rules也应该是针对整个数组进行校验。
1. ErrorMessage展示位置，ArrayField设置的field对应的是整个数组，这里rules校验后的信息看起来也应该是针对整个ArrayField级别的错误信息。
2. 关于ArrayField错误信息的表达，是否可以考虑：

- formState.errors中的错误信息分开进行独立展示，例如{ "array": "array error", "array[0].text": "array[0] text error" }。
- ArrayField某一行children的错误信息展示在对应表单项组件的后方，而ArrayField整体的错误信息展示在整个容器的后面，即所有children的后方。
- 同时存在ArrayField 级别的校验器、Field级别的校验器时，ArrayField 级别的校验器在所有children的数据发生变化时触发，Field级别的校验器在对应表单项组件发生交互时触发。

**Comment by pointhalo** [comment]
errors是一个object结构，不是一个map，它没法以这种方式存在``` { "array": "array error", "array[0].text": "array[0] text error" }```
