### ISSUE TITLE
DatePicker组件defaultPickerValue不生效

### ISSUE THREAD

**Issue by whj8** [DouyinFE/semi-design#735]
### Which Component 出现bug的组件
  - DatePicker

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 设置defaultPickerValue后，组件渲染设置的时间

### Actual result 实际的结果是什么
  - 设置defaultPickerValue后，组件没有渲染设置的时间

### Steps to reproduce 复现步骤
  - 1 在DatePicker组件中加入属性：defaultPickerValue={[Date.now(), Date.now()]}

### Reproducible code 复现代码
```
class Demo extends React.component {

    render() {
        return (
            <DatePicker
               format="yyyy-MM-dd HH:mm"
               type="dateTimeRange"
               defaultPickerValue={[Date.now(),Date.now()]}
           />
        )
    }

}

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by shijiatongxue** [comment]
可以看到有这个问题，我们看下。

**Comment by shijiatongxue** [comment]
> 可以看到有这个问题，我们看下。

defaultPickerValue 传数字时会解析失败，这是个 bug。你可以通过传 Date 对象或者一个与 format 匹配的字符串（2022-03-30 00:00:00）来避免这个问题。我们稍后修复下这个 bug。
