### ISSUE TITLE
select bug

### ISSUE THREAD

**Issue by boenfu** [DouyinFE/semi-design#743]
### Which Component 出现bug的组件
  - Select

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
不会崩溃

### Actual result 实际的结果是什么
崩溃

### Reason 原因是什么
处理高亮的时候，regex 应该转义一下，防止 new Regex 报错

### Steps to reproduce 复现步骤
  options label 中带 + 号
![image](https://user-images.githubusercontent.com/33797740/161378289-2ecfeee0-56f0-4926-b78f-8b6811413226.png)
filter 输入 `+` 号
![image](https://user-images.githubusercontent.com/33797740/161378295-7ba4fa60-e6d6-4f84-b0f0-13d2d9833d76.png)
其他特殊正则字符同理

### Reproducible code 复现代码
见图

### Additional information 补充说明
- 见 pr

**Comment by pointhalo** [comment]
fix,  v2.8.0-beta.1
