### ISSUE TITLE
react-sortable-hoc peer dependencies 不兼容 react 17 导致通过 pnpm 安装失败

### ISSUE THREAD

**Issue by YuanSa** [DouyinFE/semi-design#747]
使用 pnpm 在全新项目中运行 `pnpm add @douyinfe/semi-ui` 安装 semi 时报错：`Unmet peer dependencies`，package.json 中没有添加 `@douyinfe/semi-ui`
![screenshot](https://user-images.githubusercontent.com/13344375/161724724-f7a3c3dd-8a16-442c-827c-8727fa31261e.png)

**Comment by pointhalo** [comment]
看了下, v1.11.0的 react-sortable-hoc的pacakge.json
```
"peerDependencies": {
    "prop-types": "^15.5.7",
    "react": "^0.14.0 \|\| ^15.0.0 \|\| ^16.0.0",
     "react-dom": "^0.14.0 \|\| ^15.0.0 \|\| ^16.0.0"
}
```


在v2.0中这个包有修改 peerDependencies的版本
```
"peerDependencies": {
    "prop-types": "^15.5.7",
    "react": "^16.3.0 || ^17.0.0",
     "react-dom": "^16.3.0 || ^17.0.0"
}
```

理论上需要我们升级一下@douyinfe/semi-ui里依赖的版本

**Comment by pointhalo** [comment]
2.8.0 fix
