### ISSUE TITLE
Using with React 18 (@types/react)，type check error of children

### ISSUE THREAD

**Issue by wyb199877** [DouyinFE/semi-design#755]
### Which Component 出现bug的组件
  - Layout.Header
  - Layout.Content

### semi-ui version
  - 2.8.0
    
### Expected result 期望的结果是什么
  - 正常使用

### Actual result 实际的结果是什么
  - 仅正常使用代码就会报类型错误：
```
类型“{ children: Element; }”与类型“IntrinsicAttributes & IntrinsicClassAttributes<Component<BasicProps, any, any>> & Readonly<BasicProps>”不具有相同的属性。ts(2559)
```

### Steps to reproduce 复现步骤
  - 粘贴代码即可

### Reproducible code 复现代码
```ts
import { PureComponent } from 'react';
import { Layout, Nav } from '@douyinfe/semi-ui';

class App extends PureComponent {
  render() {
    const { Header, Sider, Content } = Layout;

    return (
      <div className="App">
        <Layout>
          <Header>Semi Design Demo</Header>
          <Layout>
            <Sider>
              <Nav
                defaultOpenKeys={['home']}
                items={[
                  { itemKey: 'home', link: '/home', text: 'Home' },
                  { itemKey: 'about', link: '/about', text: 'About' },
                ]}
              />
            </Sider>
            <Content>Semi Design Demo</Content>
          </Layout>
        </Layout>
      </div>
    );
  }
}

export default App;

```

### Additional information 补充说明
- ts类型错误

**Comment by wyb199877** [comment]
但只要我在`node_modules\@douyinfe\semi-ui\lib\es\layout\index.d.ts`这个文件中将`BasicLayoutProps`类型改成下面的样子就会消除报错：
```ts
export interface BasicProps {
    prefixCls?: string;
    style?: CSSProperties;
    className?: string;
    tagName?: keyof HTMLElementTagNameMap;
    type?: string;
    children?: ReactElement; // 新增的属性
}
```

**Comment by pointhalo** [comment]
项目中使用的react版本、react-dom版本、@types/react版本发一下？

**Comment by wyb199877** [comment]
抱歉，忘记写了：
react: 18.0.0
react-dom: 18.0.0
@types/react: 18.0.0



| |
王昱博
|
|
***@***.***
|
在2022年4月13日 ***@***.***> 写道：

***@***.***/react版本发一下？

**Comment by wyb199877** [comment]
> 项目中使用的react版本、react-dom版本、@types/react版本发一下？

后来我又试了一下，在16和17版本都是没问题的，应该只在18有问题

**Comment by pointhalo** [comment]
看了一下，react 18 他们移除了默认的children声明，囧，导致了一堆包也出现了同样的问题

**Comment by wyb199877** [comment]
> 看了一下，@types/react v18 移除了PureComponent和 Functional Component 上默认的children声明。所以如果组件自身未声明的在升级到18后都会有同样的问题

😂😂，我就说怎么在18里那么多组件会报类型错误，那我就关掉issue了

**Comment by pointhalo** [comment]
我们再观察一下，当前不确定他们是否要修复这个问题。如果他们不更新，我们会在组件侧追加 children的类型声明。

**Comment by wyb199877** [comment]
> 我们再观察一下，当前不确定他们是否要修复这个问题。如果他们不更新，我们会在组件侧追加 children的类型声明。

好的，感谢！

**Comment by pointhalo** [comment]
我计划修改一下你提的这个issue的 title 🤝 便于其他遇到同类问题的用户可以更轻易地检索到该问题。

**Comment by pointhalo** [comment]
我们计划在组件内统一增加一下声明，这个Issue我重新打开一下

**Comment by rojer95** [comment]
我最近更新了依赖，之后也遇到了和你一样的ts类型提示错误的问题..
研究了一下，貌似semi-ui中的有一个type为`@types/react-window`，他的依赖`@types/react`的版本号写的是`*`，
所以安装`@types/react`会安装为18的版本，不知道是不是这个导致的...

`yarn.lock`如下：

![image](https://user-images.githubusercontent.com/20662049/163399234-47884de7-9766-4458-bff8-f4da23f46e1a.png)

**Comment by pointhalo** [comment]
> 我最近更新了依赖，之后也遇到了和你一样的ts类型提示错误的问题.. 研究了一下，貌似semi-ui中的有一个type为`@types/react-window`，他的依赖`@types/react`的版本号写的是`*`， 所以安装`@types/react`会安装为18的版本，不知道是不是这个导致的...
> 
> `yarn.lock`如下：
> 
> ![image](https://user-images.githubusercontent.com/20662049/163399234-47884de7-9766-4458-bff8-f4da23f46e1a.png)

是这个原因，因为@types/react 做了breaking change😰 ，所以非常多react体系内的库都出现了类似问题。我们正在逐个组件追加，当前你也可以选择降级 @types/react 的版本临时规避问题。

**Comment by pointhalo** [comment]
fix v2.8.1
