### ISSUE TITLE
DatePicker 日期选择器，手动输入日期后，下方的日期没有切换

### ISSUE THREAD

**Issue by k8w** [DouyinFE/semi-design#758]
### Which Component 出现bug的组件
  - DatePicker
  
### semi-ui version
  - latest
   
### Steps to reproduce 复现步骤
  - 进入 https://semi.design/zh-CN/input/datepicker，在 【基本使用】 处
  - 点击 DatePicker
  - 输入 `2021-03-04`
  - 按下回车
 
### Expected result 期望的结果是什么
 - 修改生效，同时下方的选择器联动变化到输入的值（视觉上获得确认），如图
![image](https://user-images.githubusercontent.com/1681689/162919547-f6913d9a-e0d8-4908-a5fd-5016fdf691ff.png)

### Actual result 实际的结果是什么
![image](https://user-images.githubusercontent.com/1681689/162919675-855af990-dbc7-4d8b-a6e2-4d22cbcaf737.png)

### Additional information 补充说明

给 DatePicker 额外的建议：

也兼容形如 `20210304` `2021/03/04` 这样的输入，前者对数字工作者效率提升显著，后者有利于从其它处复制粘贴。

**Comment by shijiatongxue** [comment]
已知问题，已提 [PR](https://github.com/DouyinFE/semi-design/pull/742)。

建议也很好，这个也是有准备在优化的一项。

**Comment by shijiatongxue** [comment]
问题 v2.11 fixed，输入格式化是我们考虑在优化的一项。这个 issue 先 close 掉了。
