### ISSUE TITLE
 组件属性类型包含number，当该属性值设置成 NaN ， 如果该属性值被用在componDidUpdate中，使用===判断是否更新，会导致页面 crach（比如select的value属性）

### ISSUE THREAD

**Issue by YyumeiZhang** [DouyinFE/semi-design#763]
### Which Component 出现bug的组件
  - Select

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 正常显示NaN

### Actual result 实际的结果是什么
  - 页面崩溃
![select](https://user-images.githubusercontent.com/101110131/163307904-1298986a-1d52-4755-bcde-155ac0642a2a.png)

### Steps to reproduce 复现步骤
  - 

### Reproducible code 复现代码
```
import React from 'react';
import { Select } from '@douyinfe/semi-ui';

() => (
    <>
        <Select value={NaN} style={{ width: 120 }}>
            <Select.Option value='abc'>抖音</Select.Option>
            <Select.Option value='hotsoon'>火山</Select.Option>
            <Select.Option value='jianying' disabled>剪映</Select.Option>
            <Select.Option value='xigua'>西瓜视频</Select.Option>
        </Select>
    </>
);
```

### Additional information 补充说明
-

**Comment by pointhalo** [comment]
Components that require additional handling with isNaN （whose value supported number type）
- Select
- Rating
- Slider
- InputNumber
- Radio
- TreeSelect
- Tree

**Comment by edc-hui** [comment]
我来修复这个问题
