### ISSUE TITLE
Form.TagInput will trigger form submit event

### ISSUE THREAD

**Issue by so2liu** [DouyinFE/semi-design#767]
### Which Component 出现bug的组件
  - Form.TagInput

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 应该要阻止Form.TagInput的enter继续向上冒泡

### Actual result 实际的结果是什么
  -  Form.Input组件只能通过回车键添加tag，而回车键又会触发表单的提交

### Reproducible code 复现代码
https://codesandbox.io/s/unruffled-yonath-e5vpj5?file=/src/App.tsx

**Comment by pointhalo** [comment]
这个是标准HTML 行为。我们不计划进行干预。

【当form中仅有一个input时，enter键会触发submit事件，进而触发form的onSubmit回调】
【当form中有大于等于两个input时，enter不会触发submit事件】

详细可以参考这个：
http://david-chen-blog.logdown.com/posts/177766-how-forms-submit-when-pressing-enter

如果表单内确实只有一个Input元素（其他Select、Slider啥的不算），又不想回车时触发submit回调，`建议对input的keydown时的 enter采取preventDefault阻止默认行为`

```
() => {
    const { Option } = Form.Select;

    const oneInput = (e) => {
        if(e.keyCode==13){
            console.log('23')
            e.preventDefault();
        } 
    }
    return (
        <Form layout='horizontal'  onSubmit={()=>Toast.info('fe')}>
            <Form.Input field='UserName'  style={{width:80}} onKeyDown={oneInput}/>
        </Form>
    )
}
```

**Comment by so2liu** [comment]
> 这个是标准HTML 行为。我们不计划进行干预。会与原生保持一致。
> 
> 【当form中仅有一个input时，enter键会触发submit事件，进而触发form的onSubmit回调】 【当form中有大于等于两个input时，enter不会触发submit事件】
> 
> 详细可以参考这个： http://david-chen-blog.logdown.com/posts/177766-how-forms-submit-when-pressing-enter
> 
> 如果表单内确实只有一个Input元素（其他Select、Slider啥的不算），又不想回车时触发submit回调，`建议对input的keydown时的 enter采取preventDefault阻止默认行为`
> 
> ```
> () => {
>     const { Option } = Form.Select;
> 
>     const oneInput = (e) => {
>         if(e.keyCode==13){
>             e.preventDefault();
>         } 
>     }
>     return (
>         <Form layout='horizontal'  onSubmit={()=>Toast.info('fe')}>
>             <Form.Input field='UserName'  style={{width:80}} onKeyDown={oneInput}/>
>         </Form>
>     )
> }
> ```

但是目前当有多个input的时候，taginput依然会触发submit 。见我更新过的demo

https://codesandbox.io/s/unruffled-yonath-e5vpj5?file=/src/App.tsx

**Comment by pointhalo** [comment]
了解。感觉这里组件阻止下冒泡可能合理一些，我们再讨论下是否会有别的潜在影响。下周的版本处理一下

**Comment by pointhalo** [comment]
增加了一个 preventDefault 的逻辑。感觉相比阻止冒泡会更合理一些。跟 v2.9.0 版本发出。

**Comment by xmsz-stu** [comment]
```
import React from 'react';
import { Form, Tooltip, Button } from '@douyinfe/semi-ui';
import { IconHelpCircle } from '@douyinfe/semi-icons';

() => {
    const { Option } = Form.Select;
    const [key, setKey] = React.useState(0)

    return (
        <Form layout='horizontal' onSubmit={()=>{
            setKey(+new Date())
        }}>
        {key}
            <Form.Input field='UserName' label='用户名' style={{ width: 80 }}/>
            <Form.Input
                field='Password'
                label={{ 
                    text: '密码',
                    extra: <Tooltip content='详情'><IconHelpCircle style={{ color: 'var(--semi-color-text-2)' }}/></Tooltip> 
                }}
                style={{ width: 176 }}
            />
             <Button  htmlType='submit'>
            保存规则
          </Button>
       
        </Form>
    );
};

```

如果表单里有个`htmlType='submit'`的按钮，多个input回车也会触发onSubmit，这种情况怎么避免

**Comment by fengyxz** [comment]
> ```
> import React from 'react';
> import { Form, Tooltip, Button } from '@douyinfe/semi-ui';
> import { IconHelpCircle } from '@douyinfe/semi-icons';
> 
> () => {
>     const { Option } = Form.Select;
>     const [key, setKey] = React.useState(0)
> 
>     return (
>         <Form layout='horizontal' onSubmit={()=>{
>             setKey(+new Date())
>         }}>
>         {key}
>             <Form.Input field='UserName' label='用户名' style={{ width: 80 }}/>
>             <Form.Input
>                 field='Password'
>                 label={{ 
>                     text: '密码',
>                     extra: <Tooltip content='详情'><IconHelpCircle style={{ color: 'var(--semi-color-text-2)' }}/></Tooltip> 
>                 }}
>                 style={{ width: 176 }}
>             />
>              <Button  htmlType='submit'>
>             保存规则
>           </Button>
>        
>         </Form>
>     );
> };
> ```
> 
> 如果表单里有个`htmlType='submit'`的按钮，多个input回车也会触发onSubmit，这种情况怎么避免

情况一样，我的方法是设定
```
const handleKeyDown: KeyboardEventHandler = (event) => {
  if (event.key === 'Enter') {
    event.preventDefault();
  }
};

<Form
  onSubmit={onSubmit}
  onKeyDown={handleKeyDown} // 监听键盘按下事件
>
```
