### ISSUE TITLE
Collapse.Panel上不存在children属性

### ISSUE THREAD

**Issue by ascodelife** [DouyinFE/semi-design#772]
### Which Component 出现bug的组件
  - Collapse

### semi-ui version
  - 2.8.0
    
### Expected result 期望的结果是什么
  - 在Collapse.Panel中传入children属性

### Actual result 实际的结果是什么
  - ts类型报错 xxxx上不存在属性“children”，但实际渲染成功。

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```
import { Collapse } from "@douyinfe/semi-ui";

const Foo = () => {
  return (
    <Collapse>
      <Collapse.Panel header="This is panel header 1" itemKey="1">
        <p>Hi, bytedance dance dance. This is the docsite of Semi UI. </p>
      </Collapse.Panel>
      <Collapse.Panel header="This is panel header 2" itemKey="2">
        <p>Hi, bytedance dance dance. This is the docsite of Semi UI. </p>
      </Collapse.Panel>
      <Collapse.Panel header="This is panel header 3" itemKey="3">
        <p>Hi, bytedance dance dance. This is the docsite of Semi UI. </p>
      </Collapse.Panel>
    </Collapse>
  );
};

export default Foo;

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

![image](https://user-images.githubusercontent.com/26686921/163715214-7c2a3b2a-ed56-4df0-b6bd-c43ea1e6ea7a.png)

**Comment by ascodelife** [comment]
临时解决方案 自己打个补丁
```
declare module "@douyinfe/semi-ui/lib/es/collapse" {
  interface CollapsePanelProps {
    itemKey: string;
    extra?: ReactNode;
    header?: ReactNode;
    className?: string;
    reCalcKey?: number | string;
    style?: CSSProperties;
    children: ReactNode;
  }
}
```

**Comment by ascodelife** [comment]
react 版本是 18，打包工具是 vite，在打包的时候 tsc 发现了一些类型错误，不知道是不是组件库不兼容 react 18 的原因

**Comment by pointhalo** [comment]
与 #755 重复，这个先关掉了。问题的根本原因是 @types/react v18上周做了一个breaking change，删掉了 Component里的自带的children声明，所以基本上大部分react 库都受到了影响。可以先降级成 @types/react v17。
我们正在重新检查所有组件的interface声明，追加对应字段。

**Comment by pointhalo** [comment]
计划修复的PR：https://github.com/DouyinFE/semi-design/pull/771，预计这几天会合入。

**Comment by pointhalo** [comment]
fix v2.8.1
