### ISSUE TITLE
大量问题（有致命BUG，不敢用啊），请尽快修复

### ISSUE THREAD

**Issue by 497983606** [DouyinFE/semi-design#78]
### Which Component 出现bug的组件
  - Table （致命！）
  - Transfer （样式不严谨）
  - Toast （文档不严谨）
  - treeSelect （失控）
### semi-ui version
  - latest
### 浏览器版本
- 谷歌浏览器 版本 94.0.4606.81（正式版本） （64 位）windows 10 家庭版
### Steps to reproduce 复现步骤
  - Table 受控组件下开启列伸缩、表头筛选、固定表头，然后伸缩拖拽列宽，直接内存溢出，页面崩溃.（表头没对齐都是小事）
![image](https://user-images.githubusercontent.com/13822946/139009194-8cec258c-f4c8-4326-83aa-37b8b8e9ffde.png)

  - Transfer 有线头看着很难受，类似的card header 设计都有此类问题
![image](https://user-images.githubusercontent.com/13822946/139008181-2e041525-57b9-43d8-930f-d1fdd833c73a.png)
  - Toast 一种按钮对应一种吐司颜色，这里对不上了Success 应该是绿色
![image](https://user-images.githubusercontent.com/13822946/139008702-677e6754-5c8c-4568-a5a6-8eb64416df68.png)

  - treeSelect  选择面板隐藏的一瞬间 Asia 会从闭合状态下展开闪烁一下
![image](https://user-images.githubusercontent.com/13822946/139008528-1782f929-9f0d-4e52-b5e1-c4ad52c61ff9.png)

### Actual result 实际的结果是什么
  - 没有看
### End luck talk
非常漂亮高效的一款 UI ，我是一名全栈设计师，但目前还是不敢用啊，问题太多了，希望能尽快优化

**Comment by shijiatongxue** [comment]
除了 Table 的示例代码有问题，其他的 Bug/Style 问题在 @douyinfe/semi-ui@2.0.1 已修复。❤

Table 的问题请移步 issue #154 ~

**Comment by sunlifei1** [comment]
2021年11月2日，前端开发者小名同学带队赴DouyinFE/semi-design仓库调研开源组件开发工作推进情况。

在调研中，小名同学与开源团队的同学进行了亲切交流。

小名同学认为，此开源项目借鉴其他优秀的开源项目思想，是非常明智的可取行为，是站在巨人肩膀上对前端未来的一个眺望，望各位热心群众要秉承开源精神要求，认认真真思考借鉴并非抄袭这一症结，有序开展此开源项目的开发协助工作，突出用开源精神，武装头脑，指导实践，引导广大前端开发同学，坚守初心，推动开源项目建设工作高质量发展。

小名同学强调，要严格贯彻落实，确保责任到人。开源项目开发要做到常态化、责任化、经常化，确保建成一流开源项目。

此次调研开源项目工作中，了解到开发维护同学对此开源项目的十足信心，勉励同学努力保持开源项目的精神。小名同学语重心长的指出：“开源项目的发展道阻且长啊”

而后，相关负责人表示，要全面落实小名同学提出的各项方针，要狠抓落实，深化开源项目开发改革，紧密团结在以开源项目团队组长为代表的开发维护团队周围，切实优化开源项目使用流程，使整个开源项目达到一个新的顶峰。为互联网发展作出突出贡献和成绩，在人类计算机科学领域留下光辉的伟大篇章。

在此次观察工作中，小名同学提出“找Bug、改Bug＂的新一步开发标准化措施，最后，小名同学及其团队与开发团队同学一一亲切道别。

调研组还在仓库的Issues里察看了其他同学的项目优化建设情况。

小红同学,小张同学,小李同学等三位领导陪同调研。
