### ISSUE TITLE
InputNumber precision 删除后，输入非法字符显示 0.00

### ISSUE THREAD

**Issue by shijiatongxue** [DouyinFE/semi-design#786]
### Which Component 出现bug的组件
  - InputNumer

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 不带精度的 InputNumber 删除后输入非法值会置空

### Actual result 实际的结果是什么
  - 带精度的 InputNumber 删除后输入非法值会显示 0.00

### Steps to reproduce 复现步骤

![inputNumber-precision-bug](https://user-images.githubusercontent.com/26477537/164590016-f2623649-b122-4dea-8587-042a31e98df7.gif)

### Reproducible code 复现代码
```
import React from 'react';
import { InputNumber } from '@douyinfe/semi-ui';

() => (
    <div style={{ width: 280 }}>
        <InputNumber min={1} max={10} precision={2} />
        <br/><br/>
        <InputNumber min={1} max={10} />
        <br/><br/>
    </div>
);
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by MuxinFeng** [comment]
https://github.com/DouyinFE/semi-design/pull/810，小弟提了个pr

**Comment by pointhalo** [comment]
fix v2.10.0
