### ISSUE TITLE
使用Card组件ts类型提示“Card”不能用作 JSX 组件。

### ISSUE THREAD

**Issue by zk8080** [DouyinFE/semi-design#793]
### Which Component 出现bug的组件
  - Card

### semi-ui version
  - 2.9.0
    
### Expected result 期望的结果是什么
  - 没有ts错误提示

### Actual result 实际的结果是什么
  - ts类型报错：
  “Card”不能用作 JSX 组件。
  其实例类型 "Card" 不是有效的 JSX 元素。
    在这些类型中，"render()" 返回的类型不兼容。
      不能将类型“React.ReactNode”分配给类型“import("/Users/xx/node_modules/@types/react-window/node_modules/@types/react/index").ReactNode”。
        不能将类型“{}”分配给类型“ReactNode”。

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```
import { Card } from '@douyinfe/semi-ui';

const { Meta } = Card;

export default function IndexPage() {
  return (
    <div>
      <Card
        shadows="hover"
        style={{ maxWidth: 300 }}
        cover={
          <img
            alt="example"
            src="https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/root-web-sites/card-cover-docs-demo2.jpeg"
          />
        }
      >
        <Meta title="卡片封面" />
      </Card>
    </div>
  );

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
这个问题是由于你项目里存在两个版本的 @types/react ：VersionA.ReactNode !== VersionB.ReactNode。
需要你锁一下版本。如果是yarn可以通过 resolutions 指定一下，npm用 overrides

要么直接都用@types/react v18

**Comment by pointhalo** [comment]
不统一版本的话，这个问题没法解决。因为不光是 @types/react-window 这个包写的 @types/react是*，连 @types/react-dom也是这么写的，它也会导致你安装到 v18

**Comment by pointhalo** [comment]
pacakge.json

```
// if yarn
  "resolutions": {
    "@types/react": "^18.0.5",
    "@types/react-dom": "^18.0.1"
  },

// if npm
  "overrides": {
    "@types/react": "^18.0.5",
    "@types/react-dom": "^18.0.1"
  },

```
