### ISSUE TITLE
Notch & Software Navigation support

### ISSUE THREAD

**Issue by timothymiller** [DouyinFE/semi-design#794]
### Which Component Need Enhancement 期望新增功能的组件
- Toast

### What does the proposed API look like 期望支持的API

`padding-top: calc(20px + env(safe-area-inset-top));
`
### Feature Description 功能描述

Add additional paddingTop equal to `safe-area-inset` to support Notches & software navigation

### Additional information 补充说明

The existing `@douyinfe/semi-ui` package version `2.9.0` looks like this

<img width="495" alt="Screen Shot 2022-04-25 at 21 24 33 (2)" src="https://user-images.githubusercontent.com/46549361/165200662-321963b4-a144-4789-85ce-6af0ac51e26a.png">

**Comment by pointhalo** [comment]
Toast already provides props.top to customize the distance from the top of the pop-up position
```
Toast.info({ top: 30, content: 'test test test' });
```
Here is the hope that we can provide another API that can automatically adapt to the top safe area of iOS?
