### ISSUE TITLE
peer dependencies warning for react18

### ISSUE THREAD

**Issue by Xwudao** [DouyinFE/semi-design#798]
### Which Component 出现bug的组件
  - Dependencies 

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 

### Actual result 实际的结果是什么

```
 WARN  Issues with peer dependencies found
├─┬ @douyinfe/semi-ui
│ ├─┬ @douyinfe/semi-icons
│ │ └── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
│ ├─┬ @douyinfe/semi-illustrations
│ │ └── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
│ ├─┬ react-resizable
│ │ ├── ✕ unmet peer react@"0.14.x || 15.x || 16.x || 17.x": found 18.0.0
│ │ └── ✕ unmet peer react-dom@"0.14.x || 15.x || 16.x || 17.x": found 18.0.0
│ └─┬ react-sortable-hoc
│   ├── ✕ unmet peer react@"^16.3.0 || ^17.0.0": found 18.0.0
│   └── ✕ unmet peer react-dom@"^16.3.0 || ^17.0.0": found 18.0.0
└─┬ recoil-persist
  └── ✕ unmet peer recoil@^0.6.1: found 0.7.2

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
1. We will update the peer dependency declaration of icons and illustrations soon
2. But upstream dependencies: `react-resizable` and `react-sortable-hoc` may not be handled very quickly, depending on the authors of these packages. And the latter seems to be planned to stop maintenance, we may need to migrate to a new dependency package to continue to provide the same functionality #799

**Comment by orangecoding** [comment]
Hi. 

any news on when to update the peer dependencies?

**Comment by pointhalo** [comment]
> Hi.
> 
> any news on when to update the peer dependencies?

Sorry, no more progress here. But fortunately peer is not a blocking item, you can choose to skip warning.
We can't do much more with upstream npm packages here.

**Comment by pointhalo** [comment]
solve after v2.41.0-beta.0
