### ISSUE TITLE
在 Card 组件的 headerExtraContent 中无法使用 ButtonGroup

### ISSUE THREAD

**Issue by Moroshima** [DouyinFE/semi-design#811]
### Which Component 出现bug的组件
  - Card with ButtonGroup

### semi-ui version
  - 版本大于 2.6.0
  - 实测 2.7.1 - 2.9.0 都存在该问题
    
### Expected result 期望的结果是什么
  - ButtonGroup 在 Card 卡片标题右侧的额外内容处正常显示

### Actual result 实际的结果是什么
  - ERROR
  - ```bash
    TS2746: This JSX tag's 'children' prop expects a single child of type '(ReactChild & (boolean | ReactChild | ReactFragment | ReactPortal | null)) | undefined', but multiple children were provided.
    ```


### Steps to reproduce 复现步骤
  - 向 Card 的 headerExtraContent 传入 <ButtonGroup></ButtonGroup>


### Reproducible code 复现代码
```typescript
<Card
      shadows="hover"
      style={{ height: 64 }}
      title={problemName}
      headerExtraContent={
        <ButtonGroup size="small">
          <Button
            type="tertiary"
            onClick={() => {
              navigate(`/admin/correct/${props.item.id}`);
            }}
          >
            批改
          </Button>
          <Button
            type="primary"
            onClick={() => {
              navigate(`edit`, { state: 2 });
            }}
          >
            编辑
          </Button>
          <Button
            type="danger"
            onClick={() => {
              deleteit();
            }}
          >
            删除
          </Button>
        </ButtonGroup>
      }
      bodyStyle={{
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
      }}
    ></Card>

```

**Comment by xuerzong** [comment]
临时解决办法：
```diff
headerExtraContent={
  <ButtonGroup size="small">
-    <Button
-      type="tertiary"
-      onClick={() => {
-        navigate(`/admin/correct/${props.item.id}`);
-      }}
-    >
-      批改
-    </Button>
-    <Button
-      type="primary"
-      onClick={() => {
-        navigate(`edit`, { state: 2 });
-      }}
-    >
-      编辑
-    </Button>
-    <Button
-      type="danger"
-      onClick={() => {
-        deleteit();
-      }}
-    >
-      删除
-    </Button>
+    <>
+      <Button
+        type="tertiary"
+        onClick={() => {
+          navigate(`/admin/correct/${props.item.id}`);
+        }}
+      >
+        批改
+      </Button>
+      <Button
+        type="primary"
+        onClick={() => {
+          navigate(`edit`, { state: 2 });
+        }}
+      >
+        编辑
+      </Button>
+      <Button
+        type="danger"
+        onClick={() => {
+          deleteit();
+        }}
+      >
+        删除
+      </Button>
+    </>
  </ButtonGroup>
}
```

**Comment by xuerzong** [comment]
> ### Which Component 出现bug的组件
> * Card with ButtonGroup
> 
> ### semi-ui version
> * 版本大于 2.6.0
> * 实测 2.7.1 - 2.9.0 都存在该问题
> 
> ### Expected result 期望的结果是什么
> * ButtonGroup 在 Card 卡片标题右侧的额外内容处正常显示
> 
> ### Actual result 实际的结果是什么
> * ERROR
> * ```shell
>   TS2746: This JSX tag's 'children' prop expects a single child of type '(ReactChild & (boolean | ReactChild | ReactFragment | ReactPortal | null)) | undefined', but multiple children were provided.
>   ```
> 
> ### Steps to reproduce 复现步骤
> * 向 Card 的 headerExtraContent 传入
> 
> ### Reproducible code 复现代码
> ```ts
> <Card
>       shadows="hover"
>       style={{ height: 64 }}
>       title={problemName}
>       headerExtraContent={
>         <ButtonGroup size="small">
>           <Button
>             type="tertiary"
>             onClick={() => {
>               navigate(`/admin/correct/${props.item.id}`);
>             }}
>           >
>             批改
>           </Button>
>           <Button
>             type="primary"
>             onClick={() => {
>               navigate(`edit`, { state: 2 });
>             }}
>           >
>             编辑
>           </Button>
>           <Button
>             type="danger"
>             onClick={() => {
>               deleteit();
>             }}
>           >
>             删除
>           </Button>
>         </ButtonGroup>
>       }
>       bodyStyle={{
>         display: "flex",
>         alignItems: "center",
>         justifyContent: "space-between",
>       }}
>     ></Card>
> ```

临时解决办法， 希望能帮助到你

```diff
headerExtraContent={
  <ButtonGroup size="small">
-    <Button
-      type="tertiary"
-      onClick={() => {
-        navigate(`/admin/correct/${props.item.id}`);
-      }}
-    >
-      批改
-    </Button>
-    <Button
-      type="primary"
-      onClick={() => {
-        navigate(`edit`, { state: 2 });
-      }}
-    >
-      编辑
-    </Button>
-    <Button
-      type="danger"
-      onClick={() => {
-        deleteit();
-      }}
-    >
-      删除
-    </Button>
+    <>
+      <Button
+        type="tertiary"
+        onClick={() => {
+          navigate(`/admin/correct/${props.item.id}`);
+        }}
+      >
+        批改
+      </Button>
+      <Button
+        type="primary"
+        onClick={() => {
+          navigate(`edit`, { state: 2 });
+        }}
+      >
+        编辑
+      </Button>
+      <Button
+        type="danger"
+        onClick={() => {
+          deleteit();
+        }}
+      >
+        删除
+      </Button>
+    </>
  </ButtonGroup>
}
```

**Comment by Moroshima** [comment]
@xuerzong Thanks a lot!

**Comment by pointhalo** [comment]
试下 v2.10.0
