### ISSUE TITLE
Button按钮显示问题

### ISSUE THREAD

**Issue by strongyc** [DouyinFE/semi-design#817]
import React from 'react';
import { Form, Toast, Button, } from '@douyinfe/semi-ui';
import Title from '@douyinfe/semi-ui/lib/es/typography/title';
import { useHistory, useRequest } from 'ice';
import loginService from './services/login';

const Login = () => {
    const history = useHistory();
    const loginRequest = useRequest(loginService.Login);
    const handleSubmit = async (values) => {
        console.log(values);
        loginRequest.request(values).then((res) => {
            console.log('res---------', res);
            if (res.success) {
                Toast.success('登录成功');
                history.push('/home/index');
            }
        });

        //
    };

    return (
        <div className="w-full h-full flex  flex-col  items-center mt-60 ">

            <Title heading={2} style={{ margin: '8px 0' }}>
                登录
            </Title>
            <div>
                <Form
                    onSubmit={(values) => handleSubmit(values)}
                    style={{ width: 400 }}
                    labelPosition="left"
                    labelWidth={'80px'}
                >
                    {({ formState, values, formApi }) => (
                        <>
                            <Form.Input
                                field="account"
                                label="用户名:"
                                style={{ width: '100%' }}
                                placeholder="请输入用户名"
                                rules={[{ required: true, message: '用户名不能为空' }]}
                            ></Form.Input>
                            <Form.Input
                                field="password"
                                label="密码:"
                                style={{ width: '100%' }}
                                placeholder="请输入密码"
                                rules={[{ required: true, message: '密码不能为空' }]}
                            ></Form.Input>

                            <div>
                                <Button type="primary" theme='solid' htmlType="submit" block loading={loginRequest.loading}>登录</Button>
                            </div>
                        </>
                    )}
                </Form>
            </div>

            <Button theme='solid' type='primary' style={{ marginRight: 8 }}>深色主要</Button>
        </div>
    );
};

export default Login;，登录按钮只有鼠标悬浮过去才能显示，不能一直正常显示button按钮，不设置theme可以正常显示，这是什么原因？
![image](https://user-images.githubusercontent.com/51156342/167080427-3eadbd94-0392-4051-a06b-777c5dd4abaf.png)

**Comment by pointhalo** [comment]
有能复现的codesandbox链接吗

**Comment by shijiatongxue** [comment]
看下是不是这个主题的颜色导致的，检查下 DOM 上 Button 是否存在，以及 Button 的文本颜色是啥

**Comment by strongyc** [comment]
项目中使用了tailwind.css
![image](https://user-images.githubusercontent.com/51156342/167233543-f1eb01d1-4698-4fc5-bd0f-280e31afd661.png)
只有s鼠标悬浮才会显示，不知道是不是tailwind.css优先级的问题，这个该怎么解决

**Comment by strongyc** [comment]
已找到原因，就是因为和tailwindcss冲突，项目中去掉tailwindcss样式正常，这个有解决方案吗？

**Comment by DaiQiangReal** [comment]
> 已找到原因，就是因为和tailwindcss冲突，项目中去掉tailwindcss样式正常，这个有解决方案吗？

方法1: 关掉 tailwindcss 的 preflight
![image](https://user-images.githubusercontent.com/29626873/167235653-78fddce0-091a-4ec3-abe2-3839638fe531.png)

方法2: 自行在业务 css 中 覆盖这个type= submit 的 时候 button 的样式

**Comment by DaiQiangReal** [comment]
如果你觉得 关闭 preflight 后，一些 tailwind css 的 class 样式有变化，可以再手动人工将 tawind css 的  preflight 加在你的业务css 中，注意去除里面的  button submit 样式。
https://unpkg.com/tailwindcss@3.0.18/src/css/preflight.css

**Comment by strongyc** [comment]
有没有种好的办法，不去破坏tailwind css的样式保证semi样式正常

**Comment by pointhalo** [comment]
本质上是css 权重优先级问题。他们的css初始化设得非常激进，而我们无法干预 tailwind。这种问题只能自行规避。

**Comment by strongyc** [comment]
已找到解决方案，用tailwindcss 的指令，不用关掉 tailwindcss 的 preflight
@layer base {
  button, [type='button'], [type='reset'], [type='submit'] {
      background-color: var(--semi-color-primary); 
  }
}

**Comment by songhn233** [comment]
更新一下，可以不需要用 css layer，通过优先级覆盖即可

tailwind 的 base 样式用到的属性选择器 `button, [type='submit']` 和 `semi-button` 优先级是一样的，大概是通过代码出现顺序覆盖的，给 background-color 增加几个 class 权重就能覆盖掉

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@import "~@douyinfe/semi-ui/dist/css/semi.min.css";

.semi-button.semi-button-primary:not(.semi-button-light):not(.semi-button-borderless) {
  background-color: var(--semi-color-primary);
}
.semi-button.semi-button-light:not(.semi-button-borderless) {
  background-color: var(--semi-color-fill-0);
}
```
