### ISSUE TITLE
菜单展开问题

### ISSUE THREAD

**Issue by strongyc** [DouyinFE/semi-design#823]
菜单中使用items格式，当展开菜单点击第一个菜单时会自动折叠，点击第二个则不会，该怎么设置点击第一个菜单不自动折叠？
![image](https://user-images.githubusercontent.com/51156342/167285682-d249883e-b585-4d04-b957-d0faf3c00032.png)

**Comment by strongyc** [comment]
菜单加了oclick点击事件

**Comment by MuxinFeng** [comment]
能否在codesandbox提供个demo

**Comment by strongyc** [comment]
你好，找到问题了，是我判断的问题，感谢

**Comment by strongyc** [comment]
![image](https://user-images.githubusercontent.com/51156342/167298586-08fffa06-2f17-4f69-a4ba-b9c9418ef8e5.png)
官网这个案例折叠后图标无法显示了

**Comment by strongyc** [comment]
你好，在items中点击使用history.push()跳转时，第一个菜单总是被收起，是有什么特殊的处理吗？

**Comment by strongyc** [comment]
import React, { useEffect, useMemo, useState } from 'react';
import Sider from '@douyinfe/semi-ui/lib/es/layout/Sider';
import { Nav } from '@douyinfe/semi-ui';
import { useLocalStorageState } from 'ahooks';
import { useHistory } from 'ice';

import { isEmpty } from 'lodash';

const NavSider = () => {
  const [menus] = useLocalStorageState('menus');
  const menusItems = useMemo(() => {
    return menus;
  }, [menus]);
  const history = useHistory();
  // todo 点击时进行跳转
  const onToLink = (data) => {
    console.log('点击的data-------', data);
    // eslint-disable-next-line no-prototype-builtins
    if (data.hasOwnProperty('openKeys')) {
      console.log('进入了------------');
    } else {
      history.push(data.itemKey);
    }
  };


  return (
    <Sider style={{ backgroundColor: 'var(--semi-color-bg-1)' }}>
      <Nav
        style={{ maxWidth: 220, height: '100%' }}
        defaultSelectedKeys={['Home']}
        items={menusItems}
        footer={{
          collapseButton: true,
        }}
        onClick={onToLink}
        // selectedKeys={selectedKeys}
        // onSelect={onSelect}
        // onSelect={onSelect}
      />
    </Sider>
  );
};

export default NavSider;
代码如上，注释了history.push,一切正常，一旦跳转点了几次后就会把第一个菜单收起，需要怎么处理啊
