### ISSUE TITLE
react18 select 组件选择后 闪现两次

### ISSUE THREAD

**Issue by Anteaterv** [DouyinFE/semi-design#829]
### Which Component 出现bug的组件
  - Select

### semi-ui version
  - 2.10.1
    
### Expected result 期望的结果是什么
  - 选择之后item选项消失，而不是多次闪烁

### Actual result 实际的结果是什么
  - 选择之后item选项未消失，闪烁两次

### Steps to reproduce 复现步骤
  - 1 安装react18
  - 2 安装semi-ui
  - 3 使用Select组件
  - 4 点击选择

### Reproducible code 复现代码
```
class Demo extends React.component {

    render() {
        return (
            <Select defaultValue='en'
                                        prefix={<IconGlobeStroke />}
                                        style={{ width: 130 }}>
                                    <Select.Option value='en'>English</Select.Option>
                                    <Select.Option value='zh'>中文</Select.Option>
                                </Select>
        )
    }

}

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by nekocode** [comment]
同样遇到该情况。准确来说应该是所有 popover 都有这个问题：

https://user-images.githubusercontent.com/4783781/170463045-786649bd-7a68-44b7-aef1-a23066453ccc.mov

**Comment by pointhalo** [comment]
与 #715 重复。这个问题在跟进了。

**Comment by pointhalo** [comment]
fix v2.12.0-beta.5
