### ISSUE TITLE
Storybook preview with uncaught error

### ISSUE THREAD

**Issue by tianenpang** [DouyinFE/semi-design#831]
### Which Component 出现bug的组件
  - storybook

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - running and previewing the storybook properly

### Actual result 实际的结果是什么
  - `Uncaught Error: Singleton client API not yet initialized, cannot call addParameters.`

### Steps to reproduce 复现步骤
  - following the contribution guidelines
    - `git clone https://github.com/<your-username>/semi-design.git`
    - `cd semi-design`
    - `git checkout -b <TOPIC_BRANCH_NAME>`
    - `yarn global add lerna`
    - `npm run bootstrap`
    - `npm start`
  - open the storybook at [http://127.0.0.1:6006](http://127.0.0.1:6006) and checkout the console

### Reproducible code 复现代码
  - follow the `Steps to reproduce 复现步骤` above

### Additional information 补充说明
  - system environment info

```text
System:
  OS: Windows 10 10.0.19044
Binaries:
  Node: 16.15.0
  Yarn: 1.22.18
  npm: 8.5.5
  lerna: 4.0.0
Browsers:
  Chrome: 101.0.4951.67 (Official Build) (64-bit)
```

  - screenshot of the error message in console

![screenshot](https://user-images.githubusercontent.com/32772271/168209911-6e93a2dd-aa6e-477b-b92a-88c683ba2c18.png)

**Comment by pointhalo** [comment]
get，稍后按照你的步骤我试一下

**Comment by pointhalo** [comment]
复现不了，构建过程正常，访问 localhost：6006也正常。基本上把所有依赖都切到跟你一样的version了
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/88709023/168266375-ede23c29-7a68-4d4b-bdaa-0514571a16f3.png">

我只能怀疑是mac和windows下有些不太一样了。

另外找到一个同类的反馈 https://github.com/storybookjs/storybook/issues/10887
我查看了下yarn.lock，我们项目里确实会存在 两个版本的 `@storybook/client-api`，但因为我本地无法复现，所以我现在无法确定统一版本是否能解决你这边无法运行的问题，你方便的话，麻烦帮我们试验一下❤️ 


1. pacakge.json 锁一下 版本
```
  "resolutions": {
     "@storybook/client-api": "6.5.0-beta.1"
  },
```

2. `rm -rf node_modules`
3. `npm run bootstrap`
4. `npm start`

**Comment by tianenpang** [comment]
If using `Git Bash` in `Windows` the path needs to be strictly case-sensitive.

@pointhalo thanks for your screenshot that brought the case warning to my attention.
