### ISSUE TITLE
Moda.useModal() 返回值类型错误

### ISSUE THREAD

**Issue by YuanSa** [DouyinFE/semi-design#833]
### Which Component 出现bug的组件
  - Modal

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - Modal.useModal()[1] 有正确类型：`{ info: ..., confirm: ... }`

### Actual result 实际的结果是什么
  - Modal.useModal()[1] 类型并了一个奇怪的 JSX.Element： `JSX.Element | { info: ..., confirm: ... }`
<img width="558" alt="image" src="https://user-images.githubusercontent.com/13344375/168430281-9a38ac3a-e829-4e20-92b6-fb8c106f4229.png">

### Steps to reproduce 复现步骤
  - 使用 TypeScript
  - 调用 Modal.useModal

### Reproducible code 复现代码
```
import { Button, Modal } from "@douyinfe/semi-ui";

() => {
  const [modal, contextHolder] = Modal.useModal();

  const handleClick = () => {
    modal.info({ title: "Info" });
  };

  return (
    <>
      {contextHolder}
      <Button onClick={handleClick }>测试</Button>
    <>
  );
}

```

**Comment by DaiQiangReal** [comment]
修复 PR: https://github.com/DouyinFE/semi-design/pull/836

**Comment by YyumeiZhang** [comment]
v2.11.0已修复
![image](https://user-images.githubusercontent.com/101110131/169941471-2c01c92b-5053-41b4-823e-2d17e26b29cf.png)
