### ISSUE TITLE
TagGroup.tagList 传入 ReactNode[] 崩溃或不渲染

### ISSUE THREAD

**Issue by YuanSa** [DouyinFE/semi-design#834]
### Which Component 出现bug的组件
  - TagGroup

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - `TagGroup.tagList` 传啥渲染啥

### Actual result 实际的结果是什么
  - `TagGroup.tagList` 传入 `ReactNode[]` 崩溃
  - `TagGroup.tagList` 传入 `Semi.Tag[]` 不渲染

#### 报错：传入 `ReactNode[]`

```tsx
import { TagGroup } from '@douyinfe/semi-ui';

() => <TagGroup tagList={[<>123</>]} />;
```
<img width="459" alt="image" src="https://user-images.githubusercontent.com/13344375/168437386-979d4e19-a23a-468a-87d9-41232323b8b5.png">

#### 不渲染：传入 `Semi.Tag[]`

```tsx
import { TagGroup, Tag } from '@douyinfe/semi-ui';

() => <TagGroup tagList={[<Tag>123</Tag>]} />;
```
<img width="482" alt="image" src="https://user-images.githubusercontent.com/13344375/168437315-33117f75-d351-42b6-bef3-132a40170d01.png">

**Comment by DaiQiangReal** [comment]
https://github.com/DouyinFE/semi-design/pull/842/files

**Comment by Memoyu** [comment]
这个issue的bug是否是仍存在问题，还是我的用法有问题？
![Snipaste_2024-07-11_18-13-04](https://github.com/DouyinFE/semi-design/assets/33112476/e49ca0dc-4d92-46ca-82e1-dedae2ad6f50)

<br/>
同样的，官网也无法渲染

![Snipaste_2024-07-11_18-16-24](https://github.com/DouyinFE/semi-design/assets/33112476/e899b716-8089-42bf-9a58-a59430b083a9)

**Comment by pointhalo** [comment]
> 这个issue的bug是否是仍存在问题，还是我的用法有问题？ ![Snipaste_2024-07-11_18-13-04](https://private-user-images.githubusercontent.com/33112476/347778501-e49ca0dc-4d92-46ca-82e1-dedae2ad6f50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTY0MjYsIm5iZiI6MTcyMDY5NjEyNiwicGF0aCI6Ii8zMzExMjQ3Ni8zNDc3Nzg1MDEtZTQ5Y2EwZGMtNGQ5Mi00NmNhLTgyZTEtZGVkYWUyYWQ2ZjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDExMDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MzNkMDM0YmE5MjMyOWMzZjE5MDQ0Y2IwN2IxMTdkMGFkNWU2OTVhMTZlNDYxNjM1OGJjYjAxMzkyMGYzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wh2koK9Rhpfijp79SZyXeqCdMn3OZnMEHpkyMqf_hgg)
> 
> 
> 同样的，官网也无法渲染
> ![Snipaste_2024-07-11_18-16-24](https://private-user-images.githubusercontent.com/33112476/347778953-e899b716-8089-42bf-9a58-a59430b083a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTY0MjYsIm5iZiI6MTcyMDY5NjEyNiwicGF0aCI6Ii8zMzExMjQ3Ni8zNDc3Nzg5NTMtZTg5OWI3MTYtODA4OS00MmJmLTlhNTgtYTU5NDMwYjA4M2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDExMDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZmNmZTBmNmM5NmEyMTY1NjYzZDFjYTU3NTUxNWJlYzRjNjFjYjAzMTY2OWU4MzU2YmM5NzdlNGQwNTE0ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OtkCOAp6JTyi6c65sllmM6uDFph559faEa2vLCrGn7Y)

不支持 reactNode。props.tabList 合法类型是一个object 数组。
