### ISSUE TITLE
官网组件 Demo，代码示例面板一直加载不出来，控制台报错 Monaco initialization: error

### ISSUE THREAD

**Issue by poozhu** [DouyinFE/semi-design#844]
### Which Component 出现bug的组件
  - All

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - Demo 正常展示示例代码面板

### Actual result 实际的结果是什么
  -  Demo 示例代码面板一直转圈

### Steps to reproduce 复现步骤
  - 1 官网链接打开即可 https://semi.design/zh-CN/input/input

**Comment by pointhalo** [comment]
检查下你是否开了代理，或者换个网络看看。看起来是你所在网络获取不到对应cdn文件。
（之前有过类似反馈是用户的公司内网对某些网址进行了屏蔽，切换到4g后又好了）

**Comment by poozhu** [comment]
前两天我看这个文件切为自己的资源了，今天打开又换回了 jsdelivr ，又挂了。。。

**Comment by pointhalo** [comment]
> 无代理，切换网络无效。 看样子是这个文件加载失败了 https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/loader.js 考虑 jsdelivr 的 cdn 是否稳定呢

应该是这个域名在部分地区被墙了。

这个loader配置是 monaco-editor/react 写死在内部的。我们当前通过config的方式暂时将产物指向了另外一个cdn地址，虽然也带来了其他报错。但能暂时解决部分用户访问无法看到demo代码的问题。
<img width="593" alt="image" src="https://user-images.githubusercontent.com/88709023/169740639-cf63abe8-a3f6-436a-bde3-2adf3da11284.png">

更彻底的方案我们在跟进，可能需要将 monaco-editor/react 去掉，直接换成使用 monaco-editor。这个过程涉及一些配置的调整，我们会尽快完成。

**Comment by pointhalo** [comment]
已完成替换。
