### ISSUE TITLE
React18使用Tree组件展开子节点时会报错

### ISSUE THREAD

**Issue by itoushunta** [DouyinFE/semi-design#847]
### Which Component 出现bug的组件
  - Tree

### semi-ui version
  - 2.10.1
    
### Expected result 期望的结果是什么
  - 能够展开并显示子节点

### Actual result 实际的结果是什么
  - 默认情况(motion为true)下展开子节点时，控制台会报错误"Uncaught TypeError: Cannot read properties of null (reading 'getCurrentStates') Animation.js"，
  - 
<img width="346" alt="image" src="https://user-images.githubusercontent.com/41609161/169193943-992e4c96-82ee-4715-9af3-f49204035027.png">

  - 设置motion为false时不会报错

### Reproducible code 复现代码
```
import { Tree } from '@douyinfe/semi-ui'

export default () => {
  const treeData = [
    {
      label: '亚洲',
      value: 'Asia',
      key: '0',
      children: [
        {
          label: '中国',
          value: 'China',
          key: '0-0',
        },
      ],
    },
    {
      label: '北美洲',
      value: 'North America',
      key: '1',
    },
  ]

  return (
    <Tree treeData={treeData} />
  )
}

```

**Comment by pointhalo** [comment]
与 #745 相关，属于 React 18 createRoot + strictMode下的特有的问题。可以把strictMode关掉。或者升级至 2.11.0-beta.0 试试，已经修复过这类问题
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/88709023/169195373-6a3a653d-ef99-4362-824e-ead6af0fd989.png">

**Comment by itoushunta** [comment]
> 与 #745 相关，属于 React 18 createRoot + strictMode下的特有的问题。可以把strictMode关掉。或者升级至 2.11.0-beta.0 试试，已经修复过这类问题 <img alt="image" width="1142" src="https://user-images.githubusercontent.com/88709023/169195373-6a3a653d-ef99-4362-824e-ead6af0fd989.png">

反馈一下，stictMode关掉后，Tree节点展开后再收起时的动画期间，它的后面一个节点有时候会出现闪烁一下的情况，但是报错的问题解决了~
还有Tree使用multiple时会报一个类型问题的warning，应该就是该截图中chekbox解决的问题吧

**Comment by pointhalo** [comment]
闪烁也是react 18带来的问题，后面会单独解决。

**Comment by pointhalo** [comment]
闪烁的问题 #715 ，已于 2.12.0-beta.5 修复
