### ISSUE TITLE
Upload file size is not right on macOS

### ISSUE THREAD

**Issue by Mayandev** [DouyinFE/semi-design#848]
### Which Component Need Enhancement 期望新增功能的组件
- Upload

### What does the proposed API look like 期望支持的API

Show the right file size according to the OS platform.

### Feature Description 功能描述
MacOS calculate file size is using megabytes, which means 1000KB=1M. Otherwise windows using mebibytes, which mean 1024KB = 1M. That will get confuse when I use upload component to upload a file.

Here are some screenshots:

![image](https://user-images.githubusercontent.com/28648715/169195530-1525540e-b989-4684-833a-12b5844b5c6f.png)

![image](https://user-images.githubusercontent.com/28648715/169195326-21848685-2eb1-456b-a5a3-5da93fcfb6f5.png)

**Comment by pointhalo** [comment]
This behavior is not planned to be modified. We think this setting is reasonable for now. The file size will be related to `props.maxSize`, `props.minSize`.
The upload file size will generally be checked again by the server. The front end should maintain the same computing caliber as the server. 
The same file is operated on different operating systems, and the feedback obtained should be consistent.
