### ISSUE TITLE
官网怎么了? 组件代码区域一直加载中....

### ISSUE THREAD

**Issue by OrrinHatch** [DouyinFE/semi-design#853]
### Which Component 出现bug的组件
  - Button

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 

### Actual result 实际的结果是什么
  - 

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```
class Demo extends React.component {

    render() {
        return (
            <Button>bug</Button>
        )
    }

}

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
我们依赖 monaco-editor 的 react 封装 `@monaco-editor/react`，他们使用的是 jsdelivr cdn，看了一下，应该是这个cdn在国内某些地区无法被访问导致的。

可以先挂个代理绕一下。

我们也看下怎么找个backup降级

**Comment by pointhalo** [comment]
duplicate #844，有重复issue。先关掉这个。统一在上一个issue中进行处理。
