### ISSUE TITLE
Nav.Item['linkOptions'] is wrongly typed

### ISSUE THREAD

**Issue by SunriseFox** [DouyinFE/semi-design#856]
### Which Component 出现bug的组件
  - Nav

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - Nav.Item 的 linkOption 正常工作

### Actual result 实际的结果是什么
  -  Object literal may only specify known properties, and 'href' does not exist in type 'HTMLAttributes\<HTMLLinkElement\>'.ts(2322)

### Steps to reproduce 复现步骤
  - `<Nav.Item linkOption={{ href: '' }} />`

### Reproducible code 复现代码
```
<Nav.Item linkOption={{ href: '' }} />
```

### Additional information 补充说明
- `HTMLLinkElement` -> `HTMLAnchorElement`
- `HTMLAttributes` -> `AnchorHTMLAttributes`

**Comment by pointhalo** [comment]
Thanks for your PR, this modification has been released, `v2.11.1`
