### ISSUE TITLE
select及select关联组件在size设置为large下placeholder字体大小未生效

### ISSUE THREAD

**Issue by procyber** [DouyinFE/semi-design#859]
### Which Component 出现bug的组件
  - select、tree select

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 
 在size被设置为large属性时，placeholder的字体大小与input组件在size被设置为large后的字体大小一致

### Actual result 实际的结果是什么
  - input的placeholder变大
  - select、tree select 中的placeholder字号未变大一号

### Steps to reproduce 复现步骤
  - 1 ，官方平台-form表单-内嵌label示例 .  
  - 2，在示例中，将form.input加上size属性，设置为large,将form.select加上size属性，设置为large
  - 3，结果出现：input中的placeholder字体为large定义的大号字体，而select中的placeholder的字体不变

### Reproducible code 复现代码
```
class Demo extends React.component {

    render() {
        return (
            <Button>bug</Button>
        )
    }

}

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
fix v2.14.0-beta.0
