### ISSUE TITLE
@douyinfe/semi-theme-default@2.11.2 not found

### ISSUE THREAD

**Issue by Laffery** [DouyinFE/semi-design#864]
### Semi-ui
  - none

### semi-ui version
  - latest@2.11.2
    
### Expected result 期望结果
  - 依赖下载成功

### Actual result 实际结果
  - 依赖下载失败

```
Downloading registry.npmjs.org/@douyinfe/semi-ui/2.11.2: 5.35 MB/5.35 MB, done
/path/to/project/packages/web:
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @douyinfe/semi-theme-default@2.11.2

The latest release of @douyinfe/semi-theme-default is "2.11.1".

Other releases are:
  * alpha: 2.1.0-alpha.3
  * next: 2.1.0-next.0
  * beta: 2.11.0-beta.1
``` 

### Steps to reproduce 复现步骤
  - 添加@douyinfe/semi-ui依赖

### Reproducible code 复现代码

```shell
pnpm add @douyinfe/semi-ui
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by pointhalo** [comment]
暂时重新将latest指向了 @douyinfe/semi-ui@2.11.1 ，可以再试一下。
实际上 2.11.1 与 2.11.2之间没有diff。之所以发 2.11.2是因为昨天我们发布 2.11.1 后，在lerna publish已经成功的情况下，发现在npm中找不到 @douyinfe/semi-theme-default的 v2.11.1 版本（但今天看又出现了……有点奇怪），所以重新发了一个 2.11.2。
我们后续再排查一下 CI 是不是有网络问题或者源设置是否正确。

**Comment by pointhalo** [comment]
check了一下 CI上的log，publish是成功了的，npm上没有这个比较奇怪🤯（而且 2.11.1昨天也是这种情况，发布后npm无法查到，结果今天又有了）

<img width="851" alt="image" src="https://user-images.githubusercontent.com/88709023/170306773-58bc39c0-a53d-4f7e-93a2-647fff9984b7.png">

**Comment by Laffery** [comment]
现在下载问题解决了，感谢🙏

**Comment by pointhalo** [comment]
看起来应该确实是npm的问题，5.25我们没有做过发布操作.
- 5.25晚上时查询npm确实查不到 @douyinfe/semi-theme-default 的 v2.11.2 版本 （所以导致了你安装的时候出错了）
- 但是 5.26（今天）看又有了，而且发布时间是 2 day ago，是能对应上我们实际执行publish的时间点的

<img width="980" alt="image" src="https://user-images.githubusercontent.com/88709023/170405370-2496b0c7-bf5a-41e0-a10c-ffcc1a55d947.png">
