### ISSUE TITLE
[InputNumber] 纯数字输入

### ISSUE THREAD

**Issue by AlbertBert** [DouyinFE/semi-design#877]
### Which Component Need Enhancement 期望新增功能的组件
- InputNumber

### What does the proposed API look like 期望支持的API
增加onlyInterger参数，确保只能输入整数
### Feature Description 功能描述
稜镜平台这边很多涉及到服务端玩法配置项只能是整数，虽然现在有formatter这个参数，但是这个参数需要写正则匹配，比较繁琐，所以希望增加单独参数做输入整数配置项

**Comment by shijiatongxue** [comment]
InputNumber 的定位不是纯数字输入，暂时不准备提供 only interger 的参数。建议手动封装一个组件~
