### ISSUE TITLE
[Dropdown] 使用 Input 作为 Trigger 时，disabled 属性导致样式错乱

### ISSUE THREAD

**Issue by myWsq** [DouyinFE/semi-design#878]
### Which Component 出现bug的组件
  - Dropdown 和 Input

### semi-ui version
  - 2.10.1
    
### Expected result 期望的结果是什么
  - Input 添加 disabled 属性时，页面结构和覆盖的样式保持不变

### Actual result 实际的结果是什么
  - 多出一层 span 元素包住了 Input

### Steps to reproduce 复现步骤

If your reproduction scene is complicated, you can list the reproduction steps here

如果你的复现场景比较复杂，可以在这里列出复现的步骤
  
 - 使用 Input 作为 Dropdown 的 Trigger，添加 disabled 属性即可复现

### Reproducible code 复现代码

- You can paste a minimal reproducible code, preferably runnable in the code editing area of [Semi official website](https://semi.design/en-US/input/button)

```tsx
import React from 'react';
import { Dropdown, Input } from '@douyinfe/semi-ui';

function Demo() {
    return (
        <div style={{display: 'flex'}}>

            <Dropdown
                trigger={'focus'}
                position={'bottomLeft'}
                render={
                    <Dropdown.Menu tabIndex={-1}>
                        <Dropdown.Item>Menu Item 1</Dropdown.Item>
                        <Dropdown.Item>Menu Item 2</Dropdown.Item>
                        <Dropdown.Item>Menu Item 3</Dropdown.Item>
                    </Dropdown.Menu>
                }
            >
                <Input 
                    // disabled
                    placeholder="点击此处"
                 />
            </Dropdown>
            <div>Suffix</div>
        </div>
    );
}
```

- You can also use Codesandbox to create a minimal reproduction scene use Semi [template](https://codesandbox.io/s/semi-design-simple-story-oubej?file=/src/App.jsx)

Reproducible Codesandbox link: https://codesandbox.io

- Or, if your scene is more complex, you can use other templates to create a reproducible scene

Reproducible Codesandbox link: https://codesandbox.io

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by shijiatongxue** [comment]
先解释下这里为啥会包个 span，原因是 disabled element 无法监听到事件，如果不监听事件也就无法打开弹出层。

所以 Dropdown 会在 children 是 disabled 时自动加上一个 span。

<img width="684" alt="image" src="https://user-images.githubusercontent.com/26477537/172285606-b6ab0c0e-9970-444a-b2a4-37ee10353f30.png">

对于你这里的场景，可以传递一个 `wrapWhenSpecial=false` 这样不会包裹 span。

但是需要留意一些特殊的场景，例如 children 会将 ref 透传到 dom 结构的某个部分而不是最外层时。弹出层可能定位不准的问题（弹出层根据 ref 定位）。

默认情况我们无法避免自动嵌套 span。

**Comment by myWsq** [comment]
目前这个场景可以通过给 trigger 包一层元素来解决。

如果不禁用整个 input wrapper 的鼠标事件，仅禁用内部 input 元素的，是否可以避免元素结构的变化？当然这个改动可能比较大，提供一个思路。

**Comment by shijiatongxue** [comment]
trigger 为 custom 时，也不再对 trigger 包裹 span，你也可以使用这个方式~

```
import React from 'react';
import { Dropdown, Tag } from '@douyinfe/semi-ui';

function Demo() {
    return (
        <Dropdown
            trigger="custom"
            render={
                <Dropdown.Menu>
                    <Dropdown.Item>Menu Item 1</Dropdown.Item>
                    <Dropdown.Item>Menu Item 2</Dropdown.Item>
                    <Dropdown.Item>Menu Item 3</Dropdown.Item>
                </Dropdown.Menu>
            }
        >
            <Input disabled />
        </Dropdown>
    );
}
```

![image](https://user-images.githubusercontent.com/26477537/177094723-2a750b98-7143-4373-bd2b-451333a0031d.png)

**Comment by myWsq** [comment]
好的，感谢回复 😁
