### ISSUE TITLE
[Tabel] Editable cell

### ISSUE THREAD

**Issue by zhaogongchengsi** [DouyinFE/semi-design#887]
###  Editable cell
- Tabel

**Comment by shijiatongxue** [comment]
具体的使用方式可以描述下吗？

可编辑能力是 Table 支持？还是用户手动处理。

**Comment by zhaogongchengsi** [comment]
我希望是可以在通过表头指定哪些列可以被编辑 然后用户可以手动指定编辑的表单 然后 只要被编辑了 可以将被编辑的数据传递给onEdit 之类的回调函数 然后可以获取到行号列号之类的

**Comment by diiyw** [comment]
希望支持这个，可以像excel一样编辑每个单元格
