### ISSUE TITLE
[Table] 设置可滑动时无法固定checkbox列

### ISSUE THREAD

**Issue by diiyw** [DouyinFE/semi-design#889]
### Which Component 出现bug的组件
  - Table
只固定的指定字段的第一列
，checkbox列无法固定
![1654603457622](https://user-images.githubusercontent.com/10717965/172374777-68b697db-f22e-4b4d-8c26-2c670817ed43.png)

**Comment by pointhalo** [comment]
麻烦提供一个复现的codesandbox链接

**Comment by diiyw** [comment]
https://codesandbox.io/embed/boring-kare-y9rjuh?fontsize=14&hidenavigation=1&theme=dark

**Comment by diiyw** [comment]
> 麻烦提供一个复现的codesandbox链接
这里可复现
https://codesandbox.io/embed/boring-kare-y9rjuh?fontsize=14&hidenavigation=1&theme=dark

**Comment by diiyw** [comment]
rowSelection 设置 fixed: true 解决
