### ISSUE TITLE
replace Tag.avatarShape to shape

### ISSUE THREAD

**Issue by xialvjun** [DouyinFE/semi-design#89]
### Which Component Need Enhancement 期望新增功能的组件
- Tag

### What does the proposed API look like 期望支持的API
有时哦我们想要一个圆形边框的 tag，但这个 tag 可能没有 avatar，用现在的 api 实现不了。就现在的 api 还不够正交。也许可以
```jsx
// 现在的 api
<Tag avatarSrc={src} avatarShape='circle'>焦锐志</Tag>

// 想要的 api
<Tag shape='circle'>焦锐志</Tag>
```

**Comment by shijiatongxue** [comment]
抱歉漏掉这个 issue 了。近期给下结论。

胶囊类型 tag。

![image](https://user-images.githubusercontent.com/26477537/190408637-a52ffa89-e7cc-4375-bb1b-2d1b88e6b915.png)

**Comment by pointhalo** [comment]
support v2.20.0-beta.0
