### ISSUE TITLE
[TimePicker] can't reset value in controlled mode when setting value to undefined

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

TimePicker

### Semi Version

2.13

### Current Behavior

still show string in timepicker input after update props.value to `undefined`

### Expected Behavior

show nothing in timepicker input
![image](https://user-images.githubusercontent.com/88709023/175282713-a14a7491-f77f-4e28-8bb1-90c69f5dc009.png)

### Steps To Reproduce

1. Set a valid initial value when initializing, like.  value={new Date()} or value = {'08:00'}
2. click button , update timepicker props.value to `undefined`

### ReproducibleCode

```markdown
import React from 'react';
import { TimePicker } from '@ies/semi-ui-react';

function Demo() {
  const [v, setV] = useState('08:00'); // or useState(new Date())

const change = () => {
    setV(undefined);
}  
  return <>
    <TimePicker value={v} format='HH:mm'/>
    <Button onClick={change}>ce</Button>
  </>;
}
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by linjunc** [comment]
Looking at the code, this part is adding null and undefined filtering，i clear it
