### ISSUE TITLE
[Token] 增加动画相关的 token

### ISSUE THREAD

**Issue by aximario** [DouyinFE/semi-design#924]
### Which Component Need Enhancement 期望新增功能的组件
- Token

### What does the proposed API look like 期望支持的API
--semi-duration-slow: 500ms;
--semi-duration-normal: 200ms;
--semi-duration-fase: 100ms;
--semi-duration-very-fast: 50ms;
--semi-duration-instant: 0;

--semi-timing-function-bounce: cubic-bezier(.74,.62,.95,1.51);

### Feature Description 功能描述
增加动画时间
增加动画变化曲线

### Additional information 补充说明
希望动画也能做到统一，有一些推荐的动画效果

**Comment by pointhalo** [comment]
有这方面的计划🤝。
@DaiQiangReal 最近在梳理所有组件相关的动效。目前存在部分组件是css动画，有的是js 弹性动画。  
提供动效Token这个事情，需要将组件动画类型也统一后才更方便消费。
maybe 7月能提供部分。

**Comment by pointhalo** [comment]
v 2.18.0-beta.0  
Anchor、AutoComplete、Breadcrumb、Carousel、Cascader、Checkbox、DatePicker、Dropdown、Input、InputNumber、Navigation、Pagination、Radio、Rating、ScrollList、Select、SideSheet、Slider、Steps、Switch、Table、Tabs、TagInput、TimePicker、Transfer、Tree  26个组件增加动效相关设计变量

动效Token 在组件文档的展示会在后续加上；Semi DSM侧的配置支持也会在后续加上。
