### ISSUE TITLE
[Chore] FormApi ts type define

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#933]
### Which Component Need Enhancement 期望新增功能的组件
- Form

### What does the proposed API look like 期望支持的API
- 优化 FormApi的泛型定义

### Feature Description 功能描述
- 有如下代码时，如果 FData 不声明 [x:string] : unknown，在FormApi传入泛型定义时，按现有的写法会报错
<img width="573" alt="image" src="https://user-images.githubusercontent.com/88709023/176179692-38ad8252-2213-4438-93f2-c21154765c36.png">

因为 BaseFormApi的定义是这样写的，继承自 Record<string, unknown>
<img width="742" alt="image" src="https://user-images.githubusercontent.com/88709023/176179858-2deb21e7-adf8-4d0e-81cb-870968b3c48b.png">

### Additional information 补充说明

```
interface FData {
    test: boolean;
    test2: boolean;
    test3: string;
    // [x: string]: unknown;
}
class Demo extends React.Component<IProps> {
    constructor(props:any) {
      super(props);
      this.state = { visible: false};
    }

    getFormApi(formApi: FormApi<FData>) {
        formApi.getValue('')
    }

    render() {
      const { visible } = this.state;
      return (
        <>
          <Form getFormApi={this.getFormApi}>
          </Form>
        </>
      );
    }
  }


```

**Comment by so2liu** [comment]
为啥关了呀

**Comment by pointhalo** [comment]
在2.14.0已更新
