### ISSUE TITLE
[BUG] Spin设置样式不生效

### ISSUE THREAD

**Issue by crazyweeds** [DouyinFE/semi-design#937]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which Component

Spin

### Semi Version

2.13.0

### Current Behavior

<Spin style={{color: 'red'}}/>

### ReproducibleCode

```markdown
<Spin style={{color: 'red'}}/>
```

### Environment

```markdown
- OS:MacOS
- browser:Chrome100+
```

### Anything else?

<Spin style={{color: 'red'}}/>

**Comment by pointhalo** [comment]
https://semi.design/zh-CN/feedback/spin#FAQ

**Comment by pointhalo** [comment]
The color attribute is set by the inner wrapper, so the attribute you set through style has a lower priority than the original attribute

**Comment by crazyweeds** [comment]
您说的方式，已经尝试过了，无法工作，变量搞的鬼吧。总而言之，和文档描述有出入，算是文档BUG，还是什么BUG，哈？这个ISSUE关闭的有点草率哈。

![image](https://user-images.githubusercontent.com/16688520/176834240-8f6cecdd-e87a-4c6e-87cc-18ed9405581a.png)

**Comment by pointhalo** [comment]
> 您说的方式，已经尝试过了，无法工作，变量搞的鬼吧。总而言之，和文档描述有出入，算是文档BUG，还是什么BUG，哈？这个ISSUE关闭的有点草率哈。
> 
> ![image](https://user-images.githubusercontent.com/16688520/176834240-8f6cecdd-e87a-4c6e-87cc-18ed9405581a.png)

这个图其实能看出为什么吧。多条css规则同时对一个属性进行声明时，权重高的生效。App.cs: 13 color: 'red' 与 原有的 color 同权重时，那就是受加载顺序影响。
覆盖原有css时，可以适当增加权重。

eg
```
<Spin classname='special-spin'></Spin>

.special-spin .semi-spin-wrapper {
 color: 'red'
}
```

FAQ想表达的意思是，可以通过css类名覆盖。可能不够清晰/存在误解的可能，我们优化一下。

**Comment by crazyweeds** [comment]
感谢解答，前端初学者，我的问题有点低级。
