### ISSUE TITLE
[BUG] Toast 和 Notification 、Modal组件在18.2.x版本下抛出 createRoot 的警告信息

### ISSUE THREAD

**Issue by Wangsong2021** [DouyinFE/semi-design#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Toast、Notification 

### Semi Version

2.x

### Current Behavior

![image](https://user-images.githubusercontent.com/75063077/176861767-64f3036c-d7ac-4a20-a2ff-8da4c42d94cb.png)

### Environment

```markdown
- OS:
- browser:
```

**Comment by shijiatongxue** [comment]
more information:

![image](https://user-images.githubusercontent.com/26477537/177092656-f02360a9-fd96-4398-849e-4d67684f4fda.png)

**Comment by Wangsong2021** [comment]
> more information:
> 
> ![image](https://user-images.githubusercontent.com/26477537/177092656-f02360a9-fd96-4398-849e-4d67684f4fda.png)

还是无法解决 react版本降至17.x才能解决
![image](https://user-images.githubusercontent.com/75063077/177094422-325f3ae9-5d42-4cce-8389-582f6e2a64aa.png)

**Comment by shijiatongxue** [comment]
> > more information:
> > ![image](https://user-images.githubusercontent.com/26477537/177092656-f02360a9-fd96-4398-849e-4d67684f4fda.png)
> 
> 还是无法解决 react版本降至17.x才能解决 ![image](https://user-images.githubusercontent.com/75063077/177094422-325f3ae9-5d42-4cce-8389-582f6e2a64aa.png)

这个问题不影响使用。

在 Semi 修改这个之前（可能的方式是通过判断 React 版本来修改 ReactDOM render），降低版本可以看不见这个 warning。

**Comment by Wangsong2021** [comment]
> > > more information:
> > > ![image](https://user-images.githubusercontent.com/26477537/177092656-f02360a9-fd96-4398-849e-4d67684f4fda.png)
> > 
> > 
> > 还是无法解决 react版本降至17.x才能解决 ![image](https://user-images.githubusercontent.com/75063077/177094422-325f3ae9-5d42-4cce-8389-582f6e2a64aa.png)
> 
> 这个问题不影响使用。
> 
> 在 Semi 修改这个之前（可能的方式是通过判断 React 版本来修改 ReactDOM render），降低版本可以看不见这个 warning。

好的 谢谢

**Comment by YyumeiZhang** [comment]
项目有使用Jest and Enzyme做单测，目前Enzyme的最新更新在2021，无法保证对React18的支持。Jest and Enzyme的单测部分做改动成本较高。此前考虑根据react-dom版本动态引入。react18 有两个root API， Legacy Root API 和New Root API。涉及到的改动如下：

对于Legacy Root API 
```markdown
import ReactDom from 'react-dom';
import App from "APP";

// 装载
ReactDom.render(App, container[, callback]);

// 卸载
ReactDOM.unmountComponentAtNode(container);
```

对于new Root API
```markdown
import ReactDom from 'react-dom/client';
import App from "APP";

const root = ReactDom.createRoot(container);
// 装载
root.render(<APP />);

// 卸载
root.unmount();
```
对于我们来说涉及到的改动有
1. 引入路径不同，react-dom vs react-dom/client
2. new Root API中没有相关的callback方法，需要根据具体的实现时机处理[参考Replacing render with createRoot ](https://github.com/reactwg/react-18/discussions/5)

尝试来看根据不同的版本使用不同的render方法会有如下问题：
1. 引入路径不同，简单动态导入会导致webpack编译/项目运行期间报错；
2. 虽然可以从react-dom中去引入，其中包含createRoot方法，但是仍然会有waring，参考[Moving createRoot/hydrateRoot to react-dom/client #125](https://github.com/reactwg/react-18/discussions/125)

总的来说，根据不同的react-dom版本使用不同的render方式会比较hack，并且在全面未来全面支持react18会涉及到再次修改这些代码。

因此我们预计通过修改代码中使用了ReactDom.render部分来进行修复（涉及到的组件有：Modal，Notification，Toast， Typhography）。

**Comment by HardenSG** [comment]
刚刚看到警告，就第一时间来看issue了，果然

**Comment by zwying0814** [comment]
2023年4月25日，问题仍然存在

**Comment by pointhalo** [comment]
> 目前对于这个问题有三个解法
> 
> 1. 保持现状，缺点是：除了有 warning，Modal 等组件内部的元素渲染依旧按照 react legacy 方式渲染，这会导致用户组件表现黑盒。
> 2. 根据用户版本决定使用 createRoot API 或 render API，但因为需要同时兼容 React 18 和 18-，无法从 react-dom/client 来 import createRoot (这种写法会在 18- 的 react 版本报错，因为文件不存在，且静态错误无法被 catch)。这种方式能够解决 warning 且组件会按照 18 渲染，但是会导致另外一个 warning （react-dom 检测到未从 react-dom/client 导入 createRoot）。
> 3. 在方法2的基础上, 通过 proxy 选择性拦截（只拦截方法2的这一个 warning） react-dom 对 reactDOM.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED 内的 usingClientEntryPoint flag 的的读取，来屏蔽 warning。
> 
> @pointhalo 你的看法是什么？


我建议是无需处理，直到 v18在我们用户群体中的使用率占大多数，再进行修改。
2 决定了这种命令式调用依赖 reactDOM.render，没法同时兼容 18- 和18。我们的用户群体有90%都处在 18-的版本。这个warning的影响范围在当前，并不致命。用一个warning替代另一个warning没有实质意义。
3的方式太hack，作为lib不应该改其他全局变量。

**Comment by guangzan** [comment]
目前问题仍然存在

**Comment by pointhalo** [comment]
> 目前问题仍然存在

可以看下上面的说明，目前阶段要兼容多个版本的react。没有办法直接替换。

**Comment by ilxqx** [comment]
这个警告，真心让我很难受，一打开控制台就显示，一刷新页面就显示，糟糟心啊。。。
说实话，我没太明白，为什么还有那么多人还在用React18以下的版本，React18有很多破坏性的更新导致不向下兼容吗😂
多么希望可以解决一下这个问题

**Comment by ilxqx** [comment]
都 2025 年快～～～

**Comment by ethanz-code** [comment]
考古

**Comment by xiak** [comment]
期待更新
