### ISSUE TITLE
[DatePicker]  通过函数而不是token 来format

### ISSUE THREAD

**Issue by klwfwdk** [DouyinFE/semi-design#941]
### Which Component Need Enhancement 期望新增功能的组件
- DatePicker

### What does the proposed API look like 期望支持的API
format

### Feature Description 功能描述

传入 value 通过函数计算返回一个 字符串 这个字符串出现在 input中

### Additional information 补充说明
内部需求

**Comment by shijiatongxue** [comment]
> ### Which Component Need Enhancement 期望新增功能的组件
> * DatePicker
> 
> ### What does the proposed API look like 期望支持的API
> format
> 
> ### Feature Description 功能描述
> 传入 value 通过函数计算返回一个 字符串 这个字符串出现在 input中
> 
> ### Additional information 补充说明
> 内部需求

问题是如何将输入框的输入转换为合法的日期呢 :)
