### ISSUE TITLE
[Form] <Form Upload  typescript  ref not found>

### ISSUE THREAD

**Issue by DaiQiangReal** [DouyinFE/semi-design#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Form

### Semi Version

latest

### Current Behavior

Form Upload  typescript  ref not found

### Expected Behavior

Form Upload  typescript  ref found

### Steps To Reproduce

<Form>
<Form.Upload ref/>  //error here
</Form>

### ReproducibleCode

```markdown
<Form>
<Form.Upload ref/>  //error here
</Form>
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
fix 2.15.0-beta.0
