### ISSUE TITLE
[BUG] DefaultTabBar类型有误

### ISSUE THREAD

**Issue by so1ve** [DouyinFE/semi-design#952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Tab

### Semi Version

2.14.0

### Current Behavior

![](https://user-images.githubusercontent.com/58381667/177758995-c34a6054-a81b-463a-a4fc-14aa6a41e041.png)

DefaultTabBar的类型是`ComponentType<{}>`，导致无法将Props传入

### Expected Behavior

没有错误

### Steps To Reproduce

无

### ReproducibleCode

```markdown
使用官网标签栏二次封装的例子
```

**Comment by pointhalo** [comment]
@YannLynn 需要跟下这里类型错误的问题。
