### ISSUE TITLE
希望能增加对Remix框架的支持

### ISSUE THREAD

**Issue by zwying0814** [DouyinFE/semi-design#956]
![image](https://user-images.githubusercontent.com/51076397/178116481-dbe21d7c-ec9e-4df1-be4e-938756e9634b.png)

**Comment by pointhalo** [comment]
👌，应该需要通过plugin的方式进行处理。后续有计划跟进。

**Comment by pointhalo** [comment]
> 👌，应该需要通过plugin的方式进行处理。后续有计划跟进。

粗略调研了一下ui library对remix兼容的case，大部分都是build pure js，然后再让用户手动Link function的方式引入全量css或单个css

我们比较倾向于在现有的 build外，再额外增加一份构建产物，里面不含import css的语句。相比plugin的方式所需工作量会更少

**Comment by pointhalo** [comment]
remix 的roadmap上，有提及他们计划修改对于 css import 的限制，感觉这个等他们来支持更合理

https://github.com/remix-run/remix/discussions/4775

https://github.com/remix-run/remix/issues/4817

**Comment by pointhalo** [comment]
✅ Remix 对  css side effect import 的支持已release
✅ Semi 侧使用文档已更新

升级 remix至 latest版本，按照文档指引操作即可完成接入使用：https://semi.design/zh-CN/start/getting-started

![image](https://user-images.githubusercontent.com/88709023/213399344-031ad749-16cf-4d22-8822-0f35e7a25f5c.png)
