### ISSUE TITLE
[semi-illustrations] vite打包后引入了未使用的插画

### ISSUE THREAD

**Issue by rogepi** [DouyinFE/semi-design#961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

@douyinfe/semi-illustrations

### Semi Version

2.14.0

### Current Behavior

使用vite打包后，查看打包分析中存在未使用的插画，占据很大的体积

### Expected Behavior

按需引入

### Steps To Reproduce

1. 使用`pnpm create vite `创建一个vite+react+ts项目
2. 引入semi-ui以及插画组件`pnpm add @douyinfe/semi-ui  @douyinfe/semi-illustrations`
3. 将App.tsx改为官网`Empty`组件的例子，即`import { IllustrationConstruction, IllustrationConstructionDark } from '@douyinfe/semi-illustrations';`
5. 引入`rollup-plugin-visualizer`分析打包体积
![image](https://user-images.githubusercontent.com/56425392/178649898-e363b1b9-c954-48d8-ae99-76ab5a803661.png)
看到了未使用的插画，整个区块占据322kb的大小

### ReproducibleCode

```markdown
import React from 'react';
import { Empty } from '@douyinfe/semi-ui';
import { IllustrationConstruction, IllustrationConstructionDark } from '@douyinfe/semi-illustrations';

const App = () => (
    <Empty
        image={<IllustrationConstruction style={{width: 150, height: 150}} />}
        darkModeImage={<IllustrationConstructionDark style={{width: 150, height: 150}} />}
        title={'功能建设中'}
        description="当前功能暂未开放，敬请期待。"
    />
);

export default App
```

### Environment

```markdown
- OS:Windows11
- browser:Chrome
```

**Comment by pointhalo** [comment]
Bug，我们修复一下

**Comment by pointhalo** [comment]
fix v.2.15.0

**Comment by pointhalo** [comment]
复测了一下，还是有点问题。我再跟进一下。

**Comment by pointhalo** [comment]
fix v2.15.1
