### ISSUE TITLE
[Tooltip] when the content wrap, tooltip nowarp

### ISSUE THREAD

**Issue by zxyue25** [DouyinFE/semi-design#971]
### Which Component Need Enhancement 
- Tooltip

### What does the proposed API look like 期望支持的API
...
### Feature Description 功能描述
fact
<img width="177" alt="image" src="https://user-images.githubusercontent.com/51318010/179473902-f28117ee-3575-4738-9133-e66fe8c76822.png">

expect
<img width="162" alt="image" src="https://user-images.githubusercontent.com/51318010/179474001-f15cd790-33a1-4659-9175-318bd8769db5.png">
### Additional information 补充说明
clasName `semi-tooltip-wrapper` add css `white-space: pre`

**Comment by pointhalo** [comment]
white-space 和 work-break 两类属性，在不同语言下的需求不太一致（也有考虑过跟LocaleProvider强绑定，但如果内容是多语言混合时，又会有badCase）。所以组件侧没有内置。未来也不是很倾向于加默认设定。更建议用户按需自设。content本身支持reactNode类型传入。可以加在reactNode 的style上
