### ISSUE TITLE
Modal 使用 hook方式调用会报错

### ISSUE THREAD

**Issue by zhaogongchengsi** [DouyinFE/semi-design#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Modal

### Semi Version

^2.13.0

### Current Behavior

使用 hook方式调用会报错 
```tsx
  Modal.info({
      title: 'xxx',
      content: 'xxx'
      onOk: () => {
        console.log('ok');
      },
    });

err:
/*
*ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more
*/

```

### Expected Behavior

好像不影响行为 但是报错看着很难受

### Environment

```markdown
- OS:
- browser:
```

**Comment by pointhalo** [comment]
与 #938 相同。暂时先关掉这个。后续通过 938处理。为 react 18下的适配，需要将当前 reactDOM.render 的写法彻底换掉（例如换成 Portal 实现），否则无法达到同时兼容 react 18+/ < 18 两种场景的使用。
