### ISSUE TITLE
[BUG] <从多选模式空选再切换回单选模式，placeholder无法生效> 

### ISSUE THREAD

**Issue by iera2yy** [DouyinFE/semi-design#978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

semi-ui/Select

### Semi Version

1.32.3

### Current Behavior

从多选模式空选，再切回单选模式，placeholder显示为空

### Expected Behavior

placeholder正常显示

### Steps To Reproduce

1.将Select切换为多选模式；
2.选择若干个，之后宣布撤掉；（即空选）
3.将Select切换回单选模式。

此时代码逻辑中的renderText将变为空数组[ ]，因此在表达式{renderText || renderText === 0 ? renderText : placeholder}中renderText || renderText === 0效果为true，不会显示placeholder。

### ReproducibleCode

```markdown
renderSingleSelection(selections: Map<OptionProps['label'], any>, filterable: boolean) {
  ......
  return (
    <div className={contentWrapperCls}>
      {
         <span className={spanCls} x-semi-prop="placeholder">
           {renderText || renderText === 0 ? renderText : placeholder}
         </span>
      }
      ......
    </div>
  )
  ......
}
```

### Environment

```markdown
- OS:any
- browser:any
```

**Comment by pointhalo** [comment]
不支持动态切换单选/多选，props.multiple 不在实时监听的props范围内。单选和多选的数据处理逻辑、交互都相差太多。不要这么用。

**Comment by pointhalo** [comment]
这种case应该直接重新new 一个新select。而不是沿用然后切换props.multiple
