### ISSUE TITLE
导航菜单点击展开按钮无法展开。

### ISSUE THREAD

**Issue by easy-do** [DouyinFE/semi-design#981]
![image](https://user-images.githubusercontent.com/48109933/180111525-5288daf5-54cc-4199-81d8-7326562f7a5b.png)

      <Nav
      // style={{ maxWidth: 220, height: "100%" }}
      items={userMenuTree[0].items} />

数据结构如下：
[
  {
    "itemKey": 19,
    "parentId": 0,
    "text": "侧边导航",
    "weight": null,
    "icon": "",
    "link": "/",
    "items": [
      {
        "itemKey": 1,
        "parentId": 19,
        "text": "首页",
        "weight": null,
        "icon": "",
        "link": "/home"
      },
      {
        "itemKey": 2,
        "parentId": 19,
        "text": "系统管理",
        "weight": null,
        "icon": "",
        "link": "/",
        "items": [
          {
            "itemKey": 7,
            "parentId": 2,
            "text": "日志管理",
            "weight": null,
            "icon": "",
            "link": "/",
            "items": [
              {
                "itemKey": 8,
                "parentId": 7,
                "text": "任务日志",
                "weight": null,
                "icon": "",
                "link": "/jobLog"
              },
              {
                "itemKey": 9,
                "parentId": 7,
                "text": "系统日志",
                "weight": null,
                "icon": "",
                "link": "/sysLog"
              },
              {
                "itemKey": 10,
                "parentId": 7,
                "text": "执行日志",
                "weight": null,
                "icon": "",
                "link": "/execLog"
              }
            ]
          },
          {
            "itemKey": 11,
            "parentId": 2,
            "text": "用户管理",
            "weight": null,
            "icon": "",
            "link": "/userManager"
          },
          {
            "itemKey": 12,
            "parentId": 2,
            "text": "角色管理",
            "weight": null,
            "icon": "",
            "link": "/roleManager"
          },
          {
            "itemKey": 13,
            "parentId": 2,
            "text": "菜单管理",
            "weight": null,
            "icon": "",
            "link": "/menuManager"
          },
          {
            "itemKey": 14,
            "parentId": 2,
            "text": "话题管理",
            "weight": null,
            "icon": "",
            "link": "/discussionManager"
          },
          {
            "itemKey": 15,
            "parentId": 2,
            "text": "文件存储",
            "weight": null,
            "icon": "",
            "link": "/fileStoreManager"
          },
          {
            "itemKey": 16,
            "parentId": 2,
            "text": "授权码",
            "weight": null,
            "icon": "",
            "link": "/authCode"
          },
          {
            "itemKey": 17,
            "parentId": 2,
            "text": "定时任务",
            "weight": null,
            "icon": "",
            "link": "/job"
          }
        ]
      },
      {
        "itemKey": 3,
        "parentId": 19,
        "text": "服务管理",
        "weight": null,
        "icon": "",
        "link": "/server"
      },
      {
        "itemKey": 4,
        "parentId": 19,
        "text": "应用管理",
        "weight": null,
        "icon": "",
        "link": "/application"
      },
      {
        "itemKey": 5,
        "parentId": 19,
        "text": "APP创作",
        "weight": null,
        "icon": "",
        "link": "/app"
      },
      {
        "itemKey": 6,
        "parentId": 19,
        "text": "脚本创作",
        "weight": null,
        "icon": "",
        "link": "/appScript"
      },
      {
        "itemKey": 18,
        "parentId": 19,
        "text": "账户设置",
        "weight": null,
        "icon": "",
        "link": "/setting"
      }
    ]
  },
  {
    "itemKey": 20,
    "parentId": 0,
    "text": "顶部导航",
    "weight": null,
    "icon": "",
    "link": "/",
    "items": [
      {
        "itemKey": 21,
        "parentId": 20,
        "text": "首页",
        "weight": null,
        "icon": "",
        "link": "/"
      },
      {
        "itemKey": 22,
        "parentId": 20,
        "text": "APP市场",
        "weight": null,
        "icon": "",
        "link": "/"
      },
      {
        "itemKey": 23,
        "parentId": 20,
        "text": "讨论交流",
        "weight": null,
        "icon": "",
        "link": "/"
      },
      {
        "itemKey": 24,
        "parentId": 20,
        "text": "官方Q群",
        "weight": null,
        "icon": "",
        "link": "/"
      }
    ]
  }
]

**Comment by pointhalo** [comment]
与另一issue重复。不需要建两个，这个先关掉。在 #982 讨论吧。
