### ISSUE TITLE
[Calendar] Hope to support the function of whether the left timeline is hidden in range mode

### ISSUE THREAD

**Issue by YyumeiZhang** [DouyinFE/semi-design#991]
### Which Component Need Enhancement 期望新增功能的组件
- Calendar

### What does the proposed API look like 期望支持的API
 whether the left timeline is hidden in range mode

### Feature Description 功能描述
Hope to support the function of whether the left timeline is hidden in range mode

`current`
![image](https://user-images.githubusercontent.com/101110131/180918700-d09217d4-0edb-436f-9627-e7e4e05afc8f.png)

`expect`
![origin_img_v2_a3a5269d-aacc-4e99-9f30-e820c120111g](https://user-images.githubusercontent.com/101110131/180918255-88b8a32a-f367-46cf-9619-1b0e725d9db0.jpg)

**Comment by YannLynn** [comment]
users can hack by this way 
![image](https://user-images.githubusercontent.com/101160769/186805737-c57ce4cc-ba97-47f1-a6d5-0b2270c281f4.png)
