### ISSUE TITLE
[Question] 树形组件defaultValue传入['Chengdu','Osaka']，没有出现蓝色checkbox选中

### ISSUE THREAD

**Issue by zacard-orc** [DouyinFE/semi-design#994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Tree

### Semi Version

2.15.1

### Current Behavior

树形组件defaultValue传入['Chengdu','Osaka']，没有出现蓝色checkbox选中

### Expected Behavior

![image](https://user-images.githubusercontent.com/6058537/181013403-d55cfa6b-67a8-461c-a27f-5f0ec348cfc1.png)
希望传入['Chengdu','Osaka']，出现图上的效果

```jsx

<Tree
          treeData={tree}
          multiple
          defaultValue={['Chengdu','Osaka']}
          onChange={e => console.log('当前所有选中项: ', e)}
          onSelect={e => console.log('当前选项: ', e)}
        />
```

### Environment

```markdown
- OS:
- browser:
```

**Comment by YyumeiZhang** [comment]
官网查看了下，没发现你提到的问题
![image](https://user-images.githubusercontent.com/101110131/181429526-bfd6a54a-291c-406b-8826-84859d81ef63.png)

使用到的代码如下，复制到官网代码编辑区域即可查看
import React from 'react';
import { Tree } from '@douyinfe/semi-ui';

() => {
    const treeData = [
        {
            label: 'Asia',
            value: 'Asia',
            key: '0',
            children: [
                {
                    label: 'China',
                    value: 'China',
                    key: '0-0',
                    children: [
                        {
                            label: 'Beijing',
                            value: 'Beijing',
                            key: '0-0-0',
                        },
                        {
                            label: 'Shanghai',
                            value: 'Shanghai',
                            key: '0-0-1',
                        },
                        {
                            label: 'Chengdu',
                            value: 'Chengdu',
                            key: '0-0-2',
                        },
                    ],
                },
                {
                    label: 'Japan',
                    value: 'Japan',
                    key: '0-1',
                    children: [
                        {
                            label: 'Osaka',
                            value: 'Osaka',
                            key: '0-1-0'
                        }
                    ]
                },
            ],
        },
        {
            label: 'North America',
            value: 'North America',
            key: '1',
            children: [
                {
                    label: 'United States',
                    value: 'United States',
                    key: '1-0'
                },
                {
                    label: 'Canada',
                    value: 'Canada',
                    key: '1-1'
                }
            ]
        }
    ];
    const style = {
        width: 260,
        height: 420,
        border: '1px solid var(--semi-color-border)'
    };
    return (
        <Tree
            defaultValue={['Chengdu', 'Osaka']}
            treeData={treeData}
            multiple
            defaultExpandAll
            style={style}
        />
    );
};

**Comment by YyumeiZhang** [comment]
@zacard-orc 你给的代码中没有treeData的详细内容，建议看下treeData是否符合要求

**Comment by pointhalo** [comment]
hi，能否给出更多复现信息？如果没有的话，这个issue我们计划先关掉了哈。
