### ISSUE TITLE
[Doc] Update Table sortable demo usage

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#997]
### Which Component Need Enhancement 
Table

### Feature Description 功能描述
Update use table + react-dnd demo
![image](https://user-images.githubusercontent.com/88709023/181416860-fc05af23-8fdc-4847-8eef-0f21252a164c.png)

**Comment by shijiatongxue** [comment]
react-dnd@15 hooks 写法支持

**Comment by pointhalo** [comment]
The dragging example on the official website is based on the old version v9 of react-dnd, which is out of touch with the actual latest version. We need an updated example

**Comment by shijiatongxue** [comment]
尝试用 reacrt-dnd@15 写了一个 codesandbox，拖拽后的 index 计算有点问题。

https://codesandbox.io/s/semi-draggable-table-react-dnd-3xe3cp?file=/src/App.tsx
